### ISSUE TITLE
Last Login field does not sort properly

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11866] opened 2024-09-09 12:26 UTC
See https://github.com/rancher/dashboard/issues/10821 (specifically https://github.com/rancher/dashboard/issues/10821#issuecomment-2334490484 and comments below for ways to reproduce)

**Comment by nwmac** [comment] 2024-09-27 16:51
@richard-cox Is this different from https://github.com/rancher/dashboard/issues/12013?

**Comment by rak-phillip** [comment] 2024-09-27 19:48
Closing this as a duplicate of #12013. Please reopen if needed.

**Closed by rak-phillip** 2024-09-27 19:48 UTC
Labels: kind/bug, QA/dev-automation, status/backport-candidate
