### ISSUE TITLE
Project Owner cannot "Import Yaml" feature

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3854] opened 2021-08-14 18:22 UTC
**On 2.6-head commit id: `a55f77f`**

- Create an RKE1 cluster
- Add user1 as Project owner Of a new Project p1 and namespace ns1 _only_
- Login as this user1
- As project Owner Navigate to Cluster Explorer.
- From the top right click on Import Yaml
- Import a deployment or a namespace in the namespace user has access to
- Error is seen and Action cannot be performed
- Namespace: `failed to list /v1, Kind=Namespace for 1aacc415-369a-4b44-95bd-57c7dba134d3: namespaces is forbidden: User "u-cczqeq4tow" cannot list resource "namespaces" in API group "" at the cluster scope`
- Workloads: `failed to list apps/v1, Kind=Deployment for c2acaa61-837a-4aa8-b690-a0db0e5419f9: deployments.apps is forbidden: User "u-cczqeq4tow" cannot list resource "deployments" in API group "apps" at the cluster scope`

**Expected:**
User should be able to import. List action can fail as user may not have access to the resources.

**Comment by gaktive** [comment] 2021-08-20 16:47
We should be able to return a message like "could not retrieve X" to help clarify what's happening here. This import did succeed but we couldn't list what was imported afterwards.

**Comment by sowmyav27** [comment] 2021-08-25 01:58
@gaktive Import does not succeed. This is on 2.6-head commit: `b43e4d9`

**Comment by nwmac** [comment] 2021-09-03 13:15
The belief here is that the error is after the import has succeeded, we show a list of what was imported - but in this case the user does not have permissions to view some of the resources that were created, hence the errors in the table.

This needs to be confirmed - if this is the case, the code that shows the list of what was imported should catch the errors for cannot list and show a message that the user does not have permissions.

**Comment by catherineluse** [comment] 2021-09-11 21:46
The user can't successfully import YAML using the button in the top navigation bar, but they can do it from individual resource pages. So if you go to the Deployments page, you can create a Deployment from YAML. But you can't import the same YAML from the Import YAML button in the top nav.

It's also inconsistent that when a project owner creates a Deployment from the Deployment page, they can list the Deployments including the one they just created. It's only when attempting to import yaml that they don't have access to list resources.

**Comment by vincent99** [comment] 2021-09-11 22:33
Those are doing two very different things, even though they look similar.  Individually creating a deployment (or anything else) is POSTing to that particular type in the requested particular namespace.

Using the top-nav import button is doing generic basically "kubectl apply" via an action on the cluster which can take yaml for many resources in many namespaces. It sounds like the action doesn't work properly or isn't available in limited-RBAC access situations, so nothing is actually being created?

If the same deployment is _actually_ created in the same namespace, it should show up in the list and shouldn't matter which way you did it.

**Comment by catherineluse** [comment] 2021-09-12 00:30
That's correct, nothing is actually being created when you attempt to import YAML in a namespace that you have access to, as a project owner. It tries to POST to `/v1/management.cattle.io.clusters/local?action=apply` but it looks like project owners don't have access to that action.

**Comment by gaktive** [comment] 2021-09-14 16:58
Backend work: https://github.com/rancher/rancher/issues/34712

**Comment by snasovich** [comment] 2021-09-14 22:37
@gaktive , do you expect any UI work necessary once backend issue is fixed? I cannot think of any right away.

**Comment by gaktive** [comment] 2021-09-14 23:45
@snasovich I can't think of a scenario where the UI needs to update anything once it's fixed in the backend since ideally, the backend provides any subsequent messaging regarding errors.

**Comment by snasovich** [comment] 2021-09-15 02:51
@gaktive , thank you. Is this functionality (importing YAML at cluster level) supported in v2.5.x UI? I was not able to find it in UI, but was able to confirm the backend is failing in v2.5.9 the same way when calling v1 API (not sure if there is matching v3 API v2.5.x UI is using).

**Comment by vincent99** [comment] 2021-09-15 03:02
It is in 2.5 ['s Cluster Explorer], in roughly the same place..  
![image](https://user-images.githubusercontent.com/753917/133363544-1186dbc7-82ff-459a-b85a-1d2d21a5167e.png)

**Comment by snasovich** [comment] 2021-09-15 13:53
Thank you. I should have been more clear that I'm mostly interested in whether Ember (old) UI has this feature. Seems like the answer is "no". I did check this action and confirm it's failing with the same error in 2.5.9, so this issue is not a regression (wanted to check this for priority purposes).

**Comment by catherineluse** [comment] 2021-09-16 22:20
The Ember UI for the cluster view just had the kubectl and kubeconfig buttons, not import yaml. 
![Screen Shot 2021-09-16 at 3 19 24 PM](https://user-images.githubusercontent.com/20599230/133693097-bb53b6fc-ac90-4b43-8d97-a8402b59c531.png)

**Comment by Jono-SUSE-Rancher** [comment] 2021-11-03 17:41
It looks like there really isn't anything that is needed from the UI team once the backend ticket gets complete, so I am going to close this one based on the backend work.

**Closed by Jono-SUSE-Rancher** 2021-11-03 17:41 UTC
Labels: kind/bug, status/waiting-backend, [zube]: Backend Blocked
