### ISSUE TITLE
[2.9] UI gets stuck on fatal error trying to create an AKS cluster

### ISSUE THREAD

**Issue by ericpromislow** [rancher/dashboard#10882] opened 2024-04-25 17:49 UTC
**Setup**
- Rancher version: 2.9 dev build with PR https://github.com/rancher/rancher/pull/45246
- Rancher UI Extensions: None
- Browser type & version: Firefox latest

**Describe the bug**
I tried to create an AKS cluster. The screen is stuck at "Loading..."

The console has this error message:
`Uncaught (in promise) TypeError: this.versionChoices.firstObject is undefined` at `https://releases.rancher.com/ui/latest2/assets/addon-tree-output/shared/components/cluster-driver/driver-eks/component.js` line 72

This code:
```
const kubernetesVersion = this.versionChoices.firstObject.value;
```

**To Reproduce**
- I created and helm-installed personal images based on rancher and rancher-agent from
  cf79d4972 `- (origin/release/v2.9, origin/HEAD, release/v2.9) Merge pull request #44784`
  with the diffs from PR 45246 -- without them I can't start the auth process.

**Result**
See above

**Expected Result**
See above

**Comment by richard-cox** [comment] 2024-04-26 08:28
@ericpromislow It looks like that line only appears in the ember EKS driver, are you sure it was AKS?

AKS has been ported to the dashboard, so shouldn't be showing anything ember side.
EKS will be ported to the dashboard very soon (once https://github.com/rancher/dashboard/pull/10581 merges)

cc @mantis-toboggan-md

**Comment by mantis-toboggan-md** [comment] 2024-06-20 22:04
@ericpromislow AKS and EKS cluster provisioning have been migrated to the dashboard. I wasn't able to reproduce the issue in my own testing; could you confirm whether or not you're still seeing it?

**Comment by yonasberhe23** [comment] 2024-07-05 19:09
Unable to reproduce as well. closing issue

**Closed by yonasberhe23** 2024-07-05 19:09 UTC
Labels: kind/bug, ember, area/aks, QA/dev-automation
