### ISSUE TITLE
Error in console when user clicks on Namespace dropdown in Continuous Delivery --> Clusters window

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#6363] opened 2022-07-13 16:26 UTC
**On 2.6head commit id: `2c21373`**

- Deploy RKE1 and RKE2 clusters
- Navigate to Continuous Delivery --> Clusters
- Click on namespace Dropdown on top right --> Error TypeError: Failed to execute 'getComputedStyle' seen in console.
- Error:
```
vue.runtime.esm.js:1897 TypeError: Failed to execute 'getComputedStyle' on 'Window': parameter 1 is not of type 'Element'.
    at c (WorkspaceSwitcher.vue?5709:30:21)
    at f.<anonymous> (WorkspaceSwitcher.vue?9674:158:27)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
    at ce (vue.runtime.esm.js:1915:12)
```

**Comment by jameson-mcghee** [comment] 2022-07-22 20:19
@aalves08, On the plus side, I am not seeing ins errors in the console log while looking at this on v2.6-head. However, I noticed that the page is not updating properly when I chance from one fleet namespace to another.

e.g. when looking at fleet-local, its shoes my local cluster, but when I change the dropdown to fleet-default, the UI does not automatically update to show the correct clusters. It will display the correct clusters after refreshing the page.

Because of this issue, I am reopening this ticket.
cc @sowmyav27 @Shavindra 

Prior to changing namespace dropdown:
![image.png](https://zube.io/files/rancher/6b1f9ad0f090069179f15efc47e43d38-image.png)

After changing namespace dropdown:
![image.png](https://zube.io/files/rancher/0f376a70b03a7d1ef2dbde862d1599e8-image.png)

After refreshing the page:
![image.png](https://zube.io/files/rancher/4bc5472643a4e5a68becd440cf72b900-image.png)

**Comment by aalves08** [comment] 2022-07-26 11:24
@jameson-mcghee did this feature (workspace switcher connected properly to fleet resources) ever work on older versions? By looking into the code, I don't think it ever worked... 🤔

**Comment by jameson-mcghee** [comment] 2022-07-27 15:22
@aalves08, assuming we are talking about the same thing, then it appears to work fine for me on 2.6.5

![image.png](https://zube.io/files/rancher/1a86cc5571d191cca846e036a85bee1f-image.png)
![image.png](https://zube.io/files/rancher/9aaaaad9cf806b3f92059b873d1171b2-image.png)
![image.png](https://zube.io/files/rancher/7c35112db0fa55004b6222a9b7b7d321-image.png)

**Comment by sowmyav27** [comment] 2022-07-28 04:07
@aalves08 I don't see the console error happen anymore on latest 2.6head commit id: `78017e6` as described in the original issue.

**Comment by jameson-mcghee** [comment] 2022-07-29 20:46
I am still seeing the previous issue reproduce on v2.6.7-rc5. 

In addition, I just noticed something odd both on v2.6.5 and on v2.6.7-rc5. The first time I access the Continuous Delivery -> Clusters page, there is no Namespace dropdown list at all in the UI, even after refreshing the page.  I had to logout, and then log back in before it would finally appear.  Is this perhaps what you meant @aalves08 when you said "..did this feature (workspace switcher connected properly to fleet resources) ever work on older versions? By looking into the code, I don't think it ever worked… 🤔"?

Either way, I am gonna have to Reopen this ticket until the previous issue (meaning the UI grid not updating when swapping between Namespaces in the dropdown) is resolved.
cc @sowmyav27 

![image.png](https://zube.io/files/rancher/67a0698b7d6347006a078b8fa2642a97-image.png)

**Comment by aalves08** [comment] 2022-08-01 08:27
@jameson-mcghee the fix was merged on Friday, 29th July, at around 15:42. 

- v2.6.7-rc5 must has been cut around 26th July, 10pm.

PR here: https://github.com/rancher/dashboard/pull/6524

<img width="551" alt="Screenshot 2022-08-01 at 09 23 28" src="https://user-images.githubusercontent.com/97888974/182106519-8c3d4250-08d8-4142-bfb8-f54e6286df83.png">
<img width="917" alt="Screenshot 2022-08-01 at 09 23 39" src="https://user-images.githubusercontent.com/97888974/182106531-cbfee3b4-9925-4e1e-9d7d-5cbe9ca46454.png">

Can you please check again? thanks 🙏

**Comment by jameson-mcghee** [comment] 2022-08-01 21:58
I apologize @aalves08. I was testing on that version because v2.6-head was broken during my retesting on Friday. However, I retested this ticket today on v2.6-head Commit ID 20d6e22, and I did not observe any errors in the Console for the Continuous Delivery --> Clusters page (as was documented in my previous comments), and the other issues I have observed are unrelated to this ticket and will be logged in a separate ticket. Therefore this issue appears to be resolved, and I am closing this ticket.

**Closed** 2022-08-01 21:58 UTC
Labels: [zube]: Done, QA/XS, area/fleet, kind/bug-qa, team/area2
