### ISSUE TITLE
User Details view not accessible

### ISSUE THREAD

**Issue by edenhernandez-suse** [rancher/dashboard#12275] opened 2024-10-16 10:31 UTC
**Setup**
- Rancher version: v2.10
- Browser type & version: Chrome Version 129.0.6668.90

**Describe the bug**
The Details view of a user is not accessible from the `Config` or `YAML` tabs.

**To Reproduce**
1. Go to `Users & Authentication`, click on a user's name.
2. Go to either `Config` or `YAML`
3. Click back on `Detail`.

**Result**
The URL changes, but the screen doesn't change.

**Expected Result**
The Details view should be shown.

**Screenshots**
<img width="1029" alt="image" src="https://github.com/user-attachments/assets/ac81ffc5-6dc3-43c4-a27c-262590cf7312">

**Comment by rak-phillip** [comment] 2024-10-16 16:41
This looks like a duplicate of #12267

**Comment by cnotv** [comment] 2024-10-17 10:26
To be reviewed with https://github.com/rancher/dashboard/issues/12267 since it has been opened by QA they already know the details.

**Closed by cnotv** 2024-10-17 10:26 UTC
Labels: kind/bug, QA/dev-automation
