### ISSUE TITLE
Cannot correctly set date and time format in Rancher UI

### ISSUE THREAD

**Issue by madgrog** [rancher/dashboard#6108] opened 2022-06-06 07:58 UTC
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Firefox 101.0 and Chrome 102.0 on MacOS

**Describe the bug**
Cannot set date and time format in user preferences.
Dropdown menu shows correct options, but selecting desired option get coded string selected in both menus.
Date Format: "map[label:2022-06-06 value:YYYY-MM-DD]"
Time Format: "map[label:09:44:26 value:HH:mm:ss]"
The same format is than displayed in logs in every Rancher page.

**To Reproduce**
Rancher installed via official Helm Chart on OVH managed Kubernetes cluster

**Result**

**Expected Result**
Correct date and time format set up and display.

**Screenshots**
https://prnt.sc/mUwX13MiLUZ2
https://prnt.sc/evkZiXUk-Fvb

**Additional context**
Nothing to add

**Comment by richard-cox** [comment] 2022-06-06 08:17
Thanks for raising this issue, however it's a duplicate of https://github.com/rancher/dashboard/issues/5979 and will be resolved in `2.6.6`

**Closed by richard-cox** 2022-06-06 08:17 UTC
