### ISSUE TITLE
[BUG] UI not refreshing when cluster members are added or removed

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4904] opened 2022-01-12 09:46 UTC
Rancher v2.6.3

**To Reproduce**
1. Navigate to Cluster -> Explore -> RBAC -> Cluster Members
2. Remove a member (Context Menu -> Delete)
3. Notice that the resource remains stuck in `Removing` state
4. While keeping this browser session open, login with another user account in a different browser
5. Add a member to the cluster in the second browser session
6. Notice that the new member is not dynamically displayed in the first browser session (browser refresh required)

**Expected Result**
UI should be refreshed when resources are added or removed.

<img width="720" alt="Screenshot 2022-01-12 at 10 41 08" src="https://user-images.githubusercontent.com/3813921/149114749-0b779148-bbcc-4a92-a8a8-bc19ea237838.png">

**Comment by catherineluse** [comment] 2022-01-31 20:36
I wonder if this issue could be caused by Chrome not updating pages properly when self-signed certs are used. See Jason's comment https://github.com/rancher/dashboard/issues/3936#issuecomment-1022772061

**Comment by nwmac** [comment] 2022-04-26 13:30
Note Cluster Members is now under the 'Cluster' menu item

**Comment by nwmac** [comment] 2022-07-21 12:53
Shavin and I spent ages looking into this - there is something strange in here that is going to take longer to get to the bottom of.

**Comment by nwmac** [comment] 2022-07-21 12:53
@gaktive Pushing out to 2.7.0

**Comment by catherineluse** [comment] 2022-07-21 17:19
Nancy fixed a similar-sounding issue https://github.com/rancher/dashboard/issues/5497 with this PR - https://github.com/rancher/ui/pull/4824 Maybe a similar change would be needed here.

**Comment by dasarinaidu** [comment] 2022-12-02 17:01
**Steps to Reproduce:**

Rancher Version : v2.6.7

1. Create a RKE1 cluster
2. Cluster explorer -> Cluster Members
3. Add couple of users on the same screen
4. Delete a Member and check if the user is deleted from the list without a screen refresh
5. Add a User from a different screen and check if the added user is listing on the screen without a refresh

**Actual:**
UI is not refreshed and the deleted user is not removed from the list and newly added user is not added to the list in the same screen without a screen refresh

**Comment by dasarinaidu** [comment] 2022-12-02 23:27
I have validated this issue on `v2.7-38979f8ebe5c1ecb0121494d185758741fcb0d5b-head`

All the test cases were passed and closing the issue.

**Test cases executed:**

1. Rancher Types : Docker and HA installed
2. Clusters : RKE1, RKE2 & EKS clusters
3. User types : Admin, Standard and User base
4. Browsers : Chrome & Firefox
5. Modes : Light and Dark modes
6. User Add and User Delete

**Steps:**
1. Create a RKE1 cluster
2. Cluster explorer -> Cluster Members
3. Add couple of users on the same screen
4. Delete a Member and check if the user is deleted from the list without a screen refresh
5. Add a User from a different screen and check if the added user is listing on the screen without a refresh
7. Open rancher ->Cluster->Cluster Member on TWO browser windows and Run Step 4 & 5 
8. Make sure the user additions and deletions should reflect on both screens as expected.

**Closed by dasarinaidu** 2022-12-02 23:27 UTC
Labels: kind/bug, internal, [zube]: QA Working, team/area1
