### ISSUE TITLE
[2.7.0] hide k8s 1.22 and below for EKS/GKE/AKS in Rancher UI

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#7203] opened 2022-10-14 17:32 UTC
Hide k8s 1.22 and below for EKS/GKE/AKS in Rancher UI. 

This request is derived from https://github.com/rancher/rancher/issues/39239
 
Note: This issue is made in this rpeo because AFAIK UI generates the EKS/GKE/AKS version list.

**Comment by gaktive** [comment] 2022-10-17 15:06
We'd need to update both Ember and Vue.

**Comment by snasovich** [comment] 2022-10-17 19:46
We have an interesting situation with GKE here. Currently, 1.22 is the default. 1.23 will become the default some time in November 2022 per version table https://cloud.google.com/kubernetes-engine/docs/release-schedule#schedule_for_static_no_channel_versions (date in "Control plane and node upgrades start on/after" column is the date the version becomes default per https://cloud.google.com/kubernetes-engine/docs/release-schedule#fn5.
So depending on the timing of 2.7.0 release and when exactly 1.23 becomes default, we may have an issue with default version not be available in the filtered list of versions.

**Comment by snasovich** [comment] 2022-10-18 19:27
@catherineluse , thank you.

For AKS, I've logged https://github.com/rancher/dashboard/issues/7217 to "un-experimental" 1.24 for AKS.

Regarding GKE, I believe the versions from a channel are only used when it's set on the cluster - which can probably be only done for GKE clusters imported into Rancher. When provisioning new GKE clusters in Rancher, "no channel" (https://cloud.google.com/kubernetes-engine/docs/concepts/release-channels#no_channel) list is used:
<img width="1331" alt="image" src="https://user-images.githubusercontent.com/85187633/196525368-3df20459-d442-438a-b319-8f3b96367334.png">
Maybe there is a way to set the release channel for clusters when provisioning, but I don't know how.

**Comment by catherineluse** [comment] 2022-10-20 20:37
# QA Template 

## What was fixed, or what changes have occurred

- Hardcoded the EKS version to only 1.23. This is because 1.24 will not be available for EKS until November. The issue for adding 1.24 is here: https://github.com/rancher/dashboard/issues/7219
- Set a minimum version of 1.23 for AKS and GKE
 
## Areas or cases that should be tested
For EKS, AKS and GKE cluster provisioning, here's what I have for the K8s version dropdowns:

### EKS
<img width="759" alt="Screen Shot 2022-10-20 at 1 23 05 PM" src="https://user-images.githubusercontent.com/20599230/197053053-13434bad-c2ae-4f83-ade0-dfcf42cca5a7.png">

### AKS
<img width="689" alt="Screen Shot 2022-10-20 at 1 05 05 PM" src="https://user-images.githubusercontent.com/20599230/197053111-2dce7ea3-bdb2-45b5-8468-482ddaa8bcb9.png">

### GKE
 
<img width="783" alt="Screen Shot 2022-10-20 at 1 14 19 PM" src="https://user-images.githubusercontent.com/20599230/197053142-83e3415d-193f-4423-9da1-303fd975b604.png">

## What areas could experience regressions?
The code changes mainly affect the hosted K8s version dropdowns for GKE and AKS

**Comment by markusewalker** [comment] 2022-10-24 18:46
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|Setup a fresh install of Rancher, validate that the K8s version dropdown only has 1.23+ for an AKS cluster.|
|2|Setup a fresh install of Rancher, validate that the K8s version dropdown only has 1.23+ for an EKS cluster.|
|3|Setup a fresh install of Rancher, validate that the K8s version dropdown only has 1.23+ for an GKE cluster.|
|4|Setup Rancher `v2.6.9`, validate that the K8s version dropdown includes < 1.23 for an AKS cluster, provision highest K8s version cluster, upgrade to `v2.7-head`, validate that the K8s version DOES NOT have < v1.23 in the provisioned cluster AND when provisioning a new cluster.|
|5|Setup Rancher `v2.6.9`, validate that the K8s version dropdown includes < 1.23 for an EKS cluster, provision highest K8s version cluster, upgrade to `v2.7-head`, validate that the K8s version DOES NOT have < v1.23 in the provisioned cluster AND when provisioning a new cluster.|
|6|Setup Rancher `v2.6.9`, validate that the K8s version dropdown includes < 1.23 for an GKE cluster, provision highest K8s version cluster, upgrade to `v2.7-head`, validate that the K8s version DOES NOT have < v1.23 in the provisioned cluster AND when provisioning a new cluster.|

**Comment by markusewalker** [comment] 2022-10-24 19:55
Validated this against `v2.7-head`  https://github.com/rancher/rancher/commit/40932d62cdeb2f4594009436468c444c3378553d. Details below:

**ENVIRONMENT DETAILS**
- Rancher install: Helm
- Rancher version:
     - Fresh install: `v2.7-head https://github.com/rancher/rancher/commit/40932d62cdeb2f4594009436468c444c3378553d`
     - Upgrade: `v2.6.9` -> `v2.7-head https://github.com/rancher/rancher/commit/9e7e4bc5bb4ac18ae801fba3c076f10039267052`
- Browser: Chrome


TEST RESULT
|Scenario|Test Case|Result
|---|---|---|
|1|Setup a fresh install of Rancher, validate that the K8s version dropdown only has 1.23+ for an AKS cluster.|:white_check_mark:|
|2|Setup a fresh install of Rancher, validate that the K8s version dropdown only has 1.23+ for an EKS cluster.|:white_check_mark:|
|3|Setup a fresh install of Rancher, validate that the K8s version dropdown only has 1.23+ for an GKE cluster.|:white_check_mark:|
|4|Setup Rancher `v2.6.9`, validate that the K8s version dropdown includes < 1.23 for an AKS cluster, provision highest K8s version cluster, upgrade to `v2.7-head`, validate that the K8s version DOES NOT have < v1.23 in the provisioned cluster AND when provisioning a new cluster.|:white_check_mark:|
|5|Setup Rancher `v2.6.9`, validate that the K8s version dropdown includes < 1.23 for an EKS cluster, provision highest K8s version cluster, upgrade to `v2.7-head`, validate that the K8s version DOES NOT have < v1.23 in the provisioned cluster AND when provisioning a new cluster.|:white_check_mark:|
|6|Setup Rancher `v2.6.9`, validate that the K8s version dropdown includes < 1.23 for an GKE cluster, provision highest K8s version cluster, upgrade to `v2.7-head`, validate that the K8s version DOES NOT have < v1.23 in the provisioned cluster AND when provisioning a new cluster.|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigate to Cluster Management > Create > Azure AKS.
3. Began to provision a hosted AKS cluster and in the `Cluster Options`, validated that the K8s version dropdown only has 1.24 and 1.23:
![image](https://user-images.githubusercontent.com/52591819/197615585-8a73cc11-2b30-4132-aec8-0f53ee668bf7.png) 
____________
**Scenario 2**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigate to Cluster Management > Create > Amazon EKS.
3. Began to provision a hosted AKS cluster and in the `Cluster Options`, validated that the K8s version dropdown only has 1.23:
![image](https://user-images.githubusercontent.com/52591819/197615495-64b2732c-974e-4cb4-81c1-0b15c8d60126.png) 
___________
**Scenario 3**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigate to Cluster Management > Create > Google GKE.
3. Began to provision a hosted AKS cluster and in the `Cluster Options`, validated that the K8s version dropdown only has 1.24 and 1.23:
![image](https://user-images.githubusercontent.com/52591819/197615411-9e0a4cc8-6415-478a-8492-1707d6330fa8.png) 
___________
**Scenario 4**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigate to Cluster Management.
3. Provisioned an AKS cluster; validated the cluster came up as `Active` in Cluster Management and nodes in `Cluster Explorer`.
     - Validated that K8s versions below 1.23 were present.
4. Upgraded Rancher server to `v2.7-head https://github.com/rancher/rancher/commit/9e7e4bc5bb4ac18ae801fba3c076f10039267052`.
5. Validated that the cluster remained in a state of `Active` and the nodes as well.
6. Edited the cluster's configuration and validated that the K8s version does not include versions below 1.23:
![image](https://user-images.githubusercontent.com/52591819/197615240-7b9ae8bd-e33f-4fab-8533-4ac16eb84f3c.png) 
____________
**Scenario 5**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigate to Cluster Management.
3. Provisioned an EKS cluster; validated the cluster came up as `Active` in Cluster Management and nodes in `Cluster Explorer`.
     - Validated that K8s versions below 1.23 were present.
4. Upgraded Rancher server to `v2.7-head https://github.com/rancher/rancher/commit/9e7e4bc5bb4ac18ae801fba3c076f10039267052`.
5. Validated that the cluster remained in a state of `Active` and the nodes as well.
6. Edited the cluster's configuration and validated that the K8s version does not include versions below 1.23:
![image](https://user-images.githubusercontent.com/52591819/197615018-67a87583-76dc-4249-b1f0-21ddce9e1338.png) 
      - This would be expected considering that the original cluster was at 1.22 prior to upgrading.
_____________
**Scenario 6**
1. Setup Rancher, created a standard user and logged in as that user.
2. Navigate to Cluster Management.
3. Provisioned an GKE cluster; validated the cluster came up as `Active` in Cluster Management and nodes in `Cluster Explorer`.
     - Validated that K8s versions below 1.23 were present.
4. Upgraded Rancher server to `v2.7-head https://github.com/rancher/rancher/commit/9e7e4bc5bb4ac18ae801fba3c076f10039267052`.
5. Validated that the cluster remained in a state of `Active` and the nodes as well.
6. Edited the cluster's configuration and validated that the K8s version does not include versions below 1.23:
![image](https://user-images.githubusercontent.com/52591819/197614879-1d663984-4c49-4c44-987f-4082bf432dc0.png)

**Comment by thaneunsoo** [comment] 2022-10-27 20:02
Closing this issue as [7277](https://github.com/rancher/dashboard/issues/7277) is now resolved

**Closed** 2022-10-27 20:03 UTC
Labels: [zube]: Done, QA/XS, kind/enhancement, team/area2, ember
