### ISSUE TITLE
Cluster Explore namespace filtering results in UI freeze

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5006] opened 2022-01-28 21:56 UTC
Internal reference: SURE-3256
Reported in 2.5.7 though we should check this in 2.6.x.

*Issue description:*
In this cluster with over 200 namespaces, when attempting to filter a namespace, an exception occurs and the UI will freeze. 

*Business impact:*
A refresh of the page is required. 

*Troubleshooting steps:*
The user can reproduce the issue in Firefox, Chrome, Safari, and Edge and on different computers and OSs. The same issue happens in incognito mode.  Safari is a "clean" browser with zero plugins and the other setups really do not too many plugins.

*Repro steps:*
 * In rancher UI, attempt to sort namespace by typing in a namespace name.

*Actual behavior:*
UI locks up

*Expected behavior:*
It doesn't lock up

*Files, logs, traces:*
Possible related error:
{color:#b218b2}./1628864494_$RANCHER_URL-1628863890535.logs{color}{color:#18b2b2}:{color}{color:#000000}10:10:47.006 xhr.js:178 XHR failed loading: PUT "https://$RANCHER_URL/v1/{color}{color:#ff5454}userpreferences{color}
{color:#000000}/u-gq7gghhzg2".{color}

**Comment by gaktive** [comment] 2022-02-17 20:03
Also reported in 2.6.3 patch 1.

**Comment by gaktive** [comment] 2022-03-04 22:26
Update from user:
> This same issue looks to affect our ability to move a namespace from one project to another. We are able to back door it by updating the annotation on the namespace via kubectl but this bug is getting very annoying.

**Comment by mantis-toboggan-md** [comment] 2022-03-30 20:41
This seems to be fixed as of 2.6.4. I was able to reproduce this bug using the 2.6.3-patch1 Dashboard and not the 2.6.4 nor master Dashboards. To repro this, my cluster needed not only a large number of namespaces, but a large number of namespaces within projects.

**Comment by markusewalker** [comment] 2022-04-25 16:45
Verified on `v2.6.5-rc2`.

**ENVIRONMENT DETAILS**
- Ubuntu 20.04 VM
- Docker Install: 20.10
- Rancher version: `v2.6.3`
- Browser: Chrome, Safari, Firefox

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to Rancher UI > top-left dropdown menu > local > Projects/Namespaces.
2. In the top-right corner, click Create Project. Follow the subsequent prompts to create a project.
3. In the newly created project, click Create Namespace. Follow the subsequent prompts to create a namespace. Repeated this step over 200 times:
![image](https://user-images.githubusercontent.com/52591819/165135143-d8928bd6-d0ae-4ccf-8008-f15d547a09ae.png)
5. Attempted to filter and saw the following results:
![Apr-25-2022 09-43-24](https://user-images.githubusercontent.com/52591819/165135064-50fc73cf-6725-45ab-a520-e910c891b51d.gif)

**Closed by markusewalker** 2022-04-25 16:45 UTC
Labels: kind/bug, area/namespace, internal, [zube]: QA Working, team/area1, size/1
