### ISSUE TITLE
create deployment add container input form conflict with hot key

### ISSUE THREAD

**Issue by stardemo** [rancher/dashboard#7542] opened 2022-11-24 06:48 UTC
**Setup**
- Rancher version: [v2.6.9](https://rancher.thecover.cn/dashboard/about)
- Browser type & version:  chrome 107.0.5304.110

**Describe the bug**

create deployment  in container tab,edit container name form,input value conflict with hotkey .
<img width="1072" alt="image" src="https://user-images.githubusercontent.com/20634646/203712174-c91deffd-c877-46cf-9c99-63f8a2acfc69.png">
input string the form jump to another tab.
<img width="845" alt="image" src="https://user-images.githubusercontent.com/20634646/203713211-47eae762-46c4-4dca-9662-7db67be9cd5e.png">

**Comment by richard-cox** [comment] 2022-11-24 09:34
Thank you for creating this issue, however it's a duplicate of https://github.com/rancher/dashboard/issues/7505

**Closed by richard-cox** 2022-11-24 09:34 UTC
Labels: kind/bug
