### ISSUE TITLE
Resource search should match API group

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6002] opened 2022-05-20 10:34 UTC
In a cluster, you can click the search icon in the top right of the page - this pops up a overlay box that can be used to find resources.

This should be improved so that you can type the name of an API group and this will show you that group and all resources in the group - currently it only matches on resource name.

**Comment by catherineluse** [comment] 2022-07-12 01:42
Possible dupe of #5091 https://github.com/rancher/dashboard/issues/5091#issuecomment-1100961093

**Closed** 2022-07-19 12:49 UTC
Labels: kind/enhancement, good-first-issue
