### ISSUE TITLE
UI expired session doesn't redirect us to the login page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5418] opened 2022-03-16 22:21 UTC
Internal reference: SURE-4223
Reported in 2.6.3

Issue description:
When a user comes back to a browser tab that was left open after previously working within Rancher (and the session has since expired) the UI will allow them to click on different items and even make modifications in certain cases. It doesn't prompt that the session is expired or redirect us to the login page. This has caused a couple issues for us where they thought a configuration change had been made but it really hadn't because of the expired session. 

This doesn't require any follow up as they have become accustomed to closing or refreshing our tabs before interacting with Rancher. They just wanted us to be aware if we weren't already.

Repro steps:

Hard via docker setup.

Workaround:
Is workaround available and implemented? yes

What is the workaround:
Close and open the tab / refresh tab

Actual behavior:
When they come back to a browser tab that was left open after previously working within Rancher (and the session has since expired) the UI will allow them to click on different items and even make modifications in certain cases. It doesn't prompt that the session is expired or redirect the user to the login page. This has caused a couple issues for them where we thought a configuration change had been made but it really hadn't because of the expired session. 

Expected behavior:
After session has expired, prompt the user to re-authenticate

**Comment by markusewalker** [comment] 2022-06-02 20:16
Unable to reproduce this issue on `v2.6.3` and `v2.6-head` https://github.com/rancher/rancher/commit/7a64bb254e19c852d4a827affad68a2e43a8560a.

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher versions
     - Non-reproduced versions: `v2.6.3` / `v2.6-head` https://github.com/rancher/rancher/commit/7a64bb254e19c852d4a827affad68a2e43a8560a
- Browser: Chrome

**REPRODUCTION STEPS**
1. Setup Rancher and login to the UI in a browser that can delete cookies from a site.
2. Opened the browser's developer tools and navigate to Application and click `Clear site data`:
![Screen Shot 2022-06-02 at 1 10 28 PM](https://user-images.githubusercontent.com/52591819/171729779-baf4e1a8-d569-4056-80e9-8a45455c9c13.png)
4. Navigated around Rancher and verified I was redirected to the login page:
![Jun-02-2022 13-14-13](https://user-images.githubusercontent.com/52591819/171730097-77ad73bb-fb93-4d43-96ce-19bfa171eec6.gif)
     - I performed this workflow multiple times on both versions and I am unable to reproduce this at all.

@aalves08 I looked in the PR and attempted your repro steps as well in addition to my notes above. Still unable to reproduce....how frequently does this issue occur and do you have steps that reliably allow this to be reproduced?

**Comment by aalves08** [comment] 2022-06-06 08:54
Hi @markusewalker .

Despite the fix not being master yet (need approval from my peers), the goal is to prevent the user from starting actions without being logged in (with a valid session cookie).

By default, if you perform any action that communicates with the BE WITHOUT a valid session, you get redirected to the login, but there are certain actions that are only controlled by the FE side of the app.

So, if you delete the cookies, go back to the page (without refreshing) of a list view, you will be able to sort the table elements, select multiple items, etc, etc... With the fix, everytime you move out of the app's  tab in your browser and come back to it, it will do a check for the cookie and log you out if it's non-existent or not valid.

**Comment by markusewalker** [comment] 2022-06-21 15:55
Verified I could reproduce this on `v2.6.3` and verified that this is addressed in `v2.6-head`

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher versions
     - Reproduced version: `v2.6.3`
     - Verified version: `v2.6-head` https://github.com/rancher/rancher/commit/772b2f0232764ec1f0f9f90d938a69cce647dcdb
- Browser: Chrome

**TEST RESULT**
PASS

**REPRODUCTION STEPS**
1. Setup Rancher and login to the UI in a browser that can delete cookies from a site.
2. Using Chrome extension `Cookie-Editor`, I deleted all of my cookies available for this tab.
3. After deleting the cookies, switched to a separate tab and switched back to my Rancher tab.
4. Verified I am still able to click around in Rancher as illustrated below:
![Jun-21-2022 08-45-39](https://user-images.githubusercontent.com/52591819/174842795-9df72473-24ff-453f-89dd-fb2d70a665a8.gif)
_**Note: The other tab switched to is a completely separate Rancher setup**_

VERIFICATION STEPS
1. Setup Rancher and login to the UI in a browser that can delete cookies from a site.
2. Using Chrome extension `Cookie-Editor`, I deleted all of my cookies available for this tab.
3. After deleting the cookies, switched to a separate tab and switched back to my Rancher tab.
4. Verified that my browser immediately recognized that my session ended and that I am prompted to login again:
![Jun-21-2022 08-53-11](https://user-images.githubusercontent.com/52591819/174843940-433ca987-42d1-445b-ba03-815c54d5d660.gif)
_**Note: The other tab switched to is a completely separate Rancher setup**_

**Closed by markusewalker** 2022-06-21 15:55 UTC
Labels: kind/bug, internal, QA/S, [zube]: QA Working, team/area2, size/3, JIRA
