### ISSUE TITLE
Logging UI needs to create secrets for some outputs

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1031] opened 2020-08-14 19:00 UTC
The following fields will need a secret reference now instead of the actual value.

ES

- password
- ca_file
- client_cert
- client_key
- client_key_pass

Kafka

- username
- password
- ssl_ca_cert
- ssl_client_cert
- ssl_client_cert_chain
- ssl_client_cert_key

Splunk

- token

**Comment by codyrancher** [comment] 2020-08-18 20:54
@paynejacob are there going to be field changes?

It seems things like client_cert and client_key would be a single `certificate` secret.
Would username and password also be a single `opaque` secret? If so, what would the keys and values look like?

**Comment by paynejacob** [comment] 2020-08-18 21:46
All the secrets in the chart are opaque, they can be reused if you wanted to do 1 per output or do logical grouping like un/pw.  The chart takes a secret name and key pair to lookup the value.

example:
  password:
    secret_name: ""
    key: "password"

**Comment by codyrancher** [comment] 2020-08-19 20:49
@deniseschannon @lvuch Could we get some mockups on what we'd like an opaque secret selector to look like? For each secret field we'll need a `secret_name` and `key` value.

I was thinking something like
![image](https://user-images.githubusercontent.com/55104481/90688086-c6c84300-e222-11ea-8be4-65d2131a4c7a.png)

But then I don't have a place to put the `Password` label.

**Comment by deniseschannon** [comment] 2020-08-24 22:04
I think having "Password" above as a heading would make sense. 

We might have to do a quick layout with a broader heading but something like this: 

<img width="748" alt="Screen Shot 2020-08-24 at 3 03 46 PM" src="https://user-images.githubusercontent.com/11410997/91100985-09bb5980-e61b-11ea-8642-eac496b32026.png">

**Comment by deniseschannon** [comment] 2020-09-15 18:11
This would most likely be tested when the Logging Output pages are completed and merged. Keeping it assigned to Jacob until those pages are done

**Comment by izaac** [comment] 2020-09-22 23:41
@paynejacob just to confirm #1102 and #1103 there won't be a way to generate the secrets from the `Output` and `ClusterOutput`.

The intended behavior should be create a secret first and then select it from the `Output` and `ClusterOutput`

**Comment by paynejacob** [comment] 2020-09-22 23:43
Yes secret creation is not expected to be part of this form.

**Closed** 2020-09-22 23:44 UTC
Labels: [zube]: To Test, area/logging
