### ISSUE TITLE
Vue3: User menu pop-up doesn't close when clicking outside

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#11730] opened 2024-08-27 20:16 UTC
**Screenshots**

https://github.com/user-attachments/assets/b358ac0d-7a14-40f8-a47a-65f5afd3df06

**Comment by rak-phillip** [comment] 2024-08-27 20:21
Closing as a duplicate of #11684. I added this issue as additional information for future reference.

**Closed by rak-phillip** 2024-08-27 20:21 UTC
Labels: kind/bug, QA/dev-automation, area/vue3
