### ISSUE TITLE
Continuous Delivery UI - Reports wrong status

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5402] opened 2022-03-15 14:34 UTC
Internal reference: SURE-4198

On a cluster customer has deployed a GitRepo, and there is one job getting failed and other jobs are successful.

The UI reports all the jobs are failing and not updating the details of successful Jobs.

(more info available internally)

**Comment by Shavindra** [comment] 2022-03-17 18:07
Possible duplicate: https://github.com/rancher/dashboard/issues/4681

**Comment by gaktive** [comment] 2022-04-06 21:51
We'll keep this ticket in lieu of #4681 

Internal reference to track from that ticket: SURE-3568

**Comment by gaktive** [comment] 2022-04-08 15:49
Related backend (from the duplicate ticket): https://github.com/rancher/rancher/issues/36947
Listed as Next Up for 2.6.5 still

**Comment by gaktive** [comment] 2022-06-10 22:18
Based on how tickets have moved around, this ticket is either blocked or dependent on the transferred https://github.com/rancher/dashboard/issues/6117

@Shavindra should we get that ticket onto your backlog/next up soon?

**Comment by aalves08** [comment] 2022-07-15 09:58
Duplicate of https://github.com/rancher/dashboard/issues/6117, so that fix already merged should fix this 🙏

**Comment by brandonsuse** [comment] 2022-07-15 16:23
@AndrewHoffmanQA  Please refer to this duplicate ticket for the reproduction steps: https://github.com/rancher/dashboard/issues/6117

Additionally, just simply provide your results of testing in the comments section of this ticket once you are done testing. Thanks!

**Comment by AndrewHoffmanQA** [comment] 2022-07-19 17:13
**tested on **

**local:**
Rancher version: v2.6-df1b20
Browser type & version: HA helm
rke - v1.3.13-rc3

**result:**
passed
the resource page correctly displayed which cluster was modified

**Comment by AndrewHoffmanQA** [comment] 2022-09-12 18:07
this has been retested and passed. attached a video.  tested on rancher v2.6-68215bc


after following reproduction steps and viewing the fleet section of the UI it was clearly displaying which deployment failed.  closing this ticket. 

https://user-images.githubusercontent.com/89030218/189724940-c3d3beaa-0e3d-43f8-bf86-12439c1ddb5f.mp4

**Closed** 2022-09-12 18:09 UTC
Labels: kind/bug, [zube]: Done, internal, area/fleet, priority/1, team/area3, JIRA
