### ISSUE TITLE
[Cluster Explorer] Apps & Marketplace Version ordering

### ISSUE THREAD

**Issue by mscbpi** [rancher/dashboard#2719] opened 2021-04-18 07:50 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Enhancement

**Steps to reproduce (least amount of steps as possible):**
Go in Apps / Upgrade

**Result:**

Version are listed in alphabetical order, i.e. v2.11 is before v 2.2, 2.3,...2.9.  Should be by version number.
![image](https://user-images.githubusercontent.com/28528210/109950229-98044c80-7cdc-11eb-8dc6-43bf5c2eea65.png)

**Other details that may be helpful:**

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI):
Rancher 2.5.6

Other details IMHO irrelevant.

**Comment by gaktive** [comment] 2021-04-19 15:40
Might be fixed already. If not, should be an easy fix.

**Comment by neillsom** [comment] 2021-05-04 02:14
Appears fixed to me. I don't see any instances different than desired ordering

**Comment by mscbpi** [comment] 2021-05-04 06:24
@neillsom what version ? Have you tested with helm charts having double-digit version ?

Do you have 4.1,4.2,4.3...4.9,4.10,4.11,4.12,5.0 ? (Which is right).

Or 4.1,4.10,4.11,4.2,4.3,...,4.9,5.0 ? (Which is current and wrong).

Old version of Apps (Cluster Manager) menu had it alright.

**Comment by aaronRancher** [comment] 2021-05-04 22:35
Tested on Rancher `master-head` `version 91a6f51`

Versions are in descending order by version number.
![Screen Shot 2021-05-04 at 2 56 56 PM](https://user-images.githubusercontent.com/57409052/117077556-32890800-aced-11eb-96fc-0bffedcfb6ea.png)
![Screen Shot 2021-05-04 at 3 15 16 PM](https://user-images.githubusercontent.com/57409052/117077586-3d439d00-aced-11eb-81cc-bbd4dc015552.png)
![Screen Shot 2021-05-04 at 3 15 37 PM](https://user-images.githubusercontent.com/57409052/117077589-3ddc3380-aced-11eb-9496-d63a144666c8.png)

**Comment by mscbpi** [comment] 2021-05-05 03:58
> Tested on Rancher `master-head` `version 91a6f51`
> 
> 
> 
> Versions are in descending order by version number.
> 
> ![Screen Shot 2021-05-04 at 2 56 56 PM](https://user-images.githubusercontent.com/57409052/117077556-32890800-aced-11eb-96fc-0bffedcfb6ea.png)
> 
> ![Screen Shot 2021-05-04 at 3 15 16 PM](https://user-images.githubusercontent.com/57409052/117077586-3d439d00-aced-11eb-81cc-bbd4dc015552.png)
> 
> ![Screen Shot 2021-05-04 at 3 15 37 PM](https://user-images.githubusercontent.com/57409052/117077589-3ddc3380-aced-11eb-9496-d63a144666c8.png)
> 
> 
> 
> 

@aaronRancher 

These examples do not verify anything.

**Comment by nwmac** [comment] 2021-05-13 08:24
@neillsom Richard is changing the UI for this - so please check with him if this is still relevant

**Comment by neillsom** [comment] 2021-05-14 07:27
@richard-cox This looks like it is fixed in 2.6. Can you comment one way or another?

**Comment by richard-cox** [comment] 2021-05-14 08:58
I can confirm the version list shown in the 2.6 updated Chart Details and Install pages (merged today) is correct. 

From helm repo https://charts.bitnami.com/bitnami - airflow chart
![image](https://user-images.githubusercontent.com/18697775/118247119-b637b700-b49a-11eb-8e3d-1d77980fb251.png)

**Closed by richard-cox** 2021-05-14 08:58 UTC
Labels: [zube]: Working
