### ISSUE TITLE
[Alerting V2 UI] Create default AlertManager Config Secret on deploy

### ISSUE THREAD

**Issue by aiyengar2** [rancher/dashboard#1088] opened 2020-08-25 00:03 UTC
Dashboard should create a Secret in the `cattle-monitoring-system` namespace that is managed outside the `rancher-monitoring` deployment; it should only be created if `Deploy AlertManager` is selected as part of the Alerting V2 Basic Configuration detailed in https://github.com/rancher/dashboard/issues/1015.

Requirements for Secret:
- Name: `alertmanager-rancher-monitoring-alertmanager`
- Labels: `{ "alertmanager_config": "1" }`
- `alertmanager.yaml`: must have the contents of `.Values.alertmanager.config` specified in the deployment.
- Each entry listed in `.Values.alertmanager.templateFiles` of the deployment must be added as a key-value pair on this Secret

The label ensures that this Secret shows up in the Custom UI specified in https://github.com/rancher/dashboard/issues/1017.

If a Secret already exists with this name in the `cattle-monitoring-system` namespace, there is no need to recreate the Secret. There should also be no need for Dashboard to ever delete this Secret once it has been created.

#### Why can't this be done as part of the Helm chart?

This Secret will be the primary way that users interact with setting up notifiers on the Rancher UI, so it is something we potentially expect to be changed frequently by users based on their requirements. 

If the resource is managed by Helm, users will have to redeploy the entire Monitoring stack in order to update this value, which we should try to avoid.

Users could potentially manually create this secret ahead of time and supply it to us, but that would require creating the `cattle-monitoring-system` namespace ahead of time and creating a Secret before even trying to deploy Monitoring / Alerting V2.

**Comment by aiyengar2** [comment] 2020-08-25 00:05
Not sure if there's a better way to handle keeping the `alertmanager.yaml` and other keys in the templateFiles (i.e. `rancher_defaults.tmpl` at the moment) up to date than to just use the values set the first time the user ever deploys this chart. Open to suggestions!

**Comment by jiaqiluo** [comment] 2020-09-08 17:45
the creation of the default secret will be dropped from the UI, instead, the chart will have a pre-install hook that handles it. 

The PR to this issue will be reverted partly/fully.

**Comment by deniseschannon** [comment] 2020-09-17 14:19
Backend has been merged in, so moving this to test.

**Comment by jiaqiluo** [comment] 2020-09-18 00:47
Tested on `master-bcc8261487ecdd37761fc7a010950e4cffd40874-head` 

the secret is created and alter-manger is installed properly 

note that the label ` "alertmanager_config": "1"` mentioned in the issue is no longer needed.

**Closed by jiaqiluo** 2020-09-18 00:47 UTC
Labels: [zube]: To Test
