### ISSUE TITLE
Cluster Dashboard shows empty `Pods` Capacity card

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4630] opened 2021-11-23 11:22 UTC
![image](https://user-images.githubusercontent.com/18697775/143015537-57999618-ebd6-4330-b0f5-bc781e6ef1d2.png)

**Comment by nwmac** [comment] 2021-11-23 12:19
Duplicate of rancher/dashboard#4609

**Closed** 2021-11-23 12:20 UTC
