### ISSUE TITLE
Edit Cluster config show blank page

### ISSUE THREAD

**Issue by tokuzfunpi** [rancher/dashboard#4923] opened 2022-01-14 06:44 UTC
**Setup**
- Rancher version: v2.6.3
- Browser type & version: Chrome v97.0.4692.71

**Describe the bug**
I upgraded Rancher cluster from v2.5 to v2.6.3, after it finished, I want to upgrade k8s version via GUI, but when I tried to click "Edit Config" in cluster management page, the cluster config options didn't show up.

**To Reproduce**
Follow Rancher upgrade flow.

**Result**

**Expected Result**
I could see cluster config settings.

**Screenshots**

https://imgur.com/euhUtQR

**Additional context**

**Detailed Description**

**Context**

**Comment by tokuzfunpi** [comment] 2022-01-14 07:02
I changed to user another chrome browser with same version v97.0.4692.71, and this time the cluster edit settings were showing up.

**Comment by richard-cox** [comment] 2022-01-14 08:49
Screenshot
![euhUtQR](https://user-images.githubusercontent.com/18697775/149486128-6cb1b780-acbc-4cb9-b71f-98e0f7440d6d.png)

The error shown is `defined is not defined`, possibly related to SURE-3886

**Comment by richard-cox** [comment] 2023-11-03 16:53
Closing, could not reproduce with latest Rancher

**Closed by richard-cox** 2023-11-03 16:53 UTC
Labels: kind/bug, [zube]: Done
