### ISSUE TITLE
[BUG] Some functions not working after upgrade rancher to version 2.7.0

### ISSUE THREAD

**Issue by tommy04062019** [rancher/dashboard#7808] opened 2022-12-20 03:52 UTC
**Rancher Server Setup**
- Rancher version: 2.7.0
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.23.14
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? Imported 

**User Information**
- What is the role of the user logged in? Admin

**Describe the bug**
- When install or upgrade version of a service from `Cluster tools` (Ex: Longhorn). Click on `Edit` button but it shows nothing without errors. When using develop tools, some errors on page shows that:
<img width="1266" alt="Screen Shot 2022-12-20 at 10 32 48" src="https://user-images.githubusercontent.com/8014325/208577306-84aff560-f4cf-4a7b-a156-8358bbc20fa4.png">

**Comment by richard-cox** [comment] 2022-12-23 11:42
@tommy04062019 Could you also provide a full screenshot of the browser's console output? That first error is unfortunately a bit of a red herring

**Comment by andrew-welker** [comment] 2023-01-03 22:40
> @tommy04062019 What cloud provider is this running on? We have reproduced this on AKS so far..

I have experienced a similar issue in 2 different clusters: 1 EKS cluster and 1 k3s single-node cluster running on a VM in our network. In my case, I'm attempting to upgrade existing applications installed from our helm chart repository and getting the same symptom, a blank screen with no option to choose a helm chart version. 

In looking in dev tools console, I see the lines 
```
Find: [management] provisioning.cattle.io.cluster undefined
warning: Attempting to load a resource with no id
```

The second line is accompanied by a stack trace. Doing some digging in the repo and based on the stack trace, I think the issue is with this function in `./shell/pages/c/_cluster/apps/charts/install.vue`:
```
async getClusterRegistry() {
      const hasPermissionToSeeProvCluster = this.$store.getters[`management/schemaFor`](CAPI.RANCHER_CLUSTER);

      if (hasPermissionToSeeProvCluster) {
        const mgmCluster = this.$store.getters['currentCluster'];
        const provCluster = mgmCluster ? await this.$store.dispatch('management/find', {
          type: CAPI.RANCHER_CLUSTER,
          id:   mgmCluster.provClusterId
        }) : {};

        if (provCluster.isRke2) { // isRke2 returns true for both RKE2 and K3s clusters.
          const agentConfig = provCluster.spec.rkeConfig.machineSelectorConfig.find(x => !x.machineLabelSelector).config;

          // If a cluster scoped registry exists,
          // it should be used by default.
          const clusterRegistry = agentConfig?.['system-default-registry'] || '';

          if (clusterRegistry) {
            return clusterRegistry;
          }
        }
        if (provCluster.isRke1) {
          // For RKE1 clusters, the cluster scoped private registry is on the management
          // cluster, not the provisioning cluster.
          const rke1Registries = mgmCluster.spec.rancherKubernetesEngineConfig.privateRegistries;

          if (rke1Registries?.length > 0) {
            const defaultRegistry = rke1Registries.find((registry) => {
              return registry.isDefault;
            });

            return defaultRegistry.url;
          }
        }
      }
    },
```
Specifically, this sequence seems to be problematic:

```
const provCluster = mgmCluster ? await this.$store.dispatch('management/find', {
          type: CAPI.RANCHER_CLUSTER,
          id:   mgmCluster.provClusterId
        }) : {};
```

I'm guessing that `mgmCluster` is coming up as `undefined`, which then causes the `id` field for the find request from the store to be undefined, thus causing the issues.

**Comment by richard-cox** [comment] 2023-01-04 09:50
Thanks for the additional information @andrew-welker , the tertiary check though should mean an undefined `mgmCluster` should fall through to the empty object `{}`.

For whoever picks this up, we should address https://github.com/rancher/dashboard/issues/7833 at the same time

**Comment by andrew-welker** [comment] 2023-01-04 10:50
> Thanks for the additional information @andrew-welker , the tertiary check though should mean an undefined `mgmCluster` should fall through to the empty object `{}`.
> 
> For whoever picks this up, we should address https://github.com/rancher/dashboard/issues/7833 at the same time

Whoops, you're right. I misread that.

Let me correct myself: based on the console messages I saw, the `mgmtCluster` is defined, but missing the `provClusterId` property.

**Comment by richard-cox** [comment] 2023-01-05 13:24
Linking to SURE-5732

**Comment by gaktive** [comment] 2023-01-11 18:15
This is turning to a blocker for at least one user, so we need a workaround.

**Comment by catherineluse** [comment] 2023-01-11 19:35
The workaround should be to install/upgrade the app from the Apps > Charts page instead of Cluster Tools.
<img width="1429" alt="Screenshot 2023-01-11 at 12 34 27 PM" src="https://user-images.githubusercontent.com/20599230/211901046-3c476f43-0bd2-4a84-928e-fba86af7ad44.png">

**Comment by catherineluse** [comment] 2023-01-12 04:23
I'm having difficulty reproducing this one. In v2.7-head, I tried an imported RKE2 cluster with K8s v1.23. But it seemed to be working.

**Comment by catherineluse** [comment] 2023-01-12 04:53
I noticed that the faulty block of code is in the `getClusterRegistry` getter. But the thing is, it is not possible for an imported or hosted Kubernetes cluster to have a cluster scoped registry because those are only available for node driver clusters. The UI code should not attempt to get a cluster registry for non-applicable cluster types.

**Comment by nwmac** [comment] 2023-01-17 09:17
@tommy04062019 Could you expand on the steps to reproduce this, please, since we are having trouble doing so.

Tried:

- Install Rancher 2.6.9 via docker
- Deployed k3s (1.23) onto a VM
- Imported k3s cluster into Rancher
- Installed Monitoring and Longhorn into the imported cluster
- Upgrade Rancher to 2.7.0
- Edit either of the deployed apps in the imported cluster - unable to get the blank page

**Comment by richard-cox** [comment] 2023-02-23 08:33
Linking https://github.com/rancher/dashboard/issues/7789, that should be validated at the same time

**Comment by JohnnyCarlsson** [comment] 2023-03-31 13:28
> @tommy04062019 Could you expand on the steps to reproduce this, please, since we are having trouble doing so.
> 
> Tried:
> 
> * Install Rancher 2.6.9 via docker
> * Deployed k3s (1.23) onto a VM
> * Imported k3s cluster into Rancher
> * Installed Monitoring and Longhorn into the imported cluster
> * Upgrade Rancher to 2.7.0
> * Edit either of the deployed apps in the imported cluster - unable to get the blank page

Although it looks like this will be fixed in 2.7.2 (hoping since this is now a blocking us from upgrading from 2.6 to 2.7) I'd like to add steps where i'm able to reproduce this every time.

* Install Rancher 2.7.1 on k3s cluster
* Deploy k3s cluster on "something" (personally using k3s cluster via Rancher Desktop)
* Import cluster into Rancher with **fleetWorkspaceName** set to a custom workspace instead of the default **fleet-default**
* Wait for cluster to import and become active in Rancher.
* Try to install any app using the Rancher UI, all of them result in a blank page.

If i don't set the **fleetWorkspaceName** to a custom workspace and have it join the fleet-default one then i don't experience this bug.

Since we use custom workspaces this is blocking us, a potential workaround would've been to let the cluster join the fleet-default workspace and then move it into the custom one, however that doesnt work either since we are hitting this issue:
https://github.com/rancher/rancher/issues/36132

**Comment by richard-cox** [comment] 2023-03-31 13:35
@ronhorton Would you be able to include @JohnnyCarlsson steps when verifying this fix?

**Comment by BiggA94** [comment] 2023-04-03 18:37
I can also confirm this is fixed for us.

We had a gke cluster with the old GKE driver.
I have started the dashboard in devmode (2.7.2 branch) and it is showing me the Helm App I want to upgrade.

Some things to consider:
We have our cluster that is not working in the fleet-default workspace, while others that have their own fleet-namespace are working all the time.

In case somebody also needs a workaround, since there are no prod updates possible:
Clone https://github.com/rancher/dashboard.git
(make sure to have node <=16, since there is a problem with the crypto library)
run `yarn install`
(for me source was not working on my ubuntu 22 server, so i removed the "source" from the package.json dev task)
run `API=https://my.rancher.server.com yarn dev`

**Comment by ronhorton** [comment] 2023-04-07 21:27
**Pass** Verified in rancher `v2.7-head commit ID 1712bf9`
1. installed rancher on k3s cluster
2. created downstream k3s cluster
3. imported cluster > custom namespace
4. cluster imported successfully
5. installed rancher-monitoring-102.0.0-up40.1.2

`successfully installed; no errors observed`

**Closed** 2023-04-07 21:27 UTC
Labels: kind/bug, internal, priority/0, QA/XS, [zube]: QA Working, team/area3, size/2
