### ISSUE TITLE
(SURE-5536) Labels and max surge options are also not available in the Rancher UI.

### ISSUE THREAD

**Issue by kkaempf** [rancher/dashboard#8093] opened 2023-02-03 14:02 UTC
https://jira.suse.com/browse/SURE-5536

A priority issue for customer

need-ui

**Comment by richard-cox** [comment] 2023-02-03 15:12
Closing as duplicate of https://github.com/rancher/dashboard/issues/8073

**Closed by richard-cox** 2023-02-03 15:12 UTC
Labels: [zube]: Done, JIRA
