### ISSUE TITLE
Sortable Table sort icons wrap from the column name

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7264] opened 2022-10-24 10:48 UTC
See example below.

Look at the 'Roles' column - the sort icons have wrapped below the column title, which looks poor. They should not wrap like this.

![image](https://user-images.githubusercontent.com/1955897/197509281-12ca796c-56ff-46eb-93b3-93e8089b6c1d.png)

Adding a `display: content` to the enclosing span should fix this.

**Comment by jameson-mcghee** [comment] 2022-12-13 22:10
@torchiaf @nwmac, when testing on `v2.6.7` I have been unable to reproduce the reported issue of the _Role_ (and other) column sort arrow wrapping when screen resolution has been reduced. Is there something else I should try to reproduce this issue?

**Reduced Browser Window:**
![image](https://user-images.githubusercontent.com/13294321/207454652-a70508db-8132-43e4-b76d-1a9690f58aa5.png)

Reduced Browser Window and Increasing Browser Console Encroachment:
![image](https://user-images.githubusercontent.com/13294321/207454802-ffb85497-71ba-41fa-9555-c2571840ca2b.png)
![image](https://user-images.githubusercontent.com/13294321/207454823-155f3c6a-6da9-4ec7-864e-8a3ca5d363e3.png)

**Comment by torchiaf** [comment] 2022-12-14 09:04
Below, the steps to reproduce the bug (Chrome browser):

1. Click on the Restore button to the browser to resize the window.
2. Resize the window until the icons on the columns headers are wrapped.

![columns-wrap-see-roles-column](https://user-images.githubusercontent.com/26394656/207552493-4a955a81-e164-4799-b098-b9c51ac9ddb4.gif)

**Comment by jameson-mcghee** [comment] 2022-12-14 19:59
I was able to reproduce this issue on `v2.7.0-rc5` as was mentioned by @torchiaf, and I was also able to verify that this issue does not reproduce on `v2.7-head` (Commit ID: af68a57). Therefore I am closing this ticket.

**`v2.7.0-rc5`:**
![image](https://user-images.githubusercontent.com/13294321/207701790-02b1be20-553c-4fe0-ae25-64d8964438f1.png)

**`v2.7-head` (Commit ID: af68a57):**
![image](https://user-images.githubusercontent.com/13294321/207701849-a07bc2f7-44d4-4af4-aa0c-4c79da502037.png)

**Closed by jameson-mcghee** 2022-12-14 19:59 UTC
Labels: kind/bug, [zube]: To Test, QA/XS, good-first-issue, team/area2
