### ISSUE TITLE
`Enable IPv6 support` does not work with RKE2 + Cilium

### ISSUE THREAD

**Issue by masap** [rancher/dashboard#10047] opened 2023-11-17 01:09 UTC
Internal reference: SURE-7260

**Setup**
- Rancher version: 2.7.9
- Rancher UI Extensions:
- Browser type & version: Firefox 119.0.1 (64 bit)

**Describe the bug**
Enable IPv6 with Rancher UI but `enable-ipv6` is `false`.

```
$ kubectl -n kube-system get cm cilium-config -o json | jq '.data."enable-ipv6"'
"false"
```

**To Reproduce**
Enable IPv6 with Rancher UI and check the value with trailing command.

```
$ kubectl -n kube-system get cm cilium-config -o json | jq '.data."enable-ipv6"'
```

**Result**
```
"false"
```

**Expected Result**
```
"true"
```

**Screenshots**
![rke2-cilium-ipv6](https://github.com/rancher/dashboard/assets/1505016/f7c4ef7a-67aa-421b-af1a-fdf5cb755d08)

**Additional context**

**Comment by gaktive** [comment] 2023-11-23 00:21
Internal reference: SURE-7260
As noted, there is a PR already for us to review.

**Comment by izaac** [comment] 2024-01-23 21:58
The automated test is enough to validate the spec is sent correctly. This would need manual validation on an actual cluster.

**Comment by momesgin** [comment] 2024-07-08 20:38
I tested it with RKE2 Digital Ocean and I was able to get `"true"` after running the command in the description.

But I found a problem, if you enable ipv6 during the creation process your cluster get stuck in updating status: `waiting for cluster agent to connect`. You can still enable ipv6 later on without causing an issue. This is not happening in 2.8.

I compared the payloads of 2.8 and 2.9 and Cilium's related configs were the same, so UI probably hasn't caused a regression.

2.8:

```
{
    "type": "provisioning.cattle.io.cluster",
    "metadata": {
        "namespace": "fleet-default",
        "name": "mo-test-2-8"
    },
    "spec": {
        "rkeConfig": {
            "chartValues": {
                "rke2-cilium": {
                    "cilium": {
                        "ipv6": {
                            "enabled": true
                        }
                    }
                }
            },
            "upgradeStrategy": {
                "controlPlaneConcurrency": "1",
                "controlPlaneDrainOptions": {
                    "deleteEmptyDirData": true,
                    "disableEviction": false,
                    "enabled": false,
                    "force": false,
                    "gracePeriod": -1,
                    "ignoreDaemonSets": true,
                    "skipWaitForDeleteTimeoutSeconds": 0,
                    "timeout": 120
                },
                "workerConcurrency": "1",
                "workerDrainOptions": {
                    "deleteEmptyDirData": true,
                    "disableEviction": false,
                    "enabled": false,
                    "force": false,
                    "gracePeriod": -1,
                    "ignoreDaemonSets": true,
                    "skipWaitForDeleteTimeoutSeconds": 0,
                    "timeout": 120
                }
            },
            "machineGlobalConfig": {
                "cni": "cilium",
                "disable-kube-proxy": false,
                "etcd-expose-metrics": false
            },
            "machineSelectorConfig": [
                {
                    "config": {
                        "protect-kernel-defaults": false
                    }
                }
            ],
            "etcd": {
                "disableSnapshots": false,
                "s3": null,
                "snapshotRetention": 5,
                "snapshotScheduleCron": "0 */5 * * *"
            },
            "registries": {
                "configs": {},
                "mirrors": {}
            },
            "machinePools": [
                {
                    "name": "pool1",
                    "etcdRole": true,
                    "controlPlaneRole": true,
                    "workerRole": true,
                    "hostnamePrefix": "",
                    "labels": {},
                    "quantity": 1,
                    "unhealthyNodeTimeout": "0m",
                    "machineConfigRef": {
                        "kind": "DigitaloceanConfig",
                        "name": "nc-mo-test-2-8-pool1-lf86l"
                    },
                    "drainBeforeDelete": true
                }
            ]
        },
        "machineSelectorConfig": [
            {
                "config": {}
            }
        ],
        "kubernetesVersion": "v1.28.11+rke2r1",
        "defaultPodSecurityPolicyTemplateName": "",
        "defaultPodSecurityAdmissionConfigurationTemplateName": "",
        "cloudCredentialSecretName": "cattle-global-data:cc-22gq5",
        "localClusterAuthEndpoint": {
            "enabled": false,
            "caCerts": "",
            "fqdn": ""
        }
    }
}

```

2.9:

```
{
   "type": "provisioning.cattle.io.cluster",
  "metadata": {namespace: "fleet-default", name: "mo-test-2-9"},
  "spec": {
    "rkeConfig": {
        "chartValues": {
            "rke2-cilium": {
                "ipv6": {
                    "enabled": true
                }
            }
        },
        "upgradeStrategy": {
            "controlPlaneConcurrency": "1",
            "controlPlaneDrainOptions": {
                "deleteEmptyDirData": true,
                "disableEviction": false,
                "enabled": false,
                "force": false,
                "gracePeriod": -1,
                "ignoreDaemonSets": true,
                "skipWaitForDeleteTimeoutSeconds": 0,
                "timeout": 120
            },
            "workerConcurrency": "1",
            "workerDrainOptions": {
                "deleteEmptyDirData": true,
                "disableEviction": false,
                "enabled": false,
                "force": false,
                "gracePeriod": -1,
                "ignoreDaemonSets": true,
                "skipWaitForDeleteTimeoutSeconds": 0,
                "timeout": 120
            }
        },
        "dataDirectories": {
            "systemAgent": "",
            "provisioning": "",
            "k8sDistro": ""
        },
        "machineGlobalConfig": {
            "cni": "cilium",
            "disable-kube-proxy": false,
            "etcd-expose-metrics": false
        },
        "machineSelectorConfig": [
            {
                "config": {
                    "protect-kernel-defaults": false
                }
            }
        ],
        "etcd": {
            "disableSnapshots": false,
            "s3": null,
            "snapshotRetention": 5,
            "snapshotScheduleCron": "0 */5 * * *"
        },
        "registries": {
            "configs": {},
            "mirrors": {}
        },
        "machinePools": [
            {
                "name": "pool1",
                "etcdRole": true,
                "controlPlaneRole": true,
                "workerRole": true,
                "hostnamePrefix": "",
                "labels": {},
                "quantity": 1,
                "unhealthyNodeTimeout": "0m",
                "machineConfigRef": {
                    "kind": "DigitaloceanConfig",
                    "name": "nc-mo-test-2-9-pool1-6hjs8"
                },
                "drainBeforeDelete": true
            }
        ]
    },
    "machineSelectorConfig": [
        {
            "config": {}
        }
    ],
    "kubernetesVersion": "v1.30.2+rke2r1",
    "defaultPodSecurityAdmissionConfigurationTemplateName": "",
    "cloudCredentialSecretName": "cattle-global-data:cc-z8bnm",
    "localClusterAuthEndpoint": {
        "enabled": false,
        "caCerts": "",
        "fqdn": ""
    }
}
}


```
@nwmac should we move this to Done and create a new issue for this problem?

**Comment by momesgin** [comment] 2024-07-09 17:29
@yonasberhe23 @IsaSih I discussed this with @nwmac , and he pointed out that the reason I didn't see the problem in 2.8, as mentioned in my previous comment, is due to IPv6 not being enabled because of the wrong payload being sent. Therefore, IPv6 has never been working in 2.8 either.

Now that sending the correct payload causes the cluster to get stuck in the updating state, we can't be certain if this is an issue with our backend or something related to DO that prevents enabling IPv6 during setup. I am moving this issue to QA blocked.

**Comment by IsaSih** [comment] 2024-07-11 19:35
Should we assign this to the backend team then?

**Comment by gaktive** [comment] 2024-07-19 17:11
Per @rancher-max, there may be an AWS environment with IPv6 available in us-west-1 to test on so we can rule out DO if we can connect there.

**Comment by IsaSih** [comment] 2024-07-24 08:05
I have verified this with @rancher-max and indeed, the UI correctly sends to the backend the correct field. I'll then close the issue, and I'll file a backend issue to address the failure in provisioning the dual stack cluster
<img width="602" alt="Screenshot 2024-07-24 at 01 02 47" src="https://github.com/user-attachments/assets/74610c64-46fc-43f1-9976-b028b202b1d0">

**Closed by IsaSih** 2024-07-24 08:05 UTC
Labels: kind/bug, status/dev-validate, JIRA, QA/manual-test
