### ISSUE TITLE
[release-2.4] create gatekeeper constraint through yaml throw js error

### ISSUE THREAD

**Issue by ly5156** [rancher/dashboard#3431] opened 2021-07-09 02:44 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce (least amount of steps as possible):**
1. go to `OPA Gatekeeper > Constraint` page, click `Create From Yaml` button
2. click `Save` button

**Result:**
throw javascript  error on browser console

![image](https://user-images.githubusercontent.com/3406205/125015207-9dfea580-e0a1-11eb-9301-95cc6f832261.png)
![image](https://user-images.githubusercontent.com/3406205/125015303-d3a38e80-e0a1-11eb-82a1-4205221fa5dd.png)

**Environment information**
- Rancher version: rancher/rancher:v2.4.15

**Comment by gaktive** [comment] 2021-07-09 15:58
Dashboard wasn't GA with 2.4.x so from what I understand, there are a lot of similar issues with a then-unsupported UI.

UI will verify if this is still an issue with 2.5.x and ensure that for 2.6 at least, this error doesn't appear.

**Comment by richard-cox** [comment] 2021-07-15 11:30
I could not reproduce this issue on 2.5.8 or 2.6 (though i did hit a refresh issue - #3479). So as 2.4.x dashboard is unsupported and we don't have any plans for releasing a 2.4 dashboard, I'll close the issue.

**Closed by richard-cox** 2021-07-15 11:30 UTC
Labels: kind/bug
