### ISSUE TITLE
Error when changing volume name when adding volume to container

### ISSUE THREAD

**Issue by Mirokko** [rancher/dashboard#4052] opened 2021-08-27 13:50 UTC
Hello!

Here is how i can repeat my problem:
1. Navigate to /dashboard/c/local/explorer/apps.deployment/create#storage
2. Click on 'Add Volume'
3. Click on 'Create Persistent Volume Claim'
4. Type any letter or change somehow 'Volume Name' field.

Result:
Persistent Volume Claim dialog is closed as if you clicked close button and this error in console:
![image](https://user-images.githubusercontent.com/11059471/131136659-751b8912-97be-468d-94dd-628efd9b6ca9.png)

**Comment by Mirokko** [comment] 2021-08-28 09:54
My installation method is just `curl -sfL https://get.rancher.io | INSTALL_RANCHERD_VERSION=v2.5.9 sh -`

**Comment by Mirokko** [comment] 2021-09-03 11:31
As i tested it in 2.6.0, it is working fine. So simple solution to this error is just upgrade

**Comment by nwmac** [comment] 2021-09-10 14:55
QA: Looks like this was fixed in 2.6.0 - just need to confirm

**Comment by davidnuzik** [comment] 2021-09-17 23:59
**My checks PASSED**
Confirmed I could not reproduce this issue with Rancher v2.6.0 and latest v2.6 (v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific)
 
**Reproduction Steps:**

Not required.

-----
 
**Validation Environment:**

Rancher version: v2.6.0 and also checked v2.6-head `1a57856` pulled 9/17/21 ~9:30am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

0. Have the browser dev tools open - watch the console
1. Explore the local rancher cluster (cluster explorer)
2. On the left nav pane, click on Workload > Deployments and click the create button.
3. On the Create Deployment form, click on Storage below and click on Add Volume - pick Create Persistent Volume Claim
4. Now, enter anything into the "VolumeName" field - modify it basically.
Can confirm there is no error now in the browser console.

**Closed by davidnuzik** 2021-09-17 23:59 UTC
Labels: [zube]: QA Working
