### ISSUE TITLE
[Harvester] Namespaces present in the harvester cluster eg: rancher-server and harvester-public are not present in any of the Rancher projects like System,Default project

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4348] opened 2021-10-07 18:02 UTC
- We have some namespaces in the Harvester Cluster like rancher-server and harvester-public which are not present in any of the Rancher provided projects eg: System, Default
Virtualization management --> Harvester cluster --> Projects/namespaces
- The namespaces can be moved to rancher provided projects as applicable and can be referred via Projects accordingly from the namespace picker for a better hierarchy.

Additional context
In rancher server the upstream and downstream clusters, we have namespaces separated by projects for a better hierachy of the workloads .

Harvester issue: https://github.com/harvester/harvester/issues/1378

**Comment by guangbochen** [comment] 2021-11-01 04:08
This is by design as when the downstream Harvester cluster only uses namespace instead of a project, and while creating those namespaces it is not imported to the upstream Rancher so no project should be assigned. 
If needed, users can move the ns to the appropriate project manually by themselves. Close it for now and feel free to reopen it if u have further questions, thanks.

**Closed by guangbochen** 2021-11-01 04:08 UTC
Labels: area/harvester, kind/bug-qa, status/waiting-harvester
