### ISSUE TITLE
AlertmanagerConfig doesn't appear to save dropdown fields on Rancher v2.6

### ISSUE THREAD

**Issue by nflynt** [rancher/dashboard#8324] opened 2023-03-02 16:30 UTC
**Setup**
- Rancher version: `v2.6-head`, and also `v2.6.11-rc9`
- Browser type & version: Google Chrome `110.0.5481.177`, Mozilla Firefox `109.0.1`
- Monitoring Chart version: `100.2.0+up40.1.2`

This bug was tested also in `v2.7-head` and is **not** present in the newer version; dropdowns behave correctly in v2.7.

**Describe the bug**
When editing email receivers under Monitoring->AlertManagerConfig, it seems that all of the form fields are saving correctly except for dropdown elements, which affects secret selection. The form _appears_ to save correctly, but the contents of the dropdown do not make it into the resulting `.yaml` configuration.

**To Reproduce**
First, create a secret under Storage->Secrets. Create a new AlertManageConfig, then add an email receiver. Along with the other required information, attempt to select the secret you created, along with the key. Then save the receiver. 

**Result**
To verify the buggy behavior, open the created receiver back up and inspect the Email configuration; now the dropdown is empty.

This bug also occurs when editing existing receivers. If the `.yaml` already contains valid secret configuration then this is correctly populated into the dropdown, but any _changes_ to the dropdowns still do not save. In this case, it's impossible to switch to a different secret using the form alone. To workaround, one must hand-edit the YAML config instead.

**Expected Result**
The value the user enters into the form should be the value that is saved in the underlying `.yaml`

**Screenshots**
![email_receiver_broken_dropdowns](https://user-images.githubusercontent.com/122321752/222487736-69e8a03d-e943-4472-aa45-4ab93f02dc40.gif)

**Additional context**
I bumped into this while investigating SURE-4788 and believe it to be related.

**Comment by gaktive** [comment] 2023-03-02 21:19
Putting this into 2.6.x since this doesn't look like a blocker for 2.6.11. @nflynt correct me if I'm wrong since you've mentioned this in a backend blocker: https://github.com/rancher/rancher/issues/40307

**Comment by gaktive** [comment] 2023-03-02 22:20
@nflynt do you know what this was like in 2.6.9 or 10? We're curious if this is a regression or not.

**Comment by rak-phillip** [comment] 2023-03-02 22:30
This is definitely a bug, but I'm not seeing a regression. I'm able to reproduce the same behavior in 2.6.10 & 2.6.11.

**Comment by nflynt** [comment] 2023-03-02 22:57
I've not been able to reproduce it in `v2.6.5` specifically, but I haven't had time to try on any of the inbetween versions yet. Notably `v2.6.5` only has up to monitoring chart `100.1.3+up19.0.3` available due to k8s version requirements for the newer charts. I'm no longer convinced this dropdowns thing is causing https://github.com/rancher/rancher/issues/40307, that seems to be something else entirely.

**Comment by MKlimuszka** [comment] 2023-03-02 23:12
Doubtful it's a blocker. Nicholas found it while doing phase 1 reproduction on a ticket that has been open since June of 2022.

**Comment by gaktive** [comment] 2023-03-02 23:19
On the forensic side of what happened, @mantis-toboggan-md found that we had a fix in 2.6.7 for this but this broke with a Harvester update later on. So not a true regression but something that broke since it first came in.

https://github.com/rancher/dashboard/pull/8327 will refix this. @bmdepesa to let us know if this can sneak into 2.6.11 based on QA capacity.

**Comment by gaktive** [comment] 2023-03-03 17:48
Based on QA workload, this won't make it into 2.6.11. Holding in 2.6.x for now.

**Comment by gaktive** [comment] 2023-03-21 19:13
This is go for 2.6.next2.

**Comment by rak-phillip** [comment] 2023-03-21 19:36
Merged fix into `release-2.6` branch.

**Closed** 2023-04-18 17:00 UTC
Labels: kind/bug, [zube]: QA Working, team/area3, regression, area/monitoring-alerting
