### ISSUE TITLE
Cluster Provisioning through Node Provisioning - RKE2 Azure

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2166] opened 2021-01-05 18:24 UTC

**Comment by thehejik** [comment] 2021-06-15 13:46
**Test report:**
I was able provision RKE2 cluster on Azure by using default values from `Cluster Management` (explorer) on `rancher/rancher:master-head 66c31dd`. The cluster is reported as `Active` running k8s `v1.21.1-rc2+rke2r1` and consisting from 2 nodes/pools - 1 node with `etcd+cp` roles and 1 node with `worker` role. 

I'm using default values - only changed `Resource Group` name to be unique - default was `docker-machine`. I was using the same RG for both pools.

Used default region `westus` and image `canonical:UbuntuServer:18.04-LTS:latest`.

* I was able to SSH into nodes by selecting `SSH Shell..` in `Cluster Management -> Advanced -> Machines -> ...`
* SSH keys can be dowloaded from there ^ as well
* Tried successfully to scale up machines count within one pool by pressing `Edit Config` for the cluster in Cluster Management and changing the Machines count.
* All (almost see below) k8s/RKE2 resources seems to be ok
* When Azure credentials are not defined it will first display a dialog for creating the credentials and then it will continue to the wizard
* When Azure credentials are created they are preselected in the wizard

**Found 2 issues:**
* Nodes are still present in Machines list after cluster removal from Rancher, tracked here https://github.com/rancher/dashboard/issues/3242
* Pods on RKE2 cluster are running apart one of the kube-system pods, issue tracked here https://github.com/rancher/dashboard/issues/3240 (not reproduced on single-node cluster)

Other than that it works ok.
![azure_provisioning](https://user-images.githubusercontent.com/12828077/122063334-755ff480-cdf0-11eb-90b3-8dee20ee19a1.png)

**Comment by thehejik** [comment] 2021-06-16 11:28
I have tried various combination of the pools and their roles:
- single-node with all roles + scalingup to 3 nodes OK
- 1 node with etcd+cp roles, 1 worker node OK
- 3 nodes with etcd+cp roles, 3 worker node OK
- 1 node per role (1cp, 1etcd, 1worker) **FAILED**, reported here https://github.com/rancher/rancher/issues/33213#issuecomment-862298503

**Comment by thehejik** [comment] 2021-06-16 15:26
Closing as it basically works and the bugs are opened.

Known bugs list:
https://github.com/rancher/rancher/issues/33213
https://github.com/rancher/rancher/issues/33197
https://github.com/rancher/rancher/issues/33196 (CLOSED)

**Closed by thehejik** 2021-06-16 15:26 UTC
Labels: QA/S, [zube]: To Test, tmp-clusterprov
