### ISSUE TITLE
EKS: Allow managed node group warning to be cleared

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9618] opened 2023-08-29 22:45 UTC
Internal reference: SURE-3752
Reported in 2.5.9 & 2.7.5

Request description:
Allow the warning for 'Cluster must have at least one managed nodegroup' to be cleared, or informational

Actual behavior:
Red warning is always present in the UI

Expected behavior:
When the cluster is functioning as usual, cluster-agent is deployed and there are nodes registered, the warning is unnecessary.

This could also be confirmed via the EKS API endpoint or detecting a cluster-agent tunnel connection, if it was able to be cleared this would provide a way for users to remove the warning.

Workaround:
Kind of: add a managed node group

![Screenshot 2023-08-29 at 1.56.00 PM.png](https://zube.io/files/rancher/0a5c61dcff4e689b4d5181a1214a5ec9-screenshot-2023-08-29-at-1-56-00-pm.png)

**Comment by gaktive** [comment] 2023-10-25 15:35
Per UI analysis, all the info comes from the backend, so if an error appears, they should be useful. If it's informational, we shouldn't show it as red and then figure out the logic to clear it.

**Comment by richard-cox** [comment] 2023-10-25 15:39
I think we shouldn't remove the message, but if the state is not an error avoid showing the state and message in red.

We should work out how the prov cluster determines state and double check with the customer what the values they see which creates this state. If the info we receive indicates it's an error we need the operator side to fix. If the info indicates it's not an error we need to tweak how we deduce the colour

**Comment by salasberryfin** [comment] 2023-12-14 14:47
I've been able to reproduce this behavior when importing an EKS cluster with no managed node groups. I understand the issue is that this could be shown as a warning when importing a cluster that uses self-managed node groups. As @richard-cox mentioned it would be great to know what cluster configuration is generating these values. Would converting this red warning into an informational text (as in "Waiting for API to be available" from the screenshot) be more useful? I've tried to do so but haven't been able to get rid of the red color by updating the message from the backend, is that something that is done on the ui side?

**Comment by richard-cox** [comment] 2023-12-14 16:34
@salasberryfin i had a quick look and for eks we'll look at the `management.cattle.io.cluster` `metadata.state.error` property. If that's `true` the status will be red. Would you be able to confirm if that's what you see?

**Comment by salasberryfin** [comment] 2023-12-18 09:55
@mjura and I investigated this issue and found some relevant details:

- We have validated that, if the EKS cluster uses self-managed node groups, Rancher is able to deploy the agent to the existing instances and appear as `Active` in the dashboard. When the number of instances in the self-managed node group is set to 0, or instances are not properly associated with the cluster, the agent won't be deployed and the cluster will be `Waiting`. The screenshot in the original issue, shows that `moon-imported` has 0 machines available, which is most likely the root cause of the issue.
- Even though the agent can be deployed when there are no managed node groups, the cluster specification is designed to use this type of compute for EKS clusters, so behavior may be unstable in specific situations.

Furthermore, **the design docs state that only using managed node groups is supported** in EKS. You can read about this decision [here](https://confluence.suse.com/display/RMI/Kontainer+Engine+2.0+-+Design+Doc).

**Comment by salasberryfin** [comment] 2024-01-17 08:46
Hello @nwmac. [This](https://github.com/rancher/rancher/pull/43881) is @mjura's PR addressing this issue. We expect this to remove the warning when no managed node groups are provisioned by checking if the agent is deployed.

**Comment by nwmac** [comment] 2024-01-17 09:25
Closing this issue since backend fix will take care of it

**Closed** 2024-01-17 09:25 UTC
Labels: [zube]: Done, kind/enhancement, size/1, JIRA, team/highlander
