### ISSUE TITLE
Status changes on the nodes dont show up until the page is refresh

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3962] opened 2021-08-23 00:41 UTC
**On 2.6-head commit id: `8898bf8`**

- Deployed a DO RKE2 cluster with a worker only nodepool with multiple nodes.
- Scale down the node on the UI
- The Node remains in Active state, and get removed from the UI from the cluster.
- Refresh the page
- The status of the node changes from Running --> deleting --> Deleted when the node is scaled down.
- If there is no refresh, there is no change in status of the nodes

**Comment by gaktive** [comment] 2021-08-23 16:11
@sowmyav27 are you moving from the Machines page to the Scaling page as part of these steps?

**Comment by mantis-toboggan-md** [comment] 2021-08-24 15:22
I wasn't able to reproduce this; I see node status change as soon as I start scaling down the pool. I double-checked the kube nodes page as well and that appears to be updating too. 

>The status of the node changes from Running --> deleting --> Deleted when the node is scaled down.

@sowmyav27 (after a refresh) does the node with Deleted status stay in the list or does it eventually go away as expected?

**Comment by anupama2501** [comment] 2021-09-02 22:42
I'm able to reproduce this issue. 

1. Created an rke2 cluster with a worker pool having 3 worker nodes.
2. once all the nodes are active from the cluster management --> cluster --> machine pools --> scale down worker nodes
3. I do not see  status on the worker change for a very long time and if we refresh the page, we can then see the node will have the status `deleted` and gets deleted.

**Comment by mantis-toboggan-md** [comment] 2021-11-16 18:24
> Also seeing the following issue:
> 
> 1. Scale up the worker nodes from the above pool to more than the existing count.
> 2. Once all nodes are active, scale down 1 of the nodes [no status is changed]
> 3. Refresh and see the node gets deleted
> 4. Remove 1 more node and see the previously deleted node's status appear as `deleted` along with the current node that is being deleted
> 
>  Screen.Recording.2021-09-02.at.3.49.46.PM.mov

I was able to repro this reappearing-node issue as well; I see websocket messages with the already-deleted node come through when other changes are made to the pool.

**Comment by gaktive** [comment] 2021-11-17 23:47
This will take more time to solve, so pushing to 2.6.4

**Comment by catherineluse** [comment] 2022-01-31 20:39
Since this change involves the UI not updating, I wonder if it could be caused by Chrome not updating pages properly when self-signed certs are used. See Jason's comment https://github.com/rancher/dashboard/issues/3936#issuecomment-1022772061

**Comment by nwmac** [comment] 2022-03-07 10:07
@gaktive I think we'll need to push this to 2.6.5 - I don't think this is a release blocker - its been around for a while.

**Comment by rak-phillip** [comment] 2022-03-07 20:53
I've been trying to force a scenario that would prove to me that this issue occurs in an insecure environment vs. one with a valid cert and I've been unable to force this kind of behavior in either scenario. I'll keep running tests to see if I perhaps need a longer amount of time to allow the problem to arise..

**Comment by catherineluse** [comment] 2022-03-07 20:55
Are you testing it in Chrome? Jason Vernon said the issue was specific to Chrome

**Comment by sowmyav27** [comment] 2022-03-07 22:34
@nwmac Since RKE2 GA is in 2.6.4, wouldn't this be a release-blocker?

**Comment by rak-phillip** [comment] 2022-03-09 15:29
Thanks @catherineluse, I was using Firefox and switched to Chrome. but I still can't reproduce. I'm not seeing any indication that this might be caused by working with self-signed certs.

@sowmyav27 @anupama2501 are you able to reproduce/provide us with an environment where we can better troubleshoot? Do you remember if you were testing in an environment that had valid SSL certs?

**Comment by anupama2501** [comment] 2022-03-11 00:47
@rak-phillip I tried this on a setup with self-signed certs on firefox. I do not see the issue anymore. I see the node status change from deleting to deleted and when we scale down, previously deleted node doesn't appear.

Closing this issue for now and will re open if we reproduce it again.

**Closed** 2022-03-11 00:48 UTC
Labels: [zube]: Done, status/release-blocker, kind/bug-qa, team/area1
