### ISSUE TITLE
"Create from yaml" and "Create" buttons are stuck to each other in Secrets page

### ISSUE THREAD

**Issue by soumyalj** [rancher/dashboard#614] opened 2020-05-06 18:53 UTC
Version: master-head((7b948b289)

Steps:

1. From the dashboard, navigate to "Secrets" tab.
"Create from yaml" and "Create" buttons are stuck to each other. The buttons should be placed with some space between them.

![Screen Shot 2020-05-06 at 11 48 42 AM](https://user-images.githubusercontent.com/18536626/81216552-ee571080-8f8f-11ea-87cd-a5ba0ebcabdb.png)

**Comment by deniseschannon** [comment] 2020-05-06 20:43
Duplicate of https://github.com/rancher/dashboard/issues/598

**Closed by deniseschannon** 2020-05-06 20:43 UTC
Labels: kind/bug
