### ISSUE TITLE
Sortable Table: Column heading should respect column alignment

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#7265] opened 2022-10-24 10:49 UTC
Look at the 'age' column in the example below.

The heading is left-aligned but the column row content is right-aligned.

The heading should align the same as the content.

**Comment by gaktive** [comment] 2022-12-01 16:39
@kwwii to confirm how this looks but namely, this should all be left aligned.

**Comment by gaktive** [comment] 2023-02-02 17:22
This could connect with other work tied to table columns.

**Comment by eva-vashkevich** [comment] 2023-06-22 19:08
Duplicate of [#7560](https://github.com/rancher/dashboard/issues/7560) 
Fixed by https://github.com/rancher/dashboard/pull/7577

**Closed by eva-vashkevich** 2023-06-22 19:08 UTC
Labels: [zube]: To Triage, kind/design, kind/enhancement, good-first-issue, area/table
