### ISSUE TITLE
RBAC Roles pages

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#1208] opened 2020-09-09 05:41 UTC
In the rbac roles pages the apiGroup "" (empty string) is the "core v1" api group.  Currently it is being shown as "all api groups".  "All api groups" should only be if the api group is "*"

**Comment by deniseschannon** [comment] 2020-09-20 19:20
Duplicate of https://github.com/rancher/dashboard/issues/1204

**Closed by deniseschannon** 2020-09-20 19:20 UTC
Labels: [zube]: Next Up
