### ISSUE TITLE
Cluster agent is not able to connect to rancher server showing certificate chain issue 

### ISSUE THREAD

**Issue by manumittal89** [rancher/dashboard#8925] opened 2023-05-19 08:29 UTC
**Setup**
- Rancher version: 2.7
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
Cert-manager is creating a rancher self-signed certificates using helm 

**To Reproduce**

**Result**
Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://192.168.5.176:32541\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"dynamiclistener-ca@1684427844\")"
**Expected Result**

**Screenshots**
Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://192.168.5.176:32541\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"dynamiclistener-ca@1684427844\")"

**Additional context**
Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://192.168.5.176:32541\": x509: certificate signed by unknown authority (possibly because of \"x509: ECDSA verification failure\" while trying to verify candidate authority certificate \"dynamiclistener-ca@1684427844\")"

Regards,
Manu Mittal

**Comment by richard-cox** [comment] 2023-05-19 10:10
Please can you fill in the issue template with as much information as you can. There's a lot of copy and paste in there.

This is mostly likely an issue with the install process or how the UI is served, candidate to move to `rancher/rancher`

```
<!--------- For bugs and general issues --------->
**Setup**
- Rancher version:
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
<!--A clear and concise description of what the bug is.-->

**To Reproduce**
<!--Steps to reproduce the behavior-->

**Result**

**Expected Result**
<!--A clear and concise description of what you expected to happen.-->

**Screenshots**
<!-- If applicable, add screenshots to help explain your problem and/or errors in the browser's dev console -->

**Additional context**
<!--Add any other context about the problem here. -->
```

**Comment by richard-cox** [comment] 2023-05-22 13:49
Closing. This is a duplicate of a [previously created](https://github.com/rancher/rancher/issues/41556) `rancher/dashboard` issue that was transferred to `rancher/rancher`

**Closed by richard-cox** 2023-05-22 13:49 UTC
Labels: kind/bug, [zube]: To Triage
