### ISSUE TITLE
Support 'application/jsonl' list responses

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#4384] opened 2021-10-14 18:56 UTC
A new response type is being added to steve to support returning list results with the `application/jsonl` format.  This format will allow the frontend to being loading list results before the requests finishes transferring the response.  On clusters with many resources this could result in the dashboard being in a usable state twice as fast.

https://github.com/rancher/apiserver/pull/6

**Comment by vincent99** [comment] 2021-11-04 19:13
Dupe of #4512

**Closed by vincent99** 2021-11-04 19:13 UTC
Labels: [zube]: Working
