### ISSUE TITLE
Fleet resource filtering inappropriately calls dashboard shortcuts

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#3105] opened 2021-05-26 20:09 UTC
When using the filtering mechanism on a list of resources, one cannot type in "e" without the dashboard shortcut triggering to bring the user to the Cluster Explorer page. 

![Screen Shot 2021-05-26 at 3 08 36 PM](https://user-images.githubusercontent.com/5565738/119724450-59da7d00-be34-11eb-81af-e264ccd6ca0c.png)

This was experienced with a cluster named "eu", whose resources I wished to filter. I suspect this will impact other dashboard shortcuts as well.

**Comment by gaktive** [comment] 2021-06-11 16:35
This might be fixed based on some other shortcut work.

**Comment by richard-cox** [comment] 2021-06-15 13:26
I couldn't reproduce this in tip top of dashboard master. From the screenshot it looks like 2.5.8 (colours, styling have changed since then). There was a fix done a while back, probably 2.6, that resolved something similar.

**Comment by thehejik** [comment] 2021-06-16 14:08
This seems to be fixed in current `rancher/rancher:master-head 89b7a91`. I can type anything into filter field and no shortcut is triggered (on vivaldi-4 / chromium based).

![fiiltering](https://user-images.githubusercontent.com/12828077/122234074-dc4adf80-cebc-11eb-896b-2ad1fd57e125.png)

Close

**Closed by thehejik** 2021-06-16 14:08 UTC
Labels: [zube]: To Test, kind/bug
