### ISSUE TITLE
Unable to create OPA Gatekeeper Templates & Save button missing from Constraints

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4600] opened 2021-11-19 14:05 UTC
**Setup**
Rancher version: 2.6.3-rc1 (3 node k3s v1.21.5 KVM setup, 2 node k3s downstream cluster v1.21.5, 2 node RKE1 downstream cluster v1.21.6)
Browser type & version: Chrome 89.0.4389.90 (Official Build)

**Describe the bug**
Add Tempate button is missing in OPA Gatekeeper -> Template.

**To Reproduce**
Deploy OPA Gatekeeper.
Go to Tempate page.

Go to Constraints page.

**Result**
Template page:
No Add Template button (or maybe Create)

Constraints page:
No Save button in Constraints.

**Expected Result**
Buttons missing.

**Screenshots**
![image](https://user-images.githubusercontent.com/86831399/142635237-c709c1ce-10b7-4557-860d-1fca8cb3e8c3.png)

![image](https://user-images.githubusercontent.com/86831399/142635291-d3483a07-41d6-4af8-9179-99cad8749fe4.png)

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment] 2022-11-09 17:27
I couldn't reproduce this in 2.7-head (cusp of 2.7.0).

Note - There's no custom form for templates, so it's the generic YAML one
![image](https://user-images.githubusercontent.com/18697775/200897573-b0c87445-f7f0-42b1-aedb-cd7ff623e9ec.png)

![image](https://user-images.githubusercontent.com/18697775/200897694-222e879a-50e9-46c4-b147-ae62782fbb86.png)

@peteingithub Sorry, here's another one to try with a new Rancher. If it fails again could you let us know your user and if they had any restrictive roles?

**Comment by richard-cox** [comment] 2023-11-03 17:27
Couldn't reproduce in 2.8-head (cusp of 2.8.0)

**Comment by yonasberhe23** [comment] 2024-04-09 18:02
e2e test was added to cover this issue. moving to Done cc: @izaac

**Closed** 2024-04-09 18:02 UTC
Labels: kind/bug, [zube]: Done, area/opa, status/not-reproducible
