### ISSUE TITLE
Users with cluster member permissions should not display Local, Systemaccount and "Unable to fetch principal info" in the RBAC

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#3256] opened 2021-06-16 17:30 UTC
**Addressing 2 issues in this ticket**

Rancher version: master-head 54d4afc

- Create an rke2 node driver DO cluster single node all roles
- Create 2 users user1 and use2 and user1 in the cluster as cluster member and user2 with custom `ViewNodes` access

**`Issue1:`**
Login as user1 and from the explore cluster --> RBAC --> Cluster Members, displays a list of users along with `local` ,`System account` and `Unable to fetch principal info`.

<img width="250" alt="Screen Shot 2021-06-16 at 10 24 23 AM" src="https://user-images.githubusercontent.com/38144301/122264972-097f9980-ce8d-11eb-9db2-6eae419ca916.png">

If we refresh the RBAC --> Cluster Members page , the page is empty

**`Expected Result:`**
The cluster members page for a user with cluster member permissions, should display only the users present in the cluster. `local` ,`System account` and `Unable to fetch principal info` should not be displayed for the cluster members.

**`Issue2`**
When we log in as user3 with custom permissions, from the explore cluster --> RBAC --> Cluster Members has a `?` in place of Cluster Members

<img width="250" alt="Screen Shot 2021-06-16 at 10 22 29 AM" src="https://user-images.githubusercontent.com/38144301/122264987-0edce400-ce8d-11eb-85ce-308fe4b8e60a.png">

**`Expected Result:`**

`?` should be changed to `Cluster Members`

https://github.com/rancher/dashboard/issues/2501

**Comment by codyrancher** [comment] 2021-06-17 10:41
Issue 2:  Will be resolved with https://github.com/rancher/dashboard/pull/3280 by not showing the option in nav if the user doesn't have access.

**Comment by anupama2501** [comment] 2021-06-22 00:16
Verified on rancher server master-head 4d18400

Issue1:

- Create an rke2 node driver DO cluster single node all roles
- Created a standard user - user1 
- Added the user1 as cluster member
- Logged in as user1
- Verified `Service Account` and `Unable to fetch principal info` are removed from the cluster members list of user1

Issue2:

- Created a standard user - user2
- Added the user to the cluster with custom `View All Projects` 
- Logged in as user2 and verified RBAC is not shown for the user.

**Comment by kravciak** [comment] 2021-08-18 11:00
Reopening since I see `Unable to fetch principal info` on Member Roles list (as both admin / standard user)

![Screenshot from 2021-08-18 11-57-06](https://user-images.githubusercontent.com/538604/129886949-c4cf0375-f5fc-4fe2-b9db-a469e842cad1.png)

**Comment by kravciak** [comment] 2021-08-19 11:50
System account & principal are not visible anymore, closing.

![Screenshot from 2021-08-19 13-47-05](https://user-images.githubusercontent.com/538604/130063541-d3028dbd-302c-430b-bd21-3061af00b41f.png)

Is it possible that the fix caused this regression? https://github.com/rancher/dashboard/issues/3768

Tested on v2.6-head (2778eca)

**Closed by kravciak** 2021-08-19 11:50 UTC
Labels: kind/bug, QA/XS, [zube]: QA Next up, status/release-blocker
