### ISSUE TITLE
Solve issue with flaky tests for logout runs

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#8975] opened 2023-05-24 18:19 UTC
# Description

Solve issue with flaky tests for logout runs. 
The error occurs on menu interaction.

<img width="1366" alt="Screenshot 2023-05-24 at 20 16 58" src="https://github.com/rancher/dashboard/assets/5009481/3f4ae769-15ff-4331-8890-20db1c60fd42">

**Comment by gaktive** [comment] 2023-08-03 16:49
Per @richard-cox's research, it looks like the avatar icon is the source of this. If we can resolve this, this could help with half of the other flaky tests we have.

**Comment by gaktive** [comment] 2023-08-09 15:11
1st goal here: try to reproduce this locally.

**Comment by cnotv** [comment] 2023-08-14 08:12
> Per @richard-cox's research, it looks like the avatar icon is the source of this. If we can resolve this, this could help with half of the other flaky tests we have.

How does the icon create issues? @richard-cox

**Comment by richard-cox** [comment] 2023-08-14 08:15
> How does the icon create issues? @richard-cox

Sorry, it's not specifically the icon, but it's the menu associated with the user avatar. It seems the click is not opening the menu, even though screen elements are there and ready

**Comment by richard-cox** [comment] 2023-11-14 11:00
Let's stick with https://github.com/rancher/dashboard/pull/9718 and re-assess later. Closing this one for now

**Comment by cnotv** [comment] 2023-11-14 11:51
@richard-cox since I took the effort to check all the issues one by one and document them, can you please provide a link where we ensure this to have been fixed before close? Otherwise it's hard to track everything, thanks.

**Closed** 2023-11-14 11:51 UTC
Labels: [zube]: To Triage, area/test, kind/tech-debt, priority/1, size/5, QA/None, area/e2e
