### ISSUE TITLE
Backport bug fix: Creating a custom rke1 cluster switches UI to old UI

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#7646] opened 2022-12-07 19:55 UTC
Setup

Rancher version: 2.6.9
Browser type & version: Chrome

**Describe the bug**
Creating a custom cluster either as an Admin/Standard user takes the UI to showing a list of created clusters. If we select creating a cluster again, the UI is switched to the old UI.

**To Reproduce**
1. Install rancher on v2.6.9
2. As a standard user, created clusters RKE1 node driver and RKE2 node driver via terraform
3. From the UI, select rke1 custom cluster and click on create

**Result**
UI shows the list of clusters provisioning and then if we click on create cluster, UI shows old UI

**Expected Result**
Expected the UI page to be in custom cluster creation.

**Additional context**
Not seeing this when I select rke2 custom clusters.
There is a related issue opened in v2.7 https://github.com/rancher/dashboard/issues/7636
Once the provisioning cluster comes active, do not see this issue anymore.

**Comment by catherineluse** [comment] 2022-12-14 01:08
This has a 2.6 milestone on it, but I also reproduced it in 2.7. I created a PR that fixes it in 2.7 https://github.com/rancher/ui/pull/4925

**Comment by catherineluse** [comment] 2022-12-19 17:47
Note for QA: This should not be tested until this PR is merged https://github.com/rancher/rancher/pull/39899

**Comment by brudnak** [comment] 2023-02-09 16:50
# ✅ PASSED

## Reproduction Environment

#### Not required. Per Sr. QA. Unable to reproduce.

<hr>

## Validation Environment

| Component                        | Version / Type                                     |
| -------------------------------- | -------------------------------------------------- |
| Rancher version                  | v2.6-993608f436aab5ad51b817cbf98e5099cf01aa05-head |
| Installation option              | Docker install                                     |
| Cert Details                     | `--acme-domain`                                    |
| Docker version                   | 20.10.7, build f0df350                             |
| Authentication providers enabled | local                                              |
| Logged in user role              | admin, standard user                               |



## Validation steps

- Edit an RKE1 cluster
- User is navigated to the cluster edit page.
- The original issue seen is NOT observed anymore.
- No 404s seen in the console

## Additional Info

## RESULTS

#### ✅ Expected

No errors editing an RKE1 cluster

#### ✅ Actual

No errors editing an RKE1 cluster

**Closed by brudnak** 2023-02-09 16:50 UTC
Labels: kind/bug, [zube]: QA Working, kind/bug-qa, team/area1
