### ISSUE TITLE
Change Language only partially affects Side Menu

### ISSUE THREAD

**Issue by KzqKzq** [rancher/dashboard#7786] opened 2022-12-21 11:06 UTC
**Setup**
- Rancher version: 2.7.0
- Browser type & version: Chrome&108.0.5359.98

**Describe the bug**
Change the system language only partially effective

**To Reproduce**
1.Navigate to the  ‘**EXPLORE CLUSTER**’
2.Open the '**Preferences**' change the language to '简体中文'(Chinese)

**Result**
Back to the  ‘**EXPLORE CLUSTER**’，there still have English words in the left menu. But if i refresh this page, it worked.

- before refresh

 
![image](https://user-images.githubusercontent.com/61263079/208874805-974c0e1e-27ba-4d00-83a9-f2ed300ee38b.png)

- after refresh

![image](https://user-images.githubusercontent.com/61263079/208874994-67a9aa9d-3a6a-433c-98e1-0e823fbae2cc.png)

**Expected Result**

While change the language to '简体中文'(Chinese), all of the left menu options should be changed to the Chinese.

**Comment by richard-cox** [comment] 2022-12-21 11:09
This should hopefully be resolved by a recent PR. @bisht-richa can you validate this is fixed, if so move to test?

**Comment by jameson-mcghee** [comment] 2023-01-06 22:03
I was able to reproduce this issue on `v2.6.9` when following the Steps to Reproduce. However, I was unable to reproduce this issue on `v2.7-head` (Commit ID: 8062f1e). Therefore I am closing this ticket as Done.

**Steps to Reproduce:**
1. Navigate to the ‘EXPLORE CLUSTER’
2. Open the 'Preferences' change the language to '简体中文'(Chinese)

**`v2.6.9`:**
![image](https://user-images.githubusercontent.com/13294321/211107746-97499e4d-e407-4614-886e-82e4f50119de.png)

**`v2.7-head` (Commit ID: 8062f1e):**
![image](https://user-images.githubusercontent.com/13294321/211107605-903cb81b-2d88-4982-9cd8-7ba15fb230a3.png)

**Closed by jameson-mcghee** 2023-01-06 22:03 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, team/area2
