### ISSUE TITLE
[2.6.x backport] 'execute Shell' on Workload open Shell in other Workload in other Namespace with same Name

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8060] opened 2023-01-27 21:44 UTC
Internal reference: SURE-5799
Reported in 2.6.9

Issue description:
While open a Shell on Workload, a Shell are open from other Workload (with the same Name) on other Namespace. Same behavior if Workload are Scale = 0. This means users are unable to get exact container shell.

Related 2.7.x work: https://github.com/rancher/dashboard/issues/8040 (which may have to land first)
Possible connection to https://github.com/rancher/dashboard/issues/6982

**Comment by rak-phillip** [comment] 2023-02-10 21:36
Unable to reproduce after testing against v2.6-head. Based on description and repro steps, this looks to be resolved by #7274. Moving to test for confirmation.

**Comment by Josh-Diamond** [comment] 2023-02-13 18:45
Ticket #8060 - Test Results - ✅ 
---

With Docker on a single-node instance:

Verified on Rancher `v2.6-582851228efff89caa4ed35e49fb777be67209a6-head`:
1. Fresh install of rancher `v2.6-head`
2. Deploy a downstream RKE1 AWS Node driver cluster - [ k8s `v1.24.9` ]
3. Once `active`, create two new projects - [ `projectone`, `projecttwo` ]
4. Create `namespaceone` in `projectone` and create `namespacetwo` in `projecttwo`
5. Create the same deployment, with same name, in both `namespaceone` and in `namespacetwo`
6. Once pods are `active`, `execute shell` on each and observe targeted pod
7. Verified - Both deployed workloads resolve to correct pod when launching shell

**Closed by Josh-Diamond** 2023-02-13 18:45 UTC
Labels: kind/bug, [zube]: QA Working, team/area2, size/0.5, JIRA
