### ISSUE TITLE
Upon editing a cluster, defaults for the following fields are not set correctly, but these fields are set during create. 

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3727] opened 2021-08-09 04:22 UTC
I created a cluster with all defaults in the UI. When editing, the following fields are not populated and I can't save the cluster. I'm marking it as a release-blocker since I can't actually edit the cluster. 

Note: I have permissions for the cluster as I am able to view the cluster in my cluster dropdown, navigate to it and create k8s resources through the ui. 

[ ] etcd - Automatic Snapshots - Default is enabled in create, but no radio button is populated when editing the cluster.
<img width="242" alt="Screen Shot 2021-08-08 at 9 17 19 PM" src="https://user-images.githubusercontent.com/11410997/128660116-e85c02cc-2c16-4920-ba0f-3b463384bb65.png">

[ ] Networking - Authorized Endpoint - Default is disabled in create clsuter, but no radio button is populated when editing the cluster.

<img width="547" alt="Screen Shot 2021-08-08 at 9 21 07 PM" src="https://user-images.githubusercontent.com/11410997/128660130-a5bc8058-dde0-480c-b62e-72c439640f7a.png">

**Comment by richard-cox** [comment] 2021-08-09 16:38
@neillsom See if you can recreate this, specifically the first one, there were some recent changes to that process and it would be good to confirm if it still happens

**Comment by deniseschannon** [comment] 2021-08-10 05:16
On a fresh install as the default admin, I can reproduce the bottom 2 issues, but on a different install, where I am an admin through a group, I consistently see this issue where I created the cluster but it doesn't list me as the cluster owner on the members page. I'm trying to root cause/isolate what is the difference between my access between the different setups, but haven't been able to figure it out. 

The bottom 2 issues happen on all set ups.

**Comment by codyrancher** [comment] 2021-08-10 06:16
I saw the bottom two but not the first issue. @deniseschannon if you just have a cluster that's reproducing can you provide the instance and we can just dig into it from there.

**Comment by richard-cox** [comment] 2021-08-10 10:45
I've just given the membership issue a try (others have now been fixed), also couldn't reproduce. I have a keycloak user who's a member of a group that has an `admin` group role assigned to it. When creating an RKE2 DO cluster i left the members unchanged (could see the keycloak user as the cluster owner by default). Once cluster was created I could see the same user as owner in the edit cluster page.

@deniseschannon Was there a specific auth provider you were using, or the group rights were done a different way? Were there any errors in the console when creating the cluster? Can you see the cluster owner role for your cluster when looking at the User Detail page (Users & Authentication --> Users --> <user> --> Cluster Roles tab)?

I know the RBAC stuff for groups is in transition

**Comment by codyrancher** [comment] 2021-08-10 22:26
I'm removing the members issue from here and moving it to https://github.com/rancher/dashboard/issues/3768 so we can track it separately.

**Comment by davidnuzik** [comment] 2021-08-11 20:55
_I believe this check is sufficient to close out this issue, if not please let me know. I saw the membership issue is being handled separately. Therefore, I just tested with local admin here and a standard user._
 
**My checks PASSED**
 
**Reproduction Steps:**

Not required as I clearly understand the issue.
 
**Validation Steps:**

Rancher version: v2.6-head `9d2e08674` 8/11/21 9:00 am Pacific
Rancher cluster type: single-node docker
Docker version: 19.03
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.3-rc5+rke2r2
 
Validation steps:

Note: Members issue is covered in https://github.com/rancher/dashboard/issues/3768 as Cody mentioned in prior comment.
1. As local Admin, Create an RKE2 cluster in Rancher with node driver. In my case I tested with DigitalOcean, a 1 node cluster. I used the default options.
2. Once the cluster is ready, edit the cluster config.
3. Confirmed that the two sets of radio buttons mentioned in the issue description are no longer both null -- I see they are populated just as they were prior as per my specifications when I first created the cluster.
![image](https://user-images.githubusercontent.com/45179589/129082049-8c97ba3d-e1d5-458c-80b0-919cd96f6b1d.png)
![image](https://user-images.githubusercontent.com/45179589/129082094-370bed71-2909-4a4e-b61e-28205d58be94.png)

4. Re-tested but this time try variations of enabling/disabling automatic snapshots and authorized endpoint. Ensure that when I edit the cluster config, the setting is just as it was when I first created the cluster. This worked fine, except I found a bug unrelated to this issue. Disabling etcd backup on rke2 will pass the wrong flag to rke2-server. Bug is here: https://github.com/rancher/dashboard/issues/3801
5. Re-tested but did a smoke test with a standard user.

Additional Info:
I did a check on other fields/objects as well in the UI. I ensured that my settings for each dropdown, text box, checkbox, radio buttons were all correct and the same as when the cluster was first provisioned.

**Closed by davidnuzik** 2021-08-11 20:55 UTC
Labels: [zube]: QA Working, status/release-blocker
