### ISSUE TITLE
Detail Page - User is navigated to Explore cluster page on clicking on Show Annotation 

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#866] opened 2020-07-17 22:46 UTC
**on master-head - commit id: `16616de9c`**

- Logged in as Standard user
- Click on a resource in the Cluster Nav bar say `Cluster Role`. And click on `admin` role.
<img width="871" alt="Screen Shot 2020-07-17 at 3 46 24 PM" src="https://user-images.githubusercontent.com/26032343/87836377-afbdbc00-c844-11ea-8138-787ad1b0fdcf.png">

- On the detail page, click on `Show annotation` 
- User is navigated to Explore cluster page

**Comment by deniseschannon** [comment] 2020-07-21 04:27
Duplicate of https://github.com/rancher/dashboard/issues/867

**Closed by deniseschannon** 2020-07-21 04:28 UTC
