### ISSUE TITLE
Stuck Cluster - Removing Waiting For Machine

### ISSUE THREAD

**Issue by techmatlock** [rancher/dashboard#8109] opened 2023-02-07 19:12 UTC
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment] 2023-02-08 11:50
Closing as dupe of https://github.com/rancher/dashboard/issues/8110

**Closed by richard-cox** 2023-02-08 11:50 UTC
Labels: kind/bug, [zube]: Done
