### ISSUE TITLE
Rethink how we show nav links and keep top-level groups in menu all the time

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4431] opened 2021-10-20 16:33 UTC
In the midst of @rak-phillip researching what was going on with navigating between components in rancher/dashboard#4428, a bandaid solution to ensure that getting from Installed Apps to Apps & Marketplace can happen without hitting another page inbetween.

However, based on the wormhole of logic discovered when investigating that issue, we should figure out what we can do to keep more of the top-level groups persistent in the main navigation on the left side. At the very least, users should be able to get to the Cluster area all the time, which isn't available in some cases.  

As part of that, we shouldn't remove the namespace resources when the namespace filter is enabled since the list on the left changes a fair bit if none, one or all are selected.

@vincent99 may provide some of the contextual history as to how the modes tied to index0, index1, etc. for the nav link were put into place. It looks like tech debt from a past change with maybe some remnants of older flow still around.

related issues:

- https://github.com/rancher/dashboard/issues/5287
- https://github.com/rancher/dashboard/issues/4424
- rancher/rancher#37556

**Comment by lvuch** [comment] 2021-11-04 21:42
Alright so the crux of the issue is that the left navigation should never change. I get that what is probably trying to be done is focusing on namespace but we should treat it less as a filtering down a level from global to namespace and more of a way of aggregating multiple namespaced resources/shortcut for creation.

That is what I'd suggest in simplest terms. Another thing we could consider doing is moving namespace filter to namespaced list places. This would take the guess work from list pages as to does this belong to global or namespace level?

**Comment by lvuch** [comment] 2021-11-05 18:12
@vincent99 is there a reason or intention to those changes to the nav when namespace filters are applied?

**Comment by vincent99** [comment] 2021-11-05 19:36
You're asking to see stuff that belongs to a [set of] namespace[s], so cluster-level resources are removed because they are non-namespaced by definition.

**Comment by lvuch** [comment] 2021-11-05 20:02
https://xd.adobe.com/view/0d11936b-c060-48aa-b3ca-10ac31be1136-5842/

**Comment by lvuch** [comment] 2021-11-05 20:04
> You're asking to see stuff that belongs to a [set of] namespace[s], so cluster-level resources are removed because they are non-namespaced by definition (e.g. nodes, persistent volumes, the namespace resource itself).

Got it. I wasn't sure if this was intentional. Since we've gotten feedback that it's confusing we should change it so both cluster and namespaced resources are available. I've attached a few thoughts in the xd file.

**Comment by gaktive** [comment] 2022-02-17 17:42
@nwmac to create work items from this and then this is Done.

**Comment by catherineluse** [comment] 2022-03-07 06:13
Capturing more feedback on the nav bar from talking to @cnotv : 

- In cluster explorer, in the left nav bar, you should be able to open multiple groups at the same time. Currently when you open one group, another closes, which shifts content around on the screen in a way that someone might not expect. It would be more predictable if you could open a group without another group collapsing.
- In cluster explorer, in the left nav bar, the currently active page should always be highlighted. Currently, for example, if you are on the namespace page, the projects/namespace nav item is not always highlighted.

**Comment by cnotv** [comment] 2022-03-07 08:23
Another issue may be also related to nested navigation, where the sidebar is replaced and there's nothing in the breadcrumb. Not sure in which way it can be solved, but it's kinda of annoying to need to navigate all the way back just to get the link in the sidebar.

**Comment by richard-cox** [comment] 2022-03-10 17:32
We've had requests from a customer to keep groups expanded when accessing resources outside of that group (details available on confluence)

**Comment by catherineluse** [comment] 2022-03-19 23:10
related issue https://github.com/rancher/dashboard/issues/5287

**Comment by catherineluse** [comment] 2022-03-24 21:07
Internal reference SURE-3658

**Comment by gaktive** [comment] 2022-08-16 15:25
Also some connection with #5229

**Comment by catherineluse** [comment] 2022-08-17 23:33
SURE-3658

**Comment by catherineluse** [comment] 2022-11-04 22:35
I'm closing this issue due to its age and because the work on the side nav is being tracked in these other issues:

- https://github.com/rancher/dashboard/issues/5287
- https://github.com/rancher/dashboard/issues/4424
- https://github.com/rancher/dashboard/issues/5299
- https://github.com/rancher/dashboard/issues/6658

The epic ticket for navigation improvements in general is here: https://github.com/rancher/dashboard/issues/6417

The relevant internal ticket is linked to #6658 https://github.com/rancher/dashboard/issues/6658#issuecomment-1218653321

**Closed by catherineluse** 2022-11-04 22:35 UTC
Labels: internal, kind/design, [zube]: Design Backlog, JIRA, v2.7.0
