### ISSUE TITLE
`registry` secrets do not populate correctly for project owners

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5084] opened 2022-02-10 00:09 UTC
**Setup**
- Rancher version: v2.6.4-rc2
- Browser type & version: chrome

**Describe the bug**

as a project owner, I can create a registry secret, but dropdowns for secrets do not populate them. The same secret will populate for a cluster owner

**To Reproduce**

* create a cluster, and give a user `project-owner` permissions in the default project
* create a registry secret (secrets -> registry)
* create a workload using the registry secret as an environment variable 

**Result**
user is unable to create a workload using the registry secret as an environment variable 

**Additional context**
as project owner:
<img width="531" alt="Screen Shot 2022-02-09 at 4 06 53 PM" src="https://user-images.githubusercontent.com/16691014/153311711-2d0a3145-cccd-496a-8cf8-a383f35cfe7d.png">
<img width="523" alt="Screen Shot 2022-02-09 at 4 07 15 PM" src="https://user-images.githubusercontent.com/16691014/153311780-df72872e-dcc5-4468-9d1c-b5c106cecc87.png">

as cluster owner:
<img width="545" alt="Screen Shot 2022-02-09 at 4 08 13 PM" src="https://user-images.githubusercontent.com/16691014/153311887-d4238092-a50e-4fd8-93f8-82f917d2b9f5.png">

same result for `secret key` and `secret` 
related issue: https://github.com/rancher/dashboard/issues/3940

**Comment by nwmac** [comment] 2022-02-23 11:53
This should be addressed by this PR: https://github.com/rancher/dashboard/pull/5124

The issue is the user does not have permissions to read/write secrets - with the fix above, the user will not be able to edit the environment variable.

**Comment by Josh-Diamond** [comment] 2022-03-10 01:15
Ticket #5084

With Docker and EKS hosted cluster:

Reproduced on 2.6.4-rc2:
1. Fresh install of rancher v2.6.4-rc2
2. As admin, create a new standard user
3. As admin, create a cluster (EKS, or any other)
4. As admin, give standard user `project-owner` permissions in the default project
5. Log out admin, then log in as standard user
6. As standard user, create a registry secret
7. As standard user, create a workload using registry secret or secret key as an environment variable
8. Issue reproduced - registry secrets and secret keys are not available for `project-owner`, but are available for `cluster-owner`

As `project-owner`:
<img width="1180" alt="Screen Shot 2022-03-09 at 5 07 36 PM" src="https://user-images.githubusercontent.com/46494969/157564341-1006851e-5b96-4fba-8706-04768b5c367f.png">

<img width="938" alt="Screen Shot 2022-03-09 at 5 16 04 PM" src="https://user-images.githubusercontent.com/46494969/157564435-32e222ad-6ccc-4147-be16-cbf0540f2662.png">


As `cluster-owner`:
<img width="928" alt="Screen Shot 2022-03-09 at 5 13 19 PM" src="https://user-images.githubusercontent.com/46494969/157564481-af3fa949-0f77-4c53-8f38-e2ed27b5680e.png">

<img width="640" alt="Screen Shot 2022-03-09 at 5 14 57 PM" src="https://user-images.githubusercontent.com/46494969/157564500-43ca8087-6776-4222-b695-261cc66ebfab.png">


Verified on v2.6-e4af2465c5b4d3ed4ad02694b5fd939b81f6b76a-head:
1. Fresh install of rancher 2.6-head
2. As admin, create a new standard user
3. As admin, create a cluster (EKS or any other)
4. As admin, give standard user `project-owner` permissions in the default project
5. Log out admin, then log in as standard user
6. As standard user, create a registry secret
7. As standard user, create a workload using registry secret or secret key as an environment variable
8. Resolution Verified - registry secrets and secret keys are available for both `project-owner` and `cluster-owner`

As `project-owner`:

<img width="942" alt="Screen Shot 2022-03-09 at 6 05 47 PM" src="https://user-images.githubusercontent.com/46494969/157567434-aa95a324-3b7d-4fda-bcfc-254808a6c504.png">

<img width="928" alt="Screen Shot 2022-03-09 at 6 06 08 PM" src="https://user-images.githubusercontent.com/46494969/157567452-d29804ca-0d1d-4fbb-a77e-383a9e355b63.png">


As `cluster-owner`:

<img width="919" alt="Screen Shot 2022-03-09 at 6 07 16 PM" src="https://user-images.githubusercontent.com/46494969/157567496-eb65df02-33a3-41e7-b126-60b0c0cc56a9.png">

<img width="925" alt="Screen Shot 2022-03-09 at 6 07 33 PM" src="https://user-images.githubusercontent.com/46494969/157567506-ce6c9cce-d0be-4553-94de-dd5326413131.png">


Upgrade/Verified on 2.6.4-rc2 >> 2.6.4-head:
W.I.P.  (estimated completion by 3/10/22)

**Closed** 2022-03-10 16:29 UTC
Labels: area/secret, internal, [zube]: QA Working, kind/bug-qa, team/area2
