### ISSUE TITLE
502: bad gateway on `<put>` when removing cluster / fleet agent overrides from an existing rke2 cluster

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#9012] opened 2023-05-12 16:09 UTC
**Setup**
- Rancher version: v2.7-head(95edd02)
- Rancher UI Extensions: n/a
- Browser type & version:chrome

**Describe the bug**

when updating an rke2 cluster with existing cluster and fleet agent overrides -> removing all the settings, resulted in a 502 gateway error. 

**To Reproduce**

* deploy an rke2 cluster
  * enter cluster agent overrides for resources, add a toleration, and add a custom affinity
  * enter fleet agent overrides for resources, add a toleration, and add a custom affinity
* allow the cluster to successfully get to an active state
* upgrade the cluster
  * remove all overrides that were entered in the first step

**Result**
An error is shown in the UI and the user is kept on the cluster edit screen, however the update was actually still applied and the overrides were removed
```
a padding to disable MSIE and chrome friendly error page
```

cluster did not appear to go into an updating state

**Expected Result**

if there's an error, I wouldn't expect the new spec to have applied to the cluster

**Screenshots**

<img width="1523" alt="Screen Shot 2023-05-12 at 8 52 11 AM" src="https://github.com/rancher/dashboard/assets/16691014/f9e168b6-02cd-4d72-9468-9391014a1577">

**Additional context**

did not happen for an rke1 cluster

**Comment by aalves08** [comment] 2023-05-31 14:12
Thanks @KevinJoiner . The PR that @mantis-toboggan-md has created will address both areas, I believe 🙏  https://github.com/rancher/dashboard/pull/9011

**Comment by aalves08** [comment] 2023-05-31 15:20
> 1. Some of the fields are just in the wrong place, such as.
> 
>    - `https://<server_url>/v1/schemas/provisioning.cattle.io.v1.cluster.spec.clusterAgentDeploymentCustomization.overrideAffinity.nodeAffinity.preferredDuringSchedulingIgnoredDuringExecution`
> 2. Some fields added by Steve should be stripped because they don't exist in ETCd
>      - `metadata.fields`
>      - `metadata.relationships`
>      - `metadata.state`
> 
> 3. Other fields are added by the UI and do not exist for example 
>     - `status.conditions[12].error`
>     - `status.conditions[12].transitioning`
> 

Due to the time constraints and the intermittency in terms of reproducing this (I could never reproduce it, tbh), we will address `1.`with this [PR](https://github.com/rancher/dashboard/pull/9011) and our proposal is that we close this issue and split `2.` and `3.` into separate issues as it has possible Rancher Dashboard-wide implications because we have always sent those properties without any side-effects, until now.

FYI @gaktive @nwmac @richard-cox

**Comment by slickwarren** [comment] 2023-06-02 18:53
tested on v2.7-head (f0d4078):
* deploy an rke2 cluster with all agentCustomization set for fleet and cluster agents
* update the cluster, remove all agentCustomization / set back to default -- pass

notes: 
since this has gone in, I haven't reproduced this issue
the following warnings are still in the headers of the removal requests:
```
Warning:
299 - unknown field "metadata.fields"
Warning:
299 - unknown field "metadata.relationships"
Warning:
299 - unknown field "metadata.state"
Warning:
299 - unknown field "spec.machineSelectorConfig"
Warning:
299 - unknown field "status.conditions[0].error"
Warning:
299 - unknown field "status.conditions[0].transitioning"
Warning:
299 - unknown field "status.conditions[10].error"
Warning:
299 - unknown field "status.conditions[10].transitioning"
Warning:
299 - unknown field "status.conditions[11].error"
Warning:
299 - unknown field "status.conditions[11].transitioning"
Warning:
299 - unknown field "status.conditions[12].error"
Warning:
299 - unknown field "status.conditions[12].transitioning"
Warning:
299 - unknown field "status.conditions[13].error"
Warning:
299 - unknown field "status.conditions[13].transitioning"
Warning:
299 - unknown field "status.conditions[14].error"
Warning:
299 - unknown field "status.conditions[14].transitioning"
Warning:
299 - unknown field "status.conditions[15].error"
Warning:
299 - unknown field "status.conditions[15].transitioning"
Warning:
299 - unknown field "status.conditions[16].error"
Warning:
299 - unknown field "status.conditions[16].transitioning"
Warning:
299 - unknown field "status.conditions[17].error"
Warning:
299 - unknown field "status.conditions[17].transitioning"
Warning:
299 - unknown field "status.conditions[18].error"
Warning:
299 - unknown field "status.conditions[18].transitioning"
Warning:
299 - unknown field "status.conditions[19].error"
Warning:
299 - unknown field "status.conditions[19].transitioning"
Warning:
299 - unknown field "status.conditions[1].error"
Warning:
299 - unknown field "status.conditions[1].transitioning"
Warning:
299 - unknown field "status.conditions[20].error"
Warning:
299 - unknown field "status.conditions[20].transitioning"
Warning:
299 - unknown field "status.conditions[21].error"
Warning:
299 - unknown field "status.conditions[21].transitioning"
Warning:
299 - unknown field "status.conditions[22].error"
Warning:
299 - unknown field "status.conditions[22].transitioning"
Warning:
299 - unknown field "status.conditions[2].error"
Warning:
299 - unknown field "status.conditions[2].transitioning"
Warning:
299 - unknown field "status.conditions[3].error"
Warning:
299 - unknown field "status.conditions[3].transitioning"
Warning:
299 - unknown field "status.conditions[4].error"
Warning:
299 - unknown field "status.conditions[4].transitioning"
Warning:
299 - unknown field "status.conditions[5].error"
Warning:
299 - unknown field "status.conditions[5].transitioning"
Warning:
299 - unknown field "status.conditions[6].error"
Warning:
299 - unknown field "status.conditions[6].transitioning"
Warning:
299 - unknown field "status.conditions[7].error"

Warning:
299 - unknown field "status.conditions[7].transitioning"
Warning:
299 - unknown field "status.conditions[8].error"
Warning:
299 - unknown field "status.conditions[8].transitioning"
Warning:
299 - unknown field "status.conditions[9].error"
Warning:
299 - unknown field "status.conditions[9].transitioning"

```

**Closed** 2023-06-02 18:53 UTC
Labels: kind/bug, QA/S, [zube]: QA Working, status/release-blocker, kind/bug-qa, area/provisioning-rke2

**Comment by snasovich** [comment] 2023-06-02 18:58
@slickwarren , thank you for testing these. The warnings you mentioned should be covered as part of https://github.com/rancher/dashboard/issues/9016.
@mantis-toboggan-md @richard-cox , FYI I've added `metadata.fields` and `metadata.state` to the description of that issue. Not sure if `spec.machineSelectorConfig` should be part of it - please feel free to update as needed.
