### ISSUE TITLE
Unavailable cattle-cluster-agent results in 500 error

### ISSUE THREAD

**Issue by ebauman** [rancher/dashboard#1991] opened 2020-12-04 17:35 UTC
If the cattle-cluster-agent is unavailable in a downstream cluster, the dashboard returns a 500 error: 
![Screen Shot 2020-12-04 at 11 34 16 AM](https://user-images.githubusercontent.com/5565738/101195172-a632c600-3624-11eb-8b1d-7855c92dcfc2.png)

This occurs whether the cluster agent was scaled down to 0 pods, or if the pod was scheduled on an unavailable node.

Cluster manager remains available as (presumably) the tunnel transfers over to a node agent. 

Rancher v2.5.2
Kubernetes v1.19.4 RKE

**Comment by deniseschannon** [comment] 2021-01-05 17:53
@lvuch Can we update this page to make it look prettier and to indicate that a 500 is due to the API not being available?

**Comment by aaronRancher** [comment] 2021-03-11 01:11
The bug is reproduced with Rancher server `rancher\rancher:v2.5.3`
Steps:
Launch cluster.
Scale cluster agent down to 0 pods.
![Screen Shot 2021-03-10 at 5 38 19 PM](https://user-images.githubusercontent.com/57409052/110720578-11fc7000-81cc-11eb-9fcd-929eef0ce83a.png)

Tested with Rancher server `rancher\rancher:master-head` `version eda2a07 `
Error page has changed:
![Screen Shot 2021-03-10 at 6 00 07 PM](https://user-images.githubusercontent.com/57409052/110720562-0c068f00-81cc-11eb-9160-d7cb81aa163c.png)

Related issue: https://github.com/rancher/dashboard/issues/2151

**Comment by deniseschannon** [comment] 2021-03-11 01:15
It should indicate that this error also means that the API is unavailable. Not just a pretty page

**Comment by vincent99** [comment] 2021-03-11 08:47
The API can return something more descriptive if you want and it will get shown. 

The Ui doesn't have any info to differentiate "unavailable" from any other reason the API could have returned a 500 (which just means roughly "something went wrong on the server side").

**Comment by aaronRancher** [comment] 2021-04-14 19:08
The backend can return a more descriptive error.
Will track the backend change here: https://github.com/rancher/rancher/issues/32139
Closing issue.

**Closed by aaronRancher** 2021-04-14 19:08 UTC
Labels: QA/XS, [zube]: To Test
