### ISSUE TITLE
Rancher UI produces wrong CLI command 'taint vs taints' upon join AWS

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6827] opened 2022-09-07 22:28 UTC
Internal reference: SURE-4481
Reported in 2.6.4.

This happens on AWS EC2 Auto-Scale

As described at https://github.com/rancher/rancher/issues/36131, the Rancher UI's node registration screen produces the wrong CLI command to join a node to a cluster with a taint.

Per investigation in that ticket, @HarrisonWAffel determined that:
> I would agree that this seems to be a UI bug. From what I can tell the registration command is generated [in this file](https://github.com/rancher/dashboard/blob/811c787a408e73aeaeacc4eb83ab521837ef140a/shell/edit/provisioning.cattle.io.cluster/CustomCommand.vue), and the taints are added to the command [here](https://github.com/rancher/dashboard/blob/811c787a408e73aeaeacc4eb83ab521837ef140a/shell/edit/provisioning.cattle.io.cluster/CustomCommand.vue#L68-L76). In that file that the flag `--taint` is being pushed to the UI, as opposed to the proper `--taints` flag. 
> Curiously, this issue does not reproduce when registering custom RKE1 clusters which utilize windows worker nodes. In this case, the registration command will include the proper `--taints` flag both when generating the linux registration command as well as when generating the windows registration command.

_Originally posted by @HarrisonWAffel in https://github.com/rancher/rancher/issues/36131#issuecomment-1239968250_

**Comment by catherineluse** [comment] 2022-09-13 10:33
I haven't reproduced this issue yet. I commented on the original issue with questions (https://github.com/rancher/rancher/issues/36131#issuecomment-1245216251) so far.

**Comment by catherineluse** [comment] 2022-09-13 22:03
# QA Template
## Root cause
As Harrison pointed out (https://github.com/rancher/rancher/issues/36131#issuecomment-1239968250), the dashboard UI for provisioning custom clusters was incorrectly using `--taint` instead of `--taints` to add taints to the RKE2 custom cluster registration command.
 
## What was fixed, or what changes have occurred
A very small change that changed `taint` singular to `taints` plural in the UI-generated registration command.
 
## Areas or cases that should be tested
This is what I did to test the PR:

1. In cluster management, I went to Clusters and clicked Create
2. Made sure the toggle for K3s/RKE2 was selected
3. Clicked **Custom** under **Use existing nodes and create a cluster using RKE2/K3s**
4. Entered a name for the cluster and clicked Create
5. Still in cluster management, in the cluster detail page, on the Registration tab, I clicked **Show Advanced**.
6. Clicked Add Taint. Added two taints that way.

<img width="1248" alt="Screen Shot 2022-09-13 at 12 26 57 PM" src="https://user-images.githubusercontent.com/20599230/190015841-8b295dd9-3627-4544-b4e3-853017242033.png">

7. Confirmed that in the cluster registration command below, each taint was included in the command with the `--taints` flag:
<img width="922" alt="Screen Shot 2022-09-13 at 12 27 15 PM" src="https://user-images.githubusercontent.com/20599230/190015886-75b053d5-0303-4d94-abac-1ce4db98d0d1.png">
 
## What areas could experience regressions?
This is a very small change - one character - so I think regressions are unlikely.
 
## Are the repro steps accurate/minimal?
No. The steps that I used to test don't match the steps to repro the issue as described in the issue description on https://github.com/rancher/rancher/issues/36131. The original issue and internal ticket mention Docker, RKE1 and EC2, but after reading Harrison's comments and repro steps, it sounds like the issue doesn't have to do with any of that. The bug is really around only custom clusters, and has to do with the RKE2/K3s registration command, and doesn't have to do with any specific cloud provider.

I tried to repro the bug with RKE1/EC2 steps and could not repro the issue at all (https://github.com/rancher/rancher/issues/36131#issuecomment-1245216251), because the RKE1 provisioning pages are iFramed Ember pages and the Ember UI had added the taints correctly. As far as I could tell, Ember always added the taints properly as expected and this issue is only in the dashboard (RKE2 provisioning).

**Comment by jameson-mcghee** [comment] 2022-09-20 20:25
I was able to reproduce this issue on v2.6.4 and v2.6.5. I was then able to verify that this issue is no longer reproducing on v2.6.9-rc1. Therefore I am closing this ticket as done.

Repro Steps:
1. On the Cluster Management page, click the Create button
2. Toggle on for RKE2/K3s
3. Click the Custom option under "Use existing nodes and create a cluster using RKE2/K3s"
4. Enter a name for the cluster and click the Create button
5. While still in the Cluster Detail page, on the Registration tab, click Show Advanced
6. Click Add Taint, and input _Key_ "foo" and _Value_ "bar
Note that in the Registration command it states "--taint" (when reproducing the issue) or "--taints" (when correct).

v2.6.4:
![image.png](https://zube.io/files/rancher/fc2679cd4733502a1f14fcd06e46d52f-image.png)

v2.6.5:
![image.png](https://zube.io/files/rancher/7ecd9c8fd27afd0ec7f8c84ea972dd89-image.png)

v2.6.9-rc1:
![image.png](https://zube.io/files/rancher/a1f58110d7e71b8f97a743f0be057b08-image.png)

**Closed** 2022-09-20 20:25 UTC
Labels: kind/bug, priority/0, QA/XS, [zube]: QA Working, team/area2, JIRA
