### ISSUE TITLE
Failed Rancher-provisioned RKE1 clusters will stay on Rancher landing page after delete

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4053] opened 2021-08-27 16:54 UTC
2.6.0-rc8

![image](https://user-images.githubusercontent.com/86831399/131162138-bb60d7c1-17ec-42e2-9eb3-c5dcd39bb20e.png)

They disappear from Cluster Management -> Clusters, but stay listed on the Home page.

**Comment by gaktive** [comment] 2021-09-07 17:35
We believe this likely is a timing issue, so I'm curious to know; does this eventually clear? This may be a case of something dynamic needing updating, so let us know if this does resolve itself or a refresh occurs. We may need to pass this to the backend depending on what you find.

**Comment by peteingithub** [comment] 2021-09-07 18:03
I've not seen it disappearing. I guess I had the situation around about two days until nuking the setup for a clean start.

**Comment by catherineluse** [comment] 2021-09-14 03:45
I can't reproduce this issue. I created an RKE cluster in Digital Ocean and then deleted it. Then it quickly disappeared from both the cluster management app and from the home page.

**Comment by catherineluse** [comment] 2021-09-14 04:14
I couldn't reproduce the issue. I tried deleting both healthy and failed clusters. (I forced a newly provisioned cluster to fail by running Rancher on localhost.) After deleting the failed cluster, it disappeared quickly from the cluster management app and from the home page.

**Comment by peteingithub** [comment] 2021-09-14 06:55
It must be fixed with the new code.

The original process of mine was: 
1) Provision RKE1 with Rancher
2) Delete RKE1 with Rancher
3) Re-provision RKE1 with Rancher (forgot to re-create the VM nodes) -> failes
4) Delete RKE1 with Rancher -> clears in Cluster Management, sticks in the Home page

**Comment by nwmac** [comment] 2021-09-14 07:52
Moving to test for QA to validate and re-open with clear steps to reproduce if they are able to do so.

**Comment by sowmyav27** [comment] 2021-09-17 23:58
**On 2.6.0, cannot reproduce the issue**

- Create a custom cluster, add a node
- Delete cluster, cluster gets deleted successfully from cluster management and Home page
- Create a custom cluster with no nodes. Delete this cluster. Cluster gets deleted successfully from cluster management and Home page.
- Deploy a node driver cluster. Dlete the nodes from backend. cluster goes into error state. Delete this cluster and the cluster is deleted successfully from cluster management and Home page

**On 2.6-head commit id: `1a57856`**
- Deploy a node driver cluster. Dlete the nodes from backend. cluster goes into error state. Delete this cluster and the cluster is deleted successfully from cluster management and Home page
- Create and delete EKS/GKE/AKS clusters. clustes are deleted successfully from cluster management and Home page

Closing this issue for now. WIll log a new one or reopen if this issue is seen again.

**Closed by sowmyav27** 2021-09-17 23:58 UTC
Labels: [zube]: QA Working
