### ISSUE TITLE
Vue3: Resource search filtering doesn't work

### ISSUE THREAD

**Issue by eva-vashkevich** [rancher/dashboard#11727] opened 2024-08-27 17:55 UTC
**Setup**
- Rancher version: 2.10
- Rancher UI Extensions:
- Browser type & version:

**Describe the bug**
 
Resource search doesn't filter out values as user types

**To Reproduce**

1. Local cluster -> resource search
2. try typing "config"

**Result**
Result list is not updated
<img width="1267" alt="Screenshot 2024-08-27 at 10 56 26 AM" src="https://github.com/user-attachments/assets/4d997b24-f610-445c-9bc7-f2fbdd8ce91c">

**Expected Result**

resource list should reflect the search
<img width="1710" alt="Screenshot 2024-08-27 at 10 55 07 AM" src="https://github.com/user-attachments/assets/10afa23c-e485-49d6-a3f0-499da4c4c469">

**Screenshots**

**Additional context**

**Comment by rak-phillip** [comment] 2024-08-27 18:09
I'm closing this as a duplicate of #11700. The issue should have already been resolved, can you make sure that you are running the latest changes from master to confirm that you're not seeing this behavior anymore?

**Closed by rak-phillip** 2024-08-27 18:09 UTC
Labels: kind/bug, QA/dev-automation, area/vue3
