### ISSUE TITLE
unable to edit RKE1/Import clusters via dashboard -> iframe page is not loading

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3957] opened 2021-08-20 21:51 UTC
**Rancher Server Setup**
- Rancher version:2.6-head (06c8898)
- Installation option (Docker install/Helm Chart):docker 
   - If Helm Chart, Kubernetes Info:
         Cluster Type (RKE1, RKE2, k3s, EKS, etc):k3s
         Node Setup:
         Version:v1.21.3+k3s1
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.21.4
- Cluster Type (Local/Downstream):downstream 
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Digital Ocean

**Describe the bug**

Unable to edit the cluster through dashboard

**To Reproduce**
 
* provision the cluster (rke1)
* allow cluster to come to an `active` state
* edit the cluster through the hamburger menu ...

**Result**
iframe page never loads, and user is unable to edit the cluster through the dashboard

**Expected Result**

all iframe pages are expected to load properly through dashboard

**Screenshots**

**Additional context**

* I was able to edit the cluster in the same setup using ember
* the create iframe page is working fine for me
* there were no errors observed in the console, 
* the only error I see in the rancher logs is `http: TLS handshake error from <ip>:56671: remote error: tls: unknown certificate`

**Comment by sowmyav27** [comment] 2021-08-20 22:19
Edit as Yaml and save gives error `{ "data": "404 page not found\n" }`

**Comment by gaktive** [comment] 2021-08-20 22:51
Sounds similar to #3939

**Comment by gaktive** [comment] 2021-08-20 23:11
@nwmac not sure if there's anything you can look at here for Monday in case we run out of time today.

**Comment by gaktive** [comment] 2021-08-20 23:13
@slickwarren I was reminded that Ember was broken earlier today. Were your tests done during that time when Darren was fixing the build?

**Comment by slickwarren** [comment] 2021-08-20 23:28
No, they were done after that.  Also Sowmya verified on a later commit than I from a build today.

**Comment by mantis-toboggan-md** [comment] 2021-08-21 23:16
This definitely looks like a UI issue, but I haven't been able to pin it down, will need more help from someone more familiar with the Ember iFrame code...

(I consistently see this in production but not locally)
I get this error in the console: 
![Screen Shot 2021-08-21 at 4 10 11 PM](https://user-images.githubusercontent.com/42977925/130337014-57c40aa6-b53c-4491-9fba-9d8f3fd6ef44.png)
It looks like `default.vue` is being rendered twice (I put a break point in its `created()`), and the second time `this.$route` is the ember route: 
![Screen Shot 2021-08-21 at 4 14 07 PM](https://user-images.githubusercontent.com/42977925/130337074-85471a28-4ccc-452b-a282-b409fafd5b2d.png)
It makes sense to me that the dashboard would error when trying to load this route, but I don't know how it's getting there in the first place :L

**Comment by nwmac** [comment] 2021-08-22 09:32
The IFRAME code is working okay - inspect the page and you'll see the iframe in the DOM - it remains hidden since it turns out if loads a dashboard page, not an ember page - if you take the 'visibility: hidden' style off, you'll see that.

The URL it is loading is correct:  (e.g.) /c-m-brmpgt62/edit?provider=import&importProvider=other - but it is being served a Vue page, not an Ember page.

I remember @vincent99 said some redirect stuff had changed - we no longer have the dashboard prefix in the URL, so there is now overlap between the /c URL if ember and /c of dashboard,

**Comment by nwmac** [comment] 2021-08-23 07:37
The root cause was a change to the backend routing which meant Ember routes (/c and /p in particular) were serving the dashboard UI.

This has been fixed now.

**Comment by prabalsharma** [comment] 2021-08-23 22:48
on v2.6-b8a44fad559b05f12d973b527d9d547bbe94e8f8-head
Now I can Edit a cluster. I tried with AKSv2 cluster, when I click on `Edit Config`, I am no longer seeing a blank page.

**Closed** 2021-08-23 22:51 UTC
Labels: status/blocker, [zube]: To Test, status/release-blocker, kind/bug-qa
