### ISSUE TITLE
Members added to new Custom cluster do not create all ClusterRoleTemplateBindings and does not display in UI properly

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7582] opened 2022-11-29 22:53 UTC
Internal reference: SURE-5599
Reported in 2.6.9

When creating a cluster by going to Cluster Management > Create > Custom and adding multiple 'Member Roles' for the same user, it does not create all the roles on initial cluster creation, only the first. After saving and creating the cluster, all but one clusterRoleBindings are created (seems random which one). If you look under Cluster Management > 'cluster name' > Config > Member Roles, only one of the roles is listed for each user which can also be confusing to users.

The custom role binding (CRB) doesn't appear to be created properly as a result, though we'd need to repro to confirm what's being created. 

### Scenario 1 - 1 user with 2 member roles

- create cluster,
- add multiple roles for a user (e.g, custom roles "Create Project" and "View Nodes")
- add node
- When cluster is up, check clusterRoleBindings and check if the roles were all assigned to the users.
- Check the Member Roles under the cluster management page and see if all roles are listed.

Result: user will appear with only one of those roles (which will be random as to which one).
Note: if selecting more than 2 roles, then either only one role is applied, or all but one, but not all (need to verify this behaviour but whatever it is, isn't ideal).

### Scenario 2 - 2 users with each 2 member roles

- create cluster,
- for each user, add multiple roles 
- add node
- When cluster is up, check clusterRoleBindings and check if the roles were all assigned to the users.
- Check the Member Roles under the cluster management page and see if all roles are listed.

Result: 1 user will show both roles but the second user will show only one. Not sure of the variation with more than 2 roles but 1 user will be correct.
Note: with more than 2 users with multiple member roles, it appears, again, only one user will be impacted with showing incorrect information

### Scenario 3 - 2 users with each 1 member role

- same creation steps as above

Result: display is fine and CRBs created properly.

### Other notes

- when viewing the Member Roles, it's not clear what we should display since we show each user multiple times with a Custom role when multiple roles are selected (so in Scenario 2, we'd show one user twice and the second user once, all with Custom). This may require a separate ticket for UX on this page.

Screenshots with 3 users:

![after_roles_test.png](https://zube.io/files/rancher/2f12e33e66905c8d568039f3379beb38-after_roles_test.png)

![after_roles_test.png](https://zube.io/files/rancher/2f12e33e66905c8d568039f3379beb38-after_roles_test.png)

For 2 users, the difference between the role bindings put into place (n.b, one user clearly has two whilst the other has one):

![user2_crb.png](https://zube.io/files/rancher/3cae587d42570979f1a55bb519a1ea3b-user2_crb.png)

![user3_crb.png](https://zube.io/files/rancher/f3c8024866587261878f416397d5e53d-user3_crb.png)

**Comment by gaktive** [comment] 2023-01-11 17:17
This is happening on RKE1. Don't know if we have to look at RKE2 but this hopefully helps narrow down where to look.

**Comment by gaktive** [comment] 2023-04-05 16:06
Thanks @Shavindra. So it looks like this could be addressed by those other tickets, but those would need to be verified first and then this ticket would then be tested. Is that correct so QA knows which order to test things?

**Comment by Priyashetty17** [comment] 2023-05-24 22:40
Re-opening the ticket as the issue still exists.
	• Rancher version: v2.7-6ce75a0b57ad9e88cf135254a9b3b40082788eb6-head
	• Dashboard: master d112f1781

Steps to recreate:
Add a downstream custom RKE1 cluster. During cluster creation, add 3 users with the following roles .

- testUser1 - Create Projects, View All Projects, Manage Nodes, View Nodes
- testUser2 - Create Projects, View All Projects, Manage Nodes, View Nodes
- testUser3 - Create Projects, View All Projects, Manage Nodes, View Nodes
- testUser2 - Owner
- testUser3 - Member

**Issue1**[❌]: On the Cluster Management page, the "Member Roles" section does not include testUser2 with the role "Owner" and testUser3 with the role "Member" for the downstream RKE1 cluster.

**Issue2**[❌]:  Based on my conversation with Shavindra on slack, the fix for this issue involves separating the roles individually (in Edit Cluster) instead of grouping them under "Custom". However, the issue still persists for RKE1 clusters. For RKE2 clusters, this problem does not occur, and the roles are correctly separated individually.

![Edit_Cluster](https://github.com/rancher/dashboard/assets/42880103/8c34ef56-4b87-4580-b4e2-d2b4dd998e73)

**Note**: 
	• Verified that the cluster role bindings for each user is correct. 
	• Verified that the members and roles in the downstream cluster is correct.

<img width="1277" alt="image" src="https://github.com/rancher/dashboard/assets/42880103/fa4d8430-c841-40f2-8250-86107b5ec85a">
<img width="1267" alt="image" src="https://github.com/rancher/dashboard/assets/42880103/5d883c56-753f-4ef3-aea4-59b7ed657dd9">
<img width="1278" alt="image" src="https://github.com/rancher/dashboard/assets/42880103/421ba3b5-4caf-4587-bd10-a492aec7c413">



@Shavindra Considering the multiple issues mentioned and the discrepancy between the details provided in the linked PR and the actual problem described here, can you please provide a QA validation template with specific areas that require validation as part of this issue? By having a well-defined template, we can focus on the appropriate test scenarios for this issue and not miss testing something or duplicate what has already been validated by other tickets tagged with this issue.

**Comment by Priyashetty17** [comment] 2023-05-29 19:48
Shivendra confirmed that the issues I raised earlier are known problems specific to the RKE1 cluster, and this is due to the reliance of the RKE1 cluster creation process on the Ember UI. And, there are currently no plans to make changes to the Ember UI. So, I executed scenarios listed below to validate the PR: https://github.com/rancher/dashboard/pull/8330 to ensure the functionality described therein is verified.

| Component                        | Version         |
| -------------------------------- | ------------------------ |
| Rancher version                  | v2.7-fbca7c34e5aeae36b85d8b0e9af12a2f6f13e0ea-head                         |
| Dashboard              | Hmaster d98247e90 |

### Scenario1: Cluster Membership [✅ PASSED]

1. Add a downstream RKE2 cluster. During cluster creation, add 2 users with multiple roles - Custom, owner, member.
2. After the cluster is created, verify that the members and roles in the cluster management for downstream cluster are correct.
3. Verify that the cluster role bindings for each user is correct. 
4. In the Cluster Membership page, 
    1. Verify that the members and roles in the downstream cluster are correct.
    2. Click on the different grouping options (Flat List, Group by Namespace, Group by Role) and verify that the views change appropriately.
    5. For each grouping option,
        1. Add a user with a different role and verify  that the UI automatically refreshes to include the recently added member.
        2. Delete a member role and verify that the deletion is successful in both cluster management and cluster explorer for the downstream cluster. 
6. Delete a member role in the cluster management for downstream cluster. Verify that the role is no longer listed for the user in both the Cluster Membership page and Cluster Management. 
7. Delete one of the two created users and validate that the user, along with its associated role, is no longer available in both the cluster management and the cluster explorer for the downstream cluster. Also, verify that the associated cluster role bindings have been deleted.

**Screenshots for Step2:**
![ClusterMgmt_EditConfig](https://github.com/rancher/dashboard/assets/42880103/2ba5fe55-79e6-48e0-aab5-3a29d155724b)
![testUser1_ClusterRoles](https://github.com/rancher/dashboard/assets/42880103/bb2e1543-c3b6-461e-9ff0-7cc68f00fa4e)
![testUser2_ClusterRoles](https://github.com/rancher/dashboard/assets/42880103/a318c22f-e13b-4b1b-9b4c-ac0c7e5dcd5d)

**Screenshots for Step3:**

- testUser1: u-5dn2c
- testUser2: u-n5hrd

![testUser1_u-5dn2c_ClusterRoleBindings](https://github.com/rancher/dashboard/assets/42880103/42011570-4402-4c4d-b628-a83cb4766da2)
![testUser2_u-n5hrd_ClusterRoleBindings](https://github.com/rancher/dashboard/assets/42880103/7ce62f6a-20b1-48cb-a4ac-5a4466e4c88d)

**Screenshots for Step 4.ii:**
![ClusterExplorer_FlatList](https://github.com/rancher/dashboard/assets/42880103/f7103442-aff9-443d-9b0c-cbfca379a1a1)
![ClusterExplorer_GroupByNS](https://github.com/rancher/dashboard/assets/42880103/8d5054b9-8a89-4830-9793-5036d79b348f)
![ClusterExplorer_GroupByRole](https://github.com/rancher/dashboard/assets/42880103/ec231a54-fd49-442c-8f11-2a3cfad250a0)

### Scenario2: Project Membership [✅ PASSED]

1. Create a new Project. During project creation, add 2 users with multiple roles - Custom, owner, member. Add a 3rd user as readonly.
2. After the project is created, choose the project > Edit config. Verify that the members and roles in the project are correct.
3. In the Project Membership page, 
    1. Verify that all roles are grouped together for each user.
    2. Add a user with a different role and verify that the UI automatically refreshes to include the newly added member.
    3. Delete a role for a user and verify that the deletion is successfully reflected in both the Project Membership page and the "Projects/Namespaces>Edit Config".
    4. Delete all roles associated with a user and verify that the member is removed from the list.
4. Delete a member role in the "Projects/Namespaces>Edit Config". Verify that the role is no longer listed for the user in both the Project Membership page and "Projects/Namespaces>Edit Config"
5. Delete one of the three created users and validate that the user, along with its associated role, is no longer available in both the Project Membership page and the "Projects/Namespaces>Edit Config".
6. Enable "View in API" and verify that clicking on a role in the  Project Membership would take the user to View In API.

**Screenshot for Step2:**
![Projects_EditConfig](https://github.com/rancher/dashboard/assets/42880103/d82adb62-4504-4ebd-9009-bcffe4edcf13)

**Screenshot for Step3.i:**
![ProjectMembers](https://github.com/rancher/dashboard/assets/42880103/a651ee84-cfa7-4917-b66a-8491d40afcec)

Note:
- Tested with different browsers (Chrome and Firefox)
- Tested with different modes (Dark and Auto)
- Verified the groupings with Admin and Standard user login.

**Closed** 2023-06-05 12:34 UTC
Labels: kind/bug, [zube]: QA Working, team/area1, size/3, ember, JIRA, area/cluster-template
