### ISSUE TITLE
[virtualization management] swap `manage` and `explore` operations  to match UX in cluster management

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#4303] opened 2021-09-28 21:29 UTC
**Detailed Description**

We should swap the `manage` button to explore the cluster, and make the name of the cluster navigate to the management page. This is the behavior users are used to from cluster management. 

**Context**

here's a link to the original report: https://github.com/rancher/dashboard/issues/3466#issuecomment-924145064

In cluster management, when the user clicks the name of the cluster, they are brought to the `manage` page (node pools, related resouces, etc.) and there is a button on the far right to explore the cluster
<img width="1792" alt="Screen Shot 2021-09-21 at 9 16 02 AM" src="https://user-images.githubusercontent.com/16691014/134208242-d8ae6782-0ee1-44ce-b33f-20da450d0976.png">

however, in virtualization management, these are swapped.  There is a `manage` button on the far right, and clicking the name now brings you to the equivalent of the `explore` button from the previous example.

<img width="1791" alt="Screen Shot 2021-09-21 at 9 16 10 AM" src="https://user-images.githubusercontent.com/16691014/134208229-b2f793d4-a161-42c8-9a55-ff73bd670591.png">

**Comment by yasker** [comment] 2021-09-30 20:54
I agree we should swap the operations. We can still call the button `Manage`, but it's better if the behavior of link vs button is consistent across the pages.

**Comment by gaktive** [comment] 2021-10-01 16:42
This is working as designed; since the priority of each view is different, the consideration for the user on this screen is tied to what's most important to them. 

@yasker you can chat with @nwmac about the differences in work flow if needed.

**Comment by yasker** [comment] 2021-10-04 20:56
I understand what does @nwmac mean now.

The primary action for users to click the clusters on the `Cluster Management` page is to get information about the cluster, not accessing the explorer - which should be done via the hamburger menu.

The primary action for users to click the clusters on the `Virtualization Management` page is to access the Harvester UI, not to get information about the cluster.

So I think how it works currently makes sense in the current context (e.g. there is no Harvester cluster direct access via the hamburger menu). 

Close issue as won't fix.

**Closed by yasker** 2021-10-04 20:56 UTC
Labels: [zube]: To Triage, area/harvester, kind/bug-qa
