### ISSUE TITLE
Workloads: Unable to set various number based fields when creating a workload

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11953] opened 2024-09-18 13:20 UTC
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Entering valid values for the following are ignored
  - Cronjob --> Scaling and Upgrade Policy -->  `Successful Job History Limit` and `Failed Job History Limit` inputs
  - Container --> Health Check tab -->  set `Readiness Checks` to something other than `None` --> `Success Threshold` and `Failure Threshold` inputs
  - Container --> Health Check tab -->  set `Liveness Checks` to something other than `None` --> `Success Threshold` and `Failure Threshold` inputs
  - Container --> Health Check tab -->  set `Startup Checks` to something other than `None` --> `Success Threshold` and `Failure Threshold` inputs
  - Pod --> Security Context tab --> `Filesystem Group` input
  - Pod --> Node Scheduling --> select Run Pods on node(s) matching scheduling rules --> Add Rule --> `Weight` input

- We should understand if there's a common pattern and validate all other usages

**To Reproduce**
- Cluster Explorer --> Workloads --> Cronjobs --> Create --> CronJob tab --> Scaling and Upgrade Policy tab
- Enter numbers for either `History Limit` field 
- Defocus field

**Result**
- value is removed from input field

**Expected Result**
- value remains in input field

**Comment by rak-phillip** [comment] 2024-09-18 21:38
Waiting for further triage until #11902 merges. I suspect that the root cause is related and think that these instances could be addressed.

#11856

**Comment by mantis-toboggan-md** [comment] 2024-09-19 22:14
All cases listed here are fixed by #11902

**Comment by rak-phillip** [comment] 2024-09-19 22:21
@mantis-toboggan-md thanks for confirming! Closing as resolved in #11902.

**Closed by rak-phillip** 2024-09-19 22:21 UTC
Labels: kind/bug, priority/0, QA/dev-automation, area/vue3
