### ISSUE TITLE
Dashboard charts setting description enhancement

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2483] opened 2021-03-04 00:37 UTC
Rancher | v2.5-5a5c039d6ed75dc3803abd03c3d3504441f7e02c-head

In the cluster explorer, charts from apps and market place have descriptions for text box next to text box. Can this be changed to be present below the text box?

Example chart:
From cluster explorer --> apps and market place --> longhorn --> Private Registry Settings/Longhorn Default Settings/Longhorn Storage Class Settings/Other Settings have descriptions next to the text box.

Can we have the descriptions as follows:
<img width="500" alt="Screen Shot 2021-03-03 at 4 07 55 PM" src="https://user-images.githubusercontent.com/38144301/109891499-05ad6b80-7c3e-11eb-8bb9-bd84966d7bba.png">

Eg on dashboard 
<img width="500" alt="Screen Shot 2021-03-03 at 4 03 28 PM" src="https://user-images.githubusercontent.com/38144301/109891510-0ba34c80-7c3e-11eb-9651-73f0f4766bbc.png">

**Comment by vincent99** [comment] 2021-03-04 18:22
This was changed intentionally so that the questions are arranged in 1-dimension (top->bottom) instead of 2 (left->right + top->bottom).  Questions can be shown conditionally (based on the answer to other ones) and it's very disorienting when you do something that causes one additional question to show up but that makes some/all the fields (possibly include the question you're currently editing) "jump" to the opposite column.

Using the full width for each input is usually way more space than is needed, so the description was put on the right half instead.

**Comment by gaktive** [comment] 2021-03-29 16:11
Unless there's other feedback, this is working as designed.

**Comment by catherineluse** [comment] 2022-11-05 00:42
Closing this issue because we are no longer maintaining v2.5

**Closed by catherineluse** 2022-11-05 00:42 UTC
Labels: kind/bug, [zube]: Icebox
