### ISSUE TITLE
k3s cluster provisioned with etcd shows "Etcd Not Applicable"

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5419] opened 2022-03-16 22:52 UTC
Internal references: SURE-3459, SURE-3216
Reported in 2.5.9

Issue description:
A k3s cluster created with etcd shows "Etcd Not Applicable" in rancher UI when added to rancher.

Business impact:
Minimal, but state of etcd is not visible through UI

Troubleshooting steps:
N/A

Repro steps:

- Build k3s cluster with etcd
- Add k3s cluster to a rancher install (or install rancher on the cluster.)
- Observe the dashboard for the cluster in the rancher UI

Actual behavior:
Shows N/A

Expected behavior:
Shows status of etcd

**Comment by nwmac** [comment] 2022-04-29 12:39
@neillsom I could not reproduce this - suggest you install 2.5.9 and validate - not sure whether this is in Ember or dashboard.

**Comment by neillsom** [comment] 2022-06-07 23:23
Unable to reproduce. 

Install rancher v2.5.9 via helm following these docs https://rancher.com/docs/rancher/v2.5/en/quick-start-guide/deployment/digital-ocean-qs/

Issue may be due to etcd nodes being managed externally in the customer's environment. 
It's possible that the customer set up the cluster with the CLI and imported it into Rancher. If so, displaying "Etcd Not Applicable" would be the desired outcome. 

@catherineluse has asked a clarifying question in Jira 

![Screen Shot 2022-06-07 at 3.59.46 PM.png](https://zube.io/files/rancher/8fe07f8b165eda6e6b80c30497059b09-screen-shot-2022-06-07-at-3-59-46-pm.png)

**Comment by catherineluse** [comment] 2022-06-08 17:13
Yep. To expand on that, basically if you set up k3s with the cli, you can set master and worker nodes, and I would expect the master nodes to be treated as etcd nodes in Rancher.

But if they used the external database option with the CLI, I don't know how Rancher would be able to see the status of etcd, or if it would even be able to tell the difference between an external etcd database and an external SQLite database.

If the problem is the latter, we might have to change the error message to say something more along the lines of "could not detect etcd nodes because the external database option is selected" or something like that.

**Comment by catherineluse** [comment] 2022-06-08 17:15
To reproduce this we might have to set up k3s with an external database.

**Comment by nwmac** [comment] 2022-07-08 09:06
I can not reproduce this. This was reported in 2.5.9.

This has either been fixed or is not applicable to 2.6.

**Comment by Josh-Diamond** [comment] 2022-07-20 22:38
Unable to reproduce on `v2.6.6` and `v2.6-head`

@gaktive unsure how to proceed; not reproducible on `v2.6.6` or `v2.6-head` and no PR mentioned with potential fix; seems devs also were unable to reproduce this

**Comment by Josh-Diamond** [comment] 2022-07-21 18:23
Update:
I'd like to re-test this with Catherine's suggested implementation of using external db.. but i need to get more info from the customer:
- Are you still experiencing this issue?
- Have you upgraded?
- Request server + cluster env specs

**Comment by gaktive** [comment] 2022-08-26 23:49
At this point, one user indicated that this was fixed in 2.6.6 so I think we can wrap this up now as we'll get no other info, barring future breakage.

**Comment by Josh-Diamond** [comment] 2022-08-30 16:33
Unable to reproduce; requested info not provided;
Closing issue - [seems to have been addressed or is non-issue w/ v2.6]

**Closed by Josh-Diamond** 2022-08-30 16:33 UTC
Labels: kind/bug, [zube]: To Test, internal, QA/S, team/area2, size/1, JIRA

**Comment by Josh-Diamond** [comment] 2022-08-31 17:42
Ticket #5419 - Test Results

With Docker on a single-node instance:

Verified on rancher `v2.6.8`:
1. Fresh install of rancher `v2.6.8`
2. Create a standalone k3s cluster and import it into rancher - [ v1.24.4+k3s1 ]
3. Once active, observe `Dashboard` from `Cluster Explorer`
4. Verified - Ectd status accurately displayed
