### ISSUE TITLE
`Name` field for `Receiver` in `AlertmanagerConfig` needs to be marked as mandatory

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#6391] opened 2022-07-18 17:00 UTC
**Setup**
- Rancher version: 2.6.6
- Browser type & version: Firefox 102.0

**Describe the bug**
When creating an `Receiver` within an `AlertmanagerConfig` object, the `name` field is not marked as mandatory. If left empty, it will fail to create the object and the UI does not report the error

**To Reproduce**
1. Install the Rancher monitoring chart
2. Navigate to `Monitoring > Alerting > AlertmanagerConfigs`
3. Create an `AlertmanagerConfig` object
4. Edit the `AlertmanagerConfig` in step 3 to create a receiver
5. Select a receiver (such as Slack
6. Fill out the respective fields
7. Click `Create`

**Result**
No errors presented in the UI, the Receiver object isn't created, and the API call generates a 422: 

```
{
	"type": "error",
	"links": {},
	"code": "Invalid",
	"message": "AlertmanagerConfig.monitoring.coreos.com \"test\" is invalid: spec.receivers.name: Required value",
	"status": 422
}
```

**Expected Result**
The receiver name field to be marked as mandatory, and the UI to report if it's `null`

**Screenshots**
The Name field in the top left needs to be mandatory
![image](https://user-images.githubusercontent.com/5892615/179563829-8f73f7cd-32f0-4b95-92ba-f8aee4645a8e.png)

**Comment by Sean-McQ** [comment] 2023-06-23 15:39
Unable to reproduce, this seems to be working in latest: ![image.png](https://zube.io/files/rancher/1cb133109012b14bf8a2a99587d5da5c-image.png)

**Comment by ronhorton** [comment] 2023-08-01 19:14
**Pass** verified in rancher `v2.7-head commit ID 027246f`
1. installed monitoring v2 on downstream cluster
2. navigated to cluster > monitoring > alerting > alertmanagerconfigs
3. created new alertmanagerconfig
4. clicked 3 dots on new alertmanagerconfig and selected 'edit config'
5. clicked 'add receiver'
6. completed form to create an sms receiver
7. 'create' button grayed out/not available
8. Name field marked as required
9. added name in field
10. create button enabled
11. deleted name from field
12. create button disabled
13. added name and clicked 'create'
14. receiver added successfully 

https://zube.io/files/rancher/f4766ecda70c531af517be1d336451c8-2023-08-01_15-13-02.mp4

**Closed** 2023-08-01 19:14 UTC
Labels: [zube]: Done, kind/enhancement, team/area3, area/form-validation, area/monitoring-alerting
