### ISSUE TITLE
UI Displays Additional Node Pool When Cluster Name is 63 Characters

### ISSUE THREAD

**Issue by HarrisonWAffel** [rancher/dashboard#8033] opened 2023-01-25 21:27 UTC
**Setup**
- Rancher version: Tested on 2.6.9, 2.7.0, and 2.7-head
- Browser type & version: Any

**Describe the bug**
An additional node pool is displayed in the UI when an RKE2/K3s cluster is created containing a node pool whose name exceeds 63 characters when prepended with the cluster name. When such a configuration is provided, the Rancher backend will shorten the node-pool name so that it is at most 63 characters long. However, the original un-shortened version is also seen in the UI. This is the first time this behavior has been seen, so this is likely a regression. 

**To Reproduce**
Create an RKE2/K3s cluster and provide a name which is 63 characters long. You do not need to modify the node-pool name, as the default value will result in a valid reproduction.

Example: 

Cluster name: haffel-long-cluster-name-test-1235-loremipsumdolorsitametconsec (63 characters)
Pool Name: pool1 (6 characters)
Resulting node-pool name: haffel-long-cluster-name-test-1235-loremipsumdolorsitametconsec-pool1

**Result**

Two node pools are seen, one which has a name equal to the pool seen on the provisioning cluster yaml, and another which has a name which exceeds 63 characters and is not seen on the provisioning cluster yaml

**Expected Result**
Only one node pool is shown, and its name equals the name of the node pool seen on the provisioning clusters yaml.

**Screenshots**
![Screen Shot 2023-01-25 at 3 58 52 PM](https://user-images.githubusercontent.com/25062254/214693962-3fe75ac6-c751-476e-8c49-5db6951cb435.png)

**Additional context**
The scaling buttons on the undesired node pool work and properly scale the desired node pool.

**Comment by richard-cox** [comment] 2023-01-27 11:05
This is most probably an artefact on the original issue https://github.com/rancher/rancher/issues/40143. 

@HarrisonWAffel  Can you confirm the additional pool is returned by the backend by either loading `<rancher url>/v1/cluster.x-k8s.io.machinedeployments` or visiting the MachineDeployments list `<rancher url>/c/_/manager/cluster.x-k8s.io.machinedeployment` ?

**Comment by HarrisonWAffel** [comment] 2023-01-27 15:28
@richard-cox 

When I visit `<rancher url>/v1/cluster.x-k8s.io.machinedeployments` I only get a single machine deployment back in the response, and it has the shortened title generated by the backend. 

![Screen Shot 2023-01-27 at 10 21 38 AM](https://user-images.githubusercontent.com/25062254/215122395-9f2a673c-3c14-4e0d-841f-aac0fb76f42b.png)

I tried visiting `<rancher url>/c/_/manager/cluster.x-k8s.io.machinedeployment` however that gave me an error message. I used the cluster explorer for the local cluster and only observed a single machine deployment there too 

![Screen Shot 2023-01-27 at 10 23 50 AM](https://user-images.githubusercontent.com/25062254/215122777-96d9ef85-d98e-43a4-a616-1de8258eb23f.png)


`kubectl` also only shows a single machine deployment 

![Screen Shot 2023-01-27 at 10 26 23 AM](https://user-images.githubusercontent.com/25062254/215123347-1ba7c22c-ad4a-4b25-8668-abd9cc6883da.png)


However I can still see the additional node pool in the UI 

![Screen Shot 2023-01-27 at 10 24 55 AM](https://user-images.githubusercontent.com/25062254/215122939-655ae32f-5d0f-454f-a351-723c1ac5cd1a.png)

**Comment by gaktive** [comment] 2023-02-08 17:16
@scures saw this recently with less than 63 characters as part of hack week, though he'll have to look into the full name.

@aalves08 found some related code: https://github.com/rancher/dashboard/pull/7543/files#diff-a82b21daf1dd70199627fd86da6e1ed80f8260507e624619bd1b1519c45d9864

**Comment by jameson-mcghee** [comment] 2023-02-17 21:57
I was able to reproduce this issue on `v2.6.9-rc1` by following the Steps to Reproduce. However, I was unable to reproduce this issue on `v2.7-head` (Commit ID: a91b7fc) when following those same Steps to Reproduce. Therefore I am closing this ticket.

**Steps to Reproduce:**
1. Spin up a Rancher server
2. Provision a RKE2/K3s a single node cluster that has the cluster name "_haffel-long-cluster-name-test-1235-loremipsumdolorsitametconsec_"
3. Navigate to the _Cluster Management_ -> _Machine Pools_ page for the cluster and note the number of node pools

**`v2.6.9-rc1`:**
![image](https://user-images.githubusercontent.com/13294321/219800702-dcc5d034-766c-4324-8fc0-d8c161e447bf.png)

**`v2.7-head` (Commit ID: a91b7fc):**
![image](https://user-images.githubusercontent.com/13294321/219801114-87fde45d-21cb-4937-a077-846c9b65f0a6.png)
![image](https://user-images.githubusercontent.com/13294321/219801126-18b3b731-1bab-42d4-86db-696d75f46d56.png)

**Closed by jameson-mcghee** 2023-02-17 21:57 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, area/rke2, team/area2, size/2, team/ui
