### ISSUE TITLE
Add ability to scale a workload up/down form the detail view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5087] opened 2022-02-10 15:21 UTC
In Cluster Manager, from the workload view it was easy to scale up/down a workload.

In dashboard, you have to go to the workload, go to the edit view, change the  number of replicas and save.

Should consider bringing this out on the main detail view for the workload.

**Comment by richard-cox** [comment] 2022-02-10 15:25
You can do this from the workload list view. When those were added I looked at using the same +/- icons in the workload view header... but we have no way to inject custom content there. Think we'd need a custom workload detail page with changes to the resource detail masthead to `slot` the scaling buttons in

**Comment by catherineluse** [comment] 2022-03-29 17:32
Closing as duplicate of https://github.com/rancher/dashboard/issues/5114

**Closed by catherineluse** 2022-03-29 17:32 UTC
Labels: internal
