### ISSUE TITLE
Resources Unavailable on Monitoring page after upgrade to 2.7.5

### ISSUE THREAD

**Issue by skanakal** [rancher/dashboard#9506] opened 2023-08-09 09:01 UTC
Internal ref: SURE-6700

**Setup**
- Rancher version: 2.7.5
- Rancher UI Extensions:
- Browser type & version: 

**Describe the bug**

Users with 'View-Monitoring' but no access to catalog.cattle.io.app can no longer see the Grafana and other monitoring links from the Monitoring page in the UI.

**To Reproduce**

1. On cluster pre 2.7.5, create user with a 'cluster-user' custom role that inherits 'monitoring-ui-view' and also has the GET/CREATE on services/proxy
2. Test that monitoring links are clickable
3. Upgrade to 2.7.5

**Result**
monitoring links are unclickable 

**Expected Result**

After the upgrade monitroing link should be clickable

**Screenshots**

![image](https://github.com/rancher/dashboard/assets/124564266/9cb475a2-4096-45c0-8275-6955fff65954)

**Additional context**

As a workaround, Added read-only to the Project with monitoring or GET to [apps.catalog.cattle.io](https://apps.catalog.cattle.io/) and these restored access to the links, but this granted access to monitoring secrets...
They think they found [the commit](https://github.com/rancher/dashboard/pull/9019/files#diff-469b800976e27c571b923ecd2c6e50f43f661ebcbee01453a9f50f013aeceb2fR100-R103) that changed the behavior and is missing the try-catch, as seen [elsewhere](https://github.com/rancher/dashboard/pull/9019/files#diff-bebf1de7926da8c54d344007ddfaf43b8b70bf39f48b2bec860f8e86e127de9aR59-R63).

**Comment by skanakal** [comment] 2023-08-09 09:02
[[BUG] monitoring view, services cannot be be used (grafana, alertmanager) #42104
](https://github.com/rancher/rancher/issues/42104)

**Comment by richard-cox** [comment] 2024-02-06 14:40
Possibly resolved in 2.8.0 via https://github.com/rancher/dashboard/pull/9826. Needs validating with these specific roles (but given workaround looks hopeful)

**Comment by richard-cox** [comment] 2024-02-08 11:06
@MKlimuszka `waiting-ux` indicates it's waiting for UX/Design input. The zube labels roughly map to ui issue root state

**Comment by richard-cox** [comment] 2024-02-08 11:19
@skanakal can you provide the yaml for the custom role, and is it a cluster or project role (linked ticket talks about project but it's not clear here)? Can you also confirm if the user assigned to the role is a global `standard-user` (and not `user-base`)?

**Comment by skanakal** [comment] 2024-02-08 13:32
@richard-cox It been so long time since I reproduced this issue. If my recollection is accurate, a standard user, assigned a project role with monitoring UI view, GET/CREATE permissions on services/proxy, and other necessary permissions to access the links...

**Comment by richard-cox** [comment] 2024-02-21 10:51
I tried to reproduce this with a custom cluster role which inherited `view monitoring` and had get / create on services. Navigating to the cluster... things went wrong. It looks like there were failures fetching /endpoints (even though the user could see the schema). I could not get the monitoring tab to be visible (it requires the `monitoring.coreos.com.podmonitor` schema which is missing). The cluster also went down.

I did notice that the view monitoring role is a project one, rather than a cluster one. @skanakal to confirm, you adding it to a custom cluster rather than custom project role.. and this was working pre-upgrade? Would you be able to assist confirming the issue is resolved in 2.8.0 (or later)?

**Comment by nwmac** [comment] 2024-05-22 08:04
Verified - this is not an issue in 2.9.0.

This is the custom cluster role I used:

![image](https://github.com/rancher/dashboard/assets/1955897/af39e73e-d1e3-4d6b-9bae-a82b1d0f3b6b)

**Comment by nwmac** [comment] 2024-05-22 08:05
The code has changed a lot since 2.7.5 and now has guards, so being unable to retrieve the list of apps does not cause the problem reported in this issue

**Comment by nwmac** [comment] 2024-05-22 08:06
@gaktive I think we should move this to test, unless I am missing some context?

**Comment by IsaSih** [comment] 2024-07-02 23:04
Not reproductible

**Closed by IsaSih** 2024-07-02 23:04 UTC
Labels: kind/bug, area/monitoring, size/3, JIRA, QA/manual-test

**Comment by Chaituec806** [comment] 2024-10-22 19:27
Issue is still happening. Rancher version # [v2.9.1]

unable to view grafana dashboard

{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "error trying to reach service: dial tcp 10.0.37.2:8080: connect: connection timed out",
  "reason": "ServiceUnavailable",
  "code": 503
}
