### ISSUE TITLE
Setup: Don't ask for Server URL if multi-cluster management feature flag is off

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#3283] opened 2021-06-17 13:13 UTC
We can skip asking for the server URL in the setup flow if Rancher has been deployed with the multi-cluster management feature flag off.

We should, however, prompt the user for the server URL IF they activate the feature flag from the feature flags page (if it has not been set already).

**Comment by gaktive** [comment] 2021-06-21 17:36
Duplicate of https://github.com/rancher/dashboard/issues/3286 -- we'll close this one and use the other.

**Closed** 2021-06-21 17:37 UTC
Labels: [zube]: Done

**Comment by nwmac** [comment] 2021-06-21 17:39
@gaktive we should generally close the newer duplicate.
