### ISSUE TITLE
Support Harvester UI changes outside of the Dashboard release process

### ISSUE THREAD

**Issue by yasker** [rancher/dashboard#4109] opened 2021-09-03 22:47 UTC
Currently, the Harvester is a separate project from Rancher, but due to UI dependency, the Harvester's release cycle is tightly coupled with Rancher, because:
1. Harvester and Rancher share the same UI codebase.
2. When a user uses an upstream Rancher server to manage downstream Harvester clusters, the Harvester part of the UI is in fact provided by the upstream Rancher UI, instead of the downstream Harvester cluster. This means there will be compatibility issues if the user only upgrades upstream Rancher to a newer version or upgrade downstream Harvester cluster to a newer version.

This will also be a problem for other projects like Longhorn. 

If we can componentize the Rancher Dashboard UI, and create a library for any applications that want to integrate with Rancher to create a seamless experience, it will benefit the project like Harvester, Longhorn, and any other projects who want to integrate with Rancher UI but still requires standalone UI and release cycle.

**Comment by nwmac** [comment] 2021-09-07 07:19
@yasker This is in plan and we will be figuring out how best to achieve this.

**Comment by gaktive** [comment] 2022-01-04 23:44
Need to meet with @nwmac and other leads who have stakes in this separation to see how tenable this is for 2.6.4. Aside from Harvester and Longhorn, other projects like Kubewarden, Epinio and elsewhere would need input.

**Comment by agracey** [comment] 2022-01-21 01:42
@gaktive, I think this is also helpful for where we hope to go with Rancher Desktop as well since it'll give us more control over what we build in.

**Comment by gaktive** [comment] 2022-05-03 16:42
Once UI wraps up 2.6.5, we need to do this switch early to catch things well before release.

**Comment by gaktive** [comment] 2022-09-06 15:28
For context, Harvester needs this for 2.6.9.

**Comment by richard-cox** [comment] 2022-09-07 13:24
For clarification
1) Harvester code to be split out in to it's own UI plugin (completed via https://github.com/rancher/dashboard/pull/6729)
2) Harvester plugin to be built and served up by the Harvester Cluster
3) Fallback Harvester plugin built and served up by the Dashboard (to support legacy clusters that don't contain the plugin)
4) Dashboard to dynamically load the Harvester plugin (from cluster or dashboard) when navigating to the cluster

**Comment by richard-cox** [comment] 2022-09-13 10:23
The harvester team will handle QA. I've marked this as `dev-validate` to ensure Rancher QA avoid

**Comment by richard-cox** [comment] 2022-09-13 14:22
@slickwarren The harvester team have requested QA take a look at this from the Rancher Manager side. It's worth coordinating with them for specifics of what they would like you to cover, but it's worth you and me getting together on a call to run through how the new dynamic loading works and when it will be available to test (probably when RC 1 is created

**Comment by slickwarren** [comment] 2022-09-22 20:49
did some initial testing with rancher v2.6.9-rc1 and harvester v1.1.0-rc1:
* virtualization management -> harvester management cluster can't load the plugin. when clicking the harvester mgmt cluster through rancher, I get this error


```
Error: failed to load script from:
https://<rancher_url>/dashboard/k8s/clusters/<harvester_cluster>/v1/harvester/plugin-assets/harvester-1.1.0-rc1.umd.min.js
```

which does not lead anywhere. I was not able to look through the API through rancher and find the plugin-assets for the cluster, but this looks like some sort of routing issue. However, this doesn't appear to affect provisioning. Just that the user is unable to load the harvester UI through rancher.

**Comment by richard-cox** [comment] 2022-09-23 09:42
The harvester plugin is harvester cluster specific, anything harvester related outside of the cluster context is still bundled with the dashboard (we'll split that side out into a plugin for neatness... which might be dynamically loaded at some point but for the moment will continue to be built in to the dashboard).

For new harvester clusters that support the plugin the cluster will return plugin details from the `/ui-info` request. For the info supplied by that version of harvester it's informing the dashboard to load the plugin from the one embedded in the harvester cluster (as opposed to a URL not related to the cluster). It looks like that cluster is failing to serve it, @WuJun2016 should be able to assist.

As an update on testing the other use case (the harvester cluster does not support the plugin, and the plugin is loaded from one embedded in the dashboard), 2.6.9 RC1 had some issues which should be resolved in RC2. I've done some manual testing which required some tweaking and so far it seems to work (ensured that a version of the harvester plugin is correctly bundled with the dashboard, and then manually swapping those plugin files from the new, working harvester plugin).

**Comment by WuJun2016** [comment] 2022-09-23 11:29
> did some initial testing with rancher v2.6.9-rc1 and harvester v1.1.0-rc1:
> 
> * virtualization management -> harvester management cluster can't load the plugin. when clicking the harvester mgmt cluster through rancher, I get this error
> 
> ```
> Error: failed to load script from:
> https://<rancher_url>/dashboard/k8s/clusters/<harvester_cluster>/v1/harvester/plugin-assets/harvester-1.1.0-rc1.umd.min.js
> ```
> 
> which does not lead anywhere. I was not able to look through the API through rancher and find the plugin-assets for the cluster, but this looks like some sort of routing issue. However, this doesn't appear to affect provisioning. Just that the user is unable to load the harvester UI through rancher.

@slickwarren 

workaround:  
You can change the `ui-offline-preferred` to `Remote` in the rancher setting,  
Then go to the single cluster harvester ui, and change `ui-source` to `External`

**Comment by WuJun2016** [comment] 2022-09-23 12:10
After this [pr](https://github.com/rancher/dashboard/pull/6975) merge, you just need to change the value of rancher setting `ui-offline-preferred` to `Remote`,  you should be able to access the harvester cluster normally.

**Comment by lanfon72** [comment] 2022-09-29 08:41
Tested that Harvester could be imported and access successfully, we will do full regression after Harvester `v1.1.0-rc2` released.

**Comment by richard-cox** [comment] 2022-10-06 11:02
I gave `2.6.9-rc3` a quick **_dev_** test with a very old harvester cluster and the dashboard correctly loaded the embedded harvester plugin

**Comment by richard-cox** [comment] 2022-10-10 10:45
@slickwarren I've moved this to test now, all the different load mechanisms should be working. There are some 2.6.9 plugin changes incoming, but nothing that wouldn't be covered by their own issues/QA process

**Comment by slickwarren** [comment] 2022-10-10 18:14
for rancher QA, I have tested the following on v2.6-head (78c7ac0):
* through virtualization management, import a harvester setup pre-plugin support (v1.0.3) -- pass
  * check that harvester UI loads when selecting this cluster -- pass
* through virtualization management, import a harvester setup post-plugin support (v1.1.0-rc2) -- pass
  * check that harvester UI loads when selecting this cluster -- pass

**Closed** 2022-10-10 18:44 UTC
Labels: QA/XS, [zube]: QA Working, area/harvester, kind/enhancement, team/area2
