### ISSUE TITLE
Epic: Machine Pool UI not showing the right vSphere Template

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#9559] opened 2023-08-17 00:00 UTC
Internal reference: SURE-6778
Reported in 2.7.5

A user deploys RKE2 clusters (1.24.x) in Rancher 2.7.5 as Vsphere Clusters using Terraform. Creation works fine, the cluster appears in Rancher and gets created normally. 

They noticed that once the cluster is created, if they click on 'Edit Config' in Rancher UI, the field Template is not populated with the value defined of their TF file, but with another vm template of the vCenter. 

It seems like Rancher takes the first template of the drop-down list. Most of the time, it is not a problem because, all action they make on any existing cluster is done using Terraform, so the good template is always used. But if, for any reason, they decide to modify any parameter of the cluster using the Rancher UI without correcting the template value on each pool, it will save the wrong template and proceed to recreate all the vm of the cluster. 

Even worse, they don't need to click on save button to save the wrong template! In the 'Edit Config' interface, under 'Edit as YAML' it also save the change and start recreating the VM.

Business impact:
High. The nodes/machine will be deleted and recreated.

vSphere config & Terraform setup available.

## Proposed solution

- [x] rancher/dashboard#9698
- [x] rancher/dashboard#9699
  - [x] rancher/dashboard#10250 - Fix closing error banners issue
- [x] rancher/dashboard#9700
- [x] rancher/dashboard#9724
- [x] rancher/dashboard#10181
- moved to docs [ ] rancher/terraform-provider-rancher2#1340

**Comment by rak-phillip** [comment] 2023-09-13 17:32
Converting this to an Epic because there are multiple issues described by this ticket

**Comment by adventurousyeti** [comment] 2023-10-16 19:27
I have encountered this issue as well. When modifying the cron job for etcd. I used the UI to edit the config and it automatically selected a bad template for the control plane from the top. Since the previous template was not in the correct format in the datastore Rancher tried to rebuild the VM. This in turn caused a provisioning storm in vSphere as the template it had selected did not work. Since rancher was unable to install on the selected template it caused loss of cluster stability. This led to a 3 day outage of the downstream cluster.

**Comment by a-blender** [comment] 2023-10-20 18:49
Based on discussion with @rak-phillip about the [original issue](https://github.com/rancher/dashboard/issues/9559#issue-1854044937) described here where if a user clicks 'Edit Config' in Rancher UI, the node Template is not populated with the template defined in their TF config.

Unexpected behavior resulting from a user modifying a cluster via the UI that was originally created with Terraform _**is not necessarily supported**_. If a user creates a cluster via TF, it's expected they will update the infrastructure via running TF apply. It _is expected_, however, that the `Edit Config` page in the UI show the correct template data that the user defined via Terraform so that's the bug.

IMO this appears to be a UI issue where the UI is pulling the first vSphere node template from the backend server without considering TF template input. Either that, or TF is somehow not setting the template resource fields on the cluster management object correctly. This will need to be tested and verified. @rak-phillip I believe you were working on reproducing this - what's the status?

**Comment by adventurousyeti** [comment] 2023-10-20 19:01
I'm using 2.7.6 right now with TF provider 3.2.0. The template is showing up in the UI right now. I can reproduce this issue in 2 ways. 

1. Having an incorrect template in my TF script. (say wrong name)
2. Modification or removal of the template in vCenter. (Say packer is rebuilding the template)

I can also reproduce in my home lab by deploying a new cluster > renaming the vSphere template > edit cluster config to view say etcd data.

**Comment by a-blender** [comment] 2023-10-20 19:09
I would argue an incorrect template name in TF config is not a supported use case. But, if a correct vSphere template does not exist / is being rebuilt by packer in vCenter then you see the wrong template in the Edit Config page?

**Comment by rak-phillip** [comment] 2023-10-20 19:34
@a-blender yes, we were able to repro and identify the issue reliably. We've made some minor enhancements to the form to prevent users from entering incorrect values and to warn them about the potential impact of changes, specifically:

- A warning will be displayed if an incorrect value is supplied by a TF config
- A confirmation dialog is raised to confirm that changes to Machine Pools will be made when clicking on Edit as YAML

We intend to follow up in a later release with more enhancements, but the changes in place will at least help increase awareness when there are potential errors in supplied data.

**Comment by adventurousyeti** [comment] 2023-10-20 19:55
In vCenter I have the following templates. 
![Screenshot 2023-10-20 at 2 45 34 PM](https://github.com/rancher/dashboard/assets/147872721/bc0b2c05-9ecf-4818-89dd-fa325803417a)
Using the highlighted as the example. Rancher shows the correct template being selected. 
![Screenshot 2023-10-20 at 2 48 21 PM](https://github.com/rancher/dashboard/assets/147872721/3ea5a640-76fe-4d14-b0fb-8330fd8e9083)
Now I modify the name in vCenter. 
![Screenshot 2023-10-20 at 2 45 47 PM](https://github.com/rancher/dashboard/assets/147872721/916c0fc3-6903-4984-b0e4-86a1ea8fc731)
Then when I go back to rancher the UI shows the following. 
![Screenshot 2023-10-20 at 2 49 18 PM](https://github.com/rancher/dashboard/assets/147872721/f37d0579-a487-4da7-96f8-e73e52b4dbf2)
Which is the first template from those available in vCenter. I scrolled over this when working on setting a cron schedule thru the UI for etcd snapshots. Once I clicked save it triggered my control plane to rebuild.

**Comment by adventurousyeti** [comment] 2023-10-20 20:01
The above happened outside of using edit as yaml. This example cluster was provisioned outside of TF and strictly thru the rancher UI.

**Comment by a-blender** [comment] 2023-10-20 21:39
@rak-phillip Great, thank you!

@adventurousyeti Did you also update the name of the VM template in your TF config to `Rancher_BM_PoC` before trying to modify the cluster again?

**Comment by a-blender** [comment] 2023-10-21 00:27
@adventurousyeti Got it, that is purely a UI issue and will be fixed by the UI team.

**Comment by gaktive** [comment] 2023-11-22 16:16
@rak-phillip can help here as we transfer this ticket and related ones over.

**Comment by gaktive** [comment] 2023-11-25 00:33
Possible backend ticket that's related (or blocks us): https://github.com/rancher/rancher/issues/41307

**Comment by IsaSih** [comment] 2024-07-30 01:22
tests pass on v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head

**Closed by IsaSih** 2024-07-30 01:22 UTC
Labels: kind/bug, priority/1, area/vsphere, size/3, JIRA, Epic, QA/None
