### ISSUE TITLE
Feature Request: Add edit and detail UI for NetworkPolicies

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#4729] opened 2021-12-08 10:43 UTC
**Detailed Description**
Add a UI to edit and viel NetworkPolicies.

**Context**
NetworkPolicies are one of the more complex Kubernetes resources. But they are also frequently used in enterprise contexts to restrict incoming and outgoing traffic of pods. A UI would make this much more accessible, especially for Kubernetes beginners.

**Comment by Jono-SUSE-Rancher** [comment] 2022-01-28 20:16
Hey @richard-cox - could you do me a favor and maybe provide some clarification on what QA would be checking here since this would be a brand new page? Is there a specific happy-path that they would want to follow to ensure proper coverage?

**Comment by richard-cox** [comment] 2022-01-31 09:48
@Jono-SUSE-Rancher There's some more detail in the PRs description (including screenshots). Otherwise @bashofmann Would be able to provide some better info.

**Comment by bashofmann** [comment] 2022-02-01 15:38
You should be able to create and edit network policies as a form which results in valid manifests (https://kubernetes.io/docs/concepts/services-networking/network-policies/).

If you need inspiration for some valid NetworkPolicies that should be also create-able through the UI form, this repo has some examples: https://github.com/ahmetb/kubernetes-network-policy-recipes.

Not sure if you want to also then test the underlying NetworkPolicy functionality of Kubernetes.

**Comment by cmurphy** [comment] 2022-03-16 20:23
Validating 3b2677f:

:red_circle: Issues found:

* Error banner shown when creating ingress rule exception:

![image](https://user-images.githubusercontent.com/1220710/158663480-0d525a39-b9c5-4a0b-8cf0-bfee2c296027.png)

The CIDR is not invalid, and there's no explanation given for the error. It goes away once you enter the exception:

![image](https://user-images.githubusercontent.com/1220710/158663875-28c2635b-46fb-4951-95f8-86000f760cb3.png)

:yellow_circle: Minor issues with selectors (probably not a blocker):

* The UI only has a way to input matchExpressions, which may be confusing for users following a guide that uses matchLabels ([example](https://kubernetes.io/docs/concepts/services-networking/network-policies/#networkpolicy-resource); [doc](https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#resources-that-support-set-based-requirements)):

![image](https://user-images.githubusercontent.com/1220710/158666262-7895f4f7-d1dd-4278-b987-c3621cf5866e.png)
![image](https://user-images.githubusercontent.com/1220710/158666397-ac3c2502-64d3-4b6e-ab63-4f0575393306.png)

* You can't just tab from key to value, tabbing through causes you to tab into the operator selector menu:

![image](https://user-images.githubusercontent.com/1220710/158675317-b446399c-f2df-4e7b-b08b-f3a317b9c943.png)

* Generated selector has duplicated expressions:

![image](https://user-images.githubusercontent.com/1220710/158665778-4fed24d1-4d27-43f1-bea5-686b3cf1aa27.png)

:green_circle: Looks good:

* can create a deny-all rule by not adding any ingress rules
* can create an allow-all rule by adding an empty ingress rule
* can create rules with multiple selectors
* can create rules with multiple egress ports

@bashofmann can you check at least the first issue (the error banner)?

**Comment by jtravee** [comment] 2022-03-16 22:30
Confirmed with @catherineluse and @gaktive to add `release note` label.

**Comment by richard-cox** [comment] 2022-03-17 13:27
#5428 Resolves the critical issue (improved form validation will come in with https://github.com/rancher/dashboard/pull/4999 , but that's targetted at 2.6.5). Other issues are fine for 2.6.4

**Comment by cmurphy** [comment] 2022-03-18 18:16
@richard-cox the error is still happening but with a different message now:

![image](https://user-images.githubusercontent.com/1220710/159060149-ddb55379-056b-4ad8-a7df-18afae7f0207.png)

This is on 417d4a4

**Comment by richard-cox** [comment] 2022-03-18 18:36
@cmurphy The error message is correct, there's an invalid Exception

![image](https://user-images.githubusercontent.com/18697775/159063468-5f9b486c-bdbf-43ed-8deb-cd2c46b1dae2.png)

**Comment by cmurphy** [comment] 2022-03-18 18:41
@richard-cox the message appears as soon as "Add exception" is clicked, before the user has even had a chance to enter anything in the Exceptions field and before the save button is clicked. It also still appears above the CIDR field instead of above the Exceptions field.

**Comment by richard-cox** [comment] 2022-03-21 09:38
I've created https://github.com/rancher/dashboard/pull/5446 to cover the position of the validation message (and fix another bug). However the visibility of the initial state (where the error is shown when the user hasn't entered anything) is out of scope for this issue. It involves either tracking touched state in the ArrayList or applying per ArrayList item validation, both should be tackle as part of the wider Form validation changes brought in by @Sean-McQ

**Comment by cmurphy** [comment] 2022-03-21 17:42
Verified on 024e6fa :heavy_check_mark: 

The Exception error message is now below the Exception field

![image](https://user-images.githubusercontent.com/1220710/159332319-680481a6-ef2f-4d6f-8659-74300cecb3ff.png)

**Closed** 2022-03-22 02:15 UTC
Labels: status/dev-validate, [zube]: QA Working, release-note, team/area1
