### ISSUE TITLE
Removing Apps not as easy as before

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1475] opened 2020-09-28 20:15 UTC
Issue:  Because the Apps are being listed on a "List" page, it's confusing how to completely remove a app and all it's associated resources.  Currently Rancher is showing two deployments, the regular one and a "-crd".  But there is no overall App reference like we had in 2.x. that has it's own menu to delete/upgrade... etc...

Current:
![image](https://user-images.githubusercontent.com/11514927/94481437-8bf3ec00-018c-11eb-8e40-bf988e82c4bc.png)

2.x
![image](https://user-images.githubusercontent.com/11514927/94481518-aded6e80-018c-11eb-9d7c-54eec4ad7951.png)

**Comment by deniseschannon** [comment] 2020-09-29 17:11
This is actually by design. Some apps have dependencies on the CRD charts deployed by other apps. For example, istio relies on monitoring to have the CRDs from monitoring to be installed. So removing monitoring would remove the CRDs which would cause certain parts of the Istio chart to break.

This is a bigger discussion we need to have regards to if we want to add anything in the UI for it or do we think it's intuitive enough. 

The other question it brings up is if we want to have some kind of warnings or not when deleting.

**Comment by prachidamle** [comment] 2020-10-12 19:46
@dnoland1 brought this up as well - On the Cluster Explorer UI, Apps can be installed from the charts but to disable them it is confusing that the user has to select individual charts and then delete each of them.
It would be good to have a single button to let user "Delete/Uninstall" the App completely without worrying about individual chart components.

**Comment by vincent99** [comment] 2020-10-17 01:31
I don't know what you want here @deniseschannon.  They are explicitly separate charts for the express purpose of not destroying all the data if you delete the main app (usually to reinstall it).  And there is no explicit relation to them to even know that the 2 apps are related, nor if they were installed "together" or not.

**Comment by tfiduccia** [comment] 2020-10-17 01:50
@vincent99 @deniseschannon - I know you did this on purpose but we should at least try to create the relationship between the app & data chart.  Then we can ask the user if they want to delete all or just the app resources except for data.

**Comment by deniseschannon** [comment] 2020-10-19 22:05
@tfiduccia The separation of charts was done on purpose because there are CRDs that multiple apps might rely on. For example, istio will deploy assuming that monitoring CRDs exist, so you can't delete the CRDs without breaking istio. 

Due to the underlying dependencies that could exist, it makes it too easy for a user to break a different app if they delete the CRDs. 

As of now, we won't fix as this is by design.

**Closed by deniseschannon** 2020-10-19 22:05 UTC
Labels: [zube]: Backlog, area/apps, kind/design, status/wontfix
