### ISSUE TITLE
Vue3: User menu styling is not synced with dark mode

### ISSUE THREAD

**Issue by momesgin** [rancher/dashboard#11729] opened 2024-08-27 20:13 UTC
**Result**
<img width="746" alt="image" src="https://github.com/user-attachments/assets/5ec7cfa4-bdd2-44a1-b29e-90b1c8f7ede6">

**Expected Result**

<img width="646" alt="image" src="https://github.com/user-attachments/assets/e2da42b7-e304-4334-b96c-da86945efe06">

**Comment by rak-phillip** [comment] 2024-08-27 20:21
Closing as a duplicate of #11684. I added this issue as additional information for future reference.

**Closed by rak-phillip** 2024-08-27 20:21 UTC
Labels: kind/bug, QA/dev-automation, area/vue3
