### ISSUE TITLE
Unable to modify AKS cluster labels/annotations after cluster creation

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#6386] opened 2022-07-18 12:43 UTC
**Setup**
- Rancher version: v2.6.6 
- Browser type & version: Firefox 102.0

**Describe the bug**
Once an AKS cluster is created, it is not possible to modify the cluster objects Labels and/or Annotations. However, you can add these during the initial cluster creation process.

**To Reproduce**
1. Create an AKS cluster
2. Wait until completion
3. Edit the AKS cluster
4. Add a Label and/or annotation. 
5. Click on `Configure Cluster` -> `Save` 

This, however works:

1. Create an AKS cluster
2. Whilst specifying initial config information, add labels and/or annotations
3. Provision cluster

**Result**
*  Label and/or annotation added does not persist unless it was part of the initial cluster configuration.

**Expected Result**
*  Label and/or annotations to be added after cluster creation

**Additional context**
When `Save` is clicked, the only non `GET` request I can see includes the following request body:

```
{
	"aksConfig": {
		"linuxAdminUsername": "azureuser",
		"nodePools": [
			{
				"availabilityZones": [
					"1",
					"2",
					"3"
				],
				"count": 1,
				"maxPods": 110,
				"mode": "System",
				"name": "agentpool",
				"orchestratorVersion": "1.23.8",
				"osDiskSizeGB": 128,
				"osDiskType": "Managed",
				"osType": "Linux",
				"type": "/v3/schemas/aksNodePool",
				"vmSize": "Standard_DS2_v2"
			}
		]
	},
	"name": "davidh-aks-test-2"
}
```

There is no information pertaining to the annotations added.

**Comment by gaktive** [comment] 2022-07-20 17:47
@David-VTUK was this an RKE1 cluster you had created?

**Comment by David-VTUK** [comment] 2022-07-20 17:59
> @David-VTUK was this an RKE1 cluster you had created?

@gaktive - No, AKS

**Comment by gaktive** [comment] 2023-02-01 17:29
Duplicate of https://github.com/rancher/dashboard/issues/7631 (despite it being newer). There's a solution up for QA targetted for 2.7.2

**Closed as completed** 2023-02-01 17:29 UTC
Labels: kind/bug, size/2, ember
