### ISSUE TITLE
YAML edits made to deployments do not get applied, only the “Edit” UI changes do

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5081] opened 2022-02-08 23:35 UTC
Internal reference: SURE-4015 (might change)
Reported in 2.6.3.

A user has reported that anything they try with editing the YAML, upon saving, the edits aren't preserved unless using the Edit UI.

ENV vars, replica count, volume mounts, etc. nothing sticks when saving the YAML

**Comment by richard-cox** [comment] 2022-03-09 13:39
I couldn't reproduce this when adding env vars in any scenario below
- v2.6-head (pending 2.6.4) or v2.6.3
- imported, rke1 or rke2 cluster types
- simple deployment in or not in a project

@gaktive There's some follow on questions...
- Was the deployment created manually (command line/GUI) or automatically via Helm or Fleet?
- What type of deployment (single/multi-container, are there any init containers, etc) ?
- What was the state of the deployment (state is `Active`, state is changing, deployment is being updated, etc)?
- How was the `Edit Yaml` page reached (going via `Edit Config` option in a deployment --> `Edit as Yaml` button at the bottom of the form, or directly via `Edit YAML` option in a drop down for the deployment)?
- Are there errors/warnings in the browsers Dev Tools console, any failed network requests in the network tab?

**Comment by nwmac** [comment] 2022-03-10 13:34
@richard-cox I can reproduce this:

Local cluster - create a deployment with a name and image `nginx:latest`.

Open a terminal and configure the KUBECONFIG env with the kube config of the local cluster, so that you can make changes to the resources via the CLI (k9s).

Open k9s and find and edit the deployment you just created.
In the UI, edit the yaml for the deployment and change the image name - but don't press save.
In k9s, make a change to the resource (e.g. change the replica count) and save
Quickly in the UI click the save button - you'll get an error.

This works if you use edit config - it appears that the edit yaml process does not apply the same 409 conflict resolution as the edit config code path.

**Comment by richard-cox** [comment] 2022-03-10 16:53
Following on from the call

- The resources were created by helm, but no upgrade to those charts was happening
- The deployments weren't seen to be in a transitioning/changing state
- YAML was edited via action menu (rather than Edit Config --> Edit Yaml)
- The save action completed successfully and the user was taken to the previous page. However the deployments were not cycled and when going back to the Edit Yaml page the changes were not visible
- Give above I don't think this is a 409 conflict issue given the save completes without erroring

They were unable to reproduce their issue on the call, however did state they last saw this a long time ago. We will wait for them to reproduce issue and supply additional information

**Comment by richard-cox** [comment] 2022-03-11 14:35
@nwmac I've had a look at applying conflict management to the save yaml process.... it's more complicated than we thought. The original conflict process works with models/json and trying to use the same with yaml becomes tricky. There's magic worked when orignally converting the model from json to yaml for the edit yaml component (stripping various properties), so converting to json to use in the conflict process... to convert back to yaml to save .. is tricky. Suggest we split that out in to a separate issue

**Comment by richard-cox** [comment] 2022-03-11 17:04
I've opened https://github.com/rancher/dashboard/issues/5375 to cover the 409 conflict. Going from the customer's statement that the save was successful (and didn't error with 409) and that he now cannot replicate it I think we can close this.

**Comment by brudnak** [comment] 2022-03-15 08:18
# :x: FAILED

## Reproduction Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | 2.6.4-rc8                                           |
| Installation option       | Helm high availability (AWS)                        |
| If Helm Chart k8s cluster | RKE v1.22.6                                         |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | RKE Linode                                          |
| Downstream K8s version    | v1.23.4-rancher1-1                                  |
| Logged in user role       | Global admin                                        |
| Browser type              | Google Chrome                                       |
| Browser version           | 99.0.4844.51 (Official Build) (x86_64)              |

## Reproduction steps

1. Local cluster - create a deployment with a name and image nginx:latest
2. Open a terminal and configure the KUBECONFIG env with the kube config of the local cluster, so that you can make changes to the resources via the CLI (k9s)
3. Open k9s and find and edit the deployment you just created
4. In the UI, edit the yaml for the deployment and change the image name - but don't press save
5. In k9s, make a change to the resource (e.g. change the replica count) and save
6. Quickly in the UI click the save button - you'll get an error
  
## Additional Info


<img width="3983" alt="2022-03-15_00-37-12" src="https://user-images.githubusercontent.com/40877149/158334706-28a1ded3-f2e5-404c-804e-c469a14067a7.png">

## RESULTS

#### :white_check_mark: Expected

To edit the yaml after editing in k9s

#### :x: Actual
Quickly in the UI click the save button - you'll get an error

<hr>

**Comment by richard-cox** [comment] 2022-03-15 08:44
@brudnak The steps listed to reproduce in https://github.com/rancher/dashboard/issues/5081#issuecomment-1067690984 look like they're from the comment https://github.com/rancher/dashboard/issues/5081#issuecomment-1064070910. That issue has been split out to https://github.com/rancher/dashboard/issues/5375

**Comment by brudnak** [comment] 2022-03-15 15:27
> @brudnak The steps listed to reproduce in [#5081 (comment)](https://github.com/rancher/dashboard/issues/5081#issuecomment-1067690984) look like they're from the comment [#5081 (comment)](https://github.com/rancher/dashboard/issues/5081#issuecomment-1064070910). That issue has been split out to #5375

Okay sounds good! Thanks @richard-cox for the heads up 😃

**Comment by brudnak** [comment] 2022-03-16 15:14
# :white_check_mark: PASSED

<hr>
  
## Validation Environment

| Component                 | Version / Type                                      |
| ------------------------- | --------------------------------------------------- |
| Rancher version           | 2.6.4-rc8                                           |
| Installation option       | Helm high availability (AWS)                        |
| If Helm Chart k8s cluster | RKE v1.22.6                                         |
| Cert Details              | ingress.tls.source=secret (certificates from files) |
| Docker version            | 20.10.7, build f0df350                              |
| Helm version              | v2.16.8-rancher1                                    |
| Downstream cluster type   | RKE Linode                                          |
| Downstream K8s version    | v1.23.4-rancher1-1                                  |
| Logged in user role       | Global admin                                        |
| Browser type              | Google Chrome                                       |
| Browser version           | 99.0.4844.51 (Official Build) (x86_64)              |

## Validation steps

1. Create a deployment
2. Edit the deployment as yaml
    - Edit replica count
    - Environment Variables
    - Volume Mounts

## RESULTS

#### :white_check_mark: Expected
For the yaml edits to be preserved when saving

#### :white_check_mark:Actual
The yaml edits were preserved when saving

**Closed** 2022-03-21 17:10 UTC
Labels: kind/bug, internal, [zube]: QA Working, priority/1, team/area1, status/waiting-response
