### ISSUE TITLE
CD Dashboard: Incorrect bundles count for workspace fleet-local

### ISSUE THREAD

**Issue by mguggi** [rancher/dashboard#5974] opened 2022-05-18 13:33 UTC
**Setup**
- Rancher version: v2.6.4

**Describe the bug**
The CD dashboard does not show the correct count of bundles for the workspace `fleet-local`.

**To Reproduce**
Create GitRepo for `local` cluster. 

**Expected Result**
Green Tag in the CD dashboard with 1/1.

**Screenshots**
CD Dashboard View: 

<img width="1521" alt="Screenshot 2022-05-18 at 15 22 07" src="https://user-images.githubusercontent.com/13131781/169050073-163d3560-3eb7-4cc3-a48a-e795954a6b3d.png">

Bundle View: 

<img width="1521" alt="Screenshot 2022-05-18 at 15 21 58" src="https://user-images.githubusercontent.com/13131781/169050132-ed6da69a-26b4-44ab-89a2-4854d81f4f4b.png">

**Additional context**
It looks like a display issue, because the deployment works as expected.

**Comment by richard-cox** [comment] 2022-05-18 13:49
@aalves08 Has this one been resolved by the 2.6.5 work, or do we show something similar with the same data?

**Comment by aalves08** [comment] 2022-05-18 14:14
@richard-cox I don't believe this area has been iterated since `2.6.4`. I've tried to reproduce the issue, but in my case it works fine:

**Dashboard view**
![Screenshot 2022-05-18 at 15 09 56](https://user-images.githubusercontent.com/97888974/169062584-58e902ea-c7f9-4675-93a7-cef6be1da9a7.png)

**Git repo details**
![Screenshot 2022-05-18 at 15 09 43](https://user-images.githubusercontent.com/97888974/169062566-8f8a3a3e-bc64-47f7-8e0e-d5b06b0523dc.png)

Maybe @mguggi can share the repo that he has added in detail so that we can try to reproduce it 🙏

**Comment by mguggi** [comment] 2022-05-18 14:33
My repo detail page looks like

<img width="1521" alt="Screenshot 2022-05-18 at 16 27 10" src="https://user-images.githubusercontent.com/13131781/169066502-aa08e6e7-7060-42d2-a135-4e2277291d25.png">

And in the repository I use this `fleet.yaml` in the root directory. 

```yaml 
namespace: ...-monlog-system
targetCustomizations:
- name: lab
  clusterSelector:
    matchLabels:
      env: lab
  kustomize:
    dir: overlays/lab
```

**Comment by mguggi** [comment] 2022-05-18 14:38
The repository structure looks 

```
.
├── base
│   ├── dhcp-legacy.json
│   ├── dhcp.json
│   ├── e2.json
│   ├── elasticsearch.json
│   ├── fluent.json
│   ├── kibana.json
│   ├── kubernetes.json
│   ├── kustomization.yaml
│   ├── ldap.json
│   ├── mysql.json
│   ├── radius-legacy.json
│   └── radius.json
├── fleet.yaml
└── overlays
    └── lab
        ├── health.json
        └── kustomization.yaml
```

**Comment by aalves08** [comment] 2022-05-18 14:39
@mguggi This looks it's using some basic auth. I will need those credentials to reproduce it, right?

Don't mean to pry in your work and it's details, but really need to be able to add the same repo that you've added, otherwise I won't be able to reproduce it. 🙏

**Comment by mguggi** [comment] 2022-05-19 06:25
@aalves08 Today I‘m not in the office but tomorrow I will clone your repo and try it with basic auth.

The current repo is unfortunately a private repo of our customer which is not reachable from the internet.

When the problem is the repo I will try to reproduce it with a public repo and provide the url here. 

Last but not least can it be a problem that my local cluster was renamed? 

The count of the default cluster group in the scope fleet-local is 0 and I don't now if this is normal.

Additionally I've seen that a new git repo will not assigned to the cluster and I must change the yaml config and set the target manually.

**Comment by aalves08** [comment] 2022-05-19 08:53
@mguggi Thanks for getting back to me.
 
It's ok if it's private, no worries. The idea is just to have a set of conditions that I can reproduce on my machine, so if you could provide those in any manner, that would be fine.

> Last but not least can it be a problem that my local cluster was renamed?

Tbh, I don't know, but it could be... The best thing you could try is to spin up a new instance of Rancher (either on Digital Ocean or locally) and check if this issue happens with that particular repo in a fresh install.
I would particularly recommend this, so that we can really make sure that we find where the problem lies (either with Rancher or some particular config/param of your env).

> Additionally I've seen that a new git repo will not assigned to the cluster and I must change the yaml config and set the target manually.

Can you try to create a new Cluster on the scope you are trying to add a git repo and try again? 

Feel free to ping me on Slack if you want to schedule a quick call for us to go over this and you can also show me your env "live". I am on EMEA work time.

**Comment by mguggi** [comment] 2022-05-20 09:27
@aalves08 I've solved my issue. 

<img width="1521" alt="Screenshot 2022-05-20 at 11 12 31" src="https://user-images.githubusercontent.com/13131781/169496181-0bd3a806-f833-47df-a0d6-52588b9d840e.png">

But I am not 100% sure what was the problem. I've changed my repo structure from branch based to directory based as in the `fleet-examples` repo now it works. 

```
.
├── lab
│   ├── base
│   │   ├── dhcp-legacy.json
│   │   ├── dhcp.json
│   │   ├── e2.json
│   │   ├── elasticsearch.json
│   │   ├── fluent.json
│   │   ├── kibana.json
│   │   ├── kubernetes.json
│   │   ├── kustomization.yaml
│   │   ├── ldap.json
│   │   ├── mysql.json
│   │   ├── radius-legacy.json
│   │   └── radius.json
│   ├── fleet.yaml
│   ├── kustomization.yaml
│   └── overlays
│       └── lab
│           ├── health.json
│           └── kustomization.yaml
└── prod
    ├── base
    │   ├── dhcp.json
    │   ├── e2.json
    │   ├── elasticsearch.json
    │   ├── fluent.json
    │   ├── kibana.json
    │   ├── kubernetes.json
    │   ├── kustomization.yaml
    │   ├── ldap.json
    │   ├── mysql.json
    │   └── radius.json
    ├── fleet.yaml
    ├── kustomization.yaml
    └── overlays
        └── prod
            ├── health.json
            └── kustomization.yaml
````

Previously, I used a branch for each stage. 

> Last but not least can it be a problem that my local cluster was renamed?

That was no problem at all. 

> Additionally I've seen that a new git repo will not assigned to the cluster and I must change the yaml config and set the target manually.

The problem in my case was a wrong cluster selection clause in the default cluster group. Now each git repo will assigned to the default cluster group. 

_**I think the main reason for the problem was the missing subdirectory.**_  But if that's the case, I think it's a bug, because there's no reason why it wouldn't work.

**Comment by aalves08** [comment] 2022-05-20 14:23
@richard-cox is there an issue to be created from this or shall I close it?

**Comment by aalves08** [comment] 2022-05-25 11:25
@mguggi since the main issue has been address, I am going to close this one.

If you feel that the missing subdirectory is the main reason for this, please then raise an issue on https://github.com/rancher/rancher

Thanks. 🙏

**Closed** 2022-05-25 11:25 UTC
Labels: [zube]: To Triage, area/fleet
