### ISSUE TITLE
Create v2prov clusters in dedicated namespaces

### ISSUE THREAD

**Issue by Oats87** [rancher/dashboard#5295] opened 2022-03-03 23:02 UTC
Today, the v2prov UI will create new clusters in the `fleet-default` namespace. This is not scalable, and new clusters should be created in a dedicated namespace for each cluster.

**Comment by snasovich** [comment] 2022-03-04 02:14
@nwmac , heads-up as this is something we may want to do depending whether we can resolve some issues related to it.

@Oats87 to provide updates. We also need to agree what that namespace should be.

**Comment by snasovich** [comment] 2022-03-08 00:04
@Oats87 , after discussing with @thedadams it looks like we're not ready for this due to https://github.com/rancher/rancher/issues/36132 ?

Is this correct understanding?

Even disregarding this, I think it's too late for such a drastic change to make it into 2.6.4. Changing milestone to 2.6.5 for now - let me know if you insist on it being in 2.6.4.

**Comment by gaktive** [comment] 2022-04-08 15:48
Backend now moved to 2.6.6 so will do so here too.

**Comment by gaktive** [comment] 2022-05-25 21:13
Backend work is now unscheduled.

**Comment by gaktive** [comment] 2023-11-22 00:57
Duplicate of https://github.com/rancher/dashboard/issues/9730, which was solved in 2.8.0 as connected to https://github.com/rancher/rancher/issues/36132, as I understand. Closing.

**Closed by gaktive** 2023-11-22 00:57 UTC
Labels: status/waiting-backend, area/clusterprovisioningv2, [zube]: Backend Blocked, kind/enhancement
