### ISSUE TITLE
Formatting display incorrect on dashboard/prefs

### ISSUE THREAD

**Issue by lakako** [rancher/dashboard#6466] opened 2022-07-23 02:29 UTC
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

change time format on dashboard/prefs 
![image](https://user-images.githubusercontent.com/46197434/180587179-9992d54c-2dbd-4db9-b1cf-88011eaadfc1.png)

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment] 2022-07-25 08:10
This is another issue related to the changes to the select component and is resolved in the upcoming v2.6.7 release. This is slightly different from the other issues related to that bug though, to be sure I've checked in `master` and cannot reproduce. 

The core issue is https://github.com/rancher/dashboard/issues/6466 and some workarounds are described there in a [comment](https://github.com/rancher/dashboard/issues/5984#issuecomment-1180191702). Please note the name of the setting will change depending on your settings in the screenshot.

**Closed by richard-cox** 2022-07-25 08:10 UTC
Labels: kind/bug
