### ISSUE TITLE
Workload: Container: Unable to set cpu and memory limitations

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11955] opened 2024-09-18 13:59 UTC
**Setup**
- Rancher version: 2.10.0

**Describe the bug**
- Input fields for `CPU Reservation`, `Memory Reservation`, `CPU Limit` and `Memory Limit` are really broken
  - CPU fields - enter `1` and get `1000` instead
  - Memory fields - unable to enter anything other than 1 or 0

**To Reproduce**
Cluster Explorer --> Workloads --> Pods --> Create --> container --> Resources tab

**Result**
as per description

**Expected Result**
- user should be able to enter whatever value they wish (there might possibly be a restriction if there are resource limits set in the project of the target namespace)

**Screenshots**
![image](https://github.com/user-attachments/assets/3aa94803-3b5b-400a-aa9d-8b4b743b1145)

**Additional context**
assuming this is something to do with how we handle user input vs the actual base unit of what we set on the model

**Comment by rak-phillip** [comment] 2024-09-18 15:22
Closing this issue as a duplicate of #11881. Fixed in #11939.

**Closed by rak-phillip** 2024-09-18 15:22 UTC
Labels: kind/bug, QA/dev-automation, area/vue3
