### ISSUE TITLE
Workload: Pods: Unable to set text field

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11959] opened 2024-09-18 15:14 UTC
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- Entering content into `Priority` field is removed on de-focus

**To Reproduce**
Places
- Cluster Explorer --> Workloads --> Pods --> Create --> Pod tab --> Resources tab --> `Priority` input field
- ~Cluster Explorer --> Workloads --> Pods --> Storage --> Azure Disk --> Filesystem Type~
  - ~Note - not on Amazon EBS Disk Filesystem Type~

**Result**
- value shown, but removed on de-focus

**Expected Result**
- value to remain

**Screenshots**
![image](https://github.com/user-attachments/assets/ca153a4e-c129-4313-aedb-bfde63d3e478)

**Comment by rak-phillip** [comment] 2024-09-18 22:28
It looks like the priority field is using `model.number="podTemplateSpec.priority"`. Waiting for further triage until #11902 merges. I suspect that the root cause is related and think that these instances could be addressed.

#11856

**Comment by mantis-toboggan-md** [comment] 2024-09-19 22:18
This is indeed fixed by https://github.com/rancher/dashboard/pull/11902

**Comment by rak-phillip** [comment] 2024-09-19 22:21
@mantis-toboggan-md thanks for confirming! Closing as resolved in #11902.

**Closed by rak-phillip** 2024-09-19 22:21 UTC
Labels: kind/bug, QA/dev-automation, area/vue3
