### ISSUE TITLE
In new project view, the create button in the UI should be blocked, unless project Name is filled in

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/dashboard#5975] opened 2022-05-18 14:44 UTC
**Setup**
- Rancher version: v2.6.5
- Browser type & version: Firefox 100

**Describe the bug**
When users create a new project, the UI does not stop them from submitting the form without providing the project Name.

**To Reproduce**
1. Go to a cluster's projects view and click Create Project.
1. Do not fill in the Name, just click Create.
 
**Result**
The request is still sent to the backend, and an API error is shown in the UI.
`{"baseType":"error","code":"MissingRequired","fieldName":"name","message":"","status":422,"type":"error"}`
On every new submit attempt, the error is rendered anew, and the previous one is not cleared, so error messages are stacked on top of each other.

**Expected Result**
The UI should not allow to submit the form if Name (which is already marked as required) is not provided.

**Screenshots**
<img width="859" alt="Screen Shot 2022-05-18 at 10 35 16" src="https://user-images.githubusercontent.com/17733533/169068209-8c706d27-0813-446f-ba35-53698d6c9520.png">

**Comment by richard-cox** [comment] 2023-11-03 17:35
This has been fixed at some point, could not reproduce in 2.8-head (cusp of 2.8.0)

**Comment by aalves08** [comment] 2024-04-17 16:51
Based on https://github.com/rancher/dashboard/blob/master/cypress/e2e/blueprints/nav/fake-cluster.ts, IF this are is browsable, then it could be automated. Added `automation-candidate`.

**Comment by izaac** [comment] 2024-05-08 18:15
Clean and straightforward. E2E coverage looks good. Moving to done.

**Closed by izaac** 2024-05-08 18:15 UTC
Labels: kind/enhancement, area/form-validation, QA/dev-automation, status/not-reproducible, automation-candidate
