### ISSUE TITLE
[v2.9] Missing Login button for external provider

### ISSUE THREAD

**Issue by enrichman** [rancher/dashboard#10974] opened 2024-05-08 14:18 UTC
**Setup**
- Rancher version: v2.9.0 (pre-release)
- Rancher UI Extensions: `master`

**Describe the bug**
When an external provider is configured the Login button is not shown

![image](https://github.com/rancher/dashboard/assets/1763949/f3492f91-0694-44b7-87be-b052f1b23995)

**To Reproduce**
- Configure an external provider
- Logout
- Try to login

**Result**
Login button is not visible

**Expected Result**
Login button should be visible

**Comment by bigkevmcd** [comment] 2024-05-08 14:19
@richard-cox provided a workaround...

> as a workaround, log in as local user Global Settings --> Settings --> set ui-offline-preferred to local

**Comment by richard-cox** [comment] 2024-05-08 14:21
We should understand how this broke and add automated tests (in jenkins) to prevent another regression

**Comment by richard-cox** [comment] 2024-05-08 14:35
Caused by https://github.com/rancher/dashboard/pull/10839. `created` lifecycle hook is called before `fetch`, so `providerComponents` (which depends on `providers` set in `fetch`) is always empty.... so no login button is shown.

**Comment by gaktive** [comment] 2024-05-08 15:51
E2E required to ensure login works. Jenkins could do the credential work if there's an auth provider with an account to use.

**Comment by izaac** [comment] 2024-05-16 02:24
Moving to done as the E2E is going to be followed up on https://github.com/rancher/dashboard/issues/10984

**Closed by izaac** 2024-05-16 02:24 UTC
Labels: kind/bug, priority/0, size/1, QA/dev-automation
