### ISSUE TITLE
Add sidecar, by default the newly added sidecar tab should be selected

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#7398] opened 2022-11-10 02:36 UTC
**Setup**
- Rancher version: v2.6.9
- Browser type & version: 107.0.5304.87

**Describe the bug**

Add sidecar, by default the newly added sidecar tab should be selected

**To Reproduce**

1. Add a new sidecar to the UI
2. View the default sidecar display

**Result**
container-0 is selected by default

**Expected Result**

The newly added sidecar tab should be selected by default, which is container-1 in the example

**Screenshots**

![sidecar3](https://user-images.githubusercontent.com/19684717/200993476-4c14bd99-bc67-481a-99cf-dd204346360c.gif)

**Additional context**

**Comment by catherineluse** [comment] 2022-11-18 02:29
Moving this issue into the review column because there is a PR to fix it https://github.com/rancher/dashboard/pull/7403

**Comment by sowmyav27** [comment] 2022-12-22 05:27
Reproduced the issue on 2.6.9

**On 2.7-head commit id: `65089ee`**

- On a workload --> Add sidecar --> Container-1 is selected and listed by default
<img width="1235" alt="Screen Shot 2022-12-21 at 9 26 32 PM" src="https://user-images.githubusercontent.com/26032343/209063488-acb1b23a-aaca-49b5-b83d-c449e687ae72.png">

**Closed by sowmyav27** 2022-12-22 05:27 UTC
Labels: kind/bug, [zube]: To Test
