### ISSUE TITLE
Switching cluster while in Apps & Marketplace takes me back to Cluster Explorer

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1615] opened 2020-10-04 08:54 UTC
Steps:
1.  Have two clusters deployed
2.  Go to Apps & Marketplace
3.  From the cluster drop-down, switch clusters

Results:  Takes me back to Cluster Explorer.  Should leave me in Apps & Marketplace.

**Comment by deniseschannon** [comment] 2020-10-10 03:49
Duplicate of https://github.com/rancher/dashboard/issues/834

**Closed by deniseschannon** 2020-10-10 03:49 UTC
Labels: area/apps, kind/bug
