### ISSUE TITLE
Adding a label in fleet -> clusters doesn't get saved

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4844] opened 2021-12-30 22:44 UTC
Internal reference: SURE-3709

Reported in 2.6.2.

Issue description:

Added a label in fleet -> cluster doesn't get saved.**

Business impact:

Can't use edit UI to add labels, may be able to workaround this by editing YAML directly, but that's not very user friendly.

Troubleshooting steps:

none

Repro steps:

- Add a downstream cluster to your Rancher mgmt server, if one does not already exist.
- Go to Continuous Delivery app
- Click on Clusters in left side nav
- For a downstream cluster, select the Edit Config
- Add a label, click Save button
- Go back to Edit Config, note label is not there.

Actual behavior:
Labels not getting saved (or shown in UI?)

Expected behavior:
After adding label, coming back to Edit Config view should show that label.

**Comment by aalves08** [comment] 2022-02-15 14:31
@gaktive, using latest version on master (will be 2.6.4), went to "edit config":
![Screenshot 2022-02-15 at 14.26.46.png](https://zube.io/files/rancher/40ac783c6cf835db4ac4ded7e24d2d01-screenshot-2022-02-15-at-14-26-46.png)

On that screen, added a label, clicked save.

Refreshed the whole app, went back to "edit config" and other areas... everything seems fine. Maybe this was fixed with some other PR's.

![Screenshot 2022-02-15 at 14.26.55.png](https://zube.io/files/rancher/1dff719c293ce1a4b00ea8a81f1566f0-screenshot-2022-02-15-at-14-26-55.png)![Screenshot 2022-02-15 at 14.27.12.png](https://zube.io/files/rancher/e82e7b4eb89fea867919ebe640491f54-screenshot-2022-02-15-at-14-27-12.png)![Screenshot 2022-02-15 at 14.26.59.png](https://zube.io/files/rancher/e182258cff531620b2b155f32e914581-screenshot-2022-02-15-at-14-26-59.png)

Can you confirm if my analysis is correct? if so, then we can close this one.

Thanks

**Comment by davidnuzik** [comment] 2022-02-25 16:51
This is effectively a duplicate of https://github.com/rancher/dashboard/issues/3086 and this behavior cannot be reproduced in Rancher v2.6.3 -- I would recommend an upgrade to v2.6.3.
See my comment here with details of my findings: https://github.com/rancher/dashboard/issues/3086#issuecomment-1049327451

Since this is a duplicate I'm going to close this issue in favor of https://github.com/rancher/dashboard/issues/3086

**Closed** 2022-02-25 16:51 UTC
Labels: kind/bug, internal, area/fleet, [zube]: QA Next up, team/area3
