### ISSUE TITLE
Project Owner cannot select Services for Ingress

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7194] opened 2022-10-13 21:30 UTC
Internal reference: SURE-5304
Reported in 2.6.7

Issue description:
Project Owner cannot select Services for Ingress in Rancher UI

Troubleshooting steps:
Using a normal user (either authenticated by keycloak, or a local user), who doesn't have the global Administrator role, I can create services but I cannot create an Ingress. I cannot seem to be able to select any target services.

Repro steps:

- create a standard user
- add the user as a member in Project related to the cluster
- login as the user
- successfully creating a service to expose the app
- when creating the ingress, it fails to populate / get the available services to select

Workaround:
No

Actual behavior:
NOT able to get the list of services to select one as a backend in ingress rule

Expected behavior:
as a standard user with right permissions, get the list of services to select one as a backend in ingress rule.

**Comment by mantis-toboggan-md** [comment] 2022-10-20 17:15
I wasn't able to repro this in 2.7-head. It looks like this has been fixed in 2.6.9, via this PR: https://github.com/rancher/dashboard/pull/6718
I don't see an associated dashboard issue tracking validation of this bug, so I will refrain from closing this issue.

**Comment by mantis-toboggan-md** [comment] 2022-10-20 18:03
This is caused by an attempt to fetch ingress classes, which a project owner cannot see. The fix for the dropdown is in 2.6.9 via this PR:https://github.com/rancher/dashboard/pull/6718

Lingering nitpick: the Ingress Class tab shouldn't be visible if the current user has no ability to list ingresses; pr #7292 fixes that.

**Comment by anupama2501** [comment] 2023-03-28 23:33
Reproduced on v2.7.0

As a cluster member/project owner, unable to create ingress classes.

Verified on v2.7-head `aa7bea9` 
As a ckuster member/project owner :
1. created a cluster IP service
2. Created an ingress class by typing a custom name
3. Created a new user with role project member in the cluster to default project
4. Log in as the project member and can reference the ingress class they do not have access to.

@mantis-toboggan-md Noticed that once the ingress class is created, it doesn't show up in the drop down if we edit the workload and try to create a new one.
Notice in the screenshot current ingressclass is custom but its not listed in the kubectl:

<img width="836" alt="2023-03-28_16-30-38" src="https://user-images.githubusercontent.com/38144301/228389635-f8668201-51e5-4868-a3fd-14550aa62751.png">


 kubectl doesn't return the created ingress class:
```
> k get ingressclass -A
NAME    CONTROLLER             PARAMETERS   AGE
nginx   k8s.io/ingress-nginx   <none>       5h57m

```

**Comment by anupama2501** [comment] 2023-03-29 04:24
Verified upgrade use case from 27.0 to v2.7-head `aa7bea9`created a cluster IP service


- Install rancher on v2.7.0
- Created an ingress class and not able to type ingress class name
- Upgrade rancher to v2.7-head
- Edit the ingress and add the custom name - works as expected.
- Created an ingress class by typing a custom name
- Created a new user with role project member in the cluster to default project
- Log in as the project member and can reference the ingress class they do not have access to.

**Closed as completed** 2023-03-29 18:39 UTC
Labels: kind/bug, priority/1, team/area1, JIRA
