### ISSUE TITLE
Rotate certificates for RKE2 provisioned clusters

### ISSUE THREAD

**Issue by snasovich** [rancher/dashboard#4485] opened 2021-11-02 02:07 UTC
**Detailed Description**
The UI should provide an option to rotate certificates on RKE2 provisioned cluster, including an option to rotate certificates for an individual component. The UX should probably match what we have for RKE1 with context menu item and pop-up dialog asking to specify the settings:
![image](https://user-images.githubusercontent.com/85187633/139775023-31e8837e-bc46-4e83-ba7c-f8e451c96411.png)

![image](https://user-images.githubusercontent.com/85187633/139775063-6ede713c-d07d-4b90-b55b-bd9e7247e567.png)

**Context**

This is needed for RKE2 provisioning parity with RKE1

**Additional Details**
https://github.com/rancher/rancher/issues/35343

**Comment by catherineluse** [comment] 2022-02-08 04:15
@snasovich  After looking into this, I believe no UI changes will be needed if the backend includes `rotateCertificates` in the action links within the cluster data.

To determine what actions are available, the UI looks at the `actions` in the cluster data at `<rancher-server-url>/v3/clusters/<cluster-id>`. Currently the actions for RKE2 clusters include these actions:

```
"actions":{
      "apply":"https://192.168.0.9:8005/v1/management.cattle.io.clusters/c-m-b4qzzdqg?action=apply",
      "enableMonitoring":"https://192.168.0.9:8005/v3/clusters/c-m-b4qzzdqg?action=enableMonitoring",
      "generateKubeconfig":"https://192.168.0.9:8005/v3/clusters/c-m-b4qzzdqg?action=generateKubeconfig",
      "importYaml":"https://192.168.0.9:8005/v3/clusters/c-m-b4qzzdqg?action=importYaml"
   }
```

The actions for RKE1 clusters include the additional `rotateCertificates` action:
```
"rotateCertificates":"https://192.168.0.9:8005/v3/clusters/c-hsv9l?action=rotateCertificates",
```

To confirm that it would work if `rotateCertificates` were included in the action links, I used mock data to pretend it was included in the action links for an RKE2 cluster. In that scenario, the action is available from the context menu, the modal appears properly, and when you submit a request from the modal, it sends the appropriate network request.

**Comment by snasovich** [comment] 2022-02-08 16:18
@catherineluse , based on the implementation PR https://github.com/rancher/rancher/pull/36347 it doesn't look like that's how it's supported on backend as the changes seem to be limited to `v1` API.
@paynejacob , could you please confirm? Also, does it make sense / feasible to add `rotateCertificates` option for v3 API?

**Comment by paynejacob** [comment] 2022-02-08 18:31
@catherineluse this is adding support for v2 clusters.  v2 provisioning clusters are not supported in the v3 api.  Steve does not support actions so the rotation will need to be triggered with a patch on the provisioning cluster through the v1 api `kubectl patch -n fleet-default --patch '{"spec":{"rkeConfig":{"rotateCertificates":{"caCertificates":true,"generation":1}}}}' --type=merge cluster/cert-rotate`
```

**Comment by catherineluse** [comment] 2022-02-15 00:26
@paynejacob I noticed that when the UI does the cert rotation for RKE1 clusters, we set `caCertificates` to `false`. Is it correct that for RKE1 it should be false and for RKE2 it should be true?

**Comment by paynejacob** [comment] 2022-02-15 16:26
@catherineluse I forgot to update the ticket the `caCertificates` field is going away entirely once [this ](https://github.com/rancher/rancher/pull/36428) pr is merged.  The only fields will be the service list and the generation.  If no services are selected you just need to increment the generation to kick of rotation.

**Comment by rancher-max** [comment] 2022-03-09 22:25
#### Validating on v2.6-head commit `572ab58` -- Reopening due to last point below

- Field is available and looks correct:
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/55997940/157547384-02cb2e17-2c77-461a-a890-403ec5193a2d.png">

- After clicking on it, valid options:
<img width="972" alt="image" src="https://user-images.githubusercontent.com/55997940/157547499-9b7428f8-e31a-4156-bd09-41c587d8d3ba.png">
<img width="609" alt="image" src="https://user-images.githubusercontent.com/55997940/157547557-f1d61cd1-71f1-4673-b857-4a9a5bd75e10.png">

- Selecting individual services correctly selects and rotates that service
- Selecting to rotate all fails and only does etcd. Here is what gets passed in the request payload. Snippet posted first of the error spot, followed by the entire payload. According to my understanding, the services array should be empty in order to rotate all certs.
```
      "rotateCertificates": {
        "generation": 4,
        "services": [
          "etcd"
        ]
      },
```
```
{
  "id": "fleet-default/maxcert1",
  "type": "provisioning.cattle.io.cluster",
  "links": {
    "remove": "https://173.230.149.125/v1/provisioning.cattle.io.clusters/fleet-default/maxcert1",
    "self": "https://173.230.149.125/v1/provisioning.cattle.io.clusters/fleet-default/maxcert1",
    "update": "https://173.230.149.125/v1/provisioning.cattle.io.clusters/fleet-default/maxcert1",
    "view": "https://173.230.149.125/apis/provisioning.cattle.io/v1/namespaces/fleet-default/clusters/maxcert1"
  },
  "apiVersion": "provisioning.cattle.io/v1",
  "kind": "Cluster",
  "metadata": {
    "annotations": {
      "field.cattle.io/creatorId": "user-qhm2g"
    },
    "creationTimestamp": "2022-03-09T18:19:40Z",
    "fields": [
      "maxcert1",
      "true",
      "maxcert1-kubeconfig"
    ],
    "finalizers": [
      "wrangler.cattle.io/provisioning-cluster-remove",
      "wrangler.cattle.io/rke-cluster-remove"
    ],
    "generation": 6,
    "managedFields": [
      {
        "apiVersion": "provisioning.cattle.io/v1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:status": {
            ".": {},
            "f:clientSecretName": {},
            "f:clusterName": {},
            "f:conditions": {},
            "f:observedGeneration": {},
            "f:ready": {}
          }
        },
        "manager": "rancher",
        "operation": "Update",
        "subresource": "status",
        "time": "2022-03-09T18:25:58Z"
      },
      {
        "apiVersion": "provisioning.cattle.io/v1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:metadata": {
            "f:finalizers": {
              ".": {},
              "v:\"wrangler.cattle.io/provisioning-cluster-remove\"": {},
              "v:\"wrangler.cattle.io/rke-cluster-remove\"": {}
            }
          },
          "f:spec": {
            ".": {},
            "f:cloudCredentialSecretName": {},
            "f:kubernetesVersion": {},
            "f:localClusterAuthEndpoint": {},
            "f:rkeConfig": {
              ".": {},
              "f:chartValues": {
                ".": {},
                "f:rke2-calico": {}
              },
              "f:etcd": {
                ".": {},
                "f:snapshotRetention": {},
                "f:snapshotScheduleCron": {}
              },
              "f:machineGlobalConfig": {
                ".": {},
                "f:cni": {},
                "f:disable-kube-proxy": {},
                "f:etcd-expose-metrics": {},
                "f:profile": {}
              },
              "f:machinePools": {},
              "f:machineSelectorConfig": {},
              "f:registries": {},
              "f:rotateCertificates": {
                ".": {},
                "f:generation": {},
                "f:services": {}
              },
              "f:upgradeStrategy": {
                ".": {},
                "f:controlPlaneConcurrency": {},
                "f:controlPlaneDrainOptions": {
                  ".": {},
                  "f:timeout": {}
                },
                "f:workerConcurrency": {},
                "f:workerDrainOptions": {
                  ".": {},
                  "f:timeout": {}
                }
              }
            }
          }
        },
        "manager": "rancher",
        "operation": "Update",
        "time": "2022-03-09T18:40:46Z"
      }
    ],
    "name": "maxcert1",
    "namespace": "fleet-default",
    "relationships": [
      {
        "toId": "fleet-default/maxcert1",
        "toType": "cluster.x-k8s.io.cluster",
        "rel": "owner",
        "state": "provisioned"
      },
      {
        "toId": "fleet-default/maxcert1-managed-system-agent",
        "toType": "fleet.cattle.io.bundle",
        "rel": "owner",
        "state": "active",
        "message": "Resource is Ready"
      },
      {
        "toId": "fleet-default/r-cluster-maxcert1-view-p-dbhxs-creator-project-owner-esc-3b72d",
        "toType": "rbac.authorization.k8s.io.rolebinding",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "c-m-lcshvl5k/c-m-lcshvl5k-fleet-default-owner",
        "toType": "management.cattle.io.clusterroletemplatebinding",
        "rel": "applies",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/r-cluster-maxcert1-view-p-jrtns-creator-project-owner-esc-67214",
        "toType": "rbac.authorization.k8s.io.rolebinding",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/r-cluster-maxcert1-view",
        "toType": "rbac.authorization.k8s.io.role",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/crt-maxcert1-cluster-admin",
        "toType": "rbac.authorization.k8s.io.role",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/crt-maxcert1-nodes-manage",
        "toType": "rbac.authorization.k8s.io.role",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/crt-maxcert1-nodes-view",
        "toType": "rbac.authorization.k8s.io.role",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/nc-maxcert1-allroles-2kwqb",
        "toType": "rke-machine-config.cattle.io.amazonec2config",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/maxcert1-kubeconfig",
        "toType": "secret",
        "rel": "owner",
        "state": "active",
        "message": "Resource is always ready"
      },
      {
        "toId": "fleet-default/maxcert1",
        "toType": "fleet.cattle.io.cluster",
        "rel": "applies",
        "state": "active",
        "message": "Resource is Ready"
      },
      {
        "toId": "fleet-default/r-cluster-maxcert1-view-p-m9r8c-creator-project-owner-esc-dc976",
        "toType": "rbac.authorization.k8s.io.rolebinding",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/crt-maxcert1-cluster-member",
        "toType": "rbac.authorization.k8s.io.role",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "c-m-lcshvl5k",
        "toType": "management.cattle.io.cluster",
        "rel": "applies",
        "state": "active",
        "message": "Resource is Ready"
      },
      {
        "toId": "fleet-default/crt-maxcert1-cluster-owner",
        "toType": "rbac.authorization.k8s.io.role",
        "rel": "owner",
        "state": "active",
        "message": "Resource is current"
      },
      {
        "toId": "fleet-default/maxcert1-managed-system-upgrade-controller",
        "toType": "management.cattle.io.managedchart",
        "rel": "owner",
        "state": "active",
        "message": "Resource is Ready"
      }
    ],
    "resourceVersion": "85859",
    "state": {
      "error": false,
      "message": "Resource is Ready",
      "name": "active",
      "transitioning": false
    },
    "uid": "dc308447-eb80-41b2-a1b2-35459994a5b1"
  },
  "spec": {
    "cloudCredentialSecretName": "cattle-global-data:cc-t6xtp",
    "kubernetesVersion": "v1.21.10+rke2r1",
    "localClusterAuthEndpoint": {},
    "rkeConfig": {
      "chartValues": {
        "rke2-calico": {}
      },
      "etcd": {
        "snapshotRetention": 5,
        "snapshotScheduleCron": "0 */5 * * *"
      },
      "machineGlobalConfig": {
        "cni": "calico",
        "disable-kube-proxy": false,
        "etcd-expose-metrics": false,
        "profile": null
      },
      "machinePools": [
        {
          "controlPlaneRole": true,
          "etcdRole": true,
          "machineConfigRef": {
            "kind": "Amazonec2Config",
            "name": "nc-maxcert1-allroles-2kwqb"
          },
          "name": "allroles",
          "quantity": 3,
          "unhealthyNodeTimeout": "0s",
          "workerRole": true
        }
      ],
      "machineSelectorConfig": [
        {
          "config": {
            "protect-kernel-defaults": false
          }
        }
      ],
      "registries": {},
      "rotateCertificates": {
        "generation": 4,
        "services": [
          "etcd"
        ]
      },
      "upgradeStrategy": {
        "controlPlaneConcurrency": "10%",
        "controlPlaneDrainOptions": {
          "timeout": 0
        },
        "workerConcurrency": "10%",
        "workerDrainOptions": {
          "timeout": 0
        }
      }
    }
  },
  "status": {
    "clientSecretName": "maxcert1-kubeconfig",
    "clusterName": "c-m-lcshvl5k",
    "conditions": [
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:25:58Z",
        "status": "False",
        "transitioning": false,
        "type": "Reconciling"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:40Z",
        "status": "False",
        "transitioning": false,
        "type": "Stalled"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T22:10:39Z",
        "status": "True",
        "transitioning": false,
        "type": "Created"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T22:16:18Z",
        "status": "True",
        "transitioning": false,
        "type": "RKECluster"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:40Z",
        "status": "True",
        "transitioning": false,
        "type": "BackingNamespaceCreated"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:40Z",
        "status": "True",
        "transitioning": false,
        "type": "DefaultProjectCreated"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:40Z",
        "status": "True",
        "transitioning": false,
        "type": "SystemProjectCreated"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:41Z",
        "status": "True",
        "transitioning": false,
        "type": "InitialRolesPopulated"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T22:16:18Z",
        "status": "True",
        "transitioning": false,
        "type": "Provisioned"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:43Z",
        "status": "True",
        "transitioning": false,
        "type": "CreatorMadeOwner"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:25:44Z",
        "status": "True",
        "transitioning": false,
        "type": "Connected"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:25:26Z",
        "status": "True",
        "transitioning": false,
        "type": "Pending"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:26:12Z",
        "status": "True",
        "transitioning": false,
        "type": "Waiting"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:53Z",
        "status": "True",
        "transitioning": false,
        "type": "NoDiskPressure"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:53Z",
        "status": "True",
        "transitioning": false,
        "type": "NoMemoryPressure"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:19:58Z",
        "status": "True",
        "transitioning": false,
        "type": "SecretsMigrated"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:25:29Z",
        "status": "True",
        "transitioning": false,
        "type": "GlobalAdminsSynced"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:25:57Z",
        "status": "True",
        "transitioning": false,
        "type": "Ready"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:25:58Z",
        "status": "True",
        "transitioning": false,
        "type": "SystemAccountCreated"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:26:02Z",
        "status": "True",
        "transitioning": false,
        "type": "AgentDeployed"
      },
      {
        "error": false,
        "lastUpdateTime": "2022-03-09T18:26:07Z",
        "status": "True",
        "transitioning": false,
        "type": "Updated"
      }
    ],
    "observedGeneration": 6,
    "ready": true
  }
}
```

**Comment by rancher-max** [comment] 2022-03-10 19:25
There's another thing that should be changed as well. The individual service list should be:
```
admin
api-server
controller-manager
scheduler
rke2-controller
rke2-server
cloud-controller
etcd
auth-proxy
kubelet
kube-proxy
```
If the desire is to only have the ones currently listed, then at least the following need to be changed:
```
kube-apiserver           -->  api-server
kube-scheduler           -->  scheduler
kube-controller-manager  -->  controller-manager
```

**Comment by catherineluse** [comment] 2022-03-10 19:43
Oops, I didn't notice the service names are different in RKE2. I will change it to the full list.

**Comment by catherineluse** [comment] 2022-03-12 05:35
@Sahota1225 said this feature is being removed from the v2.6.4 release. https://github.com/rancher/rancher/issues/35436 We should clarify if this ticket should be moved to the v2.6.5 milestone.

**Comment by rancher-max** [comment] 2022-03-15 19:12
#### Validated using rke2 `v1.21.10+rke2r2` on rancher `v2.6-head` commitid `99974f0` with the help of @bguzman-3pillar 

- The list has the expected services now:
<img width="556" alt="image" src="https://user-images.githubusercontent.com/55997940/158453482-b6ee36bb-2fa3-4884-b670-cfe6d022ba62.png">

- Selecting to rotate all correctly rotates all certificates (passes an empty array to the API)

**Closed** 2022-03-15 19:36 UTC
Labels: [zube]: To Test, area/clusterprovisioningv2, status/release-blocker, area/rke2, team/area2

**Comment by jtravee** [comment] 2022-03-16 22:24
Confirmed with @catherineluse and @gaktive to add `release note` label.
