### ISSUE TITLE
UI-Add RBAC for fleet

### ISSUE THREAD

**Issue by StrongMonkey** [rancher/dashboard#1910] opened 2020-11-24 21:38 UTC
Need to add the following UI components for fleet:
1. Ability to assign other user to fleetworkspace if current user is an owner of fleetworkspace(or able to create roleBinding in the same namespace).
2. Ability to add cluster to the current fleetworkspace(by editing cluster.spec.fleetworkspaceName)

**Comment by StrongMonkey** [comment] 2020-11-24 21:49
One more item:
Standard user in local cluster now have the ability to create fleetworkspace, but UI doesn't display that option to create(probably because it can't list fleetworkspace). It should be able to add this in UI.(Similar to clusters)

**Comment by vincent99** [comment] 2020-12-06 10:28
This is going to be pretty limited compared to what the Ember UI does for projects/clusters, because there's no way to use Principals like it does, but we don't really have time to improve the API for this for 2.5.4.

 - The User you enter has to be a user that already exists, you can't refer to someone who hasn't logged in before
- You can only search the display name we (sometimes) store on the user object
- No principal information (icon, the actual display name vs login name from the auth provider, etc)
- No groups (there is a Groups CRD but it's not populated ever?)
- We're assuming you have permission to list Users at all, which is not necessarily true (but likely is if you're managing Fleet...)


@StrongMonkey:

> Ability to assign other user to fleetworkspace if current user is an owner of fleetworkspace(or able to create roleBinding in the same namespace).

This presence of edit action in the UI is controlled by "you" (the API) returning (or not) the `update` link on the resource.  I'm ignoring situations where you might be able to edit the workspace but not the bindings or vice versa for now so it's just based on the workspace.

> Standard user in local cluster now have the ability to create fleetworkspace, but UI doesn't display that option to create(probably because it can't list fleetworkspace). It should be able to add this in UI.(Similar to clusters)

This is also controlled by "you".  The type is shown by the UI if exists in the schemas that are returned by steve.  All types for fleet are currently missing in this situation (you can see `/v1` shows no fleet.* links) until you assign the user to some workspace, then they all show up.

> Ability to add cluster to the current fleetworkspace(by editing cluster.spec.fleetworkspaceName)

This is already in Ember, + you can move the assignment of clusters in Vue.

**Comment by vincent99** [comment] 2020-12-06 10:41
QA:  Presenting the bindings as user->role rows and letting you edit them individually is relatively complicated because k8s allows multiple users in one binding, and disallows editing roles on an existing.  There are 7 situations if you want to test them all:

- Adding a new entry (should make a new binding)
- Changing a subject on existing entry (should update the binding)
- Changing the role on an existing entry with one subject (should delete the whole binding and then make a new one, you're not allowed to edit the role of an existing binding)
- Changing the role of an existing entry with multiple subjects (should update binding with that subject removed, then make a new one.)
- Removing an existing entry where it's the only subject in the binding (should delete whole binding)
- Removing an existing entry where there are multiple subjects (should update binding with that subject removed)

The UI doesn't ever create a binding with more than one subject, but should support editing and preserving ones that do.  All bindings the UI creates use the generated name `ui-fleet-xxxxx`.

**Comment by tfiduccia** [comment] 2020-12-10 21:37
Removing this feature from 2.5.4:
Issues: I think the main issue is that this will only work for local server, anytime a user doesn't have access to the server that rancher is deployed on, it won't work at all.

**Comment by catherineluse** [comment] 2022-11-05 19:42
I suggest closing this issue because to my knowledge, there is no plan to allow project members or project owners the ability to have self-service for Fleet.

**Comment by richard-cox** [comment] 2022-11-08 13:47
To clarify, this is something that Fleet are looking in to and some work has already started for 2.7.1

**Comment by nwmac** [comment] 2023-02-28 16:14
Duplicate of https://github.com/rancher/dashboard/issues/7315

**Closed by nwmac** 2023-02-28 16:14 UTC
Labels: [zube]: Review, product/fleet, kind/enhancement, size/5
