### ISSUE TITLE
Deployments show list of all pods in namespace, not the pods in the deployment.

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5059] opened 2022-02-04 23:49 UTC
Internal reference: SURE-3984
Reported in 2.6.3

When clicking a deployment name in the Deployments UI, you are brought to a list of all pods in the namespace instead of seeing the pods of the deployment you just clicked on.

This is different than behaviour in past versions.

**Comment by nwmac** [comment] 2022-02-14 17:04
Can not reproduce - this seems to do the right thing for me

**Comment by sgapanovich** [comment] 2022-02-23 01:26
CAN'T REPRODUCE

### Test Environment: ###
Rancher version: v2.6-head e55a04c
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: RKE2 Digital Ocean node driver cluster + local 
Downstream K8s version: v1.21.9+rke2r1

----------

### Testing: ###
1. Deploy two deployments to the same namespace (`test1` and `test2` in this example in the default namespace)
2. Go to cluster (Cluster Explorer)
3. Click on "Workloads" -> "Deployments"
4. Click on any deployment

Result:
only pods for that deployment are listed on the next screen

![test1](https://user-images.githubusercontent.com/40282141/155245632-94e79384-1209-42fa-a25e-b02d836c0acf.gif)

-only `test1` pods (2 of them) are listed and no `test2` pods are present even though they are in the same namespace
which is expected behavior

**Comment by sgapanovich** [comment] 2022-02-23 22:35
@gaktive is it ok to close this issue (asking since it's internal) based on my testing above and notes from @nwmac ?

**Comment by gaktive** [comment] 2022-02-23 23:30
@sgapanovich go ahead and close. I'll update the Jira ticket accordingly, thanks!

**Closed** 2022-02-23 23:54 UTC
Labels: internal, [zube]: QA Working, priority/1, team/area3
