### ISSUE TITLE
Edit as Yaml: Action bar does not stick to bottom of page

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#8999] opened 2023-05-26 10:10 UTC
See example below:

<img width="1264" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/5f60acd0-9612-4a67-82a8-bb601aa507e4">

The button bar is scrolled off screen. The buttons should stick to the bottom of the view:

<img width="1264" alt="image" src="https://github.com/rancher/dashboard/assets/1955897/cf6a2fc3-5283-4084-aac0-046e49d7c8e7">

**Comment by cnotv** [comment] 2023-06-27 12:02
As first implementation of the footer menu, this was not possible to be used as pattern since the action menu is part of a component which has overwhelming level of complexity (CRUResource).

I will make a clear investigation and create a separated issue for the tech debt, because it would include multiple pages and aspects which we don't want to break and deal with all at once.
This issue can be fixed on its own.

**Comment by cnotv** [comment] 2023-06-27 12:06
@nwmac Could you please add specificity to the issue? I am not able to reproduce it.


https://github.com/rancher/dashboard/assets/5009481/0bfaaf22-fae6-41ea-806a-eb3dd5e252e4

**Comment by cnotv** [comment] 2024-01-31 16:40
This seems to be possible to be tested using unit tests and `jest-dom` using the function [`.toBeVisible()`](https://github.com/testing-library/jest-dom?tab=readme-ov-file#tobevisible).

**Comment by nwmac** [comment] 2024-02-14 08:54
@torchiaf Can we add automated tests?

**Comment by torchiaf** [comment] 2024-02-14 09:07
> jest-dom

I'm investigating on how to use `jest-dom` that Giuseppe suggested.

**Comment by torchiaf** [comment] 2024-02-14 14:38
@nwmac The YAML editor fix will be tested here, it's a new e2e tests + other configs: https://github.com/rancher/dashboard/pull/10459

It checks whether the footer is contained in the window viewport.
Visual checks are impossible to in unit tests, since the components are not actually rendered in a window, then the offsets and client dimensions are always zero for every HTML elements.

@cnotv` jest-dom` [.toBeVisible()](https://github.com/testing-library/jest-dom?tab=readme-ov-file#tobevisible) actually checks only certain html attributes which are not sufficient to check whether an element is visible in the screen.

**Comment by cnotv** [comment] 2024-02-14 15:25
If it can be done in E2E, it can be done 100% sure in unit tests.

**Comment by torchiaf** [comment] 2024-02-29 16:44
Covered by test automation here https://github.com/rancher/dashboard/pull/10459.

**Comment by yonasberhe23** [comment] 2024-03-25 21:16
e2e test coverage LGTM. I did create a follow-up issue https://github.com/rancher/qa-tasks/issues/1241 to add intercept logic to make sure we're actually creating the deployment, otherwise looks good. moving to 'done' @izaac

**Closed** 2024-03-25 21:16 UTC
Labels: kind/bug, [zube]: Done, size/2, QA/dev-automation

**Comment by izaac** [comment] 2024-03-26 17:41
Good call, e2e seems ok. But a final validation of the deployment would be of value. The follow up issue looks it capture this properly.
