### ISSUE TITLE
Incomplete wording in Edit local Rancher Cluster -> Member Roles

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4089] opened 2021-09-01 07:32 UTC
Rancher v2.6.0

Cluster Management -> local -> Three dots menu -> Edit Config -> Member Roles
"Caution: This is the cluster that is using as a data store." 
A word is missing

![image](https://user-images.githubusercontent.com/86831399/131630335-5937f4ab-42df-488a-8cc2-e5b140bdd72d.png)

Unable to add members. Should it be so?

Changing the cluster name -> Save errors out with:
"Failed while: Wait for Condition: InitialRolesPopulated: True"

Is this related to an empty role list?

**Comment by jiaqiluo** [comment] 2021-09-02 17:23
the bug is reproduced in rancher v2.6.0 docker install 

The steps are the same as the issue provides.

Results:
Although the UI is stuck in Saving state for a while and eventually shows the error message, the cluster name is changed successfully if I refresh the page or go back to cluster list. 

<img width="562" alt="Screen Shot 2021-09-02 at 10 20 31 AM" src="https://user-images.githubusercontent.com/6218999/131888905-b9eb14c4-e32e-4aca-b1b5-ffff1c1a5578.png">

<img width="564" alt="Screen Shot 2021-09-02 at 10 20 42 AM" src="https://user-images.githubusercontent.com/6218999/131888908-fe2272dd-8f29-420c-a2fe-bbfb0135db55.png">

**Comment by nwmac** [comment] 2021-09-06 08:23
I think this might be a case of the private label string not being rendered - I think it should say 'Rancher' or whatever the private label string is.

**Comment by nwmac** [comment] 2021-09-06 09:17
Message wording fixed by this PR: https://github.com/rancher/ui/pull/4751

**Comment by nwmac** [comment] 2021-09-06 10:52
This is an issue with the Ember page that we IFRAME.

**Comment by richard-cox** [comment] 2021-09-07 08:00
I've created #4115 for some follow on work.

**Comment by gaktive** [comment] 2021-09-07 17:06
@nwmac to create a backend ticket.

**Comment by gaktive** [comment] 2021-09-07 17:08
We need to make sure that this is happening on non-local clusters since this sounds like a bigger problem. If it's local only, then there may be a workaround on the create action.

**Comment by sowmyav27** [comment] 2021-09-18 00:36
**On 2.6-head commit id: `1a57856`**

Verify the word Rancher is seen included.
<img width="896" alt="Screen Shot 2021-09-17 at 5 31 30 PM" src="https://user-images.githubusercontent.com/26032343/133866000-2a2d0db8-4b0d-4269-950c-d8882a354a12.png">

Edit and saving the cluster takes us to the import cluster registration command page which is expected.

**Closed by sowmyav27** 2021-09-18 00:36 UTC
Labels: kind/bug, [zube]: To Test
