### ISSUE TITLE
In Create Constraints, show schema in Parameters yaml

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1777] opened 2020-11-03 19:58 UTC
In Paramater for OPA, we just have a empty yaml {}.  It would be nice to show the user the schema.
![image](https://user-images.githubusercontent.com/11514927/98034419-34245280-1dd4-11eb-939d-8b6994d048fb.png)

**Comment by catherineluse** [comment] 2022-11-05 20:01
I couldn't reproduce this in v2.7-head. I believe it is no longer applicable because we no longer have the Parameters nav item. Moving to test so that QA can close it out.
<img width="1478" alt="Screenshot 2022-11-05 at 1 00 22 PM" src="https://user-images.githubusercontent.com/20599230/200138813-22a47d7d-0d26-4a36-8f41-cbae7253e388.png">

**Comment by jameson-mcghee** [comment] 2023-01-06 22:31
I have confirmed on both `v2.6.9` and `v2.7-head` (Commit ID: 8062f1e) that the Parameters tab no longer exists on the current version of OPA Gatekeeper. Therefore I am closing this ticket.

**`v2.6.9`:**
![image](https://user-images.githubusercontent.com/13294321/211110668-88ff71a4-6a12-4b3a-ad01-b2dd08e2e2e5.png)

**`v2.7-head` (Commit ID: 8062f1e):**
![image](https://user-images.githubusercontent.com/13294321/211110739-478d5120-54c7-4f0b-84b4-eae637ad46a7.png)

**Closed by jameson-mcghee** 2023-01-06 22:31 UTC
Labels: [zube]: Done, product/opa, QA/XS, kind/enhancement, team/area2
