### ISSUE TITLE
Cloned RKE1 template contains agent_env_vars causes error while creating Downstream Cluster

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8188] opened 2023-02-16 00:51 UTC
Internal reference: SURE-5656
Reported in 2.6.9

Issue description:
Cloned RKE1 template contains agent_env_vars causes error while creating Downstream Cluster.

Repro steps:

Someone internally could reproduce it by the following steps:

Step 1: Create RKE1 template. Then edit with yaml and add agent_env_vars like this.

```
agent_env_vars:
  - name: foo
    value: bar
```
Step 2: Clone the template. Then the template includes trailing agent_env_vars in YAML.

```
agent_env_vars:
  - name: foo
    value: bar
    value_from: {}
```

Step 3: Create Downstream cluster with the cloned template. Then it fails with trailing error. 
![v2_error.png](https://zube.io/files/rancher/4061771cee54be55e151dbbb44ff343c-v2_error.png)

From that screenshot:

`Error while applying agent YAML, it will be retried automatically: exit status 1, clusterrole.rbac.authorization.k8s.io/proxy-clusterrole-kubeapiserver unchanged clusterrolebinding.rbac.authorization.k8s.io/proxy-role-binding-kubernetes-master unchanged namespace/cattle-system unchanged serviceaccount/cattle unchanged clusterrolebinding.rbac.authorization.k8s.io/cattle-admin-binding unchanged secret/cattle-credentials-00d8141 unchanged clusterrole.rbac.authorization.k8s.io/cattle-admin unchanged daemonset.apps/kube-api-auth unchanged service/cattle-cluster-agent unchanged Error from server (Invalid): error when creating "./management-statefile_path_redacted": Deployment.apps "cattle-cluster-agent" is invalid: spec.template.spec.containers[0].env[10].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef` Error from server (Invalid): error when creating "./management-statefile_path_redacted": DaemonSet.apps "cattle-node-agent" is invalid: spec.template.spec.containers[0].env[9].valueFrom: Invalid value: "": must specify one of: `fieldRef`, `resourceFieldRef`, `configMapKeyRef` or `secretKeyRef``
 
Workaround:
Original (not cloned RKE1 template) template can create Downstream Cluster.

Actual behavior:
Failed to create Downstream Cluster.

Expected behavior:
Successfully created Downstream Cluster.

Additional notes:
@snasovich took a look and found:
> at a glance it seems it's UI that adds `value_from: {}` to YAML when cloning the template and that's what causing the clusters provisioned from that template to fail. I don't see any network request that could explain backend being responsible for this when clicking "Clone Revision".

![image-2023-02-15-15-19-44-000.png](https://zube.io/files/rancher/cdd19f090399bf3ab3bf5a754ddf0f0e-image-2023-02-15-15-19-44-000.png)

**Comment by nwmac** [comment] 2023-02-23 09:41
This may well have been fixed by: https://github.com/rancher/dashboard/issues/6582

**Comment by nwmac** [comment] 2023-02-24 08:17
This is a different issues to 6582.

Fixed by this PR: https://github.com/rancher/ui/pull/4970

**Comment by Josh-Diamond** [comment] 2023-05-11 18:40
Ticket #8188 - Test Results - ✅ 
---

❗Unable to reproduce on 5/11/2023 - fix already implemented❗

---

Verified with HA Helm Rancher `v2.7-95edd0203b7c5f0159d09e368e6897a06c48ba77-head`:
1. Fresh install of rancher `v2.7-head`
2. Navigate to `Cluster Management > RKE1 Configuration > RKE Templates > Add Template`, and create a template
3. Once created, clone the template
4. Once cloned, provision a downstream RKE1 AWS Node driver cluster w/ the cloned template (created in step 4)
5. Verified - Cluster successfully provisions
6. Verified - No errors encountered
7. Verified - `value_from` is NOT seen in `agent_env_vars`; as expected

**Closed by Josh-Diamond** 2023-05-11 18:40 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, team/area2, ember, JIRA, area/cluster-template
