### ISSUE TITLE
2.6 UX: Allow a namespace to be created without leaving current context

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2513] opened 2021-03-11 09:32 UTC
In some places we show a namespace drop down and the user may decide they need a new namespace - currently they have to change contexts to do so - we should add an option to create a new namespace in the dropdown and then show a modal dialog with the create namespace view in it for the namespace to be created - once created, the namespace should be auto-selected in the namespace drop-down.

**Comment by richard-cox** [comment] 2021-12-14 09:11
The ability to type in a new entry to the ns drop down has been used in the helm app world. The messaging for this and actual ns create though is handled outside of the component.

This feature would also be helpful in the Epinio world when creating Epinio apps and services (though would need to exercise different actions/api calls).

**Comment by catherineluse** [comment] 2021-12-18 22:37
Assigning myself to this one because I'm doing the same thing for Epinio

**Comment by lvuch** [comment] 2022-01-12 23:05
![image](https://user-images.githubusercontent.com/3013118/149237142-53d69176-14e3-4a9c-af2c-207c3a2ffa18.png)

**Comment by catherineluse** [comment] 2022-01-13 23:55
updated design https://github.com/rancher/dashboard/issues/4861#issuecomment-1012464194

**Comment by nwmac** [comment] 2022-02-23 09:22
@catherineluse  @lvuch I don't understand the UX here - adding another input box so the user can enter a new name does not seem like a good UX to me.

**Comment by catherineluse** [comment] 2022-02-23 16:50
The new input was added to avoid having a popup. To me it does not seem like a good UX to introduce more modals and popups that aren't strictly necessary. Lauren said generally we should avoid using modals. What was the problem with the way it was done in Ember? It didn't use a modal then. It let you toggle the namespace input.

<img width="662" alt="Screen Shot 2022-02-23 at 9 46 37 AM" src="https://user-images.githubusercontent.com/20599230/155366719-940cbadb-cc11-4c72-bfeb-0bf7fb323654.png">
<img width="695" alt="Screen Shot 2022-02-23 at 9 46 32 AM" src="https://user-images.githubusercontent.com/20599230/155366802-01c42004-5f32-4a96-bc81-d81262a21fbb.png">

**Comment by nwmac** [comment] 2022-02-23 16:55
Yeah - I like the Ember approach, where you toggle the field like you showed - it feels very clear what is going on. That wasn't what @lvuch was proposing though, right? Can we use this approach @lvuch ?

**Comment by lvuch** [comment] 2022-02-23 18:36
My above suggestion was to have add namespace as a top option in the dropdown and populate a new input to the right. Ember way is a bit more graceful since it doesn't rearrange the page. @nwmac what are your thoughts on decoupling the namespace/name component so the namespace dropdown/input has a 1/3 of that top line real estate?

**Comment by catherineluse** [comment] 2022-02-23 18:38
@lvuch so the top line would be like 'name | select or create namespace | description'?

for reference, the current top line is:
<img width="1258" alt="Screen Shot 2022-02-23 at 11 37 10 AM" src="https://user-images.githubusercontent.com/20599230/155385333-8bb5a635-e8c1-4bfa-827f-bfc977befd32.png">

**Comment by lvuch** [comment] 2022-02-23 18:48
something like this:
<img width="800" alt="image" src="https://user-images.githubusercontent.com/3013118/155386885-152a8b85-62a7-4568-8107-6748d33acb7f.png">

**Comment by catherineluse** [comment] 2022-06-10 20:58
# QA Template

## What was fixed, or what changes have occurred

This PR https://github.com/rancher/dashboard/pull/6084 added the ability to create or edit a namespace from the same field. This change affects all forms where you can select a namespace. It is based on Kenneth's design: 
![Project Configuration Pane2](https://user-images.githubusercontent.com/20599230/162606268-cea78f08-10de-4243-9ab9-b982619f1bc7.png)
 
## Areas or cases that should be tested
I would say not every form that has the namespace selector should be tested because that would be a huge number of forms. But the forms for creating new workloads should be tested to make sure they look right, since I had to re-flow the tops of the forms slightly to make more space for the create namespace field.

When an invalid namespace is input, when you save the resource, you should see an error message that the namespace is invalid, not that there is a problem with the resource.
 
## What areas could experience regressions?
I tested this PR against a Harvester environment to make sure it doesn't mess up Harvester. You may want to test this in a Harvester setup as well.

This PR causes a regression when creating an Epinio namespace, but I will make a different PR to fix that aspect of the feature because the Epinio changes have to be made against a different branch and with a different development environment.

**Comment by markusewalker** [comment] 2022-06-13 16:06
Verified that this is addressed in `v2.6-head` https://github.com/rancher/rancher/commit/c0786cf2fa41eeb1ac872ebc5157cfb58e17e440.

**ENVIRONMENT DETAILS**
- Rancher HA
- Rancher version
     - Verified version: `v2.6-head` https://github.com/rancher/rancher/commit/c0786cf2fa41eeb1ac872ebc5157cfb58e17e440
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup and Rancher and navigate to the UI in a browser.
2. Created a standard user and login to Rancher as that user.
3. Provisioned a downstream RKE2 node driver cluster.
4. Once created, navigated to Cluster Explorer > cluster > Apps > Charts.
5. Clicked the `Alerting Drivers` chart and install. Verified in Step 1 that I was able to create a new namespace along with selecting pre-existing namespaces:
![image](https://user-images.githubusercontent.com/52591819/173396503-bc37c93c-4da3-4f8a-969f-c63599866449.png)
![image](https://user-images.githubusercontent.com/52591819/173396510-b467c7ca-cbcc-4c6a-9ac3-1cea9ef4db26.png)
![image](https://user-images.githubusercontent.com/52591819/173396526-16b0b5ea-a3c2-48a7-9584-59fc1bba177c.png) 
6. Created a new namespace and continued with installing the chart; verified this is successful:
![image](https://user-images.githubusercontent.com/52591819/173396573-b16e5c4a-2831-4a1d-8b26-aacfe76eea3f.png)
7. Created new test deployment and verified that I can create the deployment with a new namespace:
![image](https://user-images.githubusercontent.com/52591819/173396659-53d85228-78d5-4edc-9d80-e3712975efcd.png)
![image](https://user-images.githubusercontent.com/52591819/173396681-2b271075-0de3-46ec-bbf9-f9edd0dcf4cf.png) 
8. Repeated the same for other workloads such as DaemonSets; verified that was successful.

**Closed by markusewalker** 2022-06-13 16:06 UTC
Labels: [zube]: To Test, kind/enhancement, team/area2, size/3
