### ISSUE TITLE
[Bug RKE2] vSphere CSI add-on config options not visible on the UI in rancher v2.6.8

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/dashboard#6941] opened 2022-09-20 12:44 UTC
**Setup**
- Rancher version: v2.6.8
- Browser type & version: Any

**Describe the bug**

- CSI add-on config options are not visible on the UI for vSphere node driver clusters

**To Reproduce**

- On rancher v2.6.8, proceed to create a RKE2 node driver cluster.
- Input correct vSphere credentials.
- Goto `Cluster Configuration` -> `Basics` -> `Cloud Provider` -> select `vSphere`
- Goto `Add-On Config` tab -> CSI configuration is not showing up on UI. Only CPI configuration is visible as per below:
 
![cpiconfig](https://user-images.githubusercontent.com/36376154/191260096-424af0e0-821c-43e6-b92c-1e2ae44cf6f2.png)

**Result**
- CSI configuration not visible on the UI.

**Expected Result**

- CSI configuration should be visible as it is on rancher v2.6-head(48b6bc6) below:
![csi-config](https://user-images.githubusercontent.com/36376154/191259481-9f88755a-023b-4df5-93f4-47cd25f9c66e.png)

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment] 2022-09-20 13:29
@rishabhmsra Is this a duplicate of https://github.com/rancher/dashboard/issues/6804

**Comment by gaktive** [comment] 2022-09-20 15:13
Closing as a duplicate. Will see if we can fix this for 2.6.9 based on the regression.

**Closed** 2022-09-20 15:14 UTC
Labels: kind/bug, [zube]: To Triage, team/area2
