### ISSUE TITLE
EKS: Invalid information to select KMS key

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9638] opened 2023-08-31 08:37 UTC
**Setup**
```
Rancher version: v2.7-e0566312558ca549dfdf8b6b47f2800da0c783a6-head
Browser: Chrome Latest
```

**Describe the bug**
EKS: Invalid message to select KMS key even if the key is selected. If the KMS key is selected for Secrets Encryption, the text "Select or Enter KMS Key that will be used to encrypt secrets" must not be displayed.

**To Reproduce**
- Create/Import EKS cluster with Secrets encryption enabled
- Edit cluster and check Secrets encryption

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/73099870/6705c3e2-9b76-4f82-9322-f7fb7000e678)

Found while validating https://github.com/rancher/rancher/issues/42496

**Comment by mantis-toboggan-md** [comment] 2024-07-24 21:51
This appears to be fixed in 2.9.0
![Screenshot 2024-07-24 at 1 57 58 PM](https://github.com/user-attachments/assets/66c1c4ea-ba3e-40c8-8e23-eaeb5f0348e2)

**Comment by gaktive** [comment] 2024-07-24 22:04
Putting on to the 2.9.0 milestone though at this stage, if it's not a blocker, this could be tested for 2.9.next1.

**Comment by cpinjani** [comment] 2024-07-25 07:01
Blocked for validation on https://github.com/rancher/eks-operator/issues/669

**Comment by izaac** [comment] 2024-07-25 17:51
Moved to QA Blocked accordingly

**Comment by gaktive** [comment] 2024-07-26 16:13
Related operator issue out of 2.9.0 now so pushing to next1.

**Comment by izaac** [comment] 2024-08-21 15:30
Backend issue is closed. Moving to Working

**Comment by izaac** [comment] 2024-08-21 19:15
Rancher version: `v2.10-2b955aa0e4823baf6fbaf25c898aeae0273c6b48-head`
Dashboard version: `release-2.9 37abd4d`
HA Setup with k3s 1.28 cluster
EKS Provisioned using k8s 1.28

I can't reproduce the issue described and the message is not displayed.

**Closed by izaac** 2024-08-21 19:15 UTC
Labels: kind/bug, status/waiting-backend, team/highlander, area/eks, status/backport-candidate
