### ISSUE TITLE
Set the `skipFilter=true` parameter in the request for RKE2 chart index when creating RKE2 clusters

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#9520] opened 2023-08-10 23:41 UTC
As a part of the fix to https://github.com/rancher/dashboard/issues/9650,  UI should set `skipFilter=true` when requesting the RKE2 chart index:
```
/v1/catalog.cattle.io.clusterrepos/rancher-rke2-charts?link=index&skipFilter=true
```

The above request is sent by UI after we click the "Create" button in Rancher UI. 

Please check [this comment](https://github.com/rancher/dashboard/issues/9650) for more information.

**Comment by jiaqiluo** [comment] 2023-08-14 17:05
Hi @gaktive, AFAIK, yes, it is.

**Comment by aalves08** [comment] 2023-08-16 15:19
Probably on `rke2.vue` file we may find the actual request. Check model also for `catalog.cattle.io.clusterrepos`

**Comment by gaktive** [comment] 2023-08-16 15:19
There's one RKE2 file to edit and then a modal to update.

**Comment by momesgin** [comment] 2023-08-16 19:12
@jiaqiluo Just out of curiosity, what's the reason for not handling this on the backend rather than including a **static** parameter in the endpoint? I think backend knows when `/v1/catalog.cattle.io.clusterrepos/rancher-rke2-charts?link=index` gets hit and can always run the logic based on just the `link` parameter

**Comment by momesgin** [comment] 2023-08-16 19:59
@jiaqiluo thanks for explaining 🙏

**Comment by momesgin** [comment] 2023-08-17 20:48
@gaktive @jiaqiluo I was able to reproduce the issue on 2.7.5 but not on 2.7-head, I was wondering if it's fixed already or I'm missing something?


https://zube.io/files/rancher/bc78d1b261cfb339ba8bbec3a8e6f134-9520.mov

![image.png](https://zube.io/files/rancher/3bd593cea50e6d5b7855db9cba1d98b2-image.png)

**Comment by jiaqiluo** [comment] 2023-08-17 21:21
@momesgin, the bug can not be reproduced in v2.7-head: Rancher returns all versions of all charts because v2.7-head is not a valid "released" version. 

The fix is not merged yet ([PR](https://github.com/rancher/rancher/pull/42395))

You will need to wait for a Rancher RC to validate your changes in UI.

**Comment by momesgin** [comment] 2023-08-17 21:32
That makes sense, thanks @jiaqiluo!

**Comment by jiaqiluo** [comment] 2023-08-17 22:47
Hi @momesgin, I plan to expand the backend fix to support setting the target k8s version in the request. If UI sends to following request where the `k8sVersion` is the version of the downstream cluster:
```
/v1/catalog.cattle.io.clusterrepos/rancher-rke2-charts?link=index&k8sVersion=1.23.17+rke2r1
```
Rancher will use the version, plus the rancher version, to filter the charts' versions in the returned index file. 
If the `k8sVersion` is not sent in the request, Rancher will use the local cluster and rancher server versions as the filter (the current behavior). 

It means we need to request the chart index each time we change the cluster version on the creation page. 
From the UI's perspective,  how complex is it to achieve? Does it have any potential influences on other components?  

Also, to make it clear, UI can still use the `skipFilter` to get the "whole" index file.

**Comment by momesgin** [comment] 2023-08-18 17:15
@jiaqiluo I might not be the best person to answer this question since I've recently joined SUSE and I'm not very familiar with the codebase yet, but from my understanding an action will be dispatched by selecting a k8s version from the dropdown which we can initialize making the call from there, but re the potential impact on the rest of the components I think we need to dig deeper, it might be good to have an investigation ticket for it.

FYI @nwmac @gaktive

**Comment by richard-cox** [comment] 2023-09-01 14:44
@jiaqiluo Note quite sure where we go with this issue given the solution in https://github.com/rancher/dashboard/pull/9646. Recommend closing it, and then transferring https://github.com/rancher/rancher/issues/40641 to rancher/dashboard  and linking that PR to it.

**Comment by jiaqiluo** [comment] 2023-09-01 16:08
hi @richard-cox , this issue is supposed to track the effort on the UI side for fixing https://github.com/rancher/rancher/issues/40641 which has a link to a backend PR. 

I am ok if you want to close this and transfer 40641 here, as long as QA and PMs do not lose track.

**Comment by richard-cox** [comment] 2023-09-04 15:37
Closing, as per https://github.com/rancher/dashboard/issues/9520#issuecomment-1702869821 and https://github.com/rancher/dashboard/issues/9520#issuecomment-1702989508

**Closed by richard-cox** 2023-09-04 15:37 UTC
Labels: kind/bug, [zube]: Done, internal, area/rke2, size/2, JIRA, area/charts
