### ISSUE TITLE
[BUG] PSACT View not displaying Description field correctly

### ISSUE THREAD

**Issue by pjbgf** [rancher/dashboard#8335] opened 2023-03-03 12:20 UTC
**Rancher Server Setup**
- Rancher version:  `v2.7-62c5e321da5b576e565adf12c666489de9ea9373-head`

**Information about the Cluster**
- Kubernetes version: `v1.25.6+rke2r1`

**User Information**
- What is the role of the user logged in? 
  - Admin

**Describe the bug**

The UI is not correctly showing the field Description for PSACT when in Form mode.

**To Reproduce**

- Open the `rancher-privileged` PSACT (`/dashboard/c/local/explorer/management.cattle.io.podsecurityadmissionconfigurationtemplate/rancher-privileged`).
- Take note of the Description field.
- Switch to YAML view, compare the description field.

**Result**

The description field is populated with: `Any text you want that better describes this resource`
The YAML version description is: `The default privileged pod security admission configuration template`.

**Expected Result**
The value of the description field should be aligned regardless of the view mode.

**Screenshots**
![image](https://user-images.githubusercontent.com/5452977/222716232-5acc8c60-fec6-4214-b276-038bb525098d.png)

![image](https://user-images.githubusercontent.com/5452977/222718254-cdfabbf8-6bf6-4703-b49e-bd7b0350aafe.png)

**Additional context**

**Comment by gaktive** [comment] 2023-03-03 21:24
This supports rancher/rancher#40761
 
Code could be narrowed down to https://github.com/rancher/rancher/issues/40761#issuecomment-1453624626 per @macedogm

**Comment by nwmac** [comment] 2023-03-06 09:55
@cnotv I think you need to use `SteveDescriptionModel` as the base class for PSACT - see `plugins/steve/steve-description-model.js`

'description' is a getter on the base model, so you lose access to the root-level 'description' property unless you use this model.

**Comment by cnotv** [comment] 2023-03-06 10:45
Yeah, I created at the time an [issue to clarify these things in some docs](https://github.com/rancher/dashboard/issues/7682).
Thanks to do it now, because I could not have found out otherwise 😄

**Comment by cnotv** [comment] 2023-03-06 10:53
@pjbgf it seems like your case is way more specific, so you should add some extra info to reproduce.

It's necessary to update Rancher to the latest version and try this exclusively with existing system descriptions. PSACT created with UI are currently working as expected.


https://user-images.githubusercontent.com/5009481/223090361-38fc0424-7db5-48cb-84fe-c410642c14b2.mov

**Comment by cnotv** [comment] 2023-03-06 11:29
@nwmac the model where we try to get the description (not sure why we did not fix the main one) seems working for the API, while not for the form. It seems to be an issue with the component not updating from the model.


https://user-images.githubusercontent.com/5009481/223098072-462776a3-fffc-472f-8036-b327aa131691.mov

**Comment by cnotv** [comment] 2023-03-06 12:16
I can confirm that this does not work also in other locations where we use the `SteveDescriptionModel`. I'll check if I can find a way to make the description be editable.


https://user-images.githubusercontent.com/5009481/223107837-a01ecb9c-7258-4ae3-b3e1-8ee824aaf8a0.mov

**Comment by cnotv** [comment] 2023-03-06 18:13
@nwmac it seems like there's some side effects set in place to remove description before submit for some reasons, as the value is correctly edited and is present in the model, but it's not finally submitted on save.

**Comment by cnotv** [comment] 2023-03-07 13:14
As for all the Steve models we use `metadata.annotations.field.cattle.io/description`, for consistency we stick to that.
I will add just a fallback for `description`.
If we want to change the path we use for the description, rather update it globally.

**Comment by richard-cox** [comment] 2023-03-08 14:27
Note - Github PR history is a bit noodley. PR to resolve issue is https://github.com/rancher/dashboard/pull/8379

**Comment by markusewalker** [comment] 2023-03-09 22:50
**QA TEST PLAN**

Scenarios
|Scenario|Test Case|
|---|---|
|1|As an admin user, validate that built-in PSACT values `rancher-privileged` and `rancher-restricted` have their description values the same in form and YAML view|
|2|As an admin user, validate that a custom PSACT value has its description values the same in form and YAML view|

**Comment by markusewalker** [comment] 2023-03-09 23:03
Validated that this is addressed in `v2.7-head` https://github.com/rancher/rancher/commit/616b4b11719c1f8e0837b27b8fb97f300101406c. See details below:

**ENVIRONMENT DETAILS**
- Rancher install: Docker
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/616b4b11719c1f8e0837b27b8fb97f300101406c 
- Browser: Chrome

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As an admin user, validate that built-in PSACT values `rancher-privileged` and `rancher-restricted` have their description values the same in form and YAML view|:white_check_mark:|
|2|As an admin user, validate that a custom PSACT value has its description values the same in form and YAML view|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As an admin user, navigated to Rancher > Cluster Management > Advanced > Pod Security Admissions.
2. Took note of both `rancher-privileged` and `rancher-restricted` descriptions:
![image](https://user-images.githubusercontent.com/52591819/224179854-5aa20ff6-0a0e-45db-afc7-a5764647cff0.png) 
3. Clicked `rancher-privileged` and validated that the description appears to be the same:
![image](https://user-images.githubusercontent.com/52591819/224179834-d8d7ffff-28b4-4fe1-8d8f-c411299d89fb.png) 
4. Edited the PSACT and validated that the config and YAML views both showcase the same description as well.
5. Repeated steps 2-3 for the `rancher-restricted` PSACT value with the same results.
6. Navigated to top-left menu > local > More Resources > Rancher > Pod Security Admissions.
7. Repeated steps 2-4 for `rancher-privileged` and `rancher-restricted`, just within the viewpoint of the `local` cluster and not in Cluster Management.
_________
**Scenario 2**
1. As an admin user, navigated to Rancher > Cluster Management > Advanced > Pod Security Admissions.
2. Clicked `Create`.
3. Created a PSACT value titled `rancher-baseline` with `baseline` as the value for enforce, audit and warn.
4. Validated that the description I created appears successfully:
![image](https://user-images.githubusercontent.com/52591819/224179791-4951b171-3f54-4e0a-b722-f28305bd22c6.png) 
5. Clicked `rancher-baseline` and validated that the description appears to be the same:
![image](https://user-images.githubusercontent.com/52591819/224179766-2001eaab-1a41-4f36-9dc7-d2122164dfc9.png) 
6. Edited the PSACT and validated that the config and YAML views both showcase the same description as well.
7. Navigated to top-left menu > local > More Resources > Rancher > Pod Security Admissions.
8. Repeated steps 2-4 for `rancher-privileged` and `rancher-restricted`, just within the viewpoint of the `local` cluster and not in Cluster Management.

**Closed by markusewalker** 2023-03-09 23:03 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, team/area2, area/psa
