### ISSUE TITLE
Harvester Integration - Filtering Harvester clusters

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#3467] opened 2021-07-14 00:10 UTC
With the harvester integration, Harvester clusters can now be imported into Rancher as a cluster of type `Harvester`. 

Harvester host cluster = k8s cluster of type Harvester

If Harvester feature flag is enabled, we will need to filter harvester host clusters
- [ ] From any pages listing k8s clusters 
- [ ] From any apps that list k8s clusters (fleet, multi-cluster app, etc)

 If feature flag is disabled and a Harvester cluster is imported,
- [ ]  show the Harvester cluster in the Rancher MCM list. A warning should show on the Rancher MCM cluster list page and all pages that this is a Harvester cluster.

**Comment by gaktive** [comment] 2021-09-07 16:36
To develop, we need a Harvester backend. Can be done via ISO and VMWare though https://docs.harvesterhci.io/v0.2/dev/dev-mode/ has more written up though UI may need its own docs on how to set things up.

**Comment by yasker** [comment] 2021-09-07 16:39
@noahgildersleeve can we provide a temporary Harvester cluster to the Rancher team? I don't think v0.2.0 works with Rancher 2.6.

**Comment by noahgildersleeve** [comment] 2021-09-07 16:57
@gaktive @yasker Can it be a one node cluster, or does it need to be a multi-node cluster? Let me know and I'll get it setup.

**Comment by yasker** [comment] 2021-09-07 17:10
@noahgildersleeve One node should be good. UI needs to filter on the cluster level, so node count probably doesn't matter. @gaktive can you confirm?

**Comment by gaktive** [comment] 2021-09-07 17:14
@yasker One node should be sufficient for UI to get some data and come up with views. If there's a place where this is documented, that'd be perfect. Thanks!

**Comment by nwmac** [comment] 2021-09-08 11:08
@sheng-liang I don't understand this requirement:

show the Harvester cluster in the Rancher MCM list. A warning should show on the Rancher MCM cluster list page and all pages that this is a Harvester cluster.

Can you expand - currently we are hiding all Harvester clusters throughout Rancher - Harvester clusters will only show up if you go to Virtualisation Management -> Clusters.

We are filtering out based on the presence of the label `cluster.harvesterhci.io`

**Comment by nwmac** [comment] 2021-09-08 13:00
@yasker For this:

If feature flag is disabled and a Harvester cluster is imported,

 show the Harvester cluster in the Rancher MCM list. A warning should show on the Rancher MCM cluster list page and all pages that this is a Harvester cluster.

Rather than show them everywhere, we will show Harvester clusters on the Cluster Management Clusters list when the feature flag is off.

**Comment by yasker** [comment] 2021-09-08 15:30
> Rather than show them everywhere, we will show Harvester clusters on the Cluster Management Clusters list when the feature flag is off.

@nwmac I am fine with design. @deniseschannon what do you think? Since it's the appearance in Rancher.

**Comment by guangbochen** [comment] 2021-09-09 02:56
The feature flag is merged via https://github.com/rancher/rancher/pull/34612, we should be able to start the integration works now.

For creating a Harvester cluster the most feasible way are:
1. Download the [latest ISO image](https://releases.rancher.com/harvester/master/harvester-amd64.iso) 
2. Install the Harvester either via the [vagrant example](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester) or a Virtualbox VM(https://github.com/harvester/harvester/wiki/Setting-Up-Harvester-Development-Environment#option-3-using-virtualbox)
3. Once the cluster is up and running then import it to the upstream Rancher as a `generic k8s cluster`
4. The provider of the cluster should be `harvester` which u can use to identify the cluster type.

**Comment by slickwarren** [comment] 2021-09-20 17:57
following the above instructions on v2.6-head (45dfeb4):
* the imported harvester cluster shows as an RKE2 cluster and is not filtering out of the `cluster management` page. The harvester cluster is available in both cluster management and virtualization pages. **-- reopening for this issue --**

**Comment by richard-cox** [comment] 2021-09-21 08:54
I couldn't reproduce the failure using 2.6-head (ba43472), they seem to be filtered in the correct places. @slickwarren could you provide exact steps to reproduce?

![image](https://user-images.githubusercontent.com/18697775/134141261-2a3107d9-d8d3-45ca-bdcc-af5736e5ca3b.png)

![image](https://user-images.githubusercontent.com/18697775/134141557-d46f64b9-4d58-4a53-80d4-952ac35b365a.png)

**Comment by janeczku** [comment] 2021-09-21 14:33
Being able to import a Harvester cluster via **Cluster Management** -> **Import Generic** (see https://github.com/rancher/dashboard/issues/3467#issuecomment-915719863) but then not seeing that cluster listed on the  **Cluster Management** page (per the current design) seems completely _counter-intuitive_ from a UX PoV (confirmed by other users). It also prevents the user from checking easily whether the import was successful and from accessing context-menue actions such as deleting the cluster from Rancher.

**Comment by slickwarren** [comment] 2021-09-21 16:50
just confirmed on the latest rancher 2.6-head (ba43472) if a user adds the harvester cluster through the cluster management page, the filtering is not removing it from cluster management views. I don't think this is expected based on the original ask, can someone clarify this?

I'm also expecting the type/provider to be harvester, but here it is `rke2`
<img width="1272" alt="Screen Shot 2021-09-21 at 9 47 34 AM" src="https://user-images.githubusercontent.com/16691014/134213196-a46b2b30-80f2-472d-b4d2-1158ec2533fc.png">
<img width="1417" alt="Screen Shot 2021-09-21 at 9 47 28 AM" src="https://user-images.githubusercontent.com/16691014/134213207-0db73a24-ea85-4d6b-b8af-2524de65a3a2.png">
<img width="1379" alt="Screen Shot 2021-09-21 at 9 47 17 AM" src="https://user-images.githubusercontent.com/16691014/134213278-41c5527d-52fd-4ca7-9ee1-8ee7bbf10b9d.png">

**Comment by nwmac** [comment] 2021-09-22 09:20
I think being able to create and import Harvester clusters from Cluster Mgmt does not make sense to me and should be done from the Virtualization Mgmt section - with filtering in place, creating/importing a Harvester cluster from CM will the take the user to the list page that won't show the Harvester cluster as it will have been filtered out.

**Comment by richard-cox** [comment] 2021-09-22 11:04
I've now covered the bug causing cluster management imported harvester clusters to show in the cluster management list and also the UX issue of them potentially not showing in the list in a separate issue - https://github.com/rancher/dashboard/issues/4244. That will require either additional work covered there or non-at all.

I think this issue/PR can relate to filtering in other locations.

**Comment by slickwarren** [comment] 2021-09-22 20:26
on v2.6-head(223ec88) as a standard user, adding the harvester cluster via virtualization management:
* home page does not show harvester clusters -- pass
* cluster management does not show harvester clusters -- pass

*  fleet does not show harvester clusters in list of clusters (as admin user) -- pass
  * fleet does not count harvester clusters in total cluster count -- fail
  * <img width="515" alt="Screen Shot 2021-09-22 at 1 13 19 PM" src="https://user-images.githubusercontent.com/16691014/134415119-57b718ce-cd1c-4f86-ae61-902ce9c6f34b.png">
  * fleet does not include harvester cluster resources -- fail
    * `bundles` and `ClusterRegistrationTokens` are showing for harvester clusters
    * <img width="1104" alt="Screen Shot 2021-09-22 at 1 14 58 PM" src="https://user-images.githubusercontent.com/16691014/134415425-5b4ec4ee-77b3-40c9-8f9a-bd60ef5abcc4.png">
* local cluster resources properly show/filter harvester clusters -- fail
  * harvester clusters do not show in cluster count -- pass
    * HC are not included in total cluster count -- fail
    * <img width="590" alt="Screen Shot 2021-09-22 at 1 20 45 PM" src="https://user-images.githubusercontent.com/16691014/134416479-e667f7ec-2f37-466e-bf62-16d19273aa61.png">
  * local cluster still has access to HC resources -- fail (expecting admin to still see harvester cluster resources through the local cluster, i.e. perhaps a new `virtualization` tab under `More Resources`?

I think the fail cases are specific enough to open in new tickets and close this one.

**Closed by slickwarren** 2021-09-22 20:26 UTC
Labels: [zube]: To Test, area/harvester, status/release-blocker
