### ISSUE TITLE
[2.6] Cluster members page fails to render

### ISSUE THREAD

**Issue by maxsokolovsky** [rancher/dashboard#8613] opened 2023-04-03 22:33 UTC
**Setup**
- Rancher version: v2.6-head in Docker
- Browser type & version: Firefox 111

**Describe the bug**
There is an issue that happens when a user deletion gets stuck - the cluster members screen does not render anything, and there is an error in the console:
```
TypeError: this.principalId is undefined
    get management.cattle.io.clusterroletemplatebinding.js:31
    L object.js:87
    h sort.js:191
    h sort.js:187
    arrangedRows sorting.js:43
    VueJS 42
    n NuxtJS
    d runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 6
    A db5ad5c7fcf2db331c62.js:2
    NuxtJS 2
    VueJS 22
```

**To Reproduce**
It's hard to reproduce this consistently. I see it when user deletion gets stuck.

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by gaktive** [comment] 2024-03-13 22:45
Closing this since 2.6.x doesn't anticipate any immediate releases in the near future. Let us know if this happening in a newer version with reproducibility steps and file a new ticket.

**Closed by gaktive** 2024-03-13 22:45 UTC
Labels: kind/bug, [zube]: To Triage
