### ISSUE TITLE
When provisioning Hosted downstream clusters, the external/internal addresses are missing in the Cluster Management -> Machine Pools Page

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#8485] opened 2023-03-21 14:48 UTC
**Setup:**

- Rancher version: `v2.7.2-rc6` and `v2.7-head` (Commit ID: 6ee3949)
- Browser type & version: Brave

**Describe the bug:**

When deploying a downstream Hosted cluster, the external/internal IP does not appear in the _Cluster Management_ > _Machine Pools_ page

**To Reproduce:**

1. Spin up a Rancher server
2. Provision an Azure AKS downstream cluster
3. Once the cluster comes up Active, navigate to the _Cluster Management_ > _Machine Pools_ page for the cluster
  - Note that the external/internal IP addresses are missing

**Result:**

The external/internal IP addresses are missing in the _Cluster Management_ > _Machine Pools_ page for downstream Hosted clusters.

**Expected Result:**

The external/internal IP addresses SHOULD NOT be missing in the _Cluster Management_ > _Machine Pools_ page for any clusters.

**Screenshots:**
![image](https://user-images.githubusercontent.com/13294321/226643270-bec0e77a-3680-40b4-9761-24e63161dadc.png)
![image](https://user-images.githubusercontent.com/13294321/226643297-be858689-7905-4a3c-aba5-229049649fe9.png)
![image](https://user-images.githubusercontent.com/13294321/226643318-5754010f-6821-4992-8002-ca37f31cf4c5.png)

**Additional Information:**
This issue does not reproduce for RKE2, K3s, or RKE1 downstream clusters

This issue is related to issue [7802](https://github.com/rancher/dashboard/issues/7802)

**Comment by gaktive** [comment] 2023-08-04 14:54
Will check once we complete migrating AKS from Ember to Vue.

**Comment by mantis-toboggan-md** [comment] 2024-07-03 00:32
I have not been able to reproduce this issue using default values to provision AKS, nor when importing AKS clusters

**Comment by momesgin** [comment] 2024-07-08 21:15
This seems to be fixed in 2.9 as I was not able to reproduce it using default values to provision AKS cluster.

**Closed** 2024-07-08 21:15 UTC
Labels: kind/bug, status/dev-validate, QA/XS, kind/bug-qa, team/area2, QA/manual-test
