### ISSUE TITLE
2.7.0: Upgrading monitoring on a downstream cluster brings up blank page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7833] opened 2023-01-03 19:49 UTC
A user upgraded to 2.7 and when trying to upgrade the monitoring on a downstream cluster results in a blank page in the UI.

Another saw this issue with Rancher 2.7.0 and some of their managed clusters:
> In some clusters, attempting to upgrade an app installed via Helm using the chart repositories under the Apps section in the sidebar is failing. When I select Edit/upgrade for the already-installed application, I get a blank white screen. Looking in the Chrome developer tools console, I also see a message that says Find: [management] provisioning.cattle.io.cluster undefined, followed by a warning that says Attempting to load a resource with no id followed by a large stack trace. The cluster in question is an AWS EKS cluster running v1.20.15-eks-99076b2, but I also had this issue on another non-cloud-hosted cluster that was running v1.24.8+k3s1 and that is managed by a different Rancher instance. On that last non-cloud instance, I was able to unenroll and reenroll the cluster with Rancher, which solved the issue. I can provide any other information as necessary.

Repro:
Fresh install of Rancher from stable; importing a cluster (AKS 1.24.6); selecting an application to install; info page is ok, the blank page comes after pressing install, i.e. when you would expect the Helm options (or YAML) to show up:

![Screenshot_2022-12-23_12-09-41.png](https://zube.io/files/rancher/f3ee15e29316f0565f7f15562bce63a9-screenshot_2022-12-23_12-09-41.png)

Expanding the yellow icon:

![Screenshot_2022-12-23_15-00-41.png](https://zube.io/files/rancher/da55a7299044f9aed445cf7f4ee54539-screenshot_2022-12-23_15-00-41.png)

No errors in Rancher pod logs, though cattle-system-agent says:
```
time="2022-12-23T11:08:47Z" level=error msg="failed to parse constraint version >= 2.7.0.0 < 2.8.0-0: improper constraint: >= 2.7.0.0 < 2.8.0-0"
```

Sounds similar to https://github.com/rancher/dashboard/issues/7801 but that's on the Cluster's Project/Namespace page to Cluster Management.

Additional info (output from 2nd screenshot):
```
Attempting to load a resource with no id {type: 'collection', links: {…}, createTypes: {…}, actions: {…}, resourceType: 'provisioning.cattle.io.cluster', …}actions: {}createTypes: {provisioning.cattle.io.cluster: 'https://rancher.chfrank.net/v1/provisioning.cattle.io.clusters'}data: (2) [{…}, {…}]links: {self: 'https://rancher.chfrank.net/v1/provisioning.cattle.io.clusters'}resourceType: "provisioning.cattle.io.cluster"revision: "74124"type: "collection"_headers: {cache-control: 'no-cache, no-store, must-revalidate', content-encoding: 'gzip', content-type: 'application/json', date: 'Fri, 23 Dec 2022 13:59:13 GMT', expires: 'Wed 24 Feb 1982 18:42:00 GMT', …}_req: XMLHttpRequest {readyState: 4, timeout: 0, withCredentials: true, upload: XMLHttpRequestUpload, onreadystatechange: ƒ, …}_status: 200_statusText: ""_url: "https://rancher.chfrank.net/v1/provisioning.cattle.io.clusters"[[Prototype]]: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()__proto__: (...)get __proto__: ƒ __proto__()set __proto__: ƒ __proto__() undefined
n.forEach.console.<computed> @ console.js:31
load @ actions.js:459
(anonymous) @ vuex.esm.js:851
m.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
r.dispatch @ vuex.esm.js:779
(anonymous) @ actions.js:412
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
find @ actions.js:389
(anonymous) @ vuex.esm.js:851
m.dispatch @ vuex.esm.js:516
dispatch @ vuex.esm.js:406
(anonymous) @ install.vue:766
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
getClusterRegistry @ install.vue:761
(anonymous) @ install.vue:98
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
fetch @ install.vue:82
(anonymous) @ fetch.client.js:72
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
v @ 0c25b11bfefe987bafaa.js:2
f @ fetch.client.js:57
m @ fetch.client.js:29
ee @ vue.runtime.esm.js:1863
vn @ vue.runtime.esm.js:4235
t @ vue.runtime.esm.js:4058
Dn.$mount @ vue.runtime.esm.js:8459
init @ vue.runtime.esm.js:3137
n @ vue.runtime.esm.js:3322
(anonymous) @ vue.runtime.esm.js:6022
v @ vue.runtime.esm.js:5969
(anonymous) @ vue.runtime.esm.js:6560
t._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
Tn.get @ vue.runtime.esm.js:4495
Tn.run @ vue.runtime.esm.js:4570
Sn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
ce @ vue.runtime.esm.js:1915
Promise.then (async)
oe @ vue.runtime.esm.js:1942
pe @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Tn.update @ vue.runtime.esm.js:4560
t.$forceUpdate @ vue.runtime.esm.js:3984
(anonymous) @ vue.runtime.esm.js:8244
h @ vue.runtime.esm.js:2244
ee @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2184
(anonymous) @ vue.runtime.esm.js:7740
(anonymous) @ vue.runtime.esm.js:336
bo @ vue.runtime.esm.js:7435
(anonymous) @ vue.runtime.esm.js:7772
requestAnimationFrame (async)
(anonymous) @ vue.runtime.esm.js:7407
requestAnimationFrame (async)
yo @ vue.runtime.esm.js:7406
k @ vue.runtime.esm.js:7764
So @ vue.runtime.esm.js:7748
remove @ vue.runtime.esm.js:7841
j @ vue.runtime.esm.js:6199
T @ vue.runtime.esm.js:6173
(anonymous) @ vue.runtime.esm.js:6602
t._update @ vue.runtime.esm.js:3963
r @ vue.runtime.esm.js:4081
Tn.get @ vue.runtime.esm.js:4495
Tn.run @ vue.runtime.esm.js:4570
Sn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
ce @ vue.runtime.esm.js:1915
Promise.then (async)
oe @ vue.runtime.esm.js:1942
pe @ vue.runtime.esm.js:1999
(anonymous) @ vue.runtime.esm.js:4418
Tn.update @ vue.runtime.esm.js:4560
_t.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
jn.set @ vue.runtime.esm.js:4644
finish @ GlobalLoading.vue:14
(anonymous) @ client.js:429
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
P @ 0c25b11bfefe987bafaa.js:2
_ @ vue-router.esm.js:2362
r @ vue-router.esm.js:2087
(anonymous) @ vue-router.esm.js:2088
(anonymous) @ vue-router.esm.js:2384
(anonymous) @ client.js:131
v @ runtime.js:63
(anonymous) @ runtime.js:294
(anonymous) @ runtime.js:119
r @ asyncToGenerator.js:3
l @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
l @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
B @ 0c25b11bfefe987bafaa.js:2
_ @ vue-router.esm.js:2362
r @ vue-router.esm.js:2087
r @ vue-router.esm.js:2091
Lt @ vue-router.esm.js:2095
zt.confirmTransition @ vue-router.esm.js:2392
zt.transitionTo @ vue-router.esm.js:2260
e.push @ vue-router.esm.js:2606
ee.push @ vue-router.esm.js:3039
h.a.push @ extend-router.js:12
B.t.push @ router.js:496
install @ chart.vue:96
click @ chart.vue?06d0:1
ee @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
Dr.c._wrapper @ vue.runtime.esm.js:6961
```

**Comment by gaktive** [comment] 2023-01-03 19:50
See also https://github.com/rancher/dashboard/issues/7808

**Comment by richard-cox** [comment] 2023-01-04 09:48
Regarding the version error
```
time="2022-12-23T11:08:47Z" level=error msg="failed to parse constraint version >= 2.7.0.0 < 2.8.0-0: improper constraint: >= 2.7.0.0 < 2.8.0-0"
```

There's two `annotation` sections for neuvector in the root index.yaml and the second one contains the incorrect `2.7.0.0` value - https://github.com/rancher/charts/blob/dev-v2.7/index.yaml#L2769
There's also the same mistake in a previous version of neuvector's chart - https://github.com/rancher/charts/blob/dev-v2.7/charts/neuvector/101.0.0%2Bup2.2.3/Chart.yaml#L10

These exist in both the `dev-v2.7` and `dev-v2.7.1` branches. 

This cause be the cause of the error, or something separate. Given #7808 it may be the latter. We should raise this with them once we've resolved / investigated UI side

**Comment by richard-cox** [comment] 2023-01-04 09:50
This is most likely the same as https://github.com/rancher/dashboard/issues/7808, though might be related to the odd version error. Both should be tackled at the same time and we can then loop back on https://github.com/rancher/dashboard/issues/7833#issuecomment-1370702801

**Comment by catherineluse** [comment] 2023-01-11 20:39
I haven't reproduced this yet, but I searched for `2.7.0.0 < 2.8.0-0`, the invalid version constraint, and found it in the NeuVector chart.

<img width="1195" alt="Screenshot 2023-01-11 at 1 35 38 PM" src="https://user-images.githubusercontent.com/20599230/211912354-32be7762-70d1-45e4-95a9-f3eec2cf6609.png">

That line with the invalid constraint was last edited in this PR https://github.com/rancher/charts/pull/2097

I wonder if there are two issues here - the invalid version constraint and also a missing cluster id. I'm going to try to reproduce it as a project member and see if that works.

**Comment by iosifnicolae2** [comment] 2023-01-19 10:07
off, we're having the same problem..

**Comment by AndrewHoffmanQA** [comment] 2023-01-23 19:16
retested passed

I installed monitoring on several downstream clusters with different variables and the mointoring page loaded every time, this functionality appears to be working as intended.

tested on 2.7head 9278cf1

moving to 'done'

**Closed** 2023-01-23 19:16 UTC
Labels: kind/bug, [zube]: QA Working, area/test, priority/1, team/area3, area/helm, size/3

**Comment by sadhugit** [comment] 2023-01-25 06:39
Hi team,  Are we going to backport this fix in 2.6.x, or does the customer need to upgrade to overcome this issue?

**Comment by nwmac** [comment] 2023-01-25 08:59
@sadhugit I don't think this issue affects versions prior to 2.7.

**Comment by sadhugit** [comment] 2023-02-13 17:53
@nwmac  2.6.x has the same entry in the new vector chart. The customer is hitting the same in 2.6.x                                ` level=error msg="Unknown error: Get \"https://charts.rancher.io/assets/logos/cis-kube-bench.svg\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
2023-01-11T14:48:55.234764632Z time="2023-01-11T14:48:55Z" level=error msg="Error during subscribe websocket: close sent"
2023-01-11T14:48:58.992648887Z time="2023-01-11T14:48:58Z" level=error msg="failed to parse constraint version >= 2.7.0.0 < 2.8.0-0: improper constraint: >= 2.7.0.0 < 2.8.0-0"
`
