### ISSUE TITLE
Show pod log fail

### ISSUE THREAD

**Issue by 631068264** [rancher/dashboard#7205] opened 2022-10-17 08:52 UTC
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Chrome 106.0.5249.103

**Describe the bug**

<img width="1427" alt="image" src="https://user-images.githubusercontent.com/8144089/196132280-6a9296ba-0e59-418a-bd3b-05b627e4b217.png">
Use this pod **view log**  button,  logs view is empty
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/8144089/196132677-f1a55880-05d7-46e4-b79c-fd9a8c4a11eb.png">

Get log from server，but can't show it
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/8144089/196133208-3213ed49-426d-48db-9d13-368fbb97be45.png">

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment] 2022-10-17 09:10
Thanks for opening this issue, it is however a duplicate of https://github.com/rancher/dashboard/issues/5984 and has been resolved in 2.6.7. There are a couple of workarounds linked in [this](https://github.com/rancher/dashboard/issues/5984#issuecomment-1180191702) comment.

**Closed by richard-cox** 2022-10-17 09:10 UTC
Labels: kind/bug
