### ISSUE TITLE
After removing longhorn/Monitoring from the cluster , the items are still in the menu on the lefthand side

### ISSUE THREAD

**Issue by claudioser** [rancher/dashboard#3811] opened 2021-08-12 10:04 UTC
After removing longhorn/Monitoring from the cluster , the items are still in the menu on the lefthand side. Using rancherImageTag=master-c58f95221d76c6e6a32c89426b300f8afd2ab69a-head

![image](https://user-images.githubusercontent.com/53047113/129178474-6bd2e5ef-59d4-4bc0-b1c5-bc6e54da9f92.png)

**Comment by richard-cox** [comment] 2021-11-22 14:05
@nwmac The PR for this was targeted to 2.6.3. I've aligned this issue with that, possibly a candidate to bump out?

**Comment by ronhorton** [comment] 2022-02-01 12:47
I cannot reproduce this in 2.6.3. Mulitple installs / uninstalls of longhorn and monitoring and the left nav adds and removes sections accordingly.

**Comment by nwmac** [comment] 2022-02-01 14:45
@jordojordo Can you verify on 2.6.4 and move to test if you can't reproduce it

**Comment by jordojordo** [comment] 2022-02-01 17:56
I was not able to reproduce this on `v2.6-head` Commit ID `da382a8`. Moving to test.

**Comment by ronhorton** [comment] 2022-02-03 13:17
Cannot repro in `2.6-head Commit ID da382a8`Mulitple installs / uninstalls of longhorn and monitoring and the left nav adds and removes sections accordingly.

**Closed by ronhorton** 2022-02-03 13:17 UTC
Labels: [zube]: QA Working, team/area3
