### ISSUE TITLE
Filter panel and log content are disappeared from Pod "View Log" function 

### ISSUE THREAD

**Issue by silviatosi** [rancher/dashboard#6114] opened 2022-06-07 12:41 UTC
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Chrome Version 102.0.5005.63 (Official Build) (64-bit)

**Describe the bug**

Cannot view logs having all permissions - not even the filter panel is visible

**To Reproduce**
What I remember, I set the filter to see ALL logs of POD and then some days passed. After this, I cannot see anything anymore for any pods. We have another installation of ranchere where I can see the logs and the filter panel

**Result**

**Expected Result**
To see again all logs and the filter panel

**Screenshots**
Here the working rancher:
![image](https://user-images.githubusercontent.com/41120690/172380541-dda02195-453f-43b1-8790-52caa55ed20d.png)
Not working (It was working, I still have access to logs and I can watch them through kubectl, so I should have permissions):
![image](https://user-images.githubusercontent.com/41120690/172380738-ea78f340-e79f-49b8-a12b-1df3d909cc2c.png)

**Additional context**
This is what I can see in my chrome console only using the button View Logs from a pod
![image](https://user-images.githubusercontent.com/41120690/172381116-aa5318ff-af6a-47db-8af7-9a9b0199e3ea.png)

Thank you very much for any help

**Comment by chungcien** [comment] 2022-06-08 08:45
I temporarily solved the problem with the command:

kubectl delete preferences.management.cattle.io -n [userID] logs-range

**Comment by sowmyav27** [comment] 2022-06-09 21:32
Similar to this issue - https://github.com/rancher/dashboard/issues/5984 which has been fixed on 2.6head and will be part of 2.6.6 release

**Comment by silviatosi** [comment] 2022-06-10 11:51
> I temporarily solved the problem with the command:
> 
> kubectl delete preferences.management.cattle.io -n [userID] logs-range

this command will be executed by our kubernetes/rancher administrator - I do not have these permissions (waiting to see the result) 

Thank you for your both replies, let's wait the incoming release also!

**Comment by richard-cox** [comment] 2022-07-12 16:25
Closing as duplicate of https://github.com/rancher/dashboard/issues/5984

**Closed by richard-cox** 2022-07-12 16:25 UTC
Labels: kind/bug
