### ISSUE TITLE
vSphere: CPU value changes to default when other values are changed

### ISSUE THREAD

**Issue by jameson-mcghee** [rancher/dashboard#7783] opened 2022-12-20 19:52 UTC
**Setup**
- Rancher version: `v2.7.0` and `v2.7-head` (Commit ID: ea6b86c)
- Browser type & version: Brave: `v1.46.140` | Chromium: `v108.0.5359.99`

**Describe the bug**
If a user makes any changes to the RKE2 vSphere Provisioning form after changing the _CPU_ value, the _CPU_ value will reset to the default value of 2

**To Reproduce**
1. Spin up a `v2.7.0` Rancher server
2. Begin creating a new RKE2 vSphere Node Cluster
3. Change the _CPU_ value to 4
4. Expand the _Operating System_ dropdown, and select _windows_

**Result**
The _CPU_ value reverts back to the default value of 2

**Expected Result**
The _CPU_ value is unaffected and remains at what it was set

**Screens
![2022-12-20_14-51-35](https://user-images.githubusercontent.com/13294321/208754423-9638ab20-6722-4d2a-a751-4e7251312df5.gif)
hots**

**Additional context**
I have confirmed this issue will reproduce in `v2.7.0` but does not reproduce in the older version `v2.6.5`.

**Comment by gaktive** [comment] 2023-01-11 17:11
@jameson-mcghee do you know if a workaround would be to set this via YAML and have it stick that way? We're trying to see if that could work for now but this helps us prioritize work for this release.

**Comment by jameson-mcghee** [comment] 2023-01-17 21:52
@gaktive, this is a valid work around.

**Comment by gaktive** [comment] 2023-02-15 23:51
Internal reference: SURE-5873

**Comment by aalves08** [comment] 2023-03-01 10:24
@jameson-mcghee I can't reproduce this on `v2.7-head 4ca4a76`. Your screenshot/gif is very small and I couldn't get any info from it, but I made a screen recording:


https://zube.io/files/rancher/213c1056fbf70df6b32289c1bfafb73c-screen-recording-2023-03-01-at-10-21-03.mov

Let me know if I am doing all of the correct steps. Thank you 🙏

**Comment by jameson-mcghee** [comment] 2023-03-01 15:52
> @jameson-mcghee I can't reproduce this on `v2.7-head 4ca4a76` (latest at the time of writing this comment). Your screenshot/gif is very small and I couldn't get any info from it, but I made a screen recording:
> 
> https://zube.io/files/rancher/213c1056fbf70df6b32289c1bfafb73c-screen-recording-2023-03-01-at-10-21-03.mov
> 
> Let me know if I am doing all of the correct steps. Thank you 🙏

@aalves08, looks like you are right. I just retested this on `v2.7-head` (Commit ID: 1032039), and was also unable to reproduce the issue. Have there been any changes made since this issue was reported that could have resolved this issue?

![image](https://user-images.githubusercontent.com/13294321/222191479-96940eea-7247-479f-aeb3-6345e982a00b.png)

**Comment by aalves08** [comment] 2023-03-01 16:22
> > @jameson-mcghee I can't reproduce this on `v2.7-head 4ca4a76` (latest at the time of writing this comment). Your screenshot/gif is very small and I couldn't get any info from it, but I made a screen recording:
> > https://zube.io/files/rancher/213c1056fbf70df6b32289c1bfafb73c-screen-recording-2023-03-01-at-10-21-03.mov
> > Let me know if I am doing all of the correct steps. Thank you 🙏
> 
> @aalves08, looks like you are right. I just retested this on `v2.7-head` (Commit ID: 1032039), and was also unable to reproduce the issue. Have there been any changes made since this issue was reported that could have resolved this issue?
> 
> ![image](https://user-images.githubusercontent.com/13294321/222191479-96940eea-7247-479f-aeb3-6345e982a00b.png)

Not sure @jameson-mcghee . At least from my side, I didn't do any changes 🤷 Maybe someone from the UI team played around with cluster provisioning and accidentally fixed it.

**Comment by jameson-mcghee** [comment] 2023-03-01 21:39
Due to the fact that @aalves08 and I, are no longer able to reproduce this issue on `v2.7-head` (Commit ID: 1032039) when following the Steps to Reproduce, I am closing this ticket as Can't Repro.

**Comment by David-VTUK** [comment] 2023-09-28 12:41
I can recreate this in v2.7.6 - requesting this gets reopened:

[Screencast from 2023-09-28 13-37-01.webm](https://github.com/rancher/dashboard/assets/5892615/6bf88ba1-d8bd-43e4-a535-6047920860ef)

**Comment by David-VTUK** [comment] 2023-10-07 15:53
Under some conditions this will revert the `cpu` count when `create` is selected. This will result in the provisioned cluster having incorrect node specs.

Example attached
[Screencast from 2023-10-07 16-45-46.webm](https://github.com/rancher/dashboard/assets/5892615/4d070ddb-aa81-4789-bb12-fe7563e9c39d)

**Comment by aalves08** [comment] 2023-12-20 17:49
@David-VTUK , I've just re-tested this with a `v2.7.6` system on `Brave` Version `1.61.104` Chromium: `120.0.6099.115` and I cannot reproduce this.


https://github.com/rancher/dashboard/assets/97888974/3fb76a5b-ff09-41e1-82ec-56132c65368b

**Comment by aalves08** [comment] 2024-01-17 16:18
@gaktive @nwmac last time I looked into this issue and replied (almost a month ago) I couldn't reproduce this. Are we in a position to close this?

**Comment by aalves08** [comment] 2024-01-17 16:43
Close issue due because we cannot reproduce it @gaktive

**Closed by aalves08** 2024-01-17 16:43 UTC
Labels: kind/bug, [zube]: Next Up, QA/XS, team/area2, area/vsphere, size/3, status/waiting-response, JIRA
