### ISSUE TITLE
RKE1 custom cluster "Registration" tab missing from rancher UI.

### ISSUE THREAD

**Issue by rishabhmsra** [rancher/dashboard#11160] opened 2024-06-03 12:39 UTC
**Setup**
- Rancher version: v2.9-head(3d6ceee) or v2.9.0-alpha3
- Rancher UI Extensions:

**Describe the bug**

- "Registration" tab, that has the info regarding the cp, etcd and worker node registration command is missing from the UI for RKE1 custom cluster.
- Note: This occurs after the cluster comes in Active state.

**To Reproduce**

- Create RKE1 v1.29.5-rancher1-1 cluster (1-cp, 1-e, 1-w) used in this case.
- Wait for the cluster to come up Active.
- Goto "Cluster Management" -> click on RKE1 custom cluster(which is in Active state)
- **Observe that there is no Registration tab present:**

![custom](https://github.com/rancher/dashboard/assets/36376154/6e9a12c5-cc37-45c9-8851-75f23e7a4c15)

- **For comparison see the below image from rancher v2.8.4 where the "Registration" tab is present.**

![custom1](https://github.com/rancher/dashboard/assets/36376154/7e63fbb0-2a17-4c90-842c-d392c405f2b0)

**Result**
- " Registration" tab missing from UI for RKE1 custom clusters, see the screenshot above.

**Expected Result**

- "Registration" tab should be present.

**Comment by gaktive** [comment] 2024-06-07 15:44
We historically have a lot of problems with getting the right information on a cluster to show registrations properly since there are cases where we can't show it but have.

We'll explore a fix here but there should be a discussion since there's a lot of flip flop here. Automation could save us here too.

**Comment by aalves08** [comment] 2024-06-12 15:25
https://github.com/rancher/dashboard/pull/10319 may have had impact. Needs to be digested

**Comment by gaktive** [comment] 2024-06-12 15:25
Past work done by @aalves08 around here in https://github.com/rancher/dashboard/issues/9402

**Comment by richard-cox** [comment] 2024-06-12 15:28
Change  referenced above might be safe, given https://github.com/rancher/dashboard/pull/10319/files#diff-a82b21daf1dd70199627fd86da6e1ed80f8260507e624619bd1b1519c45d9864L518-L520. `showRegistration` is definitely the starting point

**Comment by codyrancher** [comment] 2024-07-01 18:09
So digging into this issue it seems like we intentionally hide the registration tab whenever the tab is active.

I decided to dig a little deeper and I found this issue https://github.com/rancher/dashboard/issues/3337. If anything this seems like showing the tab was the regression. 

I'm in favor of closing this unless we have new information as to why we should show the tab.

**Closed** 2024-07-01 22:06 UTC
Labels: kind/bug, size/2, regression, QA/dev-automation
