### ISSUE TITLE
Selecting a cloud provider then reverting back to none still deploys the vsphere CPI

### ISSUE THREAD

**Issue by cloudnautique** [rancher/dashboard#3468] opened 2021-07-14 04:14 UTC
**Rancher Server Setup**
- Rancher version: Rancher 2.6 master-head
- Installation option (Docker install/Helm Chart): Helm chart
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): K3S 1.21.2+k3s1
- Proxy/Cert Details: lets encrypt self signed

**Information about the Cluster**
- Kubernetes version: RKE2 1.21.2+rke2r1
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):
   - Rancher RKE2 provisioning on DO cluster. 

**Describe the bug**

When you select the vSphere cloud provider when creating an RKE 2 cluster, the YAML gets populated. If you select none the cluster object doesn't seem to save it.

**To Reproduce**
 
Cluster Manager, "Create"
Select RKE2
Select DO
Enter Cloud Credential info
Under Cluster configuration->basics select cloud provider vSphere. (Observe YAML has the vSphere images / etc.)
Then select None. (Observe YAML still has vSphere info)
when you create it silently deploys the vSphere CPI

**Result**

**Expected Result**

If None is selected during create before clicking save, then the deployment YAML for any previously selected CP should be removed and nothing deployed.

**Screenshots**

**Additional context**
<!--Add any other context about the problem here.—>

**Comment by richard-cox** [comment] 2021-08-09 09:33
Will be fixed via #3709

**Comment by deniseschannon** [comment] 2021-08-19 17:59
I am unable to reproduce this with v2.6-head 25d39aa

The YAML wil always have info about all the charts, but it only is deployed if the cloud-provider-name is set to something that is relevant. 

@cloudnautique If you can reproduce, please re-open.

**Comment by cloudnautique** [comment] 2021-08-23 20:33
@deniseschannon,

On a DigitalOcean cluster, I select a node pool with a single large node. I then click on the vSphere cloud provider, then select none.

I click on create, and the cluster starts provisioning. It then ends up in a broken state with the following:
![Screen Shot 2021-08-23 at 1 32 14 PM](https://user-images.githubusercontent.com/1989084/130515454-3cb646b5-1650-45fb-9b84-47106f88390b.png)

**Comment by deniseschannon** [comment] 2021-08-24 05:20
I am unable to reproduce your issue @cloudnautique so let's talk offline. 

My cluster comes up using the same use case.

What version of v2.6 are you running?

**Comment by gaktive** [comment] 2021-08-24 16:33
@deniseschannon let me know if UI still has to do anything here.

**Comment by gaktive** [comment] 2022-02-24 18:05
Could QA try to reproduce this and see if it's still an issue?

**Comment by slickwarren** [comment] 2022-03-21 22:32
I could not reproduce using v2.6-head (024e6fa)

**Closed by slickwarren** 2022-03-21 22:32 UTC
Labels: kind/bug, [zube]: QA Next up, team/area2, status/needs-info
