### ISSUE TITLE
[project monitoring v2] unable to select webhook from dropdown when creating receiver

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#5823] opened 2022-05-04 19:28 UTC
**Setup**
- Rancher version: `2.6-head Commit ID 054b5d1`
- Browser type & version: `chrome latest`
- `Custom Cluster`

**Describe the bug**
on Create Receiver in AlertmanagerConfig page, when selecting 'sms' for a webhook, the selection is not applied. (ie, cannot select a value in the dropdown)

**To Reproduce**
1. Cluster > Monitoring > Alerting > Alertmanage configs
2. select existing alert
3. click add receiver
4. provide name
5. select sms from dropdown

**Result**
cannot select value from dropdown

**Expected Result**
sms selected and relevant configuration appears for completion

**Screenshots**
<img width="1637" alt="Screen Shot 2022-05-04 at 3 27 39 PM" src="https://user-images.githubusercontent.com/89212856/166811207-911992f4-aa5d-4b50-8a83-6dece84ccbf7.png">

**Comment by catherineluse** [comment] 2022-05-05 21:08
This issue is addressed by https://github.com/rancher/dashboard/pull/5850

### Root cause
The webhook type selector was not correctly updating the parent component's state. It was directly modifying a prop which is not ideal in Vue
 
### What was fixed, or what changes have occurred
 Refactored it so that the parent component state is updated correctly when you click the Add Webhook button

### Areas or cases that should be tested

The webhook selection dropdown has been replaced with a button:
<img width="880" alt="Screen Shot 2022-05-05 at 2 03 43 PM" src="https://user-images.githubusercontent.com/20599230/167025307-7149fcf4-3033-4dac-9350-8723580bfd2d.png">

Selecting `MS Teams` updates the URL field with a link (which is hardcoded now, but later we will only let you select that after we validate that the link would actually work):

<img width="818" alt="Screen Shot 2022-05-05 at 2 03 27 PM" src="https://user-images.githubusercontent.com/20599230/167025337-cbd83fc1-a185-4021-b597-f7d1257d0721.png">

When `SMS` is selected, you get the other URL in the URL field:
<img width="1047" alt="Screen Shot 2022-05-05 at 2 05 49 PM" src="https://user-images.githubusercontent.com/20599230/167025556-1b5905cb-206d-4ddb-9c73-5a9df880b455.png">

The url field in YAML is also updated:
```yaml
webhookConfigs:
        - httpConfig:
            ...
          url: >-
            http://rancher-alerting-drivers-prom2teams.cattle-monitoring-system.svc:8089/v2/connector
```

 When `generic` is selected, it clears the field:
<img width="845" alt="Screen Shot 2022-05-05 at 2 06 45 PM" src="https://user-images.githubusercontent.com/20599230/167025645-463ab144-d3be-4896-bb0a-784c90b32a8e.png">

### What areas could experience regressions?

**Comment by ronhorton** [comment] 2022-05-06 19:20
**Pass** verified in `2.6-head Commit ID 455fdf6`
Selected several webhooks and form loaded correctly upon selection

![Screen Shot 2022-05-06 at 3.19.17 PM.png](https://zube.io/files/rancher/59f7c33437855302d8286f4b04885cc9-screen-shot-2022-05-06-at-3-19-17-pm.png)

**Closed** 2022-05-06 19:20 UTC
Labels: [zube]: Done, area/monitoring, area/monitoring-alerting
