### ISSUE TITLE
Unable to select existing PVC from dropdown when editing a deployment

### ISSUE THREAD

**Issue by winsonchao** [rancher/dashboard#10230] opened 2024-01-05 08:42 UTC
**Setup**
- Rancher version: v2.7.9

**Describe the bug**
When editing a deployment to add an existing PVC, dropdown shows "Sorry, no matching options"

**To Reproduce**
1. Create a PVC
2. Edit a deployment
3. Choose Pod -> Storage -> Add Volume -> Persistent Volume Claim

**Result**
Dropdown shows "Sorry, no matching options"

**Expected Result**
Show existing PVCs for the namespace

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/47791281/2e451043-61b3-45dc-ab7e-41c3ac7d8cee)
![image](https://github.com/rancher/dashboard/assets/47791281/105bb377-07b9-45b4-92ce-e4595e3c0f63)

**Additional context**
The issue can be workaround by using Edit as Yaml

**Comment by ampie** [comment] 2024-01-10 15:21
We encountered the same behaviour on ConfigMap and Secret Volumes

**Comment by aalves08** [comment] 2024-01-17 16:07
@winsonchao I cannot replicate this issue on `2.7.9` neither in `2.8.0`

![Screenshot 2024-01-17 at 16 05 10](https://github.com/rancher/dashboard/assets/97888974/cbc0d142-09d8-45ce-b850-69666aec7938)

https://github.com/rancher/dashboard/assets/97888974/d99a4dab-d563-436f-9fdb-f13207c1fc77

FYI @gaktive @nwmac

**Comment by nwmac** [comment] 2024-01-17 16:41
We can't reproduce this - the PVC must be in the same namespace as the deployment, could that be your issue?

Closing as can not reproduce - please re-open with more detailed reproduction steps if you still see this problem.

**Closed by nwmac** 2024-01-17 16:41 UTC
Labels: kind/bug, [zube]: Backlog, status/needs-info
