### ISSUE TITLE
GUI -> Deployment > Storage > Persistent Volume Claim UI is broken

### ISSUE THREAD

**Issue by jpeizer** [rancher/dashboard#3087] opened 2021-05-25 18:04 UTC
I have attempted this in multiple browsers, Mac and Windows, and it all acts the exact same.

When selecting to add a Persistent Volume Claim to a deployment, the user is unable to name the volume, and the UI breaks as a result.

Steps:
1. Add a persistent volume (I used host path with [A directory, create it it if does not exist])
2. Add a persistent volume claim using the previously defined persistent volume
3. Create a new deployment
4. select storage
5. Select add storage
6. Select Persistent Volume Claim from the drop-down
7. Select the name and press backspace or simply start typing
 - Notice the UI goes back a step as if you never selected from the drop down
 - Notice that the volume was still added regardless of the UI malfunction
 - The UI seems to act as if you pressed save and will not let you deploy without finishing the deployment editing the yaml directly.

System Information:
Kubernetes install - Microk8s
kubectl version 1.21.1
host: Ubuntu 21.04
rancher: 2.5.8 stable branch

**Comment by gaktive** [comment] 2022-01-20 23:24
We should verify the behaviour in 2.6.x, along with confirming that changing volume names work based on feedback elsewhere.

**Comment by neillsom** [comment] 2022-03-07 22:00
Unable to replicate issue after testing. 
This issue appears to be fixed as of 2.6.3 from earlier PRs [4284](https://github.com/rancher/dashboard/pull/4284) and [4486](https://github.com/rancher/dashboard/pull/4486)

**Comment by markusewalker** [comment] 2022-04-21 20:39
Unable to reproduce in `v2.6.3` or `v2.6-head` https://github.com/rancher/rancher/commit/a478def06ee49ff6f36c37c0444c550ef82a9c67.

**ENVIRONMENT DETAILS**
- Linode Ubuntu 20.04 VM
- Docker install - 20.10
- Rancher version - `v2.6-head` https://github.com/rancher/rancher/commit/a478def06ee49ff6f36c37c0444c550ef82a9c67

**VERIFICATION STEPS**
1. Setup Rancher `v2.6-head` and navigate to Rancher UI > top-left dropdown menu > Explore Cluster > local. Download the kubeconfig file and apply to client machine.
2. Apply a test PersistentVolume (PV) and a test PersistentVolumeClaim (PVC) bound to the prior PV to the cluster. PV specified must have a `hostPath` defined.
3. Back in Rancher UI, navigate to top-left dropdown menu > Explore Cluster > local > Workload > Deployments.
4. Click Create > Storage > Add Volume > Persistent Volume Claim.
5. Select the PVC you created and begin to type in the volume name; I do not see an error as expected.
![image](https://user-images.githubusercontent.com/52591819/164548355-3b6c3625-e2eb-47a6-b8dc-b7752f757ea0.png)
6. Click General, specify the name of this Deployment, specify the `nginx:latest` image and in the bottom-right corner, click Create. This deployment resource creates successfully:
![image](https://user-images.githubusercontent.com/52591819/164548401-186a9008-7771-4586-bcd6-d1b123051aeb.png)

**Closed by markusewalker** 2022-04-21 20:39 UTC
Labels: kind/bug, internal, [zube]: QA Working, team/area2
