### ISSUE TITLE
rancher-gatekeeper - When creating a new constraint if I click in Edit as YAML in the Parameters section the UI gets refreshed back to Cluster Overview

### ISSUE THREAD

**Issue by izaac** [rancher/dashboard#1011] opened 2020-08-12 17:56 UTC
- Install Rancher HA k8s
- Check Local cluster is active
- Go to Dashboard -> Apps -> Charts
- Install `rancher-gatekeeper`
- `rancher-gatekeeper:v3.1.0-beta.11` gets installed.

Go to OPA gatekeeper and Create constraint
In parameters section click Edit as YAML

Browser get reloaded completely

![opa-edit-as-yaml](https://user-images.githubusercontent.com/27659/90049975-708b5b00-dc8a-11ea-8c39-b0ccb2375043.gif)

Rancher version `master-head (08/12/2020)` _d19f179c4_

**Comment by aaronRancher** [comment] 2020-08-24 22:28
The bug ic not reproduced with Rancher server `rancher\rancher:master-head` `version 8a60de75d` `master-8a60de75db5324c73535b71c087c3e4bd5f36d29-head`
Closing issue. Will reopen if behavior is seen again.

**Comment by aaronRancher** [comment] 2020-08-25 20:14
Reopening as behavior was observed. User is redirected because of href.

![Screen Shot 2020-08-25 at 1 10 28 PM](https://user-images.githubusercontent.com/57409052/91223032-de954080-e6d4-11ea-89e7-35c57c9cb0c6.png)

**Comment by aaronRancher** [comment] 2020-09-04 20:34
The bug fix is verified with Rancher server `rancher\rancher:master-head` `version 731b33e`

User is able to edit as yaml without being redirected.
![Screen Shot 2020-09-04 at 1 34 06 PM](https://user-images.githubusercontent.com/57409052/92282841-51f83880-eeb3-11ea-8197-f8e950890b15.png)

**Closed by aaronRancher** 2020-09-04 20:34 UTC
Labels: [zube]: To Test, area/opa, kind/bug, status/blocker
