### ISSUE TITLE
Drain Control Plane Nodes and Drain Worker Nodes should be checked default

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9108] opened 2023-06-13 09:19 UTC
Internal Ref: SURE-6438

Default to setting both Drain control Plane Nodes and Drain Worker Nodes to checked.

Might be Ember only - should check Dashboard as well.

**Comment by richard-cox** [comment] 2023-06-14 15:20
This is in the RKE2 machine config Advanced section as well.

![image](https://github.com/rancher/dashboard/assets/18697775/da9450e4-9357-4abc-bc4f-85ead933201a)

**Comment by momesgin** [comment] 2023-07-04 18:12
Here's how to be able to see the two Drain options ` Drain Control Plane Nodes` and ` Drain Worker Nodes`:

1. Create a generic cluster if you don't have one running already
2. Go to Cluster Management page and click on Import Existing button on the top
3. On the next page choose the Generic option
4. On the next page put any name as the cluster name and click on Create button
5. You'll be redirected to your import cluster, there'll be some commands you can copy, copy the first `kubectl` command (Note: you might get some auth errors when running this command, in that case come back and copy the second command)
6. Check the cluster in the first step and open the Kubectl Shell for it, paste the command and run it
7. Check your **import** cluster again and go to its Edit Config page, you should be able to see the two Drain options under the Rke2 Options section

**Comment by gaktive** [comment] 2023-07-17 23:29
Awaiting confirmation from an engineer about which field needed an updated default. If this arrives quickly, we can still target Q3.

**Comment by gaktive** [comment] 2023-07-19 15:20
Been advised that "Drain control Plane Nodes and Drain Worker Nodes should be checked default. They cannot answer today, and are therefore ok if the issue is pushed to Q423"

**Comment by gaktive** [comment] 2023-08-02 21:31
Feedback received:  the configuration in the machine pool section the user would like defaulting to "drain node".

**Comment by markusewalker** [comment] 2023-09-28 18:55
**QA TEST PLAN**

**Scenarios**
|Scenario|Test Case|
|---|---|
|1|As a standard user, provision a downstream RKE2 cluster and validate that drain before delete is enabled by default)|
|2|As a standard user, provision a downstream K3S cluster with drain before delete disabled, validate that drain before delete is not enabled|

**Comment by markusewalker** [comment] 2023-09-28 19:13
Reproduced this behavior on `v2.7-head` https://github.com/rancher/rancher/commit/af7b9ed5cf34b69a3ba9656504c5966eae3882df.

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 cluster and validate that drain before delete is enabled by default)|:x:|

**REPRO STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.27.6+rke2r1` node driver cluster (1 etcd, 1 cp, 1 worker).
     - Validated that in each machine pool that drain before delete was disabled by default.
2. Validated that the cluster and nodes are `Active`.
3. Validated that `drainBeforeDelete` field does not exist in the cluster YAML.

Now that I have reproduced the issue, I will attempt to validate the fix on the latest `v2.8-head`.

**Comment by markusewalker** [comment] 2023-09-28 19:14
Validated that this addressed in `v2.8-head` https://github.com/rancher/rancher/commit/c55d3344dc46525a860c712f868f1b7ab1826b1b.

**ENVIRONMENT DETAILS**
- Rancher version: `v2.8-head` https://github.com/rancher/rancher/commit/c55d3344dc46525a860c712f868f1b7ab1826b1b
- Rancher install: Docker

**TEST RESULT**
|Scenario|Test Case|Result
|---|---|---|
|1|As a standard user, provision a downstream RKE2 cluster and validate that drain before delete is enabled by default)|:white_check_mark:|
|2|As a standard user, provision a downstream K3S cluster with drain before delete disabled, validate that drain before delete is not enabled|:white_check_mark:|

**VALIDATION STEPS**

**Scenario 1**
1. As a standard user, provisioned a downstream RKE2 `v1.27.6+rke2r1` node driver cluster (1 etcd, 1 cp, 1 worker).
     - Validated that in each machine pool that drain before delete was enabled.
2. Validated that the cluster and nodes are `Active`.
3. Validated that `drainBeforeDelete` is set to `true` in the cluster YAML.

_______

**Scenario 2**
1. Repeated scenario 1, steps 1-2, but manually disabled the drain before delete function in each machine pool in my K3S `v1.27.6+k3s1` cluster.
2. Validated that there is no `drainBeforeDelete` field in the cluster YAML.

**Closed by markusewalker** 2023-09-28 19:14 UTC
Labels: QA/XS, [zube]: QA Working, kind/enhancement, team/area2, ember, JIRA
