### ISSUE TITLE
Dropdown box on continuous delivery page for swtiching namespace is not in place

### ISSUE THREAD

**Issue by Ellenqs** [rancher/dashboard#2323] opened 2021-02-12 19:07 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
bug

**Steps to reproduce:**

- Deploy rancher single install.
- Deploy a downstream cluster.
- Go to cluster explorer -> continuous delivery.

**Result:**

The dropdown is not in place. See the screenshot below.
<img width="403" alt="Screen Shot 2021-02-11 at 8 24 41 PM" src="https://user-images.githubusercontent.com/75277058/107808373-522c1800-6d1e-11eb-8774-7afc31e48a7d.png">
<img width="358" alt="Screen Shot 2021-02-11 at 4 15 33 PM" src="https://user-images.githubusercontent.com/75277058/107808424-67a14200-6d1e-11eb-867d-d13ea344f5a3.png">

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `v2.5-head, 761c805d`
- Installation option (single install/HA): single install

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): custom

**Comment by lvuch** [comment] 2021-02-12 19:45
this is fixed in this pr: https://github.com/rancher/dashboard/pull/2267

**Comment by nwmac** [comment] 2021-02-15 10:25
This is a duplicate of #2306

**Closed by nwmac** 2021-02-15 10:25 UTC
Labels: kind/bug
