### ISSUE TITLE
[Bug] Access Harvester project/namespace page hangs

### ISSUE THREAD

**Issue by n313893254** [rancher/dashboard#6596] opened 2022-08-04 07:32 UTC
**Setup**
- Rancher version: v2.6.7-rc6
- Browser type & version: Chrome

**Describe the bug**

Harvester namespace page is stuck

**To Reproduce**

- Deploy Rancher and import a Harvester cluster
- Go to Harvester cluster
- Go to Projects/Namespaces

**Result**

- Projects/Namespaces page hangs

**Expected Result**

- Show namespace list

**Screenshots**

![image](https://user-images.githubusercontent.com/18737885/182783833-6d1e706d-f50e-4145-a32a-02bbd2e51a1e.png)

**Additional context**

```
[Vue warn]: You may have an infinite update loop in a component render function.
```

The issue is caused by `filteredRows` keep update, maybe introduced by this line https://github.com/rancher/dashboard/blob/55b05644900bec94cd454eae0d86a1be9ce0979a/shell/components/ResourceTable.vue#L206

If fix like this, the namespaces list works as expect

```js
const includedNamespaces = this.$store.getters['activeNamespaceCache'];
```

**Detailed Description**

**Context**

Harvester issue: 
- https://github.com/harvester/harvester/issues/2626

**Comment by richard-cox** [comment] 2022-08-04 08:39
@n313893254 Has verified this happens on `master` even with the changes from https://github.com/rancher/dashboard/pull/6570

**Comment by n313893254** [comment] 2022-08-05 02:18
Verified on `master` branch

The Harvester namespace list has been fixed. But the namespace detail page has the same error, which also can produce on explore namespace detail page.

![image](https://user-images.githubusercontent.com/18737885/182987451-e7abce8d-1b69-4fa1-9ccd-08ada12e2219.png)

**Comment by richard-cox** [comment] 2022-08-05 11:11
The loop is being triggered by multiple calls to `ResourceTable`s `filteredRows` (which eventually calls `getActiveNamespaces`). If a page contains multiple lists one `filteredRows` will trigger the other and so on.

I think the fix is to only update the cache `activeNamespaceCache` if there have actually been changes, so `updateActiveNAmespaceCache` becomes something like below. I need to give this a thorough test though

```
const updateActiveNamespaceCache = (state, activeNamespaceCache) => {
  // This is going to run a lot, so keep it optimised
  let cacheKey = '';

  for (const key in state.activeNamespaceCache) {
    cacheKey += key + state.activeNamespaceCache[key];
  }

  if (state.activeNamespaceCacheKey !== cacheKey) {
    state.activeNamespaceCacheKey = cacheKey;
    state.activeNamespaceCache = activeNamespaceCache;
  }
};
```

**Comment by sowmyav27** [comment] 2022-08-08 14:34
Closing this issue since the original issue was validated as fixed https://github.com/rancher/dashboard/issues/6596#issuecomment-1205966187

**Closed by sowmyav27** 2022-08-08 14:34 UTC
Labels: kind/bug, [zube]: QA Next up, status/release-blocker

**Comment by slickwarren** [comment] 2022-08-08 19:09
Tested using both 2.6.7-rc5 and 2.6-head (6a73921) on harvester v1.0.3-rc2, however I was unable to reproduce the issue using either the original steps or the video here https://github.com/rancher/dashboard/issues/6596#issuecomment-1205966187
