### ISSUE TITLE
RKE2 version is not updating in cluster edit page after the Kubernetes Version upgrade

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6956] opened 2022-09-21 21:53 UTC
Internal reference: SURE-3909
Reported in 2.6.0

Issue description:
Upgraded the RKE2 version from `1.21.4+rke2r2` to `1.21.5+rke2r2` using the script https://docs.rke2.io/upgrade/basic_upgrade/. The new versions are showing correctly in Rancher UI (Cluster explorer) Kubernetes CLI (`k get nodes --context blueprint`) but it's still showing the old version at Cluster edit page.

Business impact:
As long as the version does not match, no changes to the cluster configuration are possible. For example, adding roles or groups via the Rancher UI is no longer possible. It's making some delay to deliver the project.

Repro steps:
1. Install Rancher 2.6.0 and import one RKE2 cluster as downstream.
2. Keep the RKE2 version as 1.21.4+rke2r2
3. Upgrade the RKE2 version from 1.21.4+rke2r2 to 1.21.5+rke2r2 using the https://docs.rke2.io/upgrade/basic_upgrade/.
4. Go to the rancher UI and navigate to the cluster explorer, `k get nodes --context blueprint`
-- both result should be reflecting the new version 1.21.5+rke2r2
5. Go to the cluster edit page and see the version where it will be as old 1.21.4+rke2r2

Workaround:
Is a workaround available and implemented? Yes -- delete the cluster and import it again, the correct Kubernetes version will be updated.

Actual behavior:
After the upgrade of RKE2-Downstream Clusters (Rancher 2.6.0) from 1.21.4+rke2r2 to 1.21.5+rke2r2, the version is showing as 1.21.4+rke2r2 in the cluster edit page

Expected behavior:
After the upgrade of RKE2-Downstream Clusters (Rancher 2.6.0) from 1.21.4+rke2r2 to 1.21.5+rke2r2, the version should show as 1.21.5+rke2r2 in the cluster edit page

Additional notes:
RKE2 and Team 3 already looked at this and based on how the versions appear elsewhere outside of the UI, the thinking is that this is UI related.

**Comment by mantis-toboggan-md** [comment] 2022-10-20 21:52
I'm not sure this is actually a UI issue, but I may be misunderstanding how editing an imported cluster is supposed to work. The UI is fetching a norman cluster object then displaying/updating the `rke2Config.kubernetesVersion` field: this field doesn't update when the cluster is upgraded (per instructions at  https://docs.rke2.io/upgrade/basic_upgrade/)...so we are either trying to edit the wrong fields or the problem is outside the UI.

**Comment by snasovich** [comment] 2022-10-20 23:33
@gaktive @mantis-toboggan-md , I believe this is a duplicate of https://github.com/rancher/rancher/issues/34114 which was closed as "functions as designed".
Most relevant comments:
* https://github.com/rancher/rancher/issues/34114#issuecomment-931695473
* https://github.com/rancher/rancher/issues/34114#issuecomment-917127848
* https://github.com/rancher/rancher/issues/34114#issuecomment-896560055

cc: @Sahota1225

**Comment by gaktive** [comment] 2022-10-21 16:30
As noted, this is working as designed per https://github.com/rancher/rancher/issues/34114. That ticket is closed and there's nothing to QA, so I'll mark this done.

**Closed** 2022-11-22 18:29 UTC
Labels: kind/bug, [zube]: To Test, priority/0, JIRA
