### ISSUE TITLE
Issue with the left navigation pane in a cluster's context

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3613] opened 2021-08-03 14:29 UTC
**On master-head commit id: `30574c2`**

- Deploy a downstream cluster from cluster management
- From left slide in pane, navigate to the cluster
- Expand Apps and Market Place Menu and click on Chart
- Charts page opens up. 
- But the left menu, collapses. 
- This happens for other sections also

**Expected:**
- When selecting a Page in the Left menu, can we NOT have them collapse, as user may want to navigate to other resources in the same section, but will have to expand it one more time to navigate

**Comment by richard-cox** [comment] 2021-08-03 14:42
@rak-phillip This is probably a dupe of #3512. Can you investigate and if so comment and move to `to test`?

**Comment by rak-phillip** [comment] 2021-08-03 17:24
This definitely reads as a duplicate of #3512 . Moving to `to test`

@richard-cox @sowmyav27

**Comment by deniseschannon** [comment] 2021-08-03 20:25
Closing in favor of #3512

**Closed by deniseschannon** 2021-08-03 20:25 UTC
Labels: [zube]: To Test, kind/bug
