### ISSUE TITLE
Descriptions are not seen on apps

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#3038] opened 2021-05-19 21:31 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):** 
On Rancher `master-head` `version d8acb21`, navigate to dashboard > apps & marketplace > charts 
Install an app (OPA gatekeeper 3.3.1+up3.3.0 was used to test).
Add a description.
Install.

**Result:**
Description is not seen in app view. Or in app edit.
Adding a description during app edit succeeds in the logs:
`helm upgrade --description=test2 --history-max=5 --install=true --namespace=cattle-gatekeeper-system --timeout=10m0s --values=/home/shell/helm/values-rancher-gatekeeper-3.3.1-up3.3.0.yaml --version=3.3.1+up3.3.0 --wait=true rancher-gatekeeper /home/shell/helm/rancher-gatekeeper-3.3.1-up3.3.0.tgz`
But is not seen in the UI or on app edit.

This behavior is also seen in v2.5.8

**Comment by richard-cox** [comment] 2021-06-03 10:31
It doesn't seem like the description is accessible again, have asked the backend team.

For `v1/catalog.cattle.io.clusterrepos/<repo>?action=install` POST we set the description via `charts[x].description` (this looks like it's correct - https://github.com/rancher/rancher/blob/692a9507ebeec70118aa8496999e89d0dfa1cc18/pkg/api/steve/catalog/types/rest.go#L12). This is then visible in the log output as `helm install ... --description=<description>`. When fetching the resulting app from `v1/catalog.cattle.io.apps` I only see `spec.chart.metadata.description` of the original chart.. not what we've supplied.

**Comment by jiaqiluo** [comment] 2021-06-25 21:34
Based on my investigation in rancher:`v2.5.9-rc3`, it looks like the UI is looking at the wrong place. 

The `charts[x].description` is the correct field to set the description in the POST request.  

But when When fetching the resulting app from `v1/catalog.cattle.io.apps`, the UI should look up the value at `data[*].spec.info.description`. See the following screenshot as an example:
<img width="1608" alt="Screen Shot 2021-06-25 at 2 24 51 PM" src="https://user-images.githubusercontent.com/6218999/123487092-25d4b200-d5c2-11eb-995b-342bc5fca2f9.png">


@richard-cox   I move this issue back to the UI team. Let me know if you have any questions.

**Comment by richard-cox** [comment] 2021-06-30 15:53
@jiaqiluo It looks like `spec.info.description` is dependent on the state of the app and only updates to the user supplied description once successfully installed. I've seen it change from 

![image](https://user-images.githubusercontent.com/18697775/123992081-32db1200-d9c3-11eb-9f4d-ff5590dbb44c.png)
to
![image](https://user-images.githubusercontent.com/18697775/123992132-3d95a700-d9c3-11eb-83d0-1ad62ac3ef6c.png)

If the install/upgrade is in progress or fails it gets stuck with the state description

![image](https://user-images.githubusercontent.com/18697775/123989851-2f468b80-d9c1-11eb-97b7-6b671f7c981f.png)

It's good to how some kind of state message, however the user supplied state should still be retrievable

(If it helps with testing for the in progress/failed case I was using `console` from the repo `https://cloudfoundry.github.io/stratos`. It requires a default storage class in the cluster and none was configured causing installs/upgrades to fail)

**Comment by jiaqiluo** [comment] 2021-06-30 17:00
I talked offline with @richard-cox, and his concern is that if the user edits the app again when the app is in the upgrading state, the user will end up editing the status text instead of their own description.

I feel it might be a bug in the backend that the `spec.info.description` is updated to reflect the app's state wrongly. 

I need to do some investigation and will update my comment here.

**Comment by jiaqiluo** [comment] 2021-07-06 22:54
Ok, I think this is not a bug, let me explain it here:

The purpose of the description is to provide an optional description of a Helm operation, such as `helm install`, `helm uninstall`, or `helm upgrade`. We can find it from Helm's help:
```
> helm install -h  | grep -i description
      --description string           add a custom description
```

and the only place we can see the description is in the history of an app:
```
> helm history rancher-backup -n cattle-resources-system
REVISION	UPDATED                 	STATUS    	CHART                           	APP VERSION	DESCRIPTION
1       	Tue Jul  6 17:54:41 2021	superseded	rancher-backup-2.0.0+up2.0.0-rc3	2.0.0-rc3  	insall-the-app-from-rancher-UI
2       	Tue Jul  6 17:55:56 2021	deployed  	rancher-backup-2.0.0+up2.0.0-rc3	2.0.0-rc3  	edit to upgrade from Rancher UI
```

Therefore, back to this issue:
- `Description is not seen in app view. Or in app edit.` is expected, because 1) The cluster explore UI does not support checking the helm history of an app; 2) The field in the edit page is for setting the optional description for this occurent edit, not checking the description of the previous install/edit operation. 
- `the description is changing during the upgrading process` is also expected, because Helm manages its value, and will leave a meaningful description if the operation fails. 


@aaronRancher @richard-cox  I will close this issue for now. Let me know if you have any questions.

**Comment by cbron** [comment] 2021-07-07 00:26
Reopening because I want to better understand the problem.
@aaronRancher How did this work in 2.5.2 ? If what Jack is saying is true then it never should have worked, and I don't understand why that description box exists as it has been using helm 3 since 2.5.0.

**Comment by richard-cox** [comment] 2021-07-07 08:46
@jiaqiluo @cbron I have a feeling this has never worked, or at least is currently being presented incorrectly. If the description is only ever linked to the execution of the helm command then we need to move the context of the description field away from where it is now (implies it's more of a resource description) to somewhere more helm command specific (there's a helm options step which contains other fields like this).

**Comment by aaronRancher** [comment] 2021-07-07 18:17
@cbron This behavior is similar on Rancher v2.5.2
Helm upgrade succeeds with description.
```
SUCCESS: helm upgrade --description=test description --install=true --namespace=cattle-gatekeeper-system --timeout=10m0s --values=/home/shell/helm/values-rancher-gatekeeper-3.1.101.yaml --version=3.1.101 --wait=true rancher-gatekeeper /home/shell/helm/rancher-gatekeeper-3.1.101.tgz
```
Description is seen in YAML:
```
info:
    description: test description
```
Description is not seen in UI app view or app edit.

**Comment by jiaqiluo** [comment] 2021-07-08 17:10
> @jiaqiluo @cbron I have a feeling this has never worked, or at least is currently being presented incorrectly. If the description is only ever linked to the execution of the helm command then we need to move the context of the description field away from where it is now (implies it's more of a resource description) to somewhere more helm command specific (there's a helm options step which contains other fields like this).

@richard-cox  I think you are right! Can you make a new UI issue for UI enhancement that just likes what you described? Once you create the new issue, can you link it to and close this one?

**Comment by richard-cox** [comment] 2021-07-09 13:39
@jiaqiluo This is a good issue to track the problem with, I've created #3437 which will resolve it

**Comment by deniseschannon** [comment] 2021-08-02 22:29
There is no more description field on app deployments, but honestly I'm not sure what the point is having description as a helm command if it doesn't get saved from version to version. 

But this bug is no longer seen.

**Closed by deniseschannon** 2021-08-02 22:29 UTC
Labels: [zube]: QA Next up, kind/bug
