### ISSUE TITLE
Continuous Delivery (CD) dashboard inaccurately displays the bundle count 0/0

### ISSUE THREAD

**Issue by skanakal** [rancher/dashboard#9178] opened 2023-06-22 12:37 UTC
**Setup**
- Rancher version: 2.7.4
- local cluster: v1.24.11+rke2r1
- fleet-102.0.0+up0.6.0

**Describe the bug**
Continuous Delivery (CD) dashboard inaccurately displays the bundle count 

**To Reproduce**
- Create gitrepo with the following example: 
~~~
apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: kustomize
  namespace: fleet-local
spec:
  branch: SURE-6398
  insecureSkipTLSVerify: false
  paths: []
  repo: https://github.com/skanakal/fleet-experiments.git
~~~

**Result**
Fleet dashbaord shows incorrect bundle count 0/0

**Expected Result**
Bundle count  1/1 

**Screenshots**
bundle count 0/0
![image](https://github.com/rancher/dashboard/assets/124564266/03467842-4845-4d34-9df3-29fbae9db1e6)

but bundle is active: 

![image](https://github.com/rancher/dashboard/assets/124564266/46310b5c-eba6-4555-a645-3b2aba84572e)

**Additional context**
Internal ref: https://jira.suse.com/browse/SURE-6398

**Comment by skanakal** [comment] 2023-06-22 13:13
The issue was resolved by reorganizing the directory structure, specifically by moving all the files from the root directory to the "mans" directory. The updated directory structure is as follows:

```
mans
├── base
│   ├── health.json
│   ├── helloworld.json
│   └── kustomization.yaml
├── Chart.yaml
├── fleet.yaml
├── kustomization.yaml
└── overlays
    └── lab
        ├── health.json
        └── kustomization.yaml 
```

**Comment by gaktive** [comment] 2023-06-23 21:17
Duplicate of #9137 which is already on radar for Q3 unless I'm misreading the related internal reference. If so, perhaps both items can be handled in one ticket. Closing.

**Closed** 2023-06-23 21:17 UTC
Labels: kind/bug, status/duplicate
