### ISSUE TITLE
[Clone] Azure AD Edit Config always picks Standard endpoint in radio button

### ISSUE THREAD

**Issue by jordojordo** [rancher/dashboard#6953] opened 2022-09-21 17:37 UTC
Clone of rancher/dashboard#6428 - needed for merging into `master` branch.

Setup

    Rancher version: v2.6-head near v2.6.7 release
    Browser type & version: Firefox 102

Describe the bug
This is relevant for existing setups of Azure AD. The Edit Config screen always selects the Standard endpoint as a value in the radio button, even if the set up has China as the endpoint, or Custom.

To Reproduce
This does not happen immediately after registering Azure AD - if you register and then navigate to the Edit Config screen, then everything works correctly, China is selected, if I had registered with a China endpoint and credentials.

But if I navigate away and come back, the issue appears.

    Register Azure AD with a China endpoint.
    Go to the local cluster, then back to the Edit Config screen in Auth Providers.

Result
The radio button selects the Standard value by default

Expected Result
The radio button should select China as the endpoint, since this is how I had configured Azure AD initially.

Screenshots

Additional context

Detailed Description
The same will happen with Custom endpoint configurations. I wonder if the UI could figure out which value to select by querying the auth config and inspecting the value of Graph Endpoint. We know which Standard and China endpoints are valid. If it's none of those, then assume it's Custom.

Context
This is not urgent for the v2.6.7 Azure AD changes, just a UI enhancement.

**Comment by anupama2501** [comment] 2022-10-17 12:17
Duplicate of https://github.com/rancher/dashboard/issues/7045

**Closed** 2022-10-17 12:20 UTC
Labels: kind/bug, [zube]: QA Working, team/area1
