### ISSUE TITLE
Fleet: Add Dashboard view

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#5048] opened 2022-02-04 08:53 UTC
Add a new dashboard view to Fleet - this should be the top of the nav list and thus the default page that the user comes to.

Design:

![image](https://user-images.githubusercontent.com/1955897/152498918-71647147-e693-4ae2-9677-e903492e766a.png)

Key things to note:

- The dashboard shows a card for each Fleet workspace - these can be collapsed by toggling the icon on the right.
- There should be a way of expanding and collapsing all workspace cards
- Each card shows a maximum of 5 repos (this is not quite shown right in the design) - when there are more than this there is a 'Show N more workspaces' button (shown on 2nd workspace card in the design). When clicked, this will show the additional repositories. Note we could be more adaptive on what we show - e.g. if there are only 2 workspaces (the default), then we could show more repositories per workspace. With a larger number of workspaces, we show less repositories per workspace.
- In the workspace card, clicking on the workspace title would change the workspace filter to that workspace and take you to the Git Repos page.
- I don't know how easy it is to show the bundle state in the table for a workspace - this may be expensive requests to make to get that data, so if its slow, we can just show the Clusters and Resources info for each repository.

When there are no Git Repositories, we should show a welcome screen instead of the view above:

![image](https://user-images.githubusercontent.com/1955897/152499714-9463b34e-bc5b-477b-b043-1b7f23e130fa.png)

(We'll refine this over time, but this is good to start). Clicking 'Get Started' will take you to the Create page for Git Repos (we'll improve this at a later stage).

**Comment by aalves08** [comment] 2022-02-25 13:09
@Jono-SUSE-Rancher just added the tag for 2.6.4 so that we could push it out on this release.

I have seen that you have been tagging it for QA (if I am not mistaken). Could it be pushed to QA from your side, please?

If got this totally wrong, please let me know. Still quite new to the team.

Thanks!

**Comment by Jono-SUSE-Rancher** [comment] 2022-02-25 15:37
Just to be clear @aalves08 - I actually didn't add this to v2.6.4 or anything. What I might have done is added an associated or related backend Rancher ticket into v2.6.4 to be triaged by team 3 to see if we can _try_ to get it into v2.6.4.

**Comment by aalves08** [comment] 2022-02-25 15:50
Ok. So @Jono-SUSE-Rancher shall I keep the v2.6.4 tag that I recently added or remove it?

**Comment by Jono-SUSE-Rancher** [comment] 2022-02-25 15:52
My advice would be that if this is dependent on the backend ticket getting completed that it's unlikely to be done by v2.6.4. Though we can try. For my own sanity, is the backend ticket we're talking about https://github.com/rancher/rancher/issues/36132?

**Comment by aalves08** [comment] 2022-02-25 15:57
This doesn't have any backend tasks associated with it. It's just a FE task to implement this dashboard screen.

**Comment by davidnuzik** [comment] 2022-03-02 21:24
I am arguably kind of blocked by https://github.com/rancher/dashboard/issues/5280 but will test without creating more workspaces (this limits my ability to test the dashboard as carefully as I would like to)

**Comment by davidnuzik** [comment] 2022-03-02 21:46
**My checks PASSED**
 
**Reproduction Steps:**

Not required. Is a new enhancement.

-----
 
**Validation Environment:**

Rancher version: v2.6-head `1d2b746` 3/2/2022
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.10+rke2r1
 
**Validation steps:**

Rather than posting explicit steps, I think it may make more sense for me to make a bulleted list of areas I focused on / checked during validation of this change. This is because on top of navigating to each page I did a lot of functional, usability, and exploratory testing to ensure that to the best of my ability this change both makes sense and works as expected.

*During all testing, monitor the browser dev tools on a separate computer monitor. Ensure there are no network errors and errors in the console.
- Navigated to the Dashboard page without any gitRepos (default state)
The dashboard shows a Welcome notice and explains that there are no gitRepos listed.
The link to "Learn More." properly routes to fleet.rancher.io in a new tab.
The "Get Started" button appropriately routes me to the gitRepo creation form.
- Created a workspace that encompasses three downstream clusters. Created one gitRepo that targets this workspace.
Navigated to the Dashboard as soon as I created the repo. I watched the columns update (Clusters Ready, Bundles Ready, Resources Ready).
**I noticed that clusters ready is 0/0 but this seems to be due to bug https://github.com/rancher/dashboard/issues/5280 that I discovered. Due to this bug I won't be able to test additional workspaces.**
_I switched to use fleet-default so it can deploy a gitRepo and saw I the dashboard update correctly._
![image](https://user-images.githubusercontent.com/45179589/156452494-709d9da4-7ed8-453c-b1b3-0384ad4d0f63.png)
![image](https://user-images.githubusercontent.com/45179589/156452520-d3b914e8-6eb9-4497-8fd5-43afb10cec78.png)

- Tested Dashboard functionality
Ensured I can click on the gitrepo name to navigate to the repo's page
Ensured I can pause and unpause my repo from this (the dashboard) page
Ensured I can force an update from the dashboard page
Ensured I can edit config from this page, made a change to the gitrepo edit form and it updated correctly.
Ensured I can edit as YAML
Ensured I can clone
Ensured I can download YAML
Ensured I can delete my repo
_Ensured that when all repos are deleted the "Welcome to Fleet" content is shown again, just like in our first test in the default out-of-the-box state._
Ensured that I can add a cluster to my workspace and that the dashboard page dynamically updates the Clusters count. Did the same for Repositories and Cluster Groups as well.
Ensured that sorting of columns works as expected.
![image](https://user-images.githubusercontent.com/45179589/156454781-639d962f-f619-4336-8709-c1ff383bf302.png)

**Additional Info:**
Again, due to bug https://github.com/rancher/dashboard/issues/5280 I cannot create new workspaces (that have clusters assigned to them) and therefore could not test how the dashboard functions with multiple workspaces properly. I suspect the risk here to be low, but we may want to retest this later when that bug is resolved. However, I could test viewing several workspaces (we just couldn't deploy anything per each gitrepo).

Nitpick: the whitespace on the left is quite small both on the columns name bar and for each repo - this is probably just the Vue CSS though and could possibly be a UX decision.
![image](https://user-images.githubusercontent.com/45179589/156454444-19d4d775-48b0-4d4b-8ab9-86d75df02c57.png)
Suggest more padding here.

**Closed by davidnuzik** 2022-03-02 21:46 UTC
Labels: area/fleet, [zube]: QA Working, kind/enhancement, team/area3

**Comment by jtravee** [comment] 2022-03-16 22:29
Confirmed with @catherineluse and @gaktive to add `release note` label.
