### ISSUE TITLE
Installed app detail page does not show related resources while app is being deployed

### ISSUE THREAD

**Issue by bashofmann** [rancher/dashboard#3401] opened 2021-07-06 14:57 UTC
While an app is being deployed, the Installed app detail page does not show the related resources of the helm installation:

![Bildschirmfoto 2021-06-30 um 12 10 03](https://user-images.githubusercontent.com/243056/124621926-f43dcf80-de7a-11eb-860f-b6bef94a852a.png)

The related resources are only displayed, once the app is fully deployed

![Bildschirmfoto 2021-06-30 um 12 13 21](https://user-images.githubusercontent.com/243056/124621991-00c22800-de7b-11eb-87b7-615b1b9eb6b1.png)

It would be great to show the related resources earlier, to make it easier and more obvious why an installation may have failed or is currently stuck and to visualize the progress better.

I'm not sure if this is the right repo, or it should rather be created at rancher/rancher, since the related resources are potentially already filtered out on the backend (https://github.com/rancher/wrangler/blob/master/pkg/summary/cattletypes.go#L31).

**Comment by nwmac** [comment] 2021-09-10 15:02
@jordojordo Can you investigate and learn more here - there is additional work we can do to improve the install experience, once this is done.

**Comment by Auston-Ivison-Suse** [comment] 2021-11-04 21:58
**Setup for Reproduction and Validation**
- Rancher versions: v2.6.1 (repro) and v2.6-head[ea7823e] (validate)

**Steps for Reproduction**
1. Go to local cluster from hamburger menu
2. Go to Apps & Marketplace --> charts
3. Install Monitoring. 
4. Land on "installed apps" page and wait for the "rancher-monitoring-crd" to install and click on "rancher-monitoring"
5. You will see the following.

5a. Reproduction of the issue. 
 ![Screen Shot 2021-11-04 at 2.45.25 PM.png](https://zube.io/files/rancher/6f54eaaf30232e04e89484248a614895-screen-shot-2021-11-04-at-2-45-25-pm.png)

5b. Validated the fixed intended result.
![Screen Shot 2021-11-04 at 3.11.18 PM.png](https://zube.io/files/rancher/551f0137e4a534c285b8fe4fa3ea8039-screen-shot-2021-11-04-at-3-11-18-pm.png)

**Comment by sowmyav27** [comment] 2021-11-15 18:53
Reopening to check whether the UI banner/info goes away when the app finishes installation and the resources are displayed.

**Closed** 2021-11-22 05:46 UTC
Labels: [zube]: QA Working
