### ISSUE TITLE
Events table in cluster dashboard is being replaced with monitoring alerts table

### ISSUE THREAD

**Issue by igor-feoktistov** [rancher/dashboard#4911] opened 2022-01-12 21:16 UTC
**Detailed Description**
When monitoring is enabled in downstream cluster, events table in cluster dashboard is being replaced with monitoring alerts table.

**Context**
For platform administrators it would be nice to have events table in cluster dashboard page, perhaps as a tab, similarly to 2.5.*. This would give simple and brief overview of entire cluster.

**Comment by richard-cox** [comment] 2022-01-13 08:56
This issue came from a conversation between @igor-feoktistov and myself on slack. The events table still has value on the cluster dashboard page even after monitoring has been enabled. The ask here is to show both events and monitoring alerts in horizontal tabs. If there are no performance or ui patterns broken I think this would be a good one to do. @nwmac Could be 'first issue' worthy?

**Comment by nwmac** [comment] 2022-02-14 20:40
This is duplicate of #4911

**Comment by davidnuzik** [comment] 2022-03-02 00:15
**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.3
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.9+rke2r1
 
**Reproduction steps:**

1. Create a downstream cluster. View the cluster dashboard. Take note of the events table, like pictured below.

![image](https://user-images.githubusercontent.com/45179589/156230162-a1a3b220-4268-4e45-8b32-42b90af5b442.png)

2. Now, deploy the Monitoring app. Wait for the helm chart to finish installing. Now view the cluster dashboard again. The events table is now missing (I successfully reproduced this issue).

![image](https://user-images.githubusercontent.com/45179589/156230745-457ad8eb-e965-4b2e-9eb1-57b921caad39.png)
 
-----
 
**Validation Environment:**

Rancher version: v2.6-head `1d2b746` 3/1/2022
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke2
Downstream K8s version: v1.21.10+rke2r1
 
**Validation steps:**

1. Create a downstream cluster. View the cluster dashboard. The events table is shown.
2. Now, deploy the Monitoring app. Wait for the helm chart to finish installing. Now view the cluster dashboard again. The events table is now shown - prior to the fix the events table was hidden and replaced by the monitoring charts. Now both are shown, like pictured below :) 
 
![image](https://user-images.githubusercontent.com/45179589/156270417-f9d70f2e-2ce7-4d81-b2d5-695a99cf6b2c.png)


**Additional Info:**
Took a while to validate this one because looks like there is a bug on v2.6-head with latest monitoring chart. Dev are aware of it and fixing. Does not affect any released versions of Rancher.

**Closed by davidnuzik** 2022-03-02 00:15 UTC
Labels: kind/bug, internal, area/monitoring, [zube]: QA Working, priority/1, team/area3
