### ISSUE TITLE
Update app results in blank page

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#8841] opened 2023-05-10 20:39 UTC
Internal reference: SURE-6281
Reported in 2.7.3

When install or upgrade version of a service from Cluster tools (Ex: Longhorn). Click on Edit button but it shows nothing without errors. 

This was thought to have been resolved by https://github.com/rancher/dashboard/issues/7808 (internal reference: SURE-5732) but upon upgrading to 2.7.3, this is still an issue. It seems the initial prefix is not the case here.

History:
The user started with Rancher 2.5.7, which had the "Import existing" button in cluster management.
All clusters imported with it had the name: `"c-m-...."` (kubectl get clusters.management.cattle.io).

This button disappeared in Rancher 2.5.8 / 2.5.9, so that a downstream cluster had to be created using the "Create" button. All downstream clusters created with it were given the name `"c-xxxx"` and were also visible in "`kubectl get clusters.rancher.cattle.io -A"`.
A total of 5 out of 13 downstream clusters were affected.

Later, in Rancher 2.6.x, the "Import existing" button came back.

Workaround:
In our opinion, the ultimate solution: 
- delete the affected downstream clusters in the cluster management and import them again.
Before: save Projects/Namespaces/Permissions.
After that: restore everything saved before.

Now none of the downstream clusters have any problem installing or upgrading the apps.

Reference PR: https://github.com/rancher/dashboard/pull/7952

**Comment by gaktive** [comment] 2023-05-17 15:12
From @richard-cox:
> Clusters that were created via `Create --> Custom` in Rancher 2.5.8/2.5.9, after upgrading to 2.7.3, show the issue
> The issue is seen when trying to install a chart via Cluster Tools --> `Install` and a blank page is shown

**Comment by Sean-McQ** [comment] 2023-06-21 14:37
Created a 2.5.10 cluster and created a custom cluster

upgraded to 2.6.4 > 2.6.7 > 2.6.9 > 2.6.10 > 2.6.11 > 2.7.3

attempted to install both Monitoring and Longhorn on custom cluster but was unable to reproduce the blank screen although I am seeing some warnings in the console about missing crd's `Resource error [cluster] batch.job : notifier watch error: jobs.batch "rancher-monitoring-crd-create" not found: jobs.batch "rancher-monitoring-crd-create" not found` but since the described error never occurred it's impossible to know if that's relevant to the issue.

**Comment by gaktive** [comment] 2023-07-26 15:13
@richard-cox to sync with someone with an environment seeing this tomorrow.

**Comment by richard-cox** [comment] 2023-07-27 13:12
Setup 
- local cluster. kube version (unknown). rancher version 2.7.5 (upgraded sequentially from an older versions)
- downstream cluster #1 - rke1. kube version 1.25. created by Rancher from older version
- downstream cluster #2 - rke2. kube version 1.25. created by Rancher from current version

Issue #1
- Clicking edit on an existing Monitoring install takes user to a blank `install` page
  - This is caused by the monitoring chart in question containing annotations which are not valid (target cluster kube version too high, rancher version too high)
  - There is a message in the console that states the version cannot be found (misleading, as it was found but was invalid)
- Solution - UI needs to show specific message when the requests chart + version are not compatible with the cluster (rancher version, node os, etc)

Issue #2
- Clicking install on Alert Manager takes user to a blank `install` page
- The version is the latest. The chart's annotations are valid for the cluster. There are no failed network requests. There are no errors or warnings in the console.
- Issue is seen on ds cluster #1 only (local and ds cluster #2 are fine)
- There must be some missing metadata in a cluster resource that is required by the chart. This metadata is probably added on import (workaround)
- Workaround - delete cluster from rancher and import again (not a viable solution)
- Next Steps - We need to deep dive in code, work out what other scenarios could lead to the blank page and confirm with customer. If this fails we need to consult team Neo to understand what might be missing from an old RKE1 cluster provisioned on older ranchers that would be there when imported anew

**Comment by richard-cox** [comment] 2023-08-02 10:56
@gaktive The PR referenced won't fix this, it will provide us some better insight into the area where the issue is. I'm working with the customer to manually try to work this out, and hopefully find a fix before then though.

**Comment by gaktive** [comment] 2023-08-15 21:12
@richard-cox we got an update: the user "confirms the no matches for kind "PodSecurityPolicy" in version "policy/v1beta1" issue is resolved using the documented procedure."

**Comment by richard-cox** [comment] 2023-08-25 17:52
Debug build did actually resolve their issue and PSP migration steps resolved the users issue.

Issue revolved around a failure to fetch a cluster container registry. That exception is now handled. 

Given how challenging this is to re-create / test i'll close this issue

**Closed by richard-cox** 2023-08-25 17:52 UTC
Labels: kind/bug, [zube]: Working, priority/1, team/area3, status/needs-info, size/2, JIRA
