### ISSUE TITLE
vSphere CPI and CSI charts are not visible in rancher/charts and independent rancher/vsphere-charts repos.

### ISSUE THREAD

**Issue by vivek-infracloud** [rancher/dashboard#5269] opened 2022-03-02 10:00 UTC
**Setup**
- Rancher version: v2.6.4-rc6
- Browser type & version: Issue is not browser specific.

**Describe the bug**

vSphere CPI and CSI chart from the `rancher/charts` and  independent `rancher/vsphere-charts` repos are not visible in UI.

**To Reproduce**

- Create a rancher server v2.6.4-rc6.
- Provision a RKE1 or RKE2 vsphere node driver k8s cluster (v1.23).
- vSphere CPI and vSphere CSI charts are not visible with Rancher charts repo selected.
- Navigate to Chart Repositories.
- Add independent vsphere-charts repo in the Apps and Marketplace repositories.
- Go to charts again and select vsphere charts repo from the dropdown.
- Note that the vSphere CPI and vSphere CSI charts are not visible.

**Result**
**vsphere CPI and CSI chart won't be visible in the UI**

**Expected Result**
vsphere CPI and CSI chart is visible in the UI and possible to install.

**Screenshots**
![rancherrepo-cpi-csi-charts](https://user-images.githubusercontent.com/83208989/157233810-b3281969-9202-49eb-bbd8-e890664deb3d.png)

![cpi-csi-chart](https://user-images.githubusercontent.com/83208989/157230730-174ad3a3-66da-4e74-abf2-ba4edd81bed9.png)

**Comment by samkulkarni20** [comment] 2022-03-03 05:12
@MKlimuszka @SheilaghM Can you pls help get this issue assigned? We have seen this on 2.6-head & would be needed for v2.6.4 release.

**Comment by gaktive** [comment] 2022-03-03 17:51
Sounds similar to https://github.com/rancher/dashboard/issues/5192, which is presently in QA's hands. 

@samkulkarni20 @MKlimuszka @SheilaghM -- can one of you take a look there and see if this is the case? This would be a duplicate if so.

**Comment by gaktive** [comment] 2022-03-03 18:01
Upon investigation, it's not a dupe but it's like not UI. @codyrancher to provide details before we transfer this.

**Comment by samkulkarni20** [comment] 2022-03-03 19:11
@codyrancher here's the complete json response:
```
{
  "apiVersion": "v1",
  "generated": "2022-03-03T19:03:15.577657339Z",
  "entries": {
    "rancher-vsphere-cpi": [
      {
        "name": "rancher-vsphere-cpi",
        "sources": [
          "https://github.com/kubernetes/cloud-provider-vsphere"
        ],
        "version": "1.1.0",
        "description": "vSphere Cloud Provider Interface (CPI)",
        "keywords": [
          "infrastructure"
        ],
        "maintainers": [
          {
            "name": "Rancher",
            "email": "caleb@rancher.com"
          }
        ],
        "icon": "https://172.16.133.198/v1/catalog.cattle.io.clusterrepos/vsphere?chartName=rancher-vsphere-cpi&link=icon&version=1.1.0",
        "apiVersion": "v1",
        "appVersion": "1.1.0",
        "annotations": {
          "catalog.cattle.io/certified": "rancher",
          "catalog.cattle.io/display-name": "vSphere CPI",
          "catalog.cattle.io/kube-version": ">= 1.18.0-0 < 1.23.0-0",
          "catalog.cattle.io/namespace": "kube-system",
          "catalog.cattle.io/os": "linux",
          "catalog.cattle.io/permits-os": "linux,windows",
          "catalog.cattle.io/rancher-version": ">= 2.6.0-0 <= 2.6.100-0",
          "catalog.cattle.io/release-name": "vsphere-cpi"
        },
        "urls": [
          "https://172.16.133.198/v1/catalog.cattle.io.clusterrepos/vsphere?chartName=rancher-vsphere-cpi&link=chart&version=1.1.0"
        ],
        "created": "2022-03-03T19:03:15.583235132Z",
        "digest": "d1c654f1f6647eefdd6b8654b1e7d3e9b395af583612b64913b5e446714fb580"
      }
    ],
    "rancher-vsphere-csi": [
      {
        "name": "rancher-vsphere-csi",
        "sources": [
          "https://github.com/kubernetes-sigs/vsphere-csi-driver"
        ],
        "version": "2.4.1-rancher1",
        "description": "vSphere Cloud Storage Interface (CSI)",
        "keywords": [
          "infrastructure"
        ],
        "maintainers": [
          {
            "name": "Rancher",
            "email": "caleb@rancher.com"
          }
        ],
        "icon": "https://172.16.133.198/v1/catalog.cattle.io.clusterrepos/vsphere?chartName=rancher-vsphere-csi&link=icon&version=2.4.1-rancher1",
        "apiVersion": "v1",
        "appVersion": "2.4.1-rancher1",
        "annotations": {
          "catalog.cattle.io/certified": "rancher",
          "catalog.cattle.io/display-name": "vSphere CSI",
          "catalog.cattle.io/kube-version": ">= 1.19.0-0 < 1.23.0-0",
          "catalog.cattle.io/namespace": "kube-system",
          "catalog.cattle.io/os": "linux",
          "catalog.cattle.io/permits-os": "linux,windows",
          "catalog.cattle.io/rancher-version": ">= 2.6.0-0 <= 2.6.100-0",
          "catalog.cattle.io/release-name": "vsphere-csi"
        },
        "urls": [
          "https://172.16.133.198/v1/catalog.cattle.io.clusterrepos/vsphere?chartName=rancher-vsphere-csi&link=chart&version=2.4.1-rancher1"
        ],
        "created": "2022-03-03T19:03:15.589193911Z",
        "digest": "676cfee6d60dca5be4d881827fc7540738daaadbb1bf1c9be6d73305a7099a22"
      }
    ]
  }
}
```

**Comment by samkulkarni20** [comment] 2022-03-03 19:39
@codyrancher Upon comparing the CPI chart response object above with CSI response object, I don't see any major differences. You can try this yourself by adding [vsphere-charts repo](https://github.com/rancher/vsphere-charts/) main branch to the `apps & marketplace` repositories list.

**Comment by codyrancher** [comment] 2022-03-07 04:35
@samkulkarni20 sorry for the late response. I've been battling networking issues since Friday.

Anyway, I did some digging and I found out what the issue is. It's the version that CSI is using. That version is considered a pre-release so it's filtered out of the displayed charts. We need to get this to the appropriate backend team to resolve this specific issue.

![image](https://user-images.githubusercontent.com/55104481/156968514-b5cc5200-980b-418f-a84e-7983a53d6d37.png)

**Comment by samkulkarni20** [comment] 2022-03-07 04:43
@codyrancher do you mean versioning scheme used with CSI i.e. `2.4.1-rancher1` is considered pre-release by UI? If yes, can you provides some insights into that decision?
_Note: This is how the CSI chart versions will look like going forward._

**Comment by codyrancher** [comment] 2022-03-07 13:45
@samkulkarni20 that's what I mean.

If the version is not a valid semver or a semver pre-release it's considered a pre-release. https://github.com/rancher/dashboard/blob/master/utils/version.js#L68-L74. 

If you're wanting to know why non-semver was decided to be a pre-release I don't have the answer. To me it seems reasonable since we should follow semver for production.

**Comment by codyrancher** [comment] 2022-03-07 14:06
An additional note. You can show pre-releases by toggling a user preference 
![image](https://user-images.githubusercontent.com/55104481/157049413-187fd2ea-b270-4fbb-8b8b-4c86769087c3.png)

**Comment by samkulkarni20** [comment] 2022-03-07 14:29
Thanks @codyrancher for the insights. 

> ~~Note: This is how the CSI chart versions will look like going forward.~~

`2.4.1-rancher1` is the upstream chart version for `rancher/charts` repo. The version that Apps & Marketplace would release would look like `100.2.0+up2.4.1-rancher1` which is a valid semver & won't have this issue. So IMO we're good here. 

@vivek-infracloud can you test if CSI chart is visible in UI, if you add the dev `rancher/charts` [repo](https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-vsphere-csi) in Apps & Marketplace, since the new version is now merged?

**Comment by vivek-infracloud** [comment] 2022-03-07 15:19
@samkulkarni20 The new CSI chart version `100.2.0+up2.4.1-rancher1` is visible in `rancher/charts` repo in Apps & Marketplace.

**Comment by codyrancher** [comment] 2022-03-07 18:00
@samkulkarni20 since it's visible are you okay to close this or do we want to move this To Test?

**Comment by PennyScissors** [comment] 2022-03-07 19:22
I don't think this was ever an issue because the charts in rancher/vsphere-charts are not supposed to be used standalone. What's important is that the new CPI and CSI charts in rancher/charts which are currently pointing to rancher/vsphere-charts are visible in the UI, and I don't think that will be a problem because if it was a problem it would've been captured at the PR level.

**Comment by samkulkarni20** [comment] 2022-03-08 04:03
@vivek-infracloud verified that the CSI chart in `rancher/charts` is visible. That is a good enough, since upstream repo will not be used directly. We can close the issue.
CC: @codyrancher

**Comment by vivek-infracloud** [comment] 2022-03-08 11:59
**Updated the issue.** 

### Now vsphere CPI and CSI charts are not visible in `rancher/charts` repo as well on rancher v2.6.4-rc6.

**Comment by deniseschannon** [comment] 2022-03-16 21:04
Validate by:

* Install a RKE1 cluster - Is the vsphere CPI/CSI chart visible in Apps & Marketplace?

**Closed** 2022-03-25 22:13 UTC
Labels: internal, status/dev-validate, [zube]: QA Working, status/release-blocker, team/area4
