### ISSUE TITLE
When creating a resource, limit the namespace options based on filters in top nav

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6094] opened 2022-06-02 23:12 UTC
Internal reference: SURE-4311
Reported in 2.6.3

Issue description:

When creating a new workload in the new 2.6 UI, the "namespace" dropdown has no option for creating a new namespace. The 2.5 UI allows this, with a clickable link under the namespace dropdown that lets the user specify a new namespace for the workload.

Additionally, the namespace dropdown lists namespaces that aren't even in the selected project filter! This is very confusing for users, especially new ones that are not very familiar with Kubernetes yet.

Repro steps:

- Filter by project
- Create a new deployment in that project
- No option to create a namespace at the time of creating the deployment
- All namespaces are shown in the drop down for namespaces (even those not in the project).

Workaround:
Create a namespace separately, filter through list to find namespace

**Comment by catherineluse** [comment] 2022-07-11 22:46
There's two work items in this - one item is to limit the namespace options to the actively selected namespaces in the top nav, and one to allow creating a namespace in the workload form.

The second one has already been completed and will be in v2.6.7: https://github.com/rancher/dashboard/issues/2513

So I think this issue should be edited to be just about limiting the namespace options when creating a resource.

**Comment by catherineluse** [comment] 2022-07-11 23:48
There's also a UX question here - If you have a single project selected in the top nav, and you create a new namespace, should it automatically be created in the selected project?

What if you have more than one project selected? Should you be prompted to pick a project?

**Comment by kwwii** [comment] 2022-10-21 03:29
Maybe we can make them visually different in the dropdown (but still selectable?)

**Comment by kwwii** [comment] 2023-02-21 15:42
The current UI allows the user to create a new namespace directly when creating a workload so I am marking this as done.

**Comment by nwmac** [comment] 2023-02-23 14:09
@kwwii Re-opening - the remaining work here was that the namespace dropdown always shows all namespaces and does not restrict itself to the global project/namespace filter.

**Comment by cnotv** [comment] 2023-02-27 17:25
I also found this overwhelmingly annoying while testing the PSA namespace, as I could not seen only mine or under the project PSA.
A similar issue is also related to this enhancement: https://github.com/rancher/dashboard/issues/8031

**Comment by cnotv** [comment] 2023-03-13 08:57
Cases to be considered:
- System filter by preferences
- Harvester
- Fleet namespaces
- Mapping and other props
- Existing namespace state

**Comment by cnotv** [comment] 2023-03-13 09:00
@kwwii Something which is worth investigate for the UX is what to do with filtering the namespaces by namespaces.
It kinda makes sense by project or by category, although by single namespace is kinda odd.

Example:

![Screenshot 2023-03-13 at 09 58 26](https://user-images.githubusercontent.com/5009481/224653963-ae263425-5b16-4f7d-bfa2-4615c59db8d4.png)
![Screenshot 2023-03-13 at 09 58 31](https://user-images.githubusercontent.com/5009481/224653969-53e822e6-3f12-4477-b679-a106b9e20746.png)

**Comment by cnotv** [comment] 2023-03-13 14:45
@nwmac @kwwii There's a conflict between the namespace filter from the top navigation and the user preferenc. This happens also in the list of the Namespace resources list. Moreover that option seems to be used exclusively for the dropdown which we are updating.
Should we deprecate the user preference in this case? If a user picks the filter `Only system Namespaces` and we are filtering them, what are we supposed to do?

This is the current behavior for the resources, were nothing changes:

https://user-images.githubusercontent.com/5009481/224735835-c5ee68f4-5e24-4220-a105-6253dfbd1f6e.mov

**Comment by richard-cox** [comment] 2023-04-25 13:48
Unfortunately i didn't dive in to this at the time. It's really useful to be able to create resources outside of the namespaces in the filter. I've created an issue to enhance this feature with a toggle to allow this - https://github.com/rancher/dashboard/issues/8736

**Comment by aganesh-suse** [comment] 2023-05-17 21:45
Rancher build v2.7-head with commit: 
![image](https://github.com/rancher/dashboard/assets/129900588/320f6727-79f9-40c4-98e0-f2117a7e2959)

Based on what is selected on the top nav -> "Only system namespaces" / "Only User namespaces" / Particular namespce "test1", say,
From the Explore Cluster -> Workloads -> Create page, we can see only that drop down, or individual namespace selected. 
![Screenshot 2023-05-17 at 1 49 02 PM](https://github.com/rancher/dashboard/assets/129900588/a58a7c00-ce00-4757-896b-7bb758633d5c)
![Screenshot 2023-05-17 at 1 48 36 PM](https://github.com/rancher/dashboard/assets/129900588/d4058e5d-60dc-4edb-8fb2-9985c758a2a8)
![Screenshot 2023-05-17 at 1 48 06 PM](https://github.com/rancher/dashboard/assets/129900588/856b3716-3ef0-486f-bc79-c1713d80981d)

Also, tested user permissions/roles/preferences.
1. created different users with permissions to particular project/namespace with create namespace/manage workloads and view workloads permissions,
2. with preferences to show/not show system namespaces, and saw, only those user namespaces they had permission for, was listed for the navigation for said user, and choosable.(assuming user has cluster permissions - else they cant see system namespaces, even if the preference was selected - which am assuming is as designed)


Noticed some descrepancies in a few places that am noting here: 
1. namespace for projects user was not provided access to get listed in the top nav - but the actual create workload fails with that namespace, saying they dont have permission. Was not sure if this is as designed.  
2. Create/Edit Project page for user/role add, lists all selected roles. Same user and roles can be added multiple times. There seem to be a lot of duplicate rows created - with user/role combination.

**Comment by richard-cox** [comment] 2023-05-24 08:01
> namespace for projects user was not provided access to, get listed in the top nav - but the actual create workload fails with that namespace, saying they dont have permission. Was not sure if this is as designed.

This is a separate problem. Can you create a GH issue for 2.7Q3?

> Create/Edit Project page for user/role add, lists all selected roles. Same user and roles can be added multiple times. There seem to be a lot of duplicate rows created - with user/role combination.

Only one row per binding should be shown, but multiple bindings for the same user/group is currently allowed. Can you create GH issue for 2.7Q3 requesting that we block the creation of duplicate user/group - role bindings?

**Comment by aganesh-suse** [comment] 2023-05-24 15:23
Created an enhancement/feature request ticket for v2.7next3 milestone. https://github.com/rancher/dashboard/issues/8973

**Closed** 2023-05-24 16:53 UTC
Labels: kind/bug, [zube]: Review, JIRA, team/rke2-qa
