### ISSUE TITLE
`404 page not found` error when performing `Edit YAML` on RKE cluster

### ISSUE THREAD

**Issue by thehejik** [rancher/dashboard#4051] opened 2021-08-27 08:43 UTC
Seen on `rancher/rancher:v.2.6-head 6d10a6d`

When I entered initialy a wrong name of my DO RKE1 cluster I went to `Edit YAML` for the cluster and modified `DisplayName` value in the YAML but after pressing `Save` button an error was displayed and the value wasn't changed (it worked in `Edit Config`)

I was doing provisioning of DO RKE1 cluster and also `Edit YAML` as a `Standard User` (Owner of the Cluster). Anyway the same happens when I switch to `admin` account.

```
{ "data": "404 page not found\n" }
```

![error-saving-yaml](https://user-images.githubusercontent.com/12828077/131099262-3e671a48-899d-4353-97c1-2b456f8b4e04.png)

**Comment by ronhorton** [comment] 2021-10-20 18:50
I was able to reproduce this in 	v2.6-a2ae06ce4da1f2a8f10c9901d2295c860a4e6aca-head by:
1. click on users & authentication in left menu
2. click roles
3. on the global tab, click the three dot menu of an active role
4. select edit yaml
5. click 'save'

**Comment by neillsom** [comment] 2021-11-10 03:57
@ronhorton This appears to be working for editing roles yaml. Do you see the issue persisting anywhere else?

**Comment by ronhorton** [comment] 2021-11-15 17:22
The 404 error is still occurring in `2.6-head Commit ID 78b25c3`

1. create rke1 cluster
2. go to cluster management page
3. click on 3 dots on the cluster row on cluster management page
4. select `edit yaml`
5. click `save`

!<img width="1603" alt="Screen Shot 2021-11-15 at 12 16 22 PM" src="https://user-images.githubusercontent.com/89212856/141825803-6bea7750-a6fa-4136-a74c-2d59a8c04438.png">

**Comment by ronhorton** [comment] 2021-11-15 20:19
I am also still seeing this issue when editing the yaml for a role

1. click on users & authentication in left menu
2. click roles
3. on the global tab, click the three dot menu of an active role
4. select edit yaml
5. click 'save'

**Comment by gaktive** [comment] 2021-11-19 17:16
WIth Neill out, Nancy to look. Vince can help with some of the API fun.

**Comment by snasovich** [comment] 2021-11-19 18:15
Not sure if it will be indirectly fixed by this, so feel free to open a separate issue on this.

As soon as user clicks "Edit as YAML" on Cluster Management for any cluster, the URL changes from `/dashboard/c/(cluster-id)/manager/provisioning.cattle.io.cluster` to `/dashboard/c/c-pvrx9/manager/management.cattle.io.cluster/c-hsjld?mode=edit&as=yaml` and if they "Cancel" on this YAML editing screen they get back to `/dashboard/c/c-pvrx9/manager/management.cattle.io.cluster` which means the user is now in "Mgmt Cluster" node which looks very similar to the "Clusters" but users cannot make changes to clusters there. This is very confusing.
![image](https://user-images.githubusercontent.com/85187633/142671234-6294bb6b-abb2-4737-895e-bf9d44e9277b.png)

**Comment by mantis-toboggan-md** [comment] 2021-11-19 18:24
Thanks for calling attention to that @snasovich, that is something we can address as part of this ticket.

**Comment by snasovich** [comment] 2021-11-19 18:27
@mantis-toboggan-md , thank you. Actually, I just noticed than after cancelling it "Mgmt Clusters" tree node is not actually shown/selected making it even more confusing. My screenshot above seems to be from me finding it that node manually.

See video below:
https://user-images.githubusercontent.com/85187633/142672783-2d76902b-d70e-4222-a9dc-97f5532f98ca.mov

**Comment by swill** [comment] 2021-11-29 22:28
Is there a way to work around this in any way?  I need to add/update roles and I am currently unable to through the Rancher UI, so I am blocked.  While this is still open, can we provide a workaround for updating the running config so we can progress?  Thanks...

**Comment by ronhorton** [comment] 2021-11-29 22:44
**PASS** Verified in `2.6-head Commit ID 4375161`

The 404 reported in this bug can no longer be reproduced. The `Edit YAML` feature has been replaced by `View YAML`.

1. create rke1 cluster
2. go to cluster management page
3. click on 3 dots on the cluster row on cluster management page
Result: `View YAML is the YAML option. User can still Edit Config`
:![Screen Shot 2021-11-29 at 5.38.57 PM.png](https://zube.io/files/rancher/7640a34dad01b0304b357c4d7c88538f-screen-shot-2021-11-29-at-5-38-57-pm.png)
Also verified in other instances of app where `Edit YAML` was previously available. Now `View YAML` appears. Example, Roles
![Screen Shot 2021-11-29 at 5.38.37 PM.png](https://zube.io/files/rancher/4dfa208bee96fd92dd6b61d0e95c36e0-screen-shot-2021-11-29-at-5-38-37-pm.png)

**Comment by ronhorton** [comment] 2021-11-29 23:14
> Is there a way to work around this in any way? I need to add/update roles and I am currently unable to through the Rancher UI, so I am blocked. While this is still open, can we provide a workaround for updating the running config so we can progress? Thanks...

The config is editable (if I'm understanding your comment). Adding/Updating roles is still available. What's changed is the Edit YAML option is now a View YAML option.

**Comment by dnoland1** [comment] 2021-11-29 23:15
@ronhorton you mentioned - "The Edit YAML feature has been replaced by View YAML." This sounds like a problem. How do you edit YAML for a k3s imported cluster?

**Closed** 2021-11-29 23:15 UTC
Labels: [zube]: Done, internal, kind/bug-qa

**Comment by swill** [comment] 2021-11-30 00:19
@ronhorton I don't believe you completed the test to reproduce this (based on the screen shots).

Navigate to: `Menu > Users & Authentication > Roles > Project Member`
On this screen you will see something like this.

This is a view screen:
![image](https://user-images.githubusercontent.com/13644/143961667-c9380f27-6c09-4151-953f-669e63e4b461.png)

This is the config view screen:
![image](https://user-images.githubusercontent.com/13644/143961730-4fd2115b-2e49-4a6a-92b5-a7ae7895a13e.png)

If you go to `Edit Config`, you get this screen where you can still edit the config:
![image](https://user-images.githubusercontent.com/13644/143961817-ce5dcd74-dbf7-408a-8edc-7185a134b932.png)

This is the edit config screen:
![image](https://user-images.githubusercontent.com/13644/143962045-78cf9c0f-1ef4-49b5-a61a-b719a5f91852.png)

Now, this is where one of my problems is (but not specific to this bug, I need to create another).
If I want to enter this config into this config screen through the UI, I can't.  
```
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  verbs:
  - '*'
```

So...  I need to add this configuration...

So now, to reproduce the bug referenced in this issue, do the following.

Navigate to `Users & Authentication > Roles > Project Member`:
![image](https://user-images.githubusercontent.com/13644/143962667-5969ab0d-3cc4-4a1f-a63f-aa87de24a8ee.png)

Now go to the 3 dots, and go to `Edit YAML`.  You get a page like this.
![image](https://user-images.githubusercontent.com/13644/143962724-2df22dc8-0c41-4955-8b2d-672f880177ee.png)

Now go to the bottom of the page, without changing anything, and click on `Save`.
![image](https://user-images.githubusercontent.com/13644/143962788-5f934c5d-d388-4d0a-96e6-14c5687a589f.png)

You have now produced the error...

And I, well I can't get my roles applied.  :(

I would appreciate if this issue can be reopened, unless it can be shown to be fixed at head and is scheduled for release.  My team has reproduced this issue on a number of screens.  Another one was the cluster config, with basically the same steps to reproduce.

**Comment by swill** [comment] 2021-11-30 00:30
> @ronhorton you mentioned - "The Edit YAML feature has been replaced by View YAML." This sounds like a problem. How do you edit YAML for a k3s imported cluster? Need to be able to edit YAML for a cluster.

If I go to the `Edit Config` screen:
![image](https://user-images.githubusercontent.com/13644/143963583-6e747e96-571e-42f7-8c17-f7c7cc64e220.png)

I can change the values:
![image](https://user-images.githubusercontent.com/13644/143963632-8538808c-e516-4814-bd65-80da2c00abfb.png)

If you save the change, it completes with a green pulse in the button, but then if you review the config, the config is not updated:
![image](https://user-images.githubusercontent.com/13644/143963761-569aa92f-205c-42c7-8f02-d9c5229f1df1.png)

Its like nothing happened.

**Comment by swill** [comment] 2021-11-30 03:29
> > Is there a way to work around this in any way? I need to add/update roles and I am currently unable to through the Rancher UI, so I am blocked. While this is still open, can we provide a workaround for updating the running config so we can progress? Thanks...
> 
> The config is editable (if I'm understanding your comment). Adding/Updating roles is still available. What's changed is the Edit YAML option is now a View YAML option.

Neither edit functionality is actually working.  If you save the `Edit Config` the save doesn't actually save, even though it shows that it does with the green button background.  If you `Edit YAML` you will get the 404 when you try to save.  There is currently no way to save configurations.  This is a major bug IMHO.

**Comment by swill** [comment] 2021-11-30 13:33
@ronhorton I am testing on `master`, `head-ada992ce8d8b8f65acaf1d2941916b3acd77faec` and the regression is even worse than I expected.

**First:**
The option of `Edit YAML` is completely missing now.
![image](https://user-images.githubusercontent.com/13644/144053515-730b6709-0633-4995-99ae-4dcb8c58aca4.png)

**Second:**
The `Edit Config` does not appear to be working.
As above, I am on the `Project Member` role.  If I try to edit a role to simply add a verb, I get the following.

Original:
![image](https://user-images.githubusercontent.com/13644/144053774-9eb737f8-52c2-4bdb-9951-40f4ea1af2c4.png)

Updated:
![image](https://user-images.githubusercontent.com/13644/144053852-dd532c98-eada-486d-a457-617e301ed9b8.png)

Click save, the status says it saved.
Result:
![image](https://user-images.githubusercontent.com/13644/144054021-75c901bb-0454-4c92-abe9-3b9d3c4d1622.png)

The changes did not get saved.  Now that the `Edit YAML` functionality has been removed, the functionality is entirely broken now because `Edit Config` is not even functional.

**Third:**
Introducing new config is completely broken now.

I am using the `spark-operator` to produce `SparkApplications`.
![image](https://user-images.githubusercontent.com/13644/144054835-5c32acbb-828a-4e76-b3a8-71f66675c51b.png)

On install, a regular user can't create a `SparkApplication` because they don't have permission:
```
failed to list sparkoperator.k8s.io/v1beta2, Kind=SparkApplication for 8d5ef686-55c8-468c-bc42-acf9fd368b3a: sparkapplications.sparkoperator.k8s.io is forbidden: User "u-8njnv" cannot list resource "sparkapplications" in API group "sparkoperator.k8s.io" at the cluster scope
```
That is expected because this user has not been given permission through the roles yet.

So, I navigate to: `Menu > Users & Authentication > Roles > Project/Namespaces`
and I click on the `Project Member` role.
In the 3 dots, I click on `Edit Config`
I scroll to the bottom and click on `Add Resource`

I want to add add the following details to this role:
```
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  verbs:
  - '*'
```

I can add the `apiGroups`, but I can't actually specify the `sparkapplications` in the dropdown for **Resources** because for some reason, even though this resources is currently running within the cluster, Rancher has not discovered it and the UI won't let an "unknown" resource be added.

with the removal of the `Edit YAML` functionality, there is a HUGE regression in functionality making the UI a HUGE liability.

This is a massive issue and **MUST NOT BE RELEASED LIKE THIS** in `v2.6.3` or there will be major problems for the majority of the user base.  Please reopen this ticket until there is a solution to this problem.

**Comment by swill** [comment] 2021-11-30 13:37
Additionally, it does appear that `Edit YAML` is available on the cluster as well.  Again, this is a HUGE regression as the `Edit Config` does not provide the same functionality that `Edit YAML` provided.

![image](https://user-images.githubusercontent.com/13644/144057220-b7a36a0c-9ef5-42cd-8a3a-5d61158e9b81.png)

**Comment by mantis-toboggan-md** [comment] 2021-11-30 15:00
> First:
> The option of Edit YAML is completely missing now.

The 'edit yaml' option was intentionally removed from a handful of resources fairly recently [(here)] (https://github.com/rancher/dashboard/pull/4481) but the functionality didn't work in 2.6.0 either; due to some eleventh-hour security concerns with the api the dashboard is primarily using, we did some under-the-hood shuffling to fix the 'edit config' forms, but updating the 'edit yaml' functionality will take significantly more time so we opted to disable it for 2.6.3.  If the edit config functionality for these resources is also broken that is indeed something we want to get fixed more quickly.

re: Editing RKE1 cluster yamls, this is still possible through their 'edit config' screen:
![Screen Shot 2021-11-30 at 7 53 34 AM](https://user-images.githubusercontent.com/42977925/144070332-22fb6bc6-c8a1-4d81-88ca-44ba9f634a75.png)

> Second:
> The Edit Config does not appear to be working.
> As above, I am on the Project Member role....
> The changes did not get saved. Now that the Edit YAML functionality has been removed, the functionality is entirely broken now because Edit Config is not even functional.

I'm seeing this as well, but I'm going to file a separate ticket since it's unrelated to the original RKE1 yaml edit issue. It looks like editing the resource grants of built-in roles is disallowed, though neither the UI nor API indicate this. The old UI disables those fields for built in roles, looks like we need to port that functionality to the dashboard. 

> Third:
> Introducing new config is completely broken now.
...
> I can add the apiGroups, but I can't actually specify the sparkapplications in the dropdown for Resources because for some reason, even though this resources is currently running within the cluster, Rancher has not discovered it and the UI won't let an "unknown" resource be added.

I'm able to add arbitrary text to the 'Resource' field by typing into the dropdown and hitting enter: is that not working in your setup? I agree the UX here could be better, just trying to find a workaround for the time being.

**Comment by mantis-toboggan-md** [comment] 2021-11-30 15:13
@swill I've added a ticket to track issues with editing global/project/namespaces roles here #4671, feel free to add your own observations of course. Let me know if my workarounds for adding custom resources and editing rke1 cluster yamls are insufficient.

**Comment by swill** [comment] 2021-11-30 15:25
@mantis-toboggan-md Thank you for the follow up.  I have confirmed (in `v2.6.2` since I don't have the HEAD of the cluster manager ui running locally right now) that if I go to `Edit Config` for a cluster, then click on the `Edit YAML` within the form, and then `Save` the form (with no changes), I do not get the **404** error.  So I think this provides a work around for the editing of the Cluster YAML file.  So thank you for that.

I will test the addition of arbitrary text in the "resource" field again and provide the details in another comment.

**Comment by swill** [comment] 2021-11-30 15:34
@mantis-toboggan-md Thank you again for the detailed follow up on this.

I have been able to add a resource that is not in the list by typing it and then hitting `Enter` as you described in `v2.6.2`.  If you don't hit enter, the dropdown is cleared, so it was not obvious that it was possible to add it by hitting `Enter` after typing it.
![image](https://user-images.githubusercontent.com/13644/144076961-0b22d97a-ef46-40f2-8cfb-7f9907e7c7c1.png)

And I can confirm that by creating a new role, it saves.
![image](https://user-images.githubusercontent.com/13644/144077305-4576d272-2764-4127-8ee9-b0b39452e2d0.png)

I will confirm I am able to add this role to the user and it functions, but in general, this appears to be a workaround for the removal of the `Edit YAML` for the time being.  I will report back with my findings once I do the complete end to end validation.

Thank you very much for your thoughtful support on this.  I will review the other ticket you opened and add any details I feel are missing.

**Comment by swill** [comment] 2021-11-30 15:56
@mantis-toboggan-md for completeness, I wanted to follow up to provide a final update.  On `v2.6.2` I have been able to add the sparkapplication resource to a new cluster role that inherits the default role permissions, which provides the functionality I expected.  Thank you for providing the details around using **Enter** to make the resource entry stay.  :heart:

**Comment by mantis-toboggan-md** [comment] 2021-11-30 16:16
Glad to hear you're able to accomplish what you need to for the time being. Thanks for providing feedback on areas of the UI that are still lacking; I know the whole team appreciates hearing what areas of the dashboard are difficult to use and in need of more attention from us.

**Comment by bor8** [comment] 2021-12-07 07:07
I need `extra_binds` https://rancher.com/docs/rke/latest/en/config-options/services/services-extras/ for NFS + AutoFS + local storage. `v2.6.2` (`Kubernetes v1.21.6`) is buggy, so I updated to `v2.6-da2e59c93300619afd634d1d694117901bcf7aa4-head` - but the update failed - everything started all over again with initialising Rancher. I am back to `v2.5.8-patch3` with Kubernetes `v1.20.11` now.
