### ISSUE TITLE
Unable to open deployed pods with status Pending

### ISSUE THREAD

**Issue by cnotv** [rancher/dashboard#5577] opened 2022-04-05 07:49 UTC
**Setup**
- Rancher version: 2.6.4
- Browser type & version: Chrome

**Describe the bug**
It's not possible to open a deployed pod with status `Pending`.

**To Reproduce**
- Create a deployment
- Create a faulty storage, e.g. recreate a scenario with `0/1 nodes are available: 1 node(s) had no available disk.`

**Result**
View breaks when opening the pod.

**Expected Result**
Detail view of the pod is displayed

**Screenshots**

https://user-images.githubusercontent.com/5009481/161704941-bf6b325a-f5ed-492d-9d21-327d5c1957aa.mp4

**Comment by nwmac** [comment] 2022-04-05 09:46
Fixed in SortableTable perf PR

**Comment by cnotv** [comment] 2022-04-05 11:08
https://github.com/rancher/dashboard/pull/5435

**Comment by cnotv** [comment] 2022-04-05 15:03
Example of Deployment YAML:
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "9"
  creationTimestamp: "2022-04-04T12:45:45Z"
  generation: 9
  labels:
    workload.user.cattle.io/workloadselector: apps.deployment-default-storage
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:replicas: {}
        f:unavailableReplicas: {}
        f:updatedReplicas: {}
    manager: k3s
    operation: Update
    subresource: status
    time: "2022-04-04T16:40:55Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:workload.user.cattle.io/workloadselector: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:workload.user.cattle.io/workloadselector: {}
          f:spec:
            f:affinity: {}
            f:containers:
              k:{"name":"container-0"}:
                .: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"1d13dasd"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"amazon-mount-1"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"amazon-mount-2"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"asdasd"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"asdasdasd"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                  k:{"mountPath":"asdsdasd"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"vol-an58v"}:
                .: {}
                f:name: {}
                f:secret:
                  .: {}
                  f:defaultMode: {}
                  f:optional: {}
                  f:secretName: {}
              k:{"name":"vol-kwmvp"}:
                .: {}
                f:name: {}
                f:nfs:
                  .: {}
                  f:path: {}
                  f:server: {}
              k:{"name":"vol-qb5l7"}:
                .: {}
                f:name: {}
                f:persistentVolumeClaim:
                  .: {}
                  f:claimName: {}
              k:{"name":"vol-qrcry"}:
                .: {}
                f:hostPath:
                  .: {}
                  f:path: {}
                  f:type: {}
                f:name: {}
              k:{"name":"vol-ugcun"}:
                .: {}
                f:awsElasticBlockStore:
                  .: {}
                  f:volumeID: {}
                f:name: {}
    manager: rancher
    operation: Update
    time: "2022-04-04T16:40:55Z"
  name: storage
  namespace: default
  resourceVersion: "13084730"
  uid: bcb59ef0-aad9-47e2-aabd-bb8fef1b1a88
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-default-storage
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-default-storage
    spec:
      affinity: {}
      containers:
      - image: storage
        imagePullPolicy: Always
        name: container-0
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: amazon-mount-1
          name: vol-ugcun
        - mountPath: amazon-mount-2
          name: vol-ugcun
        - mountPath: asdasdasd
          name: vol-an58v
        - mountPath: asdsdasd
          name: vol-qb5l7
        - mountPath: asdasd
          name: vol-qrcry
        - mountPath: 1d13dasd
          name: vol-kwmvp
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - awsElasticBlockStore:
          volumeID: amazon-id
        name: vol-ugcun
      - name: vol-an58v
        secret:
          defaultMode: 420
          optional: false
          secretName: default-token-p7xw4
      - name: vol-qb5l7
        persistentVolumeClaim:
          claimName: persistennt-volume-claim
      - hostPath:
          path: dasdasd
          type: ""
        name: vol-qrcry
      - name: vol-kwmvp
        nfs:
          path: /
          server: /
status:
  conditions:
  - lastTransitionTime: "2022-04-04T12:45:45Z"
    lastUpdateTime: "2022-04-04T12:45:45Z"
    message: Deployment does not have minimum availability.
    reason: MinimumReplicasUnavailable
    status: "False"
    type: Available
  - lastTransitionTime: "2022-04-04T16:50:56Z"
    lastUpdateTime: "2022-04-04T16:50:56Z"
    message: ReplicaSet "storage-cfd9658f7" has timed out progressing.
    reason: ProgressDeadlineExceeded
    status: "False"
    type: Progressing
  observedGeneration: 9
  replicas: 2
  unavailableReplicas: 2
  updatedReplicas: 1
```

**Comment by markusewalker** [comment] 2022-04-20 19:54
Unable to reproduce this on v2.6.4 or v2.6 head https://github.com/rancher/rancher/commit/6bb6e45fba97f58443e547e2f57d2807a424467f.

**ENVIRONMENT DETAILS**
- Linode Ubuntu 20.04 VM
- Docker install
- Rancher version: `v.2.6.4`

**REPRODUCTION STEPS**
1. Setup Rancher `v2.6.4`.
2. Navigate to top-left dropdown menu > Explore Cluster > local > Workload > Deployments.
3. Create a deployment resource in the `default` namespace.
4. Grab the `kubeconfig` file for this `local` cluster, apply it to your client machine and apply the yaml file found in this [comment](https://github.com/rancher/dashboard/issues/5577#issuecomment-1088831355).
5. Verify that you have something such as the following:
<img width="1493" alt="image" src="https://user-images.githubusercontent.com/52591819/164311540-d1ccaca9-cbad-4f73-83f5-bead0b6e5c5b.png">
6. Click the storage deployment > storage pod. I note the following:
<img width="1468" alt="image" src="https://user-images.githubusercontent.com/52591819/164311707-127bd68f-ae26-48ce-a96c-414131e15602.png">

The same behavior occurs in `v2.6-head`. Additionally, I attempted adding a sidecar to the `storage` deployment as in the issue description, the video shows two pods in the `storage` deployment. However, that makes no difference. The video also shows that the URL doesn't get the `#containers` appended at the end. Mine, however, looks like this: `https://FQDN/dashboard/c/local/explorer/pod/default/storage-...#containers`.

**Comment by cnotv** [comment] 2022-04-21 09:29
@markusewalker This issue has been fixed already with another PR, so if you cannot reproduce it we can simply close it.

**Closed** 2022-04-21 14:53 UTC
Labels: kind/bug, [zube]: Reopened, team/area2
