### ISSUE TITLE
Imported K3s cluster shows up in cluster manager list view, but not in side nav

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5474] opened 2022-03-22 22:55 UTC
**Setup**
- Rancher version: 2.6.3 (v2.6-head)
- Browser type & version: Chrome

**Describe the bug**
Imported K3s cluster shows up in cluster manager list view, but not in side nav. It should show up in both places

**To Reproduce**
1. Import a K3s cluster
2. See that it is not listed after clicking the top left hamburger menu
<img width="927" alt="Screen Shot 2022-03-22 at 3 52 28 PM" src="https://user-images.githubusercontent.com/20599230/159589614-d3311dc1-e057-479d-b25a-ba42287928a3.png">

**Comment by nwmac** [comment] 2022-10-24 22:20
@Shavindra Pretty sure this is fixed - can you verify

**Comment by jameson-mcghee** [comment] 2022-12-16 21:05
During testing on `v2.6.3`, `v2.7.0`, and `v2.7-head` (Commit ID: dadb4c0), and I was unable to reproduce this issue on any of those versions. Due to that fact, as well as comments from @mantis-toboggan-md, I am closing this ticket as resolved.

**Steps to Reproduce:**
1. Create a K3s cluster outside of Rancher
2. Import the cluster into Rancher
3. Open the left side panel

**`v2.6.3`:**
![image](https://user-images.githubusercontent.com/13294321/208188063-db7da37e-eb97-4cff-b4fd-d24c8825251b.png)

**`v2.7.0`:**
![image](https://user-images.githubusercontent.com/13294321/208188173-8e21d347-7d2d-4d5d-be24-551c6e580502.png)

**`v2.7-head` (Commit ID: dadb4c0):**
![image](https://user-images.githubusercontent.com/13294321/208188274-d74eaf52-aa0b-4d49-b2e7-1ab8fbdc7ace.png)

**Closed by jameson-mcghee** 2022-12-16 21:05 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, team/area2
