### ISSUE TITLE
[Backport 2.6.x] Resource re-watch

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7779] opened 2022-12-20 17:20 UTC
What we did in https://github.com/rancher/dashboard/issues/5997 needs to go into 2.6.x.

**Comment by gaktive** [comment] 2022-12-21 16:11
@richard-cox may have done this already.

**Comment by richard-cox** [comment] 2022-12-21 16:35
Duplicate of https://github.com/rancher/dashboard/issues/7707, closing

**Closed by richard-cox** 2022-12-21 16:35 UTC
Labels: kind/bug, [zube]: Next Up, JIRA, area/performance
