### ISSUE TITLE
Enable new regions for Amazon credentials

### ISSUE THREAD

**Issue by cpinjani** [rancher/dashboard#9220] opened 2023-06-27 13:20 UTC
**Setup**
Rancher version: v2.7-3aedc24d3087c3bbc4deb4d8c5ae40f55945e913-head (2.7.5 timeline)
Browser type & version: Firefox

**Describe the bug**
Add below regions in the list of supported regions for creating AWS Cloud credentials:
ap-southeast-4, ap-south-2, me-central-1, eu-central-2, eu-south-2

**To Reproduce**
- Go to Cluster management page
- Add Cloud credentials - AWS

![image](https://github.com/rancher/dashboard/assets/73099870/afad9d30-f777-4cee-bbb7-0f289981ba50)

**Additional context**
New EKS regions were added as part https://github.com/rancher/dashboard/issues/8701
User can add creds in these regions while on create EKS cluster page. However, for better UX these can be enabled on Cloud creds list so they can be selected while creating EKS cluster from existing credentials.

**Comment by richard-cox** [comment] 2023-06-27 13:55
Given all the investigation in rancher/ui world for #8701, all this entails is adding the listed regions to the dashboard side.

If https://github.com/rancher/dashboard/issues/7295 is done, this is not needed

**Comment by gaktive** [comment] 2024-07-04 14:52
This should've been done already. Passing to QA to validate.

**Comment by gaktive** [comment] 2024-07-24 21:22
This got merged into 2.9.0 already so hopefully QA can pick this up since they did first report it. This may have been in milestone limbo though this may also be a duplicate of https://github.com/rancher/dashboard/issues/10294

**Comment by gaktive** [comment] 2024-07-24 21:23
Also some connection to https://github.com/rancher/dashboard/issues/9219 though I'm getting lost in how many fixes are tied around this area.

**Comment by izaac** [comment] 2024-07-25 17:30
These are available in Rancher `v2.9-dd23578d3e3499f54d80c4ed88cc52c44ee69539-head`

I don't have permissions to create resources on those, but this meets the acceptance criteria to close.

**Closed by izaac** 2024-07-25 17:30 UTC
Labels: kind/bug
