### ISSUE TITLE
UI 2.6.x 'events' view is confusing and 'hidden' by default

### ISSUE THREAD

**Issue by jakaye80** [rancher/dashboard#5816] opened 2022-05-03 21:32 UTC
**Setup**
- Rancher version: Rancher 2.6.x vs Rancher 2.5.x
- Browser type & version: OS X ( Version 12.2.1 (21D62)) Google Chrome (Version 101.0.4951.41 (Official Build) (arm64))

**Describe the bug**

Rancher 2.6 UI does not display 'events' fully and easy to 'find' as it was in Rancher 2.5.x. 
The main screen does not have a 'shown' 'search' box as 2.5.x 
**To Reproduce**

Bring up Rancher 2.6 and compare to Rancher 2.5 the 'events' page it is 'different' and lacking 'functionality' as Rancher 2.5 when first shown.
**Result**

**Expected Result**

Rancher 2.6 'events' should have the same function of visibility  and 'search' functions on the 'main' screen'
**Screenshots**

[1] Rancher 2.5 'events' 

![image](https://user-images.githubusercontent.com/100592648/166566508-1eb948e2-77cd-44eb-af66-51e6bc8a2143.png)

[2] Rancher 2.6 'events'
![image](https://user-images.githubusercontent.com/100592648/166566767-c4de35d3-4542-4f2c-b8a1-9db0604662da.png)

1. Search for 'events' to make it the same as Rancher 2.5 'view' of 'events'

![image](https://user-images.githubusercontent.com/100592648/166567104-28448f6e-2e09-49a3-8281-df035bb15282.png)

2. The 'events' are shown

![image](https://user-images.githubusercontent.com/100592648/166567973-929dae40-9029-4f85-be6d-2e6abe9c1366.png)

By 'default' 'events' are 'hidden' under 'core' by default. You need to 'click' to exapnd. 

![image](https://user-images.githubusercontent.com/100592648/166569835-7ae53704-18de-4086-b66a-620f2c63d8a1.png)

**Additional context**

**Detailed Description**

Rancher 2.6 'events' should be the same as Rancher 2.5 or 'easy' to 'find'. It is 'hidden' under a 'search' icon. 
**Context**

It is very confusing in 2.6 to get a quick look at your events page. This is very helpful to 'operators' to get a birds -eye view of the environment very quickly.

**Comment by richard-cox** [comment] 2022-05-04 07:11
This came about from a slack conversation regarding the missing feature set on the Events table. There was confusion given that the events table on the cluster dashboard page is meant to provide a summary (and therefore load quickly) whilst the normal events table contains the full set of list features (search, all rowa, etc). 

I don't think we should update the event list on the dashboard page to match the full list, however I do think we should make it clear that if the user needs more functionality they can get to the other list. Suggestions (only)

1) Rename the summary list as `Events Summary`
2) Add a button / link that takes user to the full list ('All Events` or `Events` , etc). Where this goes or how this looks I'm not quite sure.

**Comment by kwwii** [comment] 2022-09-12 10:10
We should add "Events" under the Cluster top-level navigation item in the menu.

We should add a link to "All Events" at the top right of the events table on the cluster dashboard.

**Comment by aalves08** [comment] 2022-09-16 16:33
@kwwii does this have any design associated or shall we just have a quick sync on monday?

**Comment by dasarinaidu** [comment] 2022-09-29 18:20
I validated this ticket and sending back to the developer with few observations : 

**Rancher Version : v2.6-head**

**Observation 1 : Left Nav: Events : Displayed number is NOT correct, its NOT matching with actual number of Events at the bottom.**

![image](https://user-images.githubusercontent.com/22034884/193110707-944dd39d-fe43-4f55-b00d-fffc2a8c7420.png)


**Observation 2 : 'Events' Link at the bottom window pane is NOT navigating to any of the place. It stays at the same place.**

![image](https://user-images.githubusercontent.com/22034884/193111072-1b40af3a-cb19-4915-b2d8-41304974f6d8.png)


**Observation 3 : 'Full events list' Link is NOT flushing the events list, it shows a blank page** 

![image](https://user-images.githubusercontent.com/22034884/193111583-f16fd253-b516-455f-8fb9-340e5211c38d.png)


**Observation 4: 'Full events list' Link + Command click is opening same rancher page in next tab but not displaying the Events list**

![image](https://user-images.githubusercontent.com/22034884/193111708-9ec4aa75-60f8-4003-8c0f-e1d94b8b02e8.png)

**Comment by aalves08** [comment] 2022-10-06 09:15
@dasarinaidu , commenting on your observations:
1) Couldn't reproduce this. All numbers matched for me.

2) This is a tab navigation and, since it's the only on present on that area, it doesn't "do" anything as it's the only "tab" route there.

3) 4) Not sure I understand what you meant by flushing but the link was broken. Now it's fixed and should take you to the `events` resource list view. Thanks for noticing that 🙏

**Comment by dasarinaidu** [comment] 2022-10-12 13:56
All the callouts were fixed and I am closing the ticket.
Rancher version : v2.7-a3502cdeee5ff9f956947974196893b7bf9696d6-head

<img width="1492" alt="image" src="https://user-images.githubusercontent.com/22034884/195362255-0cd84a67-f6ca-450f-9c24-772020629f24.png">

**Closed by dasarinaidu** 2022-10-12 13:56 UTC
Labels: internal, kind/design, [zube]: QA Working, area/dashboard, team/area1
