### ISSUE TITLE
Editing an app that was originally created in old UI causes frontend error

### ISSUE THREAD

**Issue by rmweir** [rancher/dashboard#4120] opened 2021-09-08 01:10 UTC
**Setup**
- Rancher version: v2.60
- Browser type & version: chrome

**Describe the bug**

Editing an app that was installed using the old UI leads to a front end error.

**To Reproduce**

1. Install OpenEBS in a namespace of a cluster.
2. Find app in dashboard
3. Edit as yaml
4. Save

**Result**
Encounter error stating: "Cannot read property 'annotations' of undefined". There are no console error and no request is made.

**Expected Result**

Upgrade action request is sent.

**Screenshots**

![image](https://user-images.githubusercontent.com/19376037/132429301-cbead2ab-dfff-455b-8d56-c41c1cf1537c.png)

**Additional context**

**Detailed Description**

**Context**

Working on making it so users can manage apps using the dashboard that were originally created in ember UI.

**Comment by nwmac** [comment] 2021-09-08 08:00
@rmweir When you say old UI, are you installing the OpenEBS from the old Cluster Manager UI in Rancher 2.5 ?

**Comment by rmweir** [comment] 2021-09-09 01:21
@nwmac by old UI I mean using ember in 2.6 but we can assume this emulates what would happen by creating it in 2.5 in ember as well.

**Comment by sgapanovich** [comment] 2021-10-15 02:22
Was able to reproduce the issue for test purposes on 2.6.0 Rancher
![reproduced.png](https://zube.io/files/rancher/ebcfbfa4fdce9461f0c4f0d9235fcb2f-reproduced.png)

**Comment by rmweir** [comment] 2021-11-29 20:48
How exactly is it being determined that there is no repository for an app? I've recently added logic to support a manual migration process where we require the user to add the ui-repo annotation to the app's spec.chart.metadata.annotations, however even after doing that, a user is still redirected to the legacy app.

**Comment by sgapanovich** [comment] 2021-12-03 15:19
### Test Environment: ###
Rancher version: 2.5.9 (upgraded to 2.6.3-rc3)
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: 3 node ec2 cluster
Downstream K8s version: v1.20.11

----------

### Testing: ###

There is no way to install apps in Ember in 2.6.3-rc3 using UI
![263rc3](https://user-images.githubusercontent.com/40282141/144618245-b74f5a6c-a2fa-41ad-b5c0-46b998ac1d17.jpg)

1. installed apps (2 cluster and 1 multi-cluster apps) in a default namespace/default project in the downstream cluster in2.5.9 rancher 
2. UPGRADED Rancher to 2.6.3-rc3
3. navigated to the downstream cluster -> "Apps & Marketplace" -> Installed Apps
4. right click on the app -> Edit/Upgrade
- If "legacy" feature flag is disabled (/dashboard/c/local/settings/management.cattle.io.setting)
  - there is a message that you need to to enable the feature and a link to the correct page 
  - ![legacy](https://user-images.githubusercontent.com/40282141/144619160-f9fafee8-4d46-44b1-bbcb-466a7b2a1ae4.jpg)
- if "legacy" is enabled 
  - there is a message that you need to go to legacy apps and a link to the correct page 
  - ![legacy](https://user-images.githubusercontent.com/40282141/144624732-3977d99c-e501-4990-b040-be4c47dd576d.jpg)

On the Legacy -> Project (selected the "Default" project in the drop down) I see my installed apps (2 cluster and 1 multi-cluster apps installed)
By clicking on three dots on the app I want to edit I don't see option to "Edit YAML" option
![no option](https://user-images.githubusercontent.com/40282141/144625500-25b03128-7a27-43d2-a1a8-3ddab3aeea09.jpg)

If i click on the app I am taken to the iframe where I can view/edit resources but I can't edit the app's yaml file 
![iframe](https://user-images.githubusercontent.com/40282141/144626415-24531456-9e84-4f78-8c22-2cc39075fd90.jpg)

@richard-cox @jordojordo did we remove the ability to edit the app's yaml file (see the screenshot in the issue itself) or I am missing something?

**Comment by jordojordo** [comment] 2021-12-03 21:58
@sgapanovich 
AFAIK the `Upgrade` in the Ember UI button is unanimous with `Edit` in the Dashboard UI, so you _should_ be able to edit the yaml from there. However, with the latest release `v2.6.3-rc3` it _seems_ there is a breaking change in Ember UI that is causing the `Upgrade` screen to not load.
I would suggest opening an issue in the [UI repo](https://github.com/rancher/ui). With the issue here being that you cannot update the App from the Dashboard UI (which the User shouldn't be allowed to do per [the docs](https://rancher.com/docs/rancher/v2.6/en/helm-charts/)), I think this issue being fixed has just lead to another problem all together.

**Comment by sgapanovich** [comment] 2021-12-05 01:00
2.5.11
- launch the openebs app
- navigate to the project where the app was installed
- go to Apps
- click on the three dots to edit app 
- select "Upgrade"
  - app is opened to be edited 
  - ![2511](https://user-images.githubusercontent.com/40282141/144729276-cea2cfc0-ae23-4268-b456-7633d25821c4.gif)
  - "Edit as YAML" file option can be located on that page
  - ![edit](https://user-images.githubusercontent.com/40282141/144729213-22146e0e-42d5-4845-b424-0dd4dd7e75f9.jpg)

when Rancher is upgraded to 2.6.3-rc4
- enable Legacy feature if not enabled
- On the Legacy -> Project (selected the project where the app installed in the drop down) 
- go to Apps
- click on the three dots to edit app 
- select "Upgrade"
  - app is not opened to be edited 
  - ![263rc4](https://user-images.githubusercontent.com/40282141/144729266-d77479e4-c340-4992-b7a8-3d30ab7a8077.gif)

when comparing API calls made in 2.5.11 and 2.6.3-rc4 you can see missing GET API calls with info for the app
![differences](https://user-images.githubusercontent.com/40282141/144729333-459a29db-2bb6-48fa-9d08-4e25e564d6e6.jpg)

**Comment by sgapanovich** [comment] 2021-12-05 21:12
Created an issue : https://github.com/rancher/dashboard/issues/4708 to follow up on not working "Upgrade" functionality in Legacy -> Apps
Closing this issue because the issue is no longer valid - we don't let users edit apps in dashboard

**Closed** 2021-12-05 21:13 UTC
Labels: [zube]: QA Working
