### ISSUE TITLE
Whether labels search is supported

### ISSUE THREAD

**Issue by tianhao98** [rancher/dashboard#4151] opened 2021-09-14 03:35 UTC
**Detailed Description**

Whether the Rancher Dashboard supports searching for resources by tabels

**Comment by catherineluse** [comment] 2022-04-17 22:10
Possible duplicate of https://github.com/rancher/dashboard/issues/5091

**Comment by nwmac** [comment] 2022-07-13 13:35
Closing in favor of #5091

**Closed by nwmac** 2022-07-13 13:35 UTC
Labels: kind/question
