### ISSUE TITLE
[Dark Mode enhancement] - Highlight navigation groups when child items are selected

### ISSUE THREAD

**Issue by Josh-Diamond** [rancher/dashboard#9948] opened 2023-10-18 21:45 UTC
The recent implementation of https://github.com/rancher/dashboard/issues/9428, `navigation groups are highlighted when child items are selected`, does not translate well in Rancher's Dark Mode.  

From QA perspective, this is more distracting than helpful.  This issue was created in hopes of optimizing the appearance of this recent enhancement, when Dark Mode is toggled on, to make the highlighting less distracting and more helpful to user when navigating their Rancher server.

Screenshot of concern:
<img width="513" alt="Screenshot 2023-10-18 at 12 17 03 PM" src="https://github.com/rancher/dashboard/assets/46494969/944e4881-b1ee-4ccc-a07d-6260c3cf54ab">

**Comment by richard-cox** [comment] 2023-10-19 09:34
Closing as duplicate of https://github.com/rancher/dashboard/issues/9799 which covers more cases where the highlight isn't quite right

**Closed by richard-cox** 2023-10-19 09:34 UTC
Labels: kind/design, kind/enhancement, area/dashboard, team/area2, [zube]: Design Triage
