### ISSUE TITLE
[BUG] Failed S3 snapshots are able to be restored, causing downstream clusters to be stuck in a `Provisioning` state  with error message `Operation etcd restore failed`

### ISSUE THREAD

**Issue by markusewalker** [rancher/dashboard#8839] opened 2023-05-09 20:00 UTC
The RKE1 part of this issue will be addressed by another issue: rancher/dashboard#9409  

**Rancher Server Setup**
- Rancher version: `v2.7-head` https://github.com/rancher/rancher/commit/1f014b7fcd734e9321555b613cc28b1b12bf8eeb
- Installation option (Docker install/Helm Chart): Docker
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: `v1.25.9+rke2r1`
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): AWS

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) Cluster Owner
  - If custom, define the set of permissions:

**Describe the bug**

When provisioning a downstream node driver RKE2 cluster, I enabled S3 backups. However, I used a non-existent S3 bucket when provisioning. When attempting to create a backup, I see the following:

![image](https://github.com/rancher/rancher/assets/52591819/683dfad9-e271-47aa-ae63-de1345ce3f68)

I would expect an error, so that part is fine...however, I am able to actually restore this failed backup. When I do that, I see the following error message:

![image](https://github.com/rancher/rancher/assets/52591819/ad10cf30-7137-40c1-ae48-fdc0da186790)

Looking into the logs further, I noted the following:

```
2023/05/09 19:51:19 [ERROR] [planner] rkecluster fleet-default/mew-rke2-broken-snapshot: error encountered during plan processing was operation etcd restore failed
2023/05/09 19:51:19 [ERROR] error syncing 'fleet-default/mew-rke2-broken-snapshot': handler planner: operation etcd restore failed, requeuing
2023/05/09 19:51:24 [ERROR] error syncing 'c-m-sn6t785b': handler cluster-deploy: Get "https://10.43.0.1:443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
2023/05/09 19:52:10 [ERROR] error syncing 'c-m-sn6t785b': handler cluster-deploy: Get "https://10.43.0.1:443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
2023/05/09 19:52:54 [ERROR] error syncing 'c-m-sn6t785b': handler cluster-deploy: Get "https://10.43.0.1:443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": cluster agent disconnected, requeuing
2023/05/09 19:53:19 [INFO] [planner] rkecluster fleet-default/mew-rke2-broken-snapshot: electing init node for S3 snapshot fleet-default/mew-rke2-broken-snapshot-on-demand-mew-rke2-broken-snapsh-f0d4a restoration
2023/05/09 19:53:19 [ERROR] [planner] rkecluster fleet-default/mew-rke2-broken-snapshot: error encountered during plan processing was operation etcd restore failed
```
Considering that the backup failed, I would expect to not be able to restore from a failed backup.

**To Reproduce**

1. As a standard user, provision a downstream node driver RKE2 cluster with S3 backups enabled and specify a non-existent bucket.
2. Create an S3 snapshot; validate that the bucket does not get created.
3. Restore that S3 snapshot and note that the cluster is an error state as mentioned above.

**Result**
I am able to restore my cluster using a failed S3 snapshot.

**Expected Result**

I should not able to restore my cluster if a S3 snapshot has failed; the option should not be provided to me at all.

**Comment by snasovich** [comment] 2023-05-10 18:09
@nwmac @gaktive , FYI - transferred this one to dashboard.

**Comment by momesgin** [comment] 2023-07-17 22:32
@edenhernandez-suse @kwwii there's also another place where users can trigger restoring a failed snapshot from the list of clusters on Cluster Management page:
![image.png](https://zube.io/files/rancher/69359bae028c4127409094e30f77e9d2-image.png)
it opens a prompt modal:
![image.png](https://zube.io/files/rancher/bdbe740573e20fdfdbdd601a4e228ea7-image.png)
is it acceptable as a solution if we filter the failed snapshots from the dropdown list?

**Comment by kwwii** [comment] 2023-07-18 04:00
Ideally the UI should display only valid options. That means filtering out the failed snapshots from the list of possible options.

**Comment by Josh-Diamond** [comment] 2023-07-26 22:24
Ticket #8839 - Test Results - :x: - RE-OPENED
---

Verified with HA Helm on Rancher `v2.7-369c7d37b9e678922297c3811b4329e18da4abdf-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | From `Cluster Management > Clusters` page, attempt a snapshot restore with an invalid snapshot | ✅ |
| 2. | From `Cluster Management > Cluster Details > Snapshots (tab)`, attempt a snapshot restore with an invalid snapshot | :x: |

---

Scenario 1 - ✅ 
1. Fresh install of Rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream RKE2 cluster w/ s3 etcd backup configured and pointing to a non-existent bucket
4. Verified - cluster successfully provisions
5. Take a snapshot
6. Once `active`, navigate to `Cluster Management > Clusters` page, select the three dots next to cluster and then select `Snapshot Restore`
7. Verified - invalid snapshot has been filtered out; valid local snap is displayed; as expected

---

Scenario 2 - :x:
1. Fresh install of Rancher `v2.7-head`
2. As admin, create a standard user
3. As standard user, provision a downstream RKE2 cluster w/ s3 etcd backup configured and pointing to a non-existent bucket
4. Verified - cluster successfully provisions
5. Take a snapshot
6. Once `active`, navigate to `Cluster Management > Cluster Details > Snapshots (tab)`, select the three dots next to invalid snapshot, and select `restore`
7. Veri-FAILED - Rancher attempts to restore cluster with an invalid snapshot; errored out with `operation etcd restore failed`

❗NOTE:❗
With scenario 2, after the initial failure, I attempted to reproduce this again on a new cluster, and was unable to do so.  Second attempt results showcased in screenshot below for step 6; which is expected - re-opening due to inconsistencies 

![image (36)](https://github.com/rancher/dashboard/assets/46494969/f0fca3f1-2633-470a-a6bc-8064eafa7cfa)

**Comment by Josh-Diamond** [comment] 2023-07-28 18:18
re-opening to re-test latest changes.

**Comment by Josh-Diamond** [comment] 2023-07-28 21:43
Ticket #8839 - Test Results - ✅ 
---

The following test case was executed 3 times:

With HA Helm on Rancher `v2.7-027246f77f03b82660dc2e91df6bf2cd549163f0-head`:

| Scenario | Test Case | Result |
|---|---|---|
| 1. | Provision a downstream RKE2 cluster w/ s3 configured + from `Cluster Management > Cluster Details > Snapshots (tab)`, attempt a snapshot restore with an invalid snapshot | ✅ |

---

Scenario 1 - Executed 3 times - [ ✅ ✅ ✅ ]
1. Fresh install of Rancher `v2.7-head`
2. Provision a downstream RKE2 cluster w/ s3 etcd backups configured to a non-existent s3 bucket
3. Once `active`, navigate to `Cluster Management > Cluster Details > Snapshots (tab)`, and take a snapshot
4. Verified - snapshot captured; s3 snapshot is invalid; as expected
5. Attempt to restore cluster back to invalid s3 snapshot taken
6. Verified - Unable to restore to s3 snapshot taken; UI prompts the following message: `No actions available`; as expected

**Closed by Josh-Diamond** 2023-07-28 21:43 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, good-first-issue, team/area2, size/3
