### ISSUE TITLE
Improve PSP removal banner implementation

### ISSUE THREAD

**Issue by aalves08** [rancher/dashboard#7012] opened 2022-09-27 12:52 UTC
Improve PSP removal banner implementation rancher/dashboard#6873 by adding a dismiss flag and an indicator on the same as provider and kube version with a hoverable text+icon with warning colors that replaces the banner once it was dismissed.

**Comment by sowmyav27** [comment] 2022-09-28 04:21
**On 2.7-head commit id: `c567ef3`**

- Deploy a couple of clusters - k3s node driver and EKS
- Banner is seen on an EKS cluster
- Close this banner
- indicator on the same as provider and kube version with a hoverable text+icon is available on the cluster
- On the other cluster - k3s, the banner is dismissed.

**Expected Result**
Dismissing the banner on one cluster should _not_ dismiss the banner on the other clusters. Reopening the issue

**Comment by aalves08** [comment] 2022-09-28 07:34
That's the expected behaviour @sowmyav27 , as per agreed with @nwmac . 

There's a lot of overhead of implementing a persisting solution (saving of a dismissal) of dismissing per cluster, which we considered that is not needed for the complexity of what we are trying to solve here + we have a persisting hoverable text+icon always present, when the banner is dismissed, so that the user is aware of the deprecation.

**Comment by aalves08** [comment] 2022-10-04 08:31
Correct @jameson-mcghee . There will always be that golden text+icon, if the banner has been dismissed once on any cluster. 
To be noted that the banner + icon will only appear if certain conditions are met (`1.21 <= kube version <1.25` and having `at least 1 Pod Security Policy on that cluster`).

**Comment by jameson-mcghee** [comment] 2022-10-04 15:10
@aalves08, I am not sure I agree with this implementation of closing the banner once closes it for all future and current clusters and all future and current users. However, based on the statement that the above functionality is intended as well as I and @sowmyav27 having been able to see the banner on multiple clusters and able to see the tooltip warning on all of the clusters once the banner is closed on Rancher v2.7-head (Commit IDs: c567ef3 & 314e690), I am marking this ticket as Done.

Steps to Reproduce:
1. In a Rancher server, create a downstream K3s EC2 Node Driver cluster
2. Once the cluster is Active, navigate to the Cluster Explorer page for the cluster
  - Note the banner is present at the top of the page
3. Close the banner using the "x" button
  - Note that a yellow PSPs icon is now present
4. Hover over the yellow PSPs icon
  - Note that the banner message is present in the tooltip

**Banner Present:**
![image](https://user-images.githubusercontent.com/13294321/193856643-d8376429-f0e8-43ba-8987-3ee6bc2db96f.png)
![image](https://user-images.githubusercontent.com/13294321/193856684-6e62f531-5f76-4ca7-91b4-dcb22e90bc75.png)

**Tooltip Message:**
![image](https://user-images.githubusercontent.com/13294321/193856733-847d9b80-91a1-43ba-a860-b9fe94bdaf0d.png)
![image](https://user-images.githubusercontent.com/13294321/193856770-e0dcaa2f-6070-460a-bad7-b38b4b0d51b6.png)

**Closed** 2022-10-04 15:11 UTC
Labels: [zube]: Done, QA/XS, kind/enhancement, area/dashboard, team/area2
