### ISSUE TITLE
`logs-range` preference contains an invalid value and breaks logs

### ISSUE THREAD

**Issue by JannikZed** [rancher/dashboard#6122] opened 2022-06-08 16:30 UTC
**Setup**
- Rancher version: 2.6.5
- Browser type & version: Chrome 102

**Describe the bug**
Opening container logs not working - windows stays blank:
![Screenshot 2022-06-08 at 18 28 37](https://user-images.githubusercontent.com/7526174/172668853-2b0cb7a2-1f25-4a23-b1db-bbc6744e89e1.png)

Error in the console:

```
TypeError: r.replace is not a function
    at C (opsgenie.vue?578b:153:1)
    at f.rangeOptions (opsgenie.vue?578b:116:9)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.rangeOptions (vue.runtime.esm.js:4836:17)
    at fn (rke2.svg:1:2097)
    at Object.r [as title] (vue.runtime.esm.js:2590:62)
    at f.r (rke.svg:1:159)
    at t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
```

```
TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at opsgenie.vue?578b:222:1
    at d (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at O.forEach.t.<computed> [as next] (runtime.js:97:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
```

**To Reproduce**

**Result**

**Expected Result**

**Screenshots**
![Screenshot 2022-06-08 at 18 30 09](https://user-images.githubusercontent.com/7526174/172669127-018b8017-7ea5-4b0b-be69-d8bd514204cb.png)

**Additional context**
Update by @richard-cox 
This is caused by the `logs-range` preference containing an incorrect value ` "value": "{\"label\":\"Everything\",\"value\":\"all\"}"` and is effecting a lot of installs. For 2.6.6 we should check for this bad value and convert it to a correct one.

**Comment by richard-cox** [comment] 2022-06-08 17:43
We don't see this fail in 2.6.5, could you provide more information?
- Is the log actually showing as connected (bottom right)? 
- Are there failed network requests?
- Is the container associated with something we can deploy to try to reproduce?

**Comment by Peyoz** [comment] 2022-06-09 16:13
Hi, 
Same issue here, also the same logs.
It does not look like related to a specific browser, we tested Chrome / Edge 102, and Firefox 101

I caught this websocket error also
![image](https://user-images.githubusercontent.com/61762607/172894632-96e6d343-aa67-4cc4-89e6-60fcc64db04d.png)

Not sure if it is related.

**Comment by glatino-pdxeng** [comment] 2022-06-10 12:27
same issue here after upgrading to 2.6.5, and same errors from the browsers

**Comment by glatino-pdx** [comment] 2022-06-10 12:38
same issue for me, after upgrading to rancher 2.6.5

**Comment by richard-cox** [comment] 2022-06-10 12:46
@UlixDev , @glatino-pdx  https://github.com/rancher/dashboard/issues/6122#issuecomment-1150210531

**Comment by UlixDev** [comment] 2022-06-10 12:51
@richard-cox The log window shows absolutely nothing nor the message 'connected' in bottom right

**Comment by richard-cox** [comment] 2022-06-10 12:53
@UlixDev Are you able to answer the other questions from https://github.com/rancher/dashboard/issues/6122#issuecomment-1150210531?

**Comment by UlixDev** [comment] 2022-06-10 13:07
@richard-cox There are no other errors in the network tab and also for me the issue happens in all containers

**Comment by glatino-pdx** [comment] 2022-06-10 13:09
same for me, errors only in the console tab, and for all the containers
![Screenshot 2022-06-10 150916](https://user-images.githubusercontent.com/105722462/173071377-ae64d6b9-491d-45e4-b7a1-6f699c854b79.png)

**Comment by richard-cox** [comment] 2022-06-10 13:31
Can you all
- confirm which resources you see this for, is it only Pods in Services, or also Pods in Deployments?
- the same happens after refreshing the page? the console log shows an `opsgenie` component which should in theory only show when editing a monitoring resource
- log in to Rancher, then navigate to `<your rancher url>/v3/preferences/logs-range`. Does it succeed? Is there something in `value`?

**Comment by UlixDev** [comment] 2022-06-10 13:53
Well 

- The problem exists either for Pods in Services and Pods in Deployments 
- After a refresh, the tab of the log disappears
- this is the result from the API call `<your rancher url>/v3/preferences/logs-range`
`{
"baseType": "preference",
"created": "2022-06-10T11:49:43Z",
"createdTS": 1654861783000,
"creatorId": null,
"id": ["logs-range"](https://rancher.dev.pdxeng.ch/v3/preferences/logs-range),
"links": {
"remove": ["…/v3/preferences/logs-range"](https://rancher.dev.pdxeng.ch/v3/preferences/logs-range),
"self": ["…/v3/preferences/logs-range"](https://rancher.dev.pdxeng.ch/v3/preferences/logs-range),
"update": ["…/v3/preferences/logs-range"](https://rancher.dev.pdxeng.ch/v3/preferences/logs-range)
},
"name": "logs-range",
"namespaceId": "u-kpkf7ivouz",
"type": ["preference"](https://rancher.dev.pdxeng.ch/v3/schemas/preference),
"uuid": "ceff1cb2-0493-4722-94af-042e4bda8e51",
"value": "{\"label\":\"Everything\",\"value\":\"all\"}"
}`

**Comment by richard-cox** [comment] 2022-06-10 14:00
Ok, that value looks broken. Can you try navigating back to `<your rancher url>/v3/preferences/logs-range`, pressing the `delete` button on the right of the page and then `send request` in the modal that pops up. If you then go back to Rancher and try streaming logs again it should work

**Comment by UlixDev** [comment] 2022-06-10 14:04
@richard-cox 
kind of magic! That works!
Thank you so much
  ulix

**Comment by richard-cox** [comment] 2022-06-10 14:06
@UlixDev No problem, thank you for your patience and assistance. Go team!

@JannikZed @glatino-pdx Please can you try the suggestion in https://github.com/rancher/dashboard/issues/6122#issuecomment-1152394027 ?

**Comment by JannikZed** [comment] 2022-06-10 14:08
I can confirm, that this little fix from https://github.com/rancher/dashboard/issues/6122#issuecomment-1152394027 fixes the issue for us! Working again. Thank you very much for the fast response.

**Comment by glatino-pdx** [comment] 2022-06-10 14:40
It works also for me, thanks @richard-cox :)

**Comment by catherineluse** [comment] 2022-06-10 17:37
I believe this is a duplicate of https://github.com/rancher/dashboard/issues/5984 and a fix is already in master, scheduled for the 2.6.6 milestone

**Closed** 2022-06-13 16:55 UTC
Labels: [zube]: Review

**Comment by mohag** [comment] 2022-06-21 11:03
The quick cleanup of all of the settings (run against the local cluster):
`kubectl get preference -A | grep logs-range | while read ns setting crap; do kubectl -n "$ns" delete preference "$setting"; done`
