### ISSUE TITLE
Cluster Provisioning - Node Provisioning RKE1 - Generic Node Drivers

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#2777] opened 2021-04-21 03:24 UTC
Tied to rancher/dashboard#2770

**Comment by slickwarren** [comment] 2021-05-17 21:28
I was able to test the following on master-head (5d2b7ac)
* custom cluster with RKE flag ON (default) - pass
* custom cluster already provisioned, edit cluster (add environment var) - pass
* turn RKE flag OFF, provision custom cluster - pass

**Comment by sowmyav27** [comment] 2021-05-24 22:45
Reopening to test Generic Node Drivers.

**Comment by slickwarren** [comment] 2021-06-01 23:33
so far, I have tried with the following in both iframe/dashboard and in ember UI on master-head (5d49b92f479a00773607fb41fe851f98271148c0). : 

Dashboard Tests:
* enable/disable generic node driver
  * single -- pass
  * multiple -- pass
* **provision a cluster with one of the generic node drivers -- fail**

Dashboard Specific Issues:
* **Unfortunately, _sometimes,_ dashboard is not loading the iframe windows properly for any generic node types. an `empty cache and hard reload` appears to fix this when it happens.The below notes are what are observed in the ember UI, and dashboard upon a hard reload+empty cache.  Dashboard appears to try to load iframe, fails, then loads the import cluster window upon failure when in this bad state**.
* a lot of the images aren't showing up (ember vs. dashboard below)
<img width="1294" alt="Screen Shot 2021-06-01 at 4 16 05 PM" src="https://user-images.githubusercontent.com/16691014/120401399-b89c6c80-c2f4-11eb-9fbb-c300084c1169.png">
<img width="1513" alt="Screen Shot 2021-06-01 at 4 15 50 PM" src="https://user-images.githubusercontent.com/16691014/120401402-b9350300-c2f4-11eb-8fc3-63b415add5a0.png">
* so far, I have not noticed any other differences in RKE1 provisioning of generic node drivers.

**I think there is enough here to reopen**.  Below are some other related ember/iframe issues (if need be, I can open new tickets for the below issues.).  We don't have shared QA credentials for generic provisioners, so setting up an account with each provider I've tested takes additional time for testing.  


Ember/iframe issues:
* OCI -- ran into an issue with reading the private key:
<img width="1312" alt="Screen Shot 2021-06-01 at 4 01 15 PM" src="https://user-images.githubusercontent.com/16691014/120400711-48411b80-c2f3-11eb-8148-812746001398.png">

* google -- only an option for the `authEncoded Json` is available for entry (no read file option, just manual entry).  no verification is done on this entry, so user can continue to create a cluster with an invalid key. I get this error consistently `Error setting machine configuration from flags provided: no Google Cloud Project name specified (--google-project); Timeout waiting for ssh key`

**Comment by nwmac** [comment] 2021-06-10 13:17
@caleb I couldn't reproduce the issue with the iframe not loading sometimes.

Icons should be fixed now.

Can you try and reproduce and if you see this again, can you screenshot, grab the console log and also the network tab requests. Thanks

**Comment by slickwarren** [comment] 2021-06-25 20:57
on master-head (e756276):
verified Icons are fixed. 
REOPENING FOR THE FOLLOWING:
when trying to provision an OCI cluster on RKE1, I get the following error:
```
ncaught (in promise) 
Timeout loading /meta/proxy/https://drivers.rancher.cn/node-driver-pinganyun/0.3.0/component.css
```
* also, upon reloading the page, the user is taken instead to the RKE2 page for OCI. 
* lastly, getting a 500 error when using the same OCI creds as the last test 
```
service.js:38 POST https://50.116.13.49/meta/oci/availabilityDomains 500 (Internal Server Error)
can not create client, bad configuration: asn1: structure error: tags don't match (2 vs {class:0 tag:16 length:13 isCompound:true}) {optional:false explicit:false application:false private:false defaultValue:<nil> tag:<nil> stringType:0 timeType:0 set:false omitEmpty:false} int @2"
```

**Comment by nwmac** [comment] 2021-07-02 10:47
@slickwarren I've fixed the refresh issue (https://github.com/rancher/dashboard/pull/3372)

For the other 2:

> when trying to provision an OCI cluster on RKE1, I get the following error:
This worked for me

> lastly, getting a 500 error when using the same OCI creds as the last test
I don't have an environment to test this - can you check again and provide more detail or an enviornment I can use to test.

**Comment by slickwarren** [comment] 2021-07-16 20:51
on master-head (44bb5b4):
* enable/disable generic node driver
  * single -- pass
  * multiple -- pass
* provision a cluster with one of the generic node drivers (OCI) -- pass

**Closed by slickwarren** 2021-07-16 20:51 UTC
Labels: QA/XS, [zube]: QA Working, area/cluster, tmp-clusterprov
