### ISSUE TITLE
UX for sensitive information

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#720] opened 2020-06-02 22:48 UTC
eg secret data: Ember UI employs a click-to-show option, Dashboard always shows the information.
What fields should be click-to-show? What fields should always be hidden (outside creation)?

**Comment by deniseschannon** [comment] 2020-10-12 22:54
Review what hte UX is in Secrets to see how we might want to design something for secrets in Dashboard

**Comment by lvuch** [comment] 2020-10-29 19:35
https://xd.adobe.com/view/3cf0dddb-70e3-4309-885f-f8d847399a0d-69a3/

**Comment by sadiapoddar** [comment] 2020-11-06 02:36
It's very easy to reproduce this issue,  skipping to list the exact steps since it's not secure.

**Comment by sadiapoddar** [comment] 2020-11-10 23:01
Verified the fix 2.5.-head, v2.5-0cdbf1562a1b298cc319ca4b93294e052a932654-head
1. show button shows the secret in plain test
2. But looks like the fix has some issue, there is "show value", once you click on it there is no "hide value" toggled from the "show value" 
Comment about the fix. 
1. Since we can always download the secret, wondering is there any use case where we need to show the value in plain text in UI? 
2. Instead of "show value" can it be "show" once you click on it,  it should toggle to "hide"?

**Comment by vincent99** [comment] 2020-11-10 23:08
- [ ] Show/hide should be remembered as a user pref
- [ ] Show/hide button has no space separating it from the view buttongroup. Why is it yelling at me?  Maybe it should go closer to the actual data its toggling. @lvuch 
- [ ] I think a `[ hide icon | show icon ]` button group would be more clear than a button that toggles to show the state you're not in...

There are too many modes and ideas still half-implemented in here:

- [ ] Individual values shouldn't have the `[Show Value]` toggle anymore, it's now at the top and operates on all fields.
  - [ ] For a regular ascii short value, show the whole value (in dotsfont if hidden)
  - [ ] For a long ascii value, show the first `LARGE_LIMIT` bytes and then a "+ x,xxx bytes more" link (that looks like one, not white monospace text) to show the rest
  - [ ] For a non-ascii value, show "x,xxx binary bytes" (regardless of show/hide toggle)

- [ ] Some values go in a big copy box, some have a tiny copy button at the end, some have none at all.  Pick one.
  - [ ] I think the outlined boxes are good for the special views of a e.g. Cert with a couple known fields, but a little much for opaque secret table.
  - [ ] Copy should always be available on every field, regardless of whether it's shown or hidden, public or secret, ascii or binary. (certificate public certs aren't copyable)

- [ ] Values aren't being be force-wrapped, if you look at a service acct token the token is 5000px wide.

**Comment by sadiapoddar** [comment] 2020-11-16 22:50
The fix looks good, but need more works in terms of the "show/hide" button, currently, it shows two eyes, 
<img width="572" alt="Screen Shot 2020-11-16 at 2 29 23 PM" src="https://user-images.githubusercontent.com/72409237/99317048-3944c100-281a-11eb-8f28-c88f2bc53e75.png">

If users click any of one of these eyes, it toggles the content. So we don't need to have two of them, 
The default should in hiding mode, on click ideally we need password verification to toggle to the cleartext. 

Another issue I am seeing in hide mode, hide the namespace name, which is not sensitive data.
<img width="584" alt="Screen Shot 2020-11-16 at 2 18 34 PM" src="https://user-images.githubusercontent.com/72409237/99317429-e6b7d480-281a-11eb-9d1b-de5c1bda3a0c.png">

**Comment by vincent99** [comment] 2020-11-17 02:33
The two eyes are what I asked for (though the icon comes out a little small); is a button group in which you pick one of the two options, not a button that toggles itself.  Same as the overview/yaml group next to it.

The purpose of this is to prevent someone over your shoulder from casually seeing secret values.  It doesn't prevent you from seeing or knowing them; you have access to see them any number of other ways (e.g. kubectl).  A password to toggle the option is not needed.

That particular value looks like a service accounts, so it could have a special format for displaying the data, but doesn't currently.  So it's just being displayed like a generic secret, and for those there's no way for us to know which parts of it may be sensitive or not.

**Comment by sadiapoddar** [comment] 2020-11-17 17:27
Hi Vince,

In current implementation, there are two eyes, one crossed and other is opened. If I click on the crossed one, the secret content shows as clear text, if I click on the crossed eye again the secret content  hides. The same thing with the opened one, if I click on it the secret shows in plain text.  If I click on it again, it hides the secret. So looks like these buttons are implemented with toggle functionalities and both button are doing the exact same thing which is redundant. It’s’ confusing for the users and also doesn’t match with the convention implementation where only one eye button is used to show/hide content.

If we don’t need password protection to show, it’s okay we can skip that part.

Thanks
-Sadia

**Comment by sadiapoddar** [comment] 2020-11-17 17:30
Hi Vince,

In the current implementation, there are two eyes, one crossed and the other is opened. If I click on the crossed one, the secret content shows as clear text, if I click on the crossed eye again the secret content hides. The same thing with the opened one, if I click on it the secret shows in plain text.  If I click on it again, it hides the secret. So looks like these buttons are implemented with toggle functionalities and both buttons are doing the exact same thing which is redundant. It’s’ confusing for the users and also doesn’t match with the convention implementation where only one eye button is used to show/hide content.

If we don’t need password protection to show, it’s okay we can skip that part.

Thanks
-Sadia

**Comment by sadiapoddar** [comment] 2020-11-30 19:32
Verified the fix 2.5-head 9ee39b9, and mater-head, a549b47.
steps.
1. In explorer, click on the secrets
2. click the hide(crossed eye) or show(open eye)
Looks like the fix is done having two eyes group button and it's working as expected.

**Comment by sadiapoddar** [comment] 2020-11-30 19:38
Closing this issue as the fix is working as it's designed and implemented.

**Closed by sadiapoddar** 2020-11-30 19:38 UTC
Labels: [zube]: To Test, area/general, reopened
