### ISSUE TITLE
[BUG] Unable to Install or Update Helm Apps after upgrade to 2.7.1

### ISSUE THREAD

**Issue by Notumlo** [rancher/dashboard#10011] opened 2023-03-10 15:16 UTC
**Rancher Server Setup**
- Rancher version: 2.7.1
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): k3s 1.24
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: v1.24.9+k3s2
- Cluster Type (Local/Downstream): Downstream
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider): Imported k3s cluster on Ubuntu

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom)
  - If custom, define the set of permissions:
Admin

**Describe the bug**
After updating our Rancher instance from 2.6.9 to 2.7.1 (stable) we can no longer install or update any apps under **Cluster Explorer > Apps > Charts** on our downstream cluster. When clicking the "Install" button the next page is blank and in the browser network output i can see a 404 error: 

```
{
"type": "error",
"links": { },
"code": "NotFound",
"message": "apps.catalog.cattle.io \"rancher-monitoring\" not found", (replace rancher-monitoring with any other app name)
"status": 404
}
```
The same does not occur on the local cluster, installs and updates work fine. 

This is our test instance of Rancher so only have 1 downstream connected, therefore unsure if this is a problem with this specific cluster or any other that would be managed by this Rancher instance

No obvious errors in the Rancher logs or downstream clusters cattle-agent logs 

If i revert Rancher back to 2.6.9 (VM Snapshot) the problem goes away and i can again install/update apps.

**To Reproduce**
Update Rancher from 2.6.9 to 2.7.1

**Result**

**Expected Result**
Should be able to install and update Apps using the Rancher App UI.

**Screenshots**

**Additional context**

**Comment by richard-cox** [comment] 2023-11-02 14:47
This probably has been resolved via https://github.com/rancher/dashboard/pull/9440, which was merged to 2.7.7. Can you upgrade and see if you still see the issue?

**Comment by richard-cox** [comment] 2024-04-25 15:37
No update, closing

**Closed by richard-cox** 2024-04-25 15:37 UTC
Labels: kind/bug, teams/mapps

**Comment by nandlalushir** [comment] 2024-10-01 07:02
The issue is still present. I am facing the same problem, and even after trying with the REST API, the installed apps do not upgrade.
