### ISSUE TITLE
Enabling Azure AD with Custom Endpoint fails

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2385] opened 2021-02-23 06:33 UTC
**Verified on 2.5-head commit if: `a85f4d1 `**

- Enable Azure AD -- Custom
- Enter Graph Endpoint, Auth Endpoint and Token Endpoint input fields.
- Values are NOT seen when user types/pastes the input in these Graph Endpoint, Auth Endpoint and Token Endpoint input fields.
- But when user clicks on Enable, these fields' values are sent (appear for a second in the input fields)
- But error seen on the UI
<img width="1028" alt="Screen Shot 2021-02-22 at 10 12 01 PM" src="https://user-images.githubusercontent.com/26032343/108809503-d3c14880-755d-11eb-9462-6ddbff55e6fc.png">

**Comment by richard-cox** [comment] 2021-02-23 11:38
Duplicate of #2349

**Closed by richard-cox** 2021-02-23 11:38 UTC
Labels: [zube]: Next Up, kind/bug
