### ISSUE TITLE
Hide Rancher's automatically created RBAC namespaces from users

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#6465] opened 2022-07-22 19:17 UTC
Every time you add a namespace to a project, Rancher automatically creates a separate namespace in the `local` cluster to keep track of RBAC for the project. When you delete a namespace, Rancher also deletes the corresponding RBAC namespace on the local cluster.

From an end user's perspective, this behavior looks strange as it is not immediately obvious what the namespace is for, or why Rancher is auto-deleting namespaces.

Recently I created a PR to make the namespace results consistent in the Projects/Namespaces page and the top nav filter options in Cluster Explorer. https://github.com/rancher/dashboard/pull/6394 We made it consistent by taking the system namespace filters out of the list to make it consistent with the top nav. However, we received feedback from QA that when you can see these system namespaces being automatically created and deleted, it looks like a bug. It would also be bad if a user deleted these auto-created namespaces because they would lose role bindings for cluster and would need to restore the cluster from backup. So the new approach is to filter the system namespaces for RBAC from both the Projects/Namespaces list AND the top nav.

**Comment by jameson-mcghee** [comment] 2022-08-01 18:06
@catherineluse, good news and bad news lol
Good News:
In v2.6-head, I am no longer seeing the RBAC Namespaces being added to the "Not in a Project" project.

v2.6-head RBAC Namespaces not present after creating a new Project and Namespace:
![image.png](https://zube.io/files/rancher/6169481f372b15135f9e04f8ecc489c9-image.png)
![image.png](https://zube.io/files/rancher/72f39aeaa9e4608be935908a930a7466-image.png)
![image.png](https://zube.io/files/rancher/917d2a000c764a64005d9bd60ebd4681-image.png)


Bad News:
During testing I noticed what looks like a regression of the fix for ticket [6387](https://zube.io/rancher/dashboard-ui/c/6387). When I add a new Namespace to a project, I have to refresh the page before Namespace is present in the UI grid. Therefore I am Reopening this ticket

v2.6-head new Namespace not present in UI until after refresh:
![image.png](https://zube.io/files/rancher/e30ef9d541cdefe5030dda8654472d54-image.png)
![image.png](https://zube.io/files/rancher/42454af53e64d74d59f97b0f71409a8b-image.png)

**Comment by jameson-mcghee** [comment] 2022-08-01 21:20
@catherineluse, I was just informed about GitHub ticket [6565](https://github.com/rancher/dashboard/issues/6565) which is also tracking the issue I observed separately. Therefore I am going to close this ticket, because the overall Acceptance Criteria have been met (as seen in my previous screenshots).

**Closed** 2022-08-01 21:20 UTC
Labels: [zube]: Reopened, QA/XS, kind/enhancement, team/area2
