### ISSUE TITLE
Cluster Management Cluster Node/Node Pool lists fail to show

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#4711] opened 2021-12-06 11:06 UTC
For a successfully imported cluster the node / node pool tab fails to show in the Cluster Management Cluster detail page

**Comment by davidnuzik** [comment] 2021-12-08 19:20
Reopening. I could not reproduce this.
 
**Reproduction Environment:**

Rancher version: `v2.6-a015b10b4ee838ca7961caf6ed1279e8011d1ba8-head` (build from about 5 days ago, before the change was merged in); v2.6.1 also attempted
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: imported k3s
Downstream K8s version: 1.21
 
**Reproduction steps:**

1. Import any cluster. In my case I created a 1-node K3s 1.21 cluster and imported this into Rancher.
2. Notice, the management cluster shows the machine pools tab.
 
![image](https://user-images.githubusercontent.com/45179589/145269161-e4c8bfc0-08e7-4a39-bc68-232a2cf3bce7.png)

**Additional Info:**
Is it possible I am misunderstanding the issue? No steps to reproduce were provided so I am assuming this is the right way to test this.

**Comment by richard-cox** [comment] 2021-12-09 13:42
@davidnuzik You're doing the correct steps to reproduce, however I can't tell you when this broke. There was logic that required the imported cluster's `provisioning.cattle.io.cluster` `provisioner` value to be `imported`... however this now gets updated to `k3s`. This meant we weren't showing the nodes (labelled as machines) list.

**Closed** 2021-12-09 21:20 UTC
Labels: kind/bug, [zube]: QA Next up
