### ISSUE TITLE
tab (`/t`) not stripped from `chart repositories` -> `create` fields, causes error after user adds repo

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#3706] opened 2021-08-06 22:09 UTC
issue on v2.6.0-rc1

Issue: 
tabs are not stripped in the UI, and cause an issue when trying to add a github repository

<img width="1206" alt="Screen Shot 2021-08-06 at 2 48 35 PM" src="https://user-images.githubusercontent.com/16691014/128575115-80144362-2b9b-40f5-b22c-c9d512ca2a4e.png">
<img width="538" alt="Screen Shot 2021-08-06 at 2 48 18 PM" src="https://user-images.githubusercontent.com/16691014/128575116-e2298a1d-0a01-46d1-a31a-56f746adc868.png">

Expected Result:
Whitespace should be either stripped or alert the user before the resource is created

**Comment by richard-cox** [comment] 2021-08-07 08:00
@codyrancher Is this covered by the other white space issue we have (couldn't find it) or is this one specifically split out from it?

**Comment by nwmac** [comment] 2021-08-17 12:29
We should strip the whitespace

**Comment by rak-phillip** [comment] 2021-08-17 15:29
This seems very similar to #3794, I'll double-check that tabs are addressed in the fix for that one

**Comment by rak-phillip** [comment] 2021-08-17 17:10
We can mark this one as a duplicate of #3794 - issue has been resolved in PRs #3878 & #3879

@slickwarren @nwmac

**Comment by neillsom** [comment] 2021-08-31 09:48
@rak-phillip Leaving this in 'working' for now until rancher/dashboard#3794 is resolved

**Comment by neillsom** [comment] 2021-08-31 10:50
@rak-phillip approved rancher/dashboard#3794

**Comment by sgapanovich** [comment] 2021-09-28 15:46
Reproduction:
was able to reproduce the issue on v.2.6.0-rc1

==================================

Testing Environment:
Rancher version: v2.6-fe57abd77598577487eb5722aba7bc1eebb50d70-head
Rancher cluster type: single-node docker install
Docker version: 20.10

Downstream cluster type: n/a
Downstream K8s version: n/a

-----------------------------------------------------

Confirmed that leading and/or trailing spaces are removed before a user saves the chart
- for both targets (URL and GIT)
  - spaces removed on mouse click on any other area
      - on "Save" click the spaces removed before the PUT/POST request is made 

![url spaces.gif](https://zube.io/files/rancher/ee5cb4ecd53fe15a355278f99c7d5958-url-spaces.gif)

Confirmed that repos can be added/edited/deleted

**Closed** 2021-09-28 15:46 UTC
Labels: [zube]: To Test, kind/bug-qa
