### ISSUE TITLE
BUG：Rancher Standard User，Create Deployment Page

### ISSUE THREAD

**Issue by xzxiaoshan** [rancher/dashboard#4941] opened 2022-01-19 09:03 UTC
The bug has been submitted to the issue of rancher.

Link：
[https://github.com/rancher/rancher/issues/36188](https://github.com/rancher/rancher/issues/36188)

**Comment by richard-cox** [comment] 2022-01-19 09:06
@xzxiaoshan Please can you provide more detail? What is the error and what are the steps to reproduce?

**Comment by xzxiaoshan** [comment] 2022-01-20 00:46
@richard-cox 
#### Step 1：create Standard User（testbug）
![image](https://user-images.githubusercontent.com/16459864/150240922-0c93d607-d27c-490a-884e-0ac351887ba8.png)

#### Step 2：User（testbug）Login
![image](https://user-images.githubusercontent.com/16459864/150241276-d08bd8c2-efc0-4be3-b10f-f34ca752b5e4.png)

#### Step 3：Project: Create

#### Step 4：Secret: Create

#### Step 5：Deployment: Create
【Key Point】
![image](https://user-images.githubusercontent.com/16459864/150241786-1ceb62c3-cec9-45c5-b1e9-58c0ca2196d0.png)

---

#### 【Bug reason】
![image](https://user-images.githubusercontent.com/16459864/150241870-9bd42ec7-1b49-4715-ae2c-bbaeb61076aa.png)

**Comment by xzxiaoshan** [comment] 2022-01-20 00:51
@richard-cox 
https://rancher.xxxxxx.com/k8s/clusters/c-9a3uf/v1/nodes
【Manager User/admin】success
【Standard User/xxx】failed

**Comment by xzxiaoshan** [comment] 2022-01-20 11:32
@richard-cox 
Now I need to manually add an API to "standard user". How should I fill it in? 3Q

![image](https://user-images.githubusercontent.com/16459864/150330873-9f263621-1ebd-499a-910e-b6f56f008f00.png)

**Comment by xzxiaoshan** [comment] 2022-01-20 12:03
I tried to add nodes (get, list), which is invalid after saving

**Comment by richard-cox** [comment] 2023-11-09 15:35
1. The secret needs to be of type `kubernetes.io/dockercfg` or `kubernetes.io/dockerconfigjson`. I've made a change that will make that filtering cleared. Note - We don't currently support making those directly in the UI. 
2. Service Accounts are different to secrets
3. Looks like the node based comments are a different issue

**Comment by aalves08** [comment] 2024-04-17 16:46
Based on https://github.com/rancher/dashboard/blob/master/cypress/e2e/blueprints/nav/fake-cluster.ts, IF workload page is browsable, tooltip can be asserted. Adding label `automation-candidate`.

**Comment by nwmac** [comment] 2024-05-07 11:20
@richard-cox So, did we 'just' add a tooltip? In terms of test automation, what would you recommend we do?

**Comment by richard-cox** [comment] 2024-05-07 12:11
Correct. I took the bug here to be that it's not clear only some types of secret are allowed. There are other points mentioned, though aren't clear enough to action.

Could write a unit test to confirm the text in the tooltip, either unit or e2e. Not quite sure it's worth it though

**Comment by IsaSih** [comment] 2024-06-19 00:15
Tooltip is present in pull secrets component. Are we still considering to add a unit test for this?

**Comment by IsaSih** [comment] 2024-06-19 03:47
@yonasberhe23 and I agreed to close the issue.

**Closed by IsaSih** 2024-06-19 03:47 UTC
Labels: kind/bug, QA/manual-test, automation-candidate
