### ISSUE TITLE
Project is created with resource quota even after the quota is removed

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5173] opened 2022-02-18 22:19 UTC
This issue may require both back and and front end changes, but I'm opening the dashboard ticket to track the front-end aspect described in [this comment](https://github.com/rancher/rancher/issues/35688#issuecomment-1026655227). The original issue is here: https://github.com/rancher/rancher/issues/35688

To reproduce (steps are copied from the [other issue](https://github.com/rancher/rancher/issues/35688#issuecomment-1026655227)):

1. Create a new project. In the Project creation dialog, add a Quota item, insert specific numbers for the Project Limit and Namespace Default Limit (for example, choose Config Maps and set both Project Limit and Namespace Default Limit to 50) - do not click Create
2. Then remove the Quotas by clicking remove while still within with the Project creation dialog
3. The Quota item disappears as expected
4. Then click Create to create the Project
5. The Project is created with the Quota even though it was removed.

Similar issue: https://github.com/rancher/dashboard/issues/4047

**Comment by gaktive** [comment] 2022-04-28 22:20
Internal reference: SURE-4533

**Comment by gaktive** [comment] 2022-04-28 22:27
Per https://github.com/rancher/rancher/issues/35688, this points more as more UI now.

**Comment by aalves08** [comment] 2022-05-12 14:08
Moved to Backend Blocked as being dependent of https://github.com/rancher/rancher/issues/37704

**Comment by aalves08** [comment] 2022-05-12 14:09
Changes merged improved code and mitigate of a couple of minor issues regarding this topic. Also, brings a consistent way for the BE to reproduce the issue in https://github.com/rancher/rancher/issues/37704

**Comment by gaktive** [comment] 2022-05-13 22:46
Since there's some circular information elsewhere, I'll see if I can straighten things out.

https://github.com/rancher/rancher/issues/35688 is the original expected backend work. https://github.com/rancher/rancher/issues/37704 was marked a duplicate of that and closed.

At one point, 35688 was to be transferred to dashboard but now seems to circle back to backend again per this PR: https://github.com/rancher/dashboard/pull/5841.

**Comment by KevinJoiner** [comment] 2022-05-18 15:38
@aalves08 I believe the solution will need to be implemented in the dashboard https://github.com/rancher/rancher/issues/35688#issuecomment-1130046378

**Comment by aalves08** [comment] 2022-05-18 15:39
@KevinJoiner Thanks for the update! Much appreciated! Looking into it as we speak 👍

**Comment by timhaneunsoo** [comment] 2022-05-31 19:54
### Test Environment: ###
Rancher version: v2.6-head 68c6c13
Rancher cluster type: HA
Docker version: 20.10

----------

### Testing: ###

Tested this issue with the following steps:
1. Create a new project. In the Project creation dialog, add a Quota item, insert specific numbers for the Project Limit and Namespace Default Limit (for example, choose Config Maps and set both Project Limit and Namespace Default Limit to 50) - do not click Create
2. Then remove the Quotas by clicking remove while still within with the Project creation dialog
3. The Quota item disappears as expected
4. Then click Create to create the Project
5. The Project is created with the Quota even though it was removed.

**Result** - Pass

Project is created without the Resource Quota
![image.png](https://zube.io/files/rancher/cf2927c4e475d32dde17ff0277b4af29-image.png)

**Closed by timhaneunsoo** 2022-05-31 19:54 UTC
Labels: kind/bug, [zube]: To Test, internal, priority/1, team/area2, area/project-quota, size/2, JIRA
