### ISSUE TITLE
Scroll bar missing on "Add Project Member" and "Project Permissions" therefore not all role

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#6499] opened 2022-07-26 12:46 UTC
Internal Reference: SURE-4934

Create a few project roles.

Go to the local cluster -> Cluster -> Projects/Namespaces.

Choose a project and from the three dots, choose 'Edit Config'. Click 'Add' beneath members.

Shrink the height of the browser window - dialog does not scroll, so you can't access the buttons or see all of the content:

![image](https://user-images.githubusercontent.com/1955897/181009017-640ccca9-e7bc-402a-a247-d7f0f76face4.png)

**Comment by nwmac** [comment] 2022-07-26 12:54
This issue was fixe din 2.6.7 by another PR.

To Test:

Follow instructions above.

UI should now show a scroll bar along the right-hand side of the dialog:

<img width="693" alt="image" src="https://user-images.githubusercontent.com/1955897/181010765-6c5f2fd4-548c-4973-af95-44c2a668aebc.png">

**Comment by markusewalker** [comment] 2022-07-28 17:40
While we wait for the new PR to be merged, reproduced this behavior in `2.6.6`.

**ENVIRONMENT DETAILS**
- Rancher Install: Docker
- Rancher version
     - Reproduced version: `v2.6.6`
- Browser: Chrome

**TEST RESULT**
REPRODUCED

**REPRODUCTION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Navigated to Cluster Explorer > Users & Authentication > Roles > Project/Namespaces.
3. Created multiple placeholder project roles (I created five).
4. Navigated to Cluster Explorer > local > Cluster > Projects/Namespaces.
5. Clicked `Create Project` > `Add` member.
6. Minimized the window and verified that no scrollbar appears:
![image](https://user-images.githubusercontent.com/52591819/181602424-a309f6ce-67a0-41be-8834-3848076b0288.png) 
     - Full screen view looks like this:
![image](https://user-images.githubusercontent.com/52591819/181602397-823b4143-f15d-4a5b-8c83-ba392a033f7f.png)

**Comment by markusewalker** [comment] 2022-08-01 15:29
Verified that this is addressed on `v2.6-head` https://github.com/rancher/rancher/commit/93a4f30d9c361c8c274f58ebdff73e4f6cc45a81.

**ENVIRONMENT DETAILS**
- Rancher Install: Docker
- Rancher version
     - Reproduced version: `v2.6-head` https://github.com/rancher/rancher/commit/93a4f30d9c361c8c274f58ebdff73e4f6cc45a81
- Browser: Chrome

**TEST RESULT**
PASS

**VERIFICATION STEPS**
1. Setup Rancher and navigate to the UI in a browser.
2. Navigated to Cluster Explorer > Users & Authentication > Roles > Project/Namespaces.
3. Created multiple placeholder project roles (I created five).
4. Navigated to Cluster Explorer > local > Cluster > Projects/Namespaces.
5. Clicked `Create Project` > `Add` member.
6. Minimized the window and verified that a scrollbar now appears:
![Aug-01-2022 08-26-50](https://user-images.githubusercontent.com/52591819/182184769-6485d8f2-c47a-411c-88a2-dc2d77abef39.gif)

**Closed by markusewalker** 2022-08-01 15:29 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, team/area2, JIRA
