### ISSUE TITLE
Vue3: KeyValue component doesn't render 'values' when editing secrets

### ISSUE THREAD

**Issue by mantis-toboggan-md** [rancher/dashboard#11747] opened 2024-08-28 15:38 UTC
**Describe the bug**
The KeyValue component is not rendering values when editing secrets. 

**To Reproduce**
Navigate to the cluster explorer secrets view
Edit an existing secret that has key:value pairs defined

**Result**
The 'Values' column of inputs is empty

**Expected Result**
The 'values' inputs should be populated

**Screenshots**

![Screenshot 2024-08-28 at 8 35 54 AM](https://github.com/user-attachments/assets/0cdfb462-956d-4ba2-8e0f-5dee3593daec)

![Screenshot 2024-08-28 at 8 36 09 AM](https://github.com/user-attachments/assets/017ff111-7dea-423f-998e-61d8c731983b)

**Comment by codyrancher** [comment] 2024-09-16 22:50
This appears to be working as intended now. It appears someone else has already resolved this issue. Moving to test.

https://github.com/user-attachments/assets/61314f31-135e-48a3-95b0-9c7643923bec

**Comment by IsaSih** [comment] 2024-09-19 23:42
Tests pass on v2.10-61d79963733364046c6fc8e9003bd9d6948a6db0-head, dashboard version master f9d6f31

**Closed by IsaSih** 2024-09-19 23:42 UTC
Labels: kind/bug, QA/dev-automation, area/vue3
