### ISSUE TITLE
Kubernetes label not saved properly through Continuous Delivery -> Edit Config (Edit YAML works)

### ISSUE THREAD

**Issue by peteingithub** [rancher/dashboard#4598] opened 2021-11-19 13:47 UTC
**Setup**
Rancher version: 2.6.3-rc1 (3 node k3s KVM setup, 2 node k3s downstream cluster v1.21.5, 2 node RKE1 downstream cluster v1.21.6)
Browser type & version: Chrome 89.0.4389.90 (Official Build)

**Describe the bug**
Rancher Main Menu -> Continuous Delivery -> Clusters -> [cluster] -> ... -> Edit Config -> Add Label -> [label:value] -> Save

**To Reproduce**
Steps above.

**Result**
Go back to Edit Config (or click the cluster) -> Label and value are missing, Cluster Grouping does not work. 

**Expected Result**
Label and value should be set and saved. 

With Edit YAML setting a label works.

**Screenshots**
![image](https://user-images.githubusercontent.com/86831399/142632818-167c3e8f-5911-41d3-9ff2-6416007a3f8f.png)

![image](https://user-images.githubusercontent.com/86831399/142632898-18b68c6e-f202-4657-8ef3-b62cdfc7cea9.png)

**Additional context**

**Detailed Description**

**Context**

**Comment by richard-cox** [comment] 2021-11-19 13:50
Duplicate of https://github.com/rancher/dashboard/issues/4310

**Closed by richard-cox** 2021-11-19 13:50 UTC
