### ISSUE TITLE
If I create new cluster & add a new user, they can't create anything because there is no project

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#2024] opened 2020-12-08 21:46 UTC
Steps:
1.  Create a local user (name him user1)
2.  Add a new cluster & add user1 as member
3.  Go to cluster Explorer

Results:  All the workload & service discovery section is missing.  Also all the Create buttons are missing.  If I go back to Cluster Manager and add a project & namespace, then I can see everything just fine.

**Comment by catherineluse** [comment] 2022-08-12 00:11
Related issue https://github.com/rancher/dashboard/issues/5306

**Comment by gaktive** [comment] 2022-11-14 23:56
Closing as a duplicate of the related issue, though I'll copy the missing info there for posterity.

**Closed by gaktive** 2022-11-14 23:56 UTC
Labels: kind/bug, area/namespace, area/cluster, area/authentication, [zube]: Backlog
