### ISSUE TITLE
Download kubeconfig for a cluster

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#2904] opened 2021-05-05 13:35 UTC
- In ember this was a `Kubeconfig File` button in the cluster dashboard page
- We should add this possibly in a similar place, in the new cluster dashboard page

**Comment by vincent99** [comment] 2021-05-12 00:24
Dupe of https://github.com/rancher/dashboard/issues/2898

**Closed by vincent99** 2021-05-12 00:24 UTC
Labels: [zube]: To Test
