### ISSUE TITLE
Cluster - Individual Overview page (dashboard)

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#350] opened 2020-03-05 20:22 UTC
Overview Page (Dashboard)

https://xd.adobe.com/view/1c6215de-c2a2-424e-5748-bd49cd49606d-6a53/screen/8e167eb2-3bf1-4277-894b-a4386b424dcb/Cluster-Details-Main-Dashboard

**Comment by tfiduccia** [comment] 2020-03-25 20:13
Deployed -  bugs will be tracked in newly created issues

**Comment by tfiduccia** [comment] 2020-04-17 19:57
There are some outstanding issues that can be found by associated link, but otherwise ready for QA.

**Comment by deniseschannon** [comment] 2020-04-24 22:29
Changes to columns in Cluster Overview:

<img width="709" alt="Screen Shot 2020-04-24 at 3 25 04 PM" src="https://user-images.githubusercontent.com/11410997/80261637-d56d6780-863f-11ea-9507-d568d9ec9e34.png">

[ ] Move the Memory graphs to be under the CPU usage into the 2nd column
[ ] Move Pods to the 3rd column
[ ] Follow mock for the 4th column. Showing `Total Nodes` and removing `Nodes` from the roles. Reasoning: it was confusing that it could show 1 worker node, 1 etcd node, 1 control plane node, but there is really only 1 node. 

@westlywright 
Question: What currently populates the `state` in Unhealthy Nodes section?

**Comment by westlywright** [comment] 2020-04-27 19:39
@deniseschannon Sorry I missed your question. Currently only nodes that do not have a healthy or active state will be pushed into the unhealthy nodes section.

**Comment by tfiduccia** [comment] 2020-05-04 20:26
@deniseschannon 
Numbers for Worker, etcd & Ctrl plane are missing now?  Is that by design?

**Comment by deniseschannon** [comment] 2020-05-04 21:22
Yes, by design/requirements, we've removed it.

Nodes don't translate directly to roles as one node can have multiple roles. It was looking weird when you would have 1 etcd, 1 worker, 1 control plane on the overview, but you really only had 1 node. 

If any of the nodes are unhealthy, they will show up in the "Unhealthy Nodes" section, which lists which roles they play.

**Comment by deniseschannon** [comment] 2020-05-04 21:55
## Detail Page

### Opaque Type

- [ ] Somehow the protip is underneath the Title

<img width="641" alt="Screen Shot 2020-05-04 at 2 36 53 PM" src="https://user-images.githubusercontent.com/11410997/81016181-d018d580-8e14-11ea-8fc3-c8d0bf7628e1.png">

Overall, there are some design issues that will be taken care of other issues (KeyValue component https://github.com/rancher/dashboard/issues/589, masthead https://github.com/rancher/dashboard/issues/538#issuecomment-623722980)

**Comment by deniseschannon** [comment] 2020-05-04 23:44
- Test local and downstream clusters 
- Test what unhealthy nodes and gatekeeper violations look like and show up as. 

Note: Due to https://github.com/rancher/dashboard/issues/559 where you can't create OPA resources on `master-head`, you can use the `master` branch of the UI on a 2.4 setup. 

change v3/settings/dashboard-index to point to "latest"

"latest" is for master
"release-2.4" is for 2.4

**Comment by izaac** [comment] 2020-05-08 18:49
For the Unhealthy Nodes info box could we get a list or mapping of the different states that Rancher/K8s would consider a node Unhealthy. K8s has the following state types as per the documentation:

Condition Types: 

- MemoryPressure
- DiskPressure
- PIDPressure
- Ready

So far the only one I could get into the Unhealthy info box was the `Unavailable` (not Ready)

I also tried DiskPressure but it doesn't appear in the info box for me:

![Screen Shot 2020-05-08 at 10 45 47 AM](https://user-images.githubusercontent.com/27659/81438555-d616fb00-9121-11ea-9dd2-81908cb38fe2.png)
![Screen Shot 2020-05-08 at 10 43 24 AM](https://user-images.githubusercontent.com/27659/81438646-f5158d00-9121-11ea-946c-8010ea1183ec.png)

![Screen Shot 2020-05-08 at 10 45 00 AM](https://user-images.githubusercontent.com/27659/81438687-02cb1280-9122-11ea-82a8-fa4edb48da28.png)

**Comment by westlywright** [comment] 2020-05-11 17:20
@deniseschannon Perhaps we need to define the requirements better around what and what is not included in these boxes re: @izaac comment above. We were able to look at the disk pressure scenario and the state of these nodes is still healthy, which is why they don't show up in the `Unhealthy Nodes` box. The diskpressure warning among others are on the conditions for a node and do not change the state. Maybe these should be rendered elsewhere as we do in Ember Rancher?

**Comment by izaac** [comment] 2020-05-21 00:00
Cordoned node is listed as Unhealthy node:

![Screen Shot 2020-05-20 at 4 59 42 PM](https://user-images.githubusercontent.com/27659/82508905-54c54e00-9abb-11ea-9fff-c25e011af410.png)

**Comment by deniseschannon** [comment] 2020-05-22 21:43
Noticed that we don't have a place for `description` of a cluster on the overview page.

**Comment by deniseschannon** [comment] 2020-05-23 05:05
@westlywright I'm curious to how we determined that the cordoned node was cordoned in this view because I know we had to explicitly set it in the node list view.

**Comment by westlywright** [comment] 2020-05-28 22:55
@deniseschannon We loop through all the nodes and look for nodes that are not `healthy` or `active`. This list can be expanded but I didn't want to do that until we had stronger requirements around what is included here.

**Comment by izaac** [comment] 2020-07-02 22:40
There are still items to address 

- Description https://github.com/rancher/dashboard/issues/350#issuecomment-632919955
- Nodes health

**Comment by deniseschannon** [comment] 2020-07-13 21:42
The sizzle page is going to be replacing this issue, so going to close this in favor of: https://github.com/rancher/dashboard/issues/819

**Closed by deniseschannon** 2020-07-13 21:42 UTC
Labels: [zube]: Reopened, area/cluster, area/overview
