### ISSUE TITLE
For a standard user that is a Cluster Member, creating a Namespace fails

### ISSUE THREAD

**Issue by igomez06** [rancher/dashboard#3829] opened 2021-08-12 20:52 UTC
on v2.6.0-head on commit-id: 0784199

**Repro Steps:**

- Login as Admin
- Create a RKE2 Cluster
- Create a standard user 
- Assign this user with Cluster Member for the cluster
- Login as the user ^^.
- Create a project.
- Attempted to create a Namespace. 

**Result:**

The Create Namespace call fails with this error: `Method POST not supported`

**Additional context:**
The creating Namespace may work at first, so create and delete a Namespace several times to get this error. After creating and deleting a few times, the create namespace calls always fails. 

**API request:**
```
{type: "error", links: {}, code: "PermissionDenied", message: "Method POST not supported", status: 403}
code: "PermissionDenied"
links: {}
message: "Method POST not supported"
status: 403
type: "error"
```

**Screenshot:**
![image](https://user-images.githubusercontent.com/2364045/129268071-66340087-050d-4a42-84a0-a9b1c688fcac.png)

**Comment by gaktive** [comment] 2021-08-20 16:36
Unable to reproduce this as a non-admin or admin, though it was spotted that the projects page needed to be refreshed to load properly.

@mantis-toboggan-md can you see if you can repro this? Vince wasn't able to.

**Comment by mantis-toboggan-md** [comment] 2021-08-20 16:38
Yeah I'll take a stab today.

**Comment by mantis-toboggan-md** [comment] 2021-08-20 22:04
I've created and deleted namespaces over and over without hitting this. I wonder if your UI session has expired and you haven't been logged out properly? @igomez06, if you see this again, what happens when you refresh the page? Still logged in or taken to the login page?

**Comment by igomez06** [comment] 2021-08-20 22:07
@mantis-toboggan-md I actually don't remember, and if I haven't been able to replicate it anymore. It's working fine now. I wonder if that was the issue to being with. .

**Comment by mantis-toboggan-md** [comment] 2021-08-20 22:20
Blehg well I just tested my theory and it was wrong, session timeout correctly boots me to the login screen. It's definitely possible this was inadvertently fixed in the ~7 days since it was reported.

**Comment by kravciak** [comment] 2021-08-25 06:07
I am also not able to reproduce, closing

**Closed by kravciak** 2021-08-25 06:07 UTC
Labels: [zube]: QA Next up, kind/bug-qa
