### ISSUE TITLE
[BUG] Cluster Name is limited to 190 characters

### ISSUE THREAD

**Issue by ldevulder** [rancher/dashboard#3533] opened 2021-07-22 08:54 UTC
When you try to create a new cluster or import an existing one there is an issue when the cluster name as more than 19 characters.

For example, I tried `harvester-loic-provo` and this lead to the cluster stall in `Creating` state with this error message: `clusters.management.cattle.io "harvester-loic-provo" not found`. No issue if I name the cluster `harvester-loic-prv`.

I tried different names with different characters and it's clearly a limitation with the number of characters.

**Comment by richard-cox** [comment] 2021-07-22 08:57
@ldevulder What version of rancher are you using?

**Comment by vincent99** [comment] 2021-07-22 09:28
Close but it's not the number of characters directly, but because it contains a substring of the form`c-xxxxx`.  Shorter only works because you don't have 5 characters after the`c-` anymore.

This is a duplicate of https://github.com/rancher/rancher/issues/33694

**Closed by vincent99** 2021-07-22 09:28 UTC
