### ISSUE TITLE
Global Settings -> Performance

### ISSUE THREAD

**Issue by scures** [rancher/dashboard#8793] opened 2023-05-04 16:22 UTC
**Setup**
- Rancher version: latest `master`

**To Reproduce**

While in https://localhost:8005/c/local/settings/performance, if you refresh multiples times eventually an error will occurs (check screenshoot) and break the UI

We need to look into why it happens and how we can solve it.

**Screenshots**

![image](https://user-images.githubusercontent.com/88777903/236264551-8ca9609c-2b0e-4d37-93e8-a09c462c67ff.png)
**Additional context**

**Comment by richard-cox** [comment] 2023-05-05 10:30
The initial error messages come from the ResourceList component trying to load given a `performance` schema (which isn't a thing). The second probably comes from the sortable table trying to group using a missing schema. 

I couldn't reproduce this locally, either by refreshing and waiting to load, or refresh spamming.

My gut says there's some routing issue going on where it's trying to display a generic resource list for a `settings` product's `performance` resource type. 

@scures Do you have any extensions installed?

**Comment by richard-cox** [comment] 2023-05-05 12:42
Cool. Can you confirm which version of the plug-in you've got? @aalves08 Could this be the overlapping routes issue that i think's fixed in the latest version?

**Comment by aalves08** [comment] 2023-05-05 14:29
@richard-cox it might be. @scures what version of rancher (backend) are you running?

**Closed** 2023-05-18 13:12 UTC
Labels: kind/bug, [zube]: Review, area/performance, team/rke2-qa
