### ISSUE TITLE
Unable to copy/paste from ui log window in 2.7-head

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#7722] opened 2022-12-15 16:09 UTC
**Setup**
- Rancher version: `v2.7-bae32412042cf2320edb828eea254feaecfed1da-head`
- Browser type & version: `chrome Version 107.0.5304.121`

**Describe the bug**

The logs in the ui are now able to be relocated around the ui - ie, click to move to left side of browser window; the logs, however, can no longer be copied with a highlight. ability to copy logs from window is a time saver and facilitates debugging
**To Reproduce**

1. create downstream rke1 cluster (observed this in k8s 1.25, but verified same behavior in k8s 1.24)
2. install [logging](rancher-logging:101.1.0+up3.17.10)
3. in log window that shows install status, try to click and highlight a log line 
**Result**
unable to highlight, copy
**Expected Result**

able to copy, highlight
**Screenshots**

**Additional context**
workaround is to download the logs from the logging window, then highlight and copy text from downloaded logfile.

**Comment by richard-cox** [comment] 2022-12-15 16:13
Closing as dupe of https://github.com/rancher/dashboard/issues/7524

**Closed** 2022-12-15 16:43 UTC
Labels: kind/bug, kind/bug-qa, team/area3
