### ISSUE TITLE
Usage of Storage Provisioner for k3s confusing

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6091] opened 2022-06-02 22:13 UTC
Internal reference: SURE-4008
Reported in 2.6.3
K3s version: 1.21

(Wording gets tricky as there's the initial report and then subsequent investigation that points to UI.)

Issue description:
There is some confusion with respect to the Azure File Share Usage in Rancher 2.6.0 for storage class.

There are two provisioners and the user wanted to know the difference in usage and use case.

- provisioner: kubernetes.io/azure-file
- provisioner: file.csi.azure.com

When using K3S cluster, there is option to select the provisioner.

Business impact:
Without knowing the impact, unable to proceed the further installation. The user is stuck at K3S provisioning on Azure without knowing the impact of using different storage provisioner for K3S. If you could validate the approach and provide the feedback can be the solution here and we don't have much visibility due to the lack of documentation for same.

Two approaches considered:

**Approach 1:**

The Storage class provisioner: kubernetes.io/azure-file which is also in the Rancher UI in any imported cluster.

With the above approach and K3S as the imported cluster, failed to use azure file share. ( as k3s doesn’t have storage driver in it).

And we are not sure which particular driver is needed for this provisioner : kubernetes.io/azure-file

**Approach 2:**

In this approach , installed the Azure File Share CSI driver (as helm chart) in K3S cluster and azure secret from  storage account credentials.

The Storage class in this case has provisioner as: provisioner: file.csi.azure.com and we were able to get the file share created dynamically in the Azure Storage account with a file share.

Installing CSI driver Helm chart: 

https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/charts#install-a-specific-version

Creating azure-secret and storage class and then deploying this custom application which successfully created file share:

https://github.com/kubernetes-sigs/azurefile-csi-driver/blob/master/deploy/example/e2e_usage.md#option2-bring-your-own-storage-account-only-for-smb-protocol

----

Backend already looked into this and it was determined it tied into the UI; they looked into this issue to see where the UI gets the information for the CSI driver and to see how Rancher might be able to display this properly. 

From their understanding, this is a UI issue, and needs to be updated here: https://github.com/rancher/dashboard/blob/master/shell/models/storage.k8s.io.storageclass.js as well as a few other places.

Repro steps:

There is no relevant documentation which is giving the hint to approach this scenario. 

Workaround: none

Actual behavior:
No options to select storage provisioner from Rancher UI for K3S imported cluster.

Expected behavior:
The storage provisioner should be selected from Rancher UI

Files, logs, traces:
No Logs

Additional notes:
Kubernetes project in using CSI driver for Kubernetes instead of traditional in tree Volume plugin

**Comment by brandond** [comment] 2022-06-03 20:35
The crux of the issue is that one of the provisioners is deprecated upstream and may not work, but is marked as supported by the UI. The provisioner that is currently recommended (and should work if deployed properly) is marked as unsupported by the UI. Most likely we just need to update the documentation and UI to track upstream changes to how they recommend deploying the azure-file CSI provisioner.

**Comment by cbron** [comment] 2022-06-22 15:34
This would be question for @snasovich or @jakefhyde

**Comment by jakefhyde** [comment] 2022-09-20 04:37
According to [this](https://kubernetes.io/blog/2021/12/10/storage-in-tree-to-csi-migration-status-update/#timeline-and-status), I think marking current default as deprecated is the right choice, given 1.26's expected release day of 12/6.

**Comment by thaneunsoo** [comment] 2022-12-15 22:04
### Test Environment: ###
Rancher version: v2.7-head a2ef50b
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: imported k3s cluster

----------

### Testing: ###

Tested this issue with the following steps:
1. Import a k3s cluster into Rancher
2. Wait for cluster to be imported successfully
3. Go to explore cluster
4. Install CSIDriver using link in the description https://github.com/kubernetes-sigs/azurefile-csi-driver/tree/master/charts#install-a-specific-version
5. After installation is successful, go to Storage section
6. Create a storage class and verify you can select provisioner

**Result**
User is able to select provisioner when creating storage class whereas before was unable to
![image.png](https://zube.io/files/rancher/64c4f25019b6f1615bd469b71c95059b-image.png)

**Closed** 2022-12-15 22:04 UTC
Labels: kind/bug, QA/S, [zube]: QA Working, priority/1, team/area2, JIRA
