### ISSUE TITLE
Shell doesn't work in Safari

### ISSUE THREAD

**Issue by cogor** [rancher/dashboard#9847] opened 2023-10-04 11:40 UTC
**Setup**
- Rancher version:   v2.7.2
- Rancher UI Extensions:
- Browser type & version: Safari 16.6

**Describe the bug**
Shell doesn't work in Safari, because Safari <16 doesn't support webgl

**To Reproduce**
Open safari
Open cluster Workloads -> Pods -> click "Execute Shell" on any pod
Get an error

**Result**
Got an error 

**Expected Result**
Shell works in Safari

**Screenshots**
![Error](https://i.imgur.com/bXkXoRu.png)

**Comment by cnotv** [comment] 2023-10-04 12:34
It seems like the only unsupported feature is the [WebGL2](https://caniuse.com/webgl2) and is for Safari < 15, which is released in 2021. Not so sure we need such coverage.

**Comment by richard-cox** [comment] 2023-10-04 13:14
@cogor Can you confirm the exact version of safari you see this issue on?

**Comment by cogor** [comment] 2023-10-04 13:23
> Can you confirm the exact version of safari you see this issue on?

Latest, 17.0

xterm-addon-webgl:0.13.0 [just checks browser](https://github.com/xtermjs/xterm.js/commit/3597d43788118869183de05d41b513282b783f98#diff-134444cb2e1d1ec9873fba9fbcd953970e15bbfe53af0f3c86dbbc923254e6a4L35)

**Comment by aalves08** [comment] 2024-01-10 17:12
@yonasberhe23 @izaac we already e2e tests that open the terminal and execute commands, but nevertheless i'll put this issue on your test flow to give it a check. Thank you. 🙏

**Comment by izaac** [comment] 2024-01-10 19:04
This needs manual validation on Safari 17+ which is installed on macOS Sonoma, macOS Ventura, and macOS Monterey.
I'll cover this validation.

**Comment by yonasberhe23** [comment] 2024-01-26 04:11
Moving 'To Test' since this needs manual validation

**Comment by IsaSih** [comment] 2024-04-12 08:51
Tested in Safari 16.6 and shell failed to execute for a different reason, as shown in the screenshot![Screenshot 2024-04-12 at 1.48.51 AM.png](https://zube.io/files/rancher/17364eb9f6537f69fb579b9cad2efc7e-screenshot-2024-04-12-at-1-48-51-am.png)
Shell is being now supported on Safari 16.6, so the purpose of this issue was accomplished.

**Comment by aalves08** [comment] 2024-04-15 16:56
@IsaSih have you tried opening shell via the button on the header? Maybe the pod has some error of some sort...

**Comment by IsaSih** [comment] 2024-04-19 00:43
So, I was able to reproduce the error on Google Chrome too. I moved this issue to Done, as one can open the shell in Safari, and I created issue https://github.com/rancher/dashboard/issues/10840 to keep track of this error. 
![Screenshot 2024-04-18 at 3.33.04 PM.png](https://zube.io/files/rancher/1784770d4fef4cead94b8b8ae909d59a-screenshot-2024-04-18-at-3-33-04-pm.png)

**Closed** 2024-04-19 00:44 UTC
Labels: kind/bug, [zube]: Done, QA/manual-test
