### ISSUE TITLE
Unable to edit/upgrade installed apps after upgrading from 2.6.9 => 2.7.0

### ISSUE THREAD

**Issue by ChrML** [rancher/dashboard#7697] opened 2022-12-12 09:48 UTC
In this version, the upgrade page is blank.

![image](https://user-images.githubusercontent.com/38761430/207014211-ceb557ce-66a9-406a-8ff1-4b2cffc5cbf9.png)

When I click the yellow version label:

![image](https://user-images.githubusercontent.com/38761430/207014303-ea7c393e-c8ff-47db-9cb3-3956616870b6.png)

Additional data from the console log:
![image](https://user-images.githubusercontent.com/38761430/207016222-6a69d8b5-deba-4602-8be8-924ebfe0c5fc.png)

Rancher Kubernetes cluster: v1.23.12
AKS Kubernetes cluster with the apps: v1.24.6
Rancher version: 2.7.0

If i downgrade Rancher back to 2.6.9, this works again as it should.

**Comment by prachidamle** [comment] 2022-12-13 21:54
@gaktive transferred this ticket to UI team to take a look as per the comments above

**Comment by temirg** [comment] 2022-12-21 08:59
Hello UI Team,
any news?

Regards, termirg.

**Comment by gaktive** [comment] 2023-01-04 17:22
Related to (possibly duplicate of): #7808 and

**Comment by richard-cox** [comment] 2023-01-05 10:03
@temirg if there is a SURE issue can you reference the number here please?

I think there's enough in this issue covered by both #7808 and #7787 to warrant closing this one. Once we have the SURE i'll link those two github issues to it

**Closed by richard-cox** 2023-01-05 10:03 UTC
Labels: kind/bug, [zube]: Backlog, kind/bug-qa, team/area3, area/ui

**Comment by temirg** [comment] 2023-01-05 12:13
@richard-cox  sure, its 00500983.
Many thanks!

Regards, temirg.

**Comment by richard-cox** [comment] 2023-01-05 12:48
@temirg sorry I may have misunderstood. You may need to contact your support representative for them to assist us  (dev) with our internal tracking.

**Comment by temirg** [comment] 2023-01-05 12:50
ok, no problem.

**Comment by vincebrannon** [comment] 2023-01-05 13:13
The internal ticket is SURE-5732
