### ISSUE TITLE
Not able to provision RKE2 cluster on Azure

### ISSUE THREAD

**Issue by prabalsharma** [rancher/dashboard#3798] opened 2021-08-11 18:50 UTC
1. on v2.6-9d2e08674b9318e440fb6396c6e168a9c9bdca91-head
2. try to provision RKE2 cluster on Azure with default values

Error:`Cannot read property 'match' of undefined` 

<img width="1435" alt="RKE2onAzure" src="https://user-images.githubusercontent.com/3749546/129085868-f75395af-b06d-4717-89bf-88063b21365f.png">

**Comment by vincent99** [comment] 2021-08-13 00:11
This appears to be that the cluster name was empty and have nothing to do with Azure.  The name is "required" but when you don't provide one we generate one, and the check that they [not be certain names](https://github.com/rancher/dashboard/pull/3616) broke the empty case.

**Comment by richard-cox** [comment] 2021-08-16 10:17
@vincent99 Was there a fix for this, it looks like this is caused by https://github.com/rancher/dashboard/pull/3616/files#diff-da140a408fe7cabaef6dd36abf7dabe1a0ec570bd7bdf28d34e68cef4e679885R6 ?

**Comment by prabalsharma** [comment] 2021-08-18 20:20
tested on 2.6-rc4

**Closed** 2021-08-18 20:20 UTC
Labels: [zube]: Done, status/release-blocker, kind/bug-qa
