### ISSUE TITLE
Unable to modify the cluster name of the imported cluster

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#6033] opened 2022-05-25 06:42 UTC
**Setup**
- Rancher version: v2.6.5
- Browser type & version: Google Chrome & 101.0.4951.64

**Describe the bug**

Unable to modify the cluster name of the imported cluster
**To Reproduce**

1. Import a cluster, I imported k3s
2. Select the imported cluster and click `Edit Config` on the right
3. Modify the cluster name of the imported cluster
4. Save

**Result**
The cluster name has not changed, and the console reports an error
```
router_js.js:1895 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'inaccessibleByURL')
    at s._updateURL (router_js.js:1895:1)
    at router_js.js:1454:1
    at v (rsvp.js:493:1)
    at rsvp.js:558:1
    at invoke (backburner.js:340:1)
    at p.flush (backburner.js:229:1)
    at m.flush (backburner.js:426:1)
    at q._end (backburner.js:960:1)
    at _boundAutorunEnd (backburner.js:629:1)
```

**Expected Result**

The cluster name of the imported cluster can be modified

**Screenshots**

<img width="1215" alt="image" src="https://user-images.githubusercontent.com/19684717/170197076-eb35fd0f-ad34-481c-8f36-3d01be7f617f.png">

**Comment by dasarinaidu** [comment] 2023-01-21 06:14
I m seeing the same issue on `v2.7-c81b8b45136f3b5d26d41dca9ef0ddcabd2e026c-head`

**Comment by dasarinaidu** [comment] 2023-03-03 23:57
I am unable to update cluster name OR unable to all a cluster member. After the SAVE the button keeps spinning but it did not saving.

`v2.7-c24fb8b0869a0b445f55b3307c6ed4582e147747-head`

Note:
This is happening only with Cluster imported with `Generic`


![image](https://user-images.githubusercontent.com/22034884/222856859-9facfe7a-b009-4b33-afc9-3addaf8c2ab5.png)

**Comment by gaktive** [comment] 2024-03-11 21:06
Also reported in 2.8.1 here: https://github.com/rancher/dashboard/issues/10432

**Comment by gaktive** [comment] 2024-05-07 22:45
Although this is the original report, I'll mark this as a duplicate of #10432 for tracking purposes as that report came in during the 2.8.x timeframe.

**Closed by gaktive** 2024-05-07 22:45 UTC
Labels: kind/bug
