### ISSUE TITLE
Create a RKE2 cluster, TLS Secret only shows the None option only

### ISSUE THREAD

**Issue by kingsd041** [rancher/dashboard#8287] opened 2023-02-28 09:03 UTC
**Setup**
- Rancher version: v2.7.1
- Browser type & version: Chrome 110.0.5481.100

**Describe the bug**

The TLS Certification was successfully created in the Local cluster, but when creating the RKE2 cluster, it is impossible to select the TLS Certification of created in the `registry authentication`

**To Reproduce**

1. Create TLS Certification in the Local cluster and select the `fleet-default` namespace.
2. Create a RKE2 cluster and set the `registries` parameter
3. Select `Configure advanced container mirroring and registry authentication options`, select` TLS Secret`

**Result**
The drop-down box only has `None` as an option, and the TLS Secret created in the local cluster is not displayed

**Expected Result**

The TLS Secret created in the local cluster can be displayed in the drop-down box
**Screenshots**

![secret](https://user-images.githubusercontent.com/19684717/221803587-785b6125-0e3f-4379-b8d0-a7e7f8581ac9.gif)

**Comment by jameson-mcghee** [comment] 2023-03-06 21:47
@nwmac and @ly5156 , I am moving this issue to Review until [this Test Template ](https://github.com/rancher/dashboard/pull/8288#issue-1602632821) is completed.

**Comment by mantis-toboggan-md** [comment] 2023-03-06 22:59
I've updated the PR with test scenarios.

**Comment by jameson-mcghee** [comment] 2023-03-08 22:54
During testing on `v2.7.1`, I was able to reproduce the issue by following the Steps to Reproduce. However, when testing on `v2.7-head` (Commit ID: 23074b5), I was not able to reproduce this issue. Therefore I am closing this ticket as Done.

**Steps to Reproduce:**
1. Spin up a Rancher server
2. Navigate to the _Cluster Explorer_ -> _Storage_ -> _Secrets_ page for the `local` cluster
3. Create a _TLS Certification_ in the `local` cluster and select the `fleet-default` namespace
  - **Note:** It is possible to copy a _Private Key_ and _Certificate_ from an existing TLS Certification secret for use in Step 3
4. While provisioning a RKE2 cluster, select the _Registries_ tab, choose _Configure advanced container mirroring and registry authentication options_, and then click _Add Registry_
5. Expand the _TLS Secret_ dropdown list
  - **Note:** When reproducing this issue, the TLS Secret (created in Steps 2-3) is not present in the list
6. Finish provisioning the RKE2 cluster
7. Once the cluster is _Active_, navigate to the _Cluster Explorer_ -> _Apps_ for the `local` cluster, and install the _Logging_ app on the _System_
8. Once _Logging_ is successfully installed, navigate to _Logging_ -> _Outputs_ for the `local` cluster, and start creating an _Output_
9. Select the `fleet-default` namespace, expand the _Output_ -> _Access_ -> _Key Id from Secret_ and _Secret Key from Secret_ dropdown lists, and verify the TLS Secret (created in Steps 2-3) is present in each of the dropdown lists

**`v2.7.1`:**
![image](https://user-images.githubusercontent.com/13294321/223869548-b8a9eabc-02a1-4d86-b4ab-4eb72e8c3c94.png)
![image](https://user-images.githubusercontent.com/13294321/223869564-e9231028-87be-4587-94a0-3afbf5865f28.png)

**`v2.7-head` (Commit ID: 23074b5):**
![image](https://user-images.githubusercontent.com/13294321/223869689-fe69a396-5f66-4e84-baa9-6fe9dfc8a69b.png)
![image](https://user-images.githubusercontent.com/13294321/223869703-6a134013-fbde-460f-a6ac-b1ecc5b8155d.png)
![image](https://user-images.githubusercontent.com/13294321/223869723-7d84ec87-6401-4c27-8aaa-c8ce182bb153.png)
![image](https://user-images.githubusercontent.com/13294321/223869738-55ac9002-90e1-4cbe-9c3f-ec66a2c820f4.png)

**Closed by jameson-mcghee** 2023-03-08 22:54 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, team/area2, test-needed
