### ISSUE TITLE
State of `Cluster Credentials` inconsistent when switching between `Cluster Credentials` and `Create Cluster`

### ISSUE THREAD

**Issue by David-VTUK** [rancher/dashboard#3936] opened 2021-08-19 09:26 UTC
The `Cloud Credentials` dropdown for AWS clusters is inconsistent with the available credentials when switching between the `Create Cluster` and `Cloud Credentials` sections of the UI.

Example below, workflow being:

Log in > Initial state is correct > go to Cloud Credentials > Delete Cloud Credential > Create Cluster > Deleted Cloud Credential visible in the dropdown

Add Cloud Credential > Create EKS Cluster > Cloud credential not listed in the dropdown

In both situations, if you refresh the page the drop down list contains the expected values.

**Comment by catherineluse** [comment] 2022-01-14 02:45
I could not reproduce this issue on `v2.6-head`.

To test this,

1. I created two AWS credentials
2. Went to the form to create an EKS cluster and both credentials were there
3. Went to the form to create an EC2 node template and both credentials were there
4. Deleted one of the cloud credentials
5. Went to the form to create an EKS cluster and only the not-deleted credential was there
6. Went to the form to create an EC2 node template and only the not-deleted credential was there
7. Deleted the last remaining cloud credential
8. Went to the form to create an EKS cluster and no credentials were available
9. Went to the form to create an EC2 node template and no credentials were available

I think this is all working as expected.

**Comment by jmcsagdc** [comment] 2022-01-27 01:56
Closing as Can Not Reproduce

I also couldn't reproduce this on 2.6-head (v2.6-0463e4cdeb2e693aa0dc9a013c2b6e9442191c7b-head)

Interesting thing to note was that when I used self-signed certs (like with a simple docker run of rancher), in Chrome, sometimes the page cache hides the fact that it seems Chrome expires the security exception and the page isn't updated. This made it appear sometimes as if that key was still present. A hard refresh would update the page and the key is actually gone.

Just using valid certs like in a production environment, this issue is not seen.

**Closed by jmcsagdc** 2022-01-27 01:56 UTC
Labels: kind/bug, [zube]: To Test, team/area3
