### ISSUE TITLE
RBAC Loading Issues

### ISSUE THREAD

**Issue by codyrancher** [rancher/dashboard#879] opened 2020-07-21 21:37 UTC
When users with minimal RBAC access visit the dashboard the cluster overview page (possibly others as well) errors out.

**Comment by deniseschannon** [comment] 2020-08-18 19:57
seems to be duplicate of https://github.com/rancher/dashboard/issues/527?

**Comment by deniseschannon** [comment] 2020-09-11 03:54
Closing in favor of the other issue.

**Closed by deniseschannon** 2020-09-11 03:54 UTC
Labels: [zube]: Next Up
