### ISSUE TITLE
[Backport 2.6.x] Changing a Container Name highlights the Deployment tab when creating a Deployment via the Cluster Explorer UI

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#7505] opened 2022-11-19 01:17 UTC
Internal reference: SURE-5516
Reported in 2.6.9

Issue description:
When trying to create a Deployment via the Rancher UI (in Cluster Explorer), it is not possible to change the container name directly. Each keystroke, or when pasting a value in the container name field, switches the open form to the Deployment tab. This means that users cannot easily complete the form when creating a Deployment.

Repro steps:
- Create a Deployment (Cluster Explorer > Workload > Deployment > Create).
- Edit the Container Name (default is `container-0`).

Workaround:
Paste the container name text in the Container Name field; create as YAML (via UI), or using `kubectl create/apply`.

Actual behavior:
Each keystroke, or when pasting a value in the Container Name field, switches the form to the Deployment tab.

Expected behavior:
It should be possible to change the Container Name via form.

![create_deploy_2-6-9_ui_form.jpg](https://zube.io/files/rancher/34a3fa19d95ca0d4260d925938b332f5-create_deploy_2-6-9_ui_form.jpg)

**Comment by richard-cox** [comment] 2022-11-21 12:06
Dupe of https://github.com/rancher/dashboard/issues/7404 (as this has a `SURE` reference i'll close the other one). This works fine in 2.7.0, but not in 2.6.9. There's probably a fix that needs to go in to 2.6.x

**Comment by gaktive** [comment] 2023-01-04 17:25
@richard-cox to find the relate 2.7.x PR and link here.
@Shavindra to then validate if this is still an issue in 2.6.x

**Comment by richard-cox** [comment] 2023-01-05 10:12
I couldn't find a PR that addressed this, maybe i was confused with the duplicate issues. 

To be sure we should validate the behaviour in `2.6.9` (and maybe quickly in `2.7-head` again just in case)

**Comment by thaneunsoo** [comment] 2023-02-07 20:40
### Test Environment: ###
Rancher version: v2.6-head e36364e
Rancher cluster type: HA
Docker version: 20.10
Downstream cluster type: rke2

----------

### Testing: ###
Tested this issue with the following steps:
1. Create a Deployment (Cluster Explorer > Workload > Deployment > Create).
2. Edit the Container Name (default is container-0).

**Result**
User is now able to change the container name text in the UI
![image.png](https://zube.io/files/rancher/715fbc584b48d1f881cd5df2347c0269-image.png)

**Closed by thaneunsoo** 2023-02-07 20:40 UTC
Labels: kind/bug, [zube]: QA Working, team/area2, size/5, JIRA
