### ISSUE TITLE
Create/Edit Workloads |  remove white-spaces in the "Container Image" field

### ISSUE THREAD

**Issue by sgapanovich** [rancher/dashboard#4317] opened 2021-09-30 02:38 UTC
**Setup**
Rancher version: 2.6.1-rc7
Browser type & version: Chrome version: 94.0.4606.61 (Official Build) (x86_64)

**Describe the bug**

the deployment can't be created if a user left leading/trailing white-spaces in the container image field 

**To Reproduce**

1. go to the Main menu
2. select your cluster
3. in Workloads click on "Deployments"
4. click "Create"
5. type a name and leave leading/trailing white-spaces in the "Container Image" field
6. click "Create"

**Result**
error is returned 
`Pod "test-65697cc7cb-bdvsg" is invalid: spec.containers[0].image: Invalid value: " ranchertest/mytestcontainer": must not have leading or trailing whitespace:Updated: 0/1`
![white spaces](https://user-images.githubusercontent.com/40282141/135376727-fdc3741d-42d8-405b-8b1d-0860ac2fdb73.png)

**Expected Result**

UI removes white-spaces in the Container Image field

**Comment by davidnuzik** [comment] 2021-12-08 22:08
@gaktive it looks like this issue also has the wrong milestone. Unless I'm mistaken any PRs merged into master are for upcoming v2.6.3 release, not in next v2.6.4. I'm updating the milestone here as well. Please correct me if I am mistaken.

**Comment by davidnuzik** [comment] 2021-12-08 22:21
**My checks PASSED**
 
**Reproduction Environment:**

Rancher version: v2.6.1
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Reproduction steps:**

1. Create any cluster.
2. Explore the cluster. Create a workload -- a Deployment specifically although other types likely have this issue as well.
3. For the container image field, add leading spaces
4. Click Create
5. Successfully reproduced. I got the error indicated in the issue description:
![image](https://user-images.githubusercontent.com/45179589/145293016-0f759ed5-9482-49b8-8b7d-b706ee3b8f17.png)

 
-----
 
**Validation Environment:**

Rancher version: v2.6-head `0d14421` 12/8/2021
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Create any cluster.
2. Explore the cluster. Create a workload -- a deployment.
3. For the container image field, add leading spaces - notice when you click off the field it removes these extra spaces. Add trailing spaces - these are removed as well. Also if you enter text with leading/trailing spaces but don't click off the field and click create the form will still be submitted correctly without the leading or trailing spaces.
4. Edit the config - When editing I still cannot add leading or trailing spaces.
5. I encountered no issues - my deployment deployed without any errors.

**Closed by davidnuzik** 2021-12-08 22:21 UTC
Labels: area/workloads, [zube]: QA Working, kind/bug-qa
