### ISSUE TITLE
Link to github developer settings in auth provider setup doesn't open in a new tab

### ISSUE THREAD

**Issue by nickwsuse** [rancher/dashboard#9379] opened 2023-07-19 22:21 UTC
**Setup**
- Rancher version: v2.7-head Commit ID: 
- Rancher UI Extensions: N/A
- Browser type & version: Chrome Version 114.0.5735.198 (Official Build) (arm64)

**Describe the bug**
The link to https://github.com/settings/developers should be opening in a new tab, but is opening in the same tab when clicked. The text with the link suggests that it should - `[Click here](https://github.com/settings/developers) to go to GitHub application settings in a new window.`

**To Reproduce**
1. Create a Rancher instance on v2.7-head (or v2.7.3/v2.7.5)
2. Log into the Rancher instance
3. Click the hamburger menu in the upper left of the page
4. Click Users & Authentication
5. Click Auth Providers on the left side of the page
6. Click the Github OAuth option
7. See the link and text that suggests the link will open in a new tab/window
8. Click the link

**Result**
Clicking the link opens it in the same tab

**Expected Result**
Clicking the link opens it in a new tab

**Screenshots**
![image](https://github.com/rancher/dashboard/assets/107147272/757682b3-9c67-49cc-8cae-0eceba2387db)

![2023-07-19_15-19-49 (1)](https://github.com/rancher/dashboard/assets/107147272/d0d6840e-6430-4ff0-b8c2-bd1cecd5689c)

**Additional context**
I can repro this on v2.7.5 and on v2.7.3

**Comment by richard-cox** [comment] 2023-08-10 17:49
Moving out of v2.7q3, given we've passed code freeze

**Comment by jonatan5524** [comment] 2023-08-19 11:23
Hi, can I work on this issue? 
I have tested this bug in a local environment and saw it also happen in the Google Authentication link

**Comment by jonatan5524** [comment] 2023-08-20 20:13
After testing I saw that the `t` method returns the lins with `target="_blank"` but in HTML it is not presented (that is the attribute that opens the link in a new tab)
After changing the `v-clean-html` to `v-html` in this line:
https://github.com/rancher/dashboard/blob/7d8a223eab88b23c3a956b9b985f22e396bfafca/shell/edit/auth/github.vue#L191
The new tab link worked.
I saw `v-html` is Vue native but security advised not to use it, where did the `v-clean-html` come from?

**Comment by richard-cox** [comment] 2023-08-21 09:28
Hi @jonatan5524 , thanks for taking a look at this issue. `v-clean-html` is `shell/plugins/clean-html-directive.js` which sanitises html input. It looks like the `target` attribute in intentionally stripped from the output. The team here will need to decide how best to handle this scenario

**Comment by jonatan5524** [comment] 2023-08-21 09:37
> Hi @jonatan5524 , thanks for taking a look at this issue. `v-clean-html` is `shell/plugins/clean-html-directive.js` which sanitises html input. It looks like the `target` attribute in intentionally stripped from the output. The team here will need to decide how best to handle this scenario

Thank you for the reply, If a desicion is made and need to make a change I will gladly take that 😊.

**Comment by richard-cox** [comment] 2024-02-15 13:27
Reproducible in 2.8.2, but not in 2.9-head (2.9.0). Believe this to be fixed via https://github.com/rancher/dashboard/issues/9920 was the fix

**Closed by richard-cox** 2024-02-15 13:27 UTC
Labels: kind/bug, [zube]: Done
