### ISSUE TITLE
`config` view of custom rke2 cluster brings user to the `edit imported cluster` screen instead

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#5922] opened 2022-05-11 15:47 UTC
**Setup**
- Rancher version: v2.6.5-rc10
- Browser type & version: chrome

**Describe the bug**
with a custom cluster, when the user goes to `config` view, the user is instead taken to the `edit` page for the cluster. however the view is identical to the `edit` page of an imported cluster. 

**To Reproduce**
* create a custom rke2 cluster
* register at least 1 node with the cluster
* from `cluster management` -> select your cluster -> select `config` view

**Result**
when the user goes to `config` view, the user is instead taken to the `edit` page for the cluster. however the view is identical to the `edit` page of an imported cluster. 

**Expected Result**
user should be shown a read-only screen displaying values that the user entered while creating the cluster (this is the behavior for node driver clusters)

**Screenshots**

<img width="1425" alt="Screen Shot 2022-05-11 at 8 42 53 AM" src="https://user-images.githubusercontent.com/16691014/167891446-1915038d-0d64-4976-a8f2-e09373b194cf.png">
<img width="1000" alt="Screen Shot 2022-05-11 at 8 42 32 AM" src="https://user-images.githubusercontent.com/16691014/167891456-0a0dd088-344d-4552-89de-7fef990763dc.png">

**Additional context**
* this is not happening for node driver clusters at this time, only for custom clusters

**Comment by catherineluse** [comment] 2022-05-27 11:07
I couldn't reproduce this bug. For the backend I'm using v2.6.5 and for the front end I'm using the latest master branch.

Here's what I tried:

1. Provisioned a digital ocean droplet
2. Went to Cluster Manager and clicked Create
3. Clicked Custom
4. Ran the custom cluster command to install RKE2 on the digital ocean node
5. Went to Cluster Manager, went to the new RKE2 cluster and clicked **⋮ > Edit Config**
6. Confirmed the form is correct:
<img width="1488" alt="Screen Shot 2022-05-27 at 4 01 26 AM" src="https://user-images.githubusercontent.com/20599230/170687559-5ffa1654-aa3e-4904-b547-8f713d89aed1.png">

**Comment by catherineluse** [comment] 2022-05-27 11:13
In the issue description, I noticed that even for an imported cluster, that form would still be incorrect because there are fields missing. I wonder if the issue is that Rancher disconnected from the back end but didn't show it on the front end.

**Comment by catherineluse** [comment] 2022-07-14 23:55
I'm having trouble creating a custom cluster in v2.6-head:
<img width="1229" alt="Screen Shot 2022-07-14 at 4 54 27 PM" src="https://user-images.githubusercontent.com/20599230/179120129-ac77cd49-7ca9-4dec-a894-d142efed01db.png">

**Comment by catherineluse** [comment] 2022-07-19 00:38
The cluster provisioning errors are no longer happening and I was able to successfully provision and edit a custom RKE2 cluster in `v2.6-head`

![Uploading Screen Shot 2022-07-18 at 5.37.42 PM.png…]()

**Comment by catherineluse** [comment] 2022-07-19 00:39
@slickwarren Since I can't reproduce it, I'm moving it to test - can you try reproducing it once more?

**Comment by slickwarren** [comment] 2022-07-20 20:26
I am still able to reproduce this as of 2.6.7-rc3 on a custom rke cluster. I have not re-tested rke2 cluster yet.

**Comment by catherineluse** [comment] 2022-07-21 00:17
I'll try to repro with RKE1 - previously I had only tried with RKE2.

**Comment by catherineluse** [comment] 2022-07-21 22:59
We had different results because Caleb clicked the word Config on the cluster detail page, whereas I got there from the context menu on the cluster list page. The context menu gives the correct URL but clicking the Config button doesn't. PR incoming

**Comment by sowmyav27** [comment] 2022-07-28 03:59
**On 2.6.6**

- On clicking `config` of a custom RKE2 cluster, imported cluster page is loaded
<img width="1507" alt="Screen Shot 2022-07-27 at 8 57 32 PM" src="https://user-images.githubusercontent.com/26032343/181417145-ab5bde92-e41c-49e7-8685-a2edd3d89cd9.png">

**On 2.6head commit `78017e6`**
- On clicking `config` of a custom RKE2 cluster, cluster config page is loaded
<img width="1497" alt="Screen Shot 2022-07-27 at 8 58 30 PM" src="https://user-images.githubusercontent.com/26032343/181417378-7ba30c57-b0f2-4125-933a-3aa081f2ae28.png">

**Closed by sowmyav27** 2022-07-28 03:59 UTC
Labels: area/cluster, [zube]: QA Next up, kind/bug-qa, team/area2, size/1
