### ISSUE TITLE
Rancher UI crash when mouse hovers over action buttons

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#9779] opened 2023-09-26 14:07 UTC
Downstream Cluster : Cluster --> Projects/Namespaces 

If there is no namespace listed under "Not in a Project" then the UI crashes if mouse hovers over one of the three the action buttons ( <MOVE> // <Download YAML> // <Delete>).

By default, it seems, there is always a namespace "local" listed in the subsection "Not in a Project". But if someone moves this namespace to a project or deletes it, and there is no other namespace, then the UI crashes as described. 

Even after browser refresh the issue happens again and again until you create a simple namespace which is not assigned to an existing project – the name of the new namespace does not have to be local, you can name it whatever you want. The only requirement for the new namespace is that it does not belong to a project. 

Troubleshooting steps:

Make sure that there is no namespace available which does not belong to a project
Hover mouse over one of the action buttons and the UI crashes with
e.availableActions is undefined console.js:31:30

  e console.js:31

  e client.js:111

  Babel 7

  errorHandler client.js:113

  VueJS 16

  setBulkActionOfInterest index.vue:799

  mouseover index.vue:1

  VueJS 33

**Comment by jordojordo** [comment] 2023-09-26 15:55
I could not replicate this with 2.8-head or 2.7.7-rc4:

https://github.com/rancher/dashboard/assets/40806497/d7808607-3521-4478-a87f-8ca20ddfcec7

**Comment by gaktive** [comment] 2023-09-26 21:56
Internal reference: SURE-6939

**Comment by ronhorton** [comment] 2023-10-02 19:44
**Pass** verified in rancher `v2.8-head commit ID 436f4de`

replicated rancher crash in v2.7.6
1. created downstream cluster
2. created project
3. created namespace
4. moved namespaces out of 'not in a namespace'
5. moved test-namespace out of test-project
6. moused over 'move' button in UI
7. crash - `cannot read properties of undefined ('reading find')`

when verifying, repeated step of moving namespaces and mousing over/clicking Move button several times. verified fixed in 
- existing downstream cluster
- new downstream cluster

crash window from v2.7.6:
<img width="1144" alt="2023-10-02_15-22-03" src="https://github.com/rancher/dashboard/assets/89212856/c4e080c3-e46f-4898-9050-2cb52696215c">

**Closed** 2023-10-02 19:45 UTC
Labels: kind/bug, [zube]: Done, team/area3, JIRA

**Comment by cnotv** [comment] 2023-10-04 13:55
Side note: the issue is the same of https://github.com/rancher/dashboard/issues/9665 and the error is generated when interacting with the table (because it will trigger the check on row actions).
An unit test is going to be added for the other case.
