### ISSUE TITLE
Apps - filter charts in the dropdown list in app's installation page 

### ISSUE THREAD

**Issue by jiaqiluo** [rancher/dashboard#1601] opened 2020-10-03 00:20 UTC
enhancement 

in rancher:master-head 87e7cd with the latest UI

We can change the chart from the dropdown list in any app’s installation page,  but the list contains some charts that do NOT show in the `charts` page, for example, the fleet-related chart.

We should apply the same logic as the chart page here to hide those charts.

<img width="1288" alt="Screen Shot 2020-10-02 at 4 54 53 PM" src="https://user-images.githubusercontent.com/6218999/94978729-91766c80-04d3-11eb-9d53-7122d5b1bcd3.png">

**Comment by deniseschannon** [comment] 2020-10-19 22:07
Helm doesn't have any relation between installed charts and available charts.

This would be a change needed in the backend about the apps API.

**Comment by sadiapoddar** [comment] 2020-11-03 18:28
Reproduced the issue with 2.5.1
steps.
1. Go to the explorer 
2. from app tab, try to install longhorn or any app
3. The drop-down list shows a bunch of irrelevant names that don't exist on the chart page. 
![Uploading Screen Shot 2020-11-03 at 10.07.51 AM.png…]()

**Comment by sadiapoddar** [comment] 2020-11-03 18:35
Verified the fix 2.5-head, the exact commit #v2.5-100198aff107b9a0feccdcc3e6fb5b57e83f1fd7-head
Couldn't reproduce the issue
1. Explorer->App->Chart
2. Click on any chart to install, 
3. Drop-down menu doesn't have nonexisting
<img width="1683" alt="Screen Shot 2020-11-03 at 10 17 44 AM" src="https://user-images.githubusercontent.com/72409237/98026635-498f8180-1dc0-11eb-95b1-077b08280498.png">
 chars name in the list.

**Comment by sadiapoddar** [comment] 2020-11-03 18:41
Closing this issue as it's fixed.

**Comment by sadiapoddar** [comment] 2020-11-03 20:27
**The issue was reproducible with 2.5.1**
1. From Explorer->APP and try to install any app, say "longhorn", the drop menu shows lots of app names that are not listed on the Chart page as available apps.
The screenshot shows it has lots of app names in the dropdown menu, these apps don't exist on the chart page.

<img width="1697" alt="Screen Shot 2020-11-03 at 11 03 20 AM" src="https://user-images.githubusercontent.com/72409237/98036206-7c407680-1dce-11eb-83ec-c8bceaf1be08.png">


Verified the fix with 2.5-head. The problem is not reproducible,
Tried the same step and don't see any apps names in the drop-down menu that are not listed on the chart page
<img width="1674" alt="Screen Shot 2020-11-03 at 11 04 16 AM" src="https://user-images.githubusercontent.com/72409237/98036945-b5c5b180-1dcf-11eb-95fb-df559f2890d1.png">


Looks like the fix is working as expected we can close the bug.

**Closed** 2020-11-04 16:00 UTC
Labels: [zube]: To Test, product/apps
