### ISSUE TITLE
Add event list to Pod detail page

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#7374] opened 2022-11-08 20:00 UTC
The event list is visible for workloads including Deployments, but is not visible for the detail page for individual Pods.

If the Pod crash loops or fails to pull the image, the events will show there.

**Comment by richard-cox** [comment] 2022-11-08 20:11
Think this is a regression brought in by https://github.com/rancher/dashboard/pull/6683 and applies to ALL resources were we don't force the visibility of events. We gated the visibility of the events tab on if we have events OR we're manually forcing it. If we're not forcing it we fetch the events when we visit the tab (which we can't do because it's never visible).

We need to address this in 2.7.1

**Comment by steffeneichler** [comment] 2022-11-17 06:17
Hi,

we would be very pleased if this could be fixed in 2.6.x too.

**Comment by sowmyav27** [comment] 2022-12-15 02:01
**On 2.7-head commit id: `a2ef50b`**

<img width="1505" alt="Screen Shot 2022-12-14 at 5 59 06 PM" src="https://user-images.githubusercontent.com/26032343/207754674-0ed1dc96-9142-4689-b056-3768fc8ee720.png">

**Closed by sowmyav27** 2022-12-15 02:01 UTC
Labels: kind/bug, [zube]: To Test
