### ISSUE TITLE
Continuous Delivery page is not available for a cluster Owner

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#2206] opened 2021-01-13 22:41 UTC
On 2.5-head commit id: `2ba49cb`

- Deploy 2.5-head, deploy a few downstream cluster as a cluster owner - user1
- From Dashboard top left, select Continuous delivery

**Issue#1**
- The page is displayed like this.
<img width="1009" alt="Screen Shot 2021-01-13 at 2 39 09 PM" src="https://user-images.githubusercontent.com/26032343/104518883-51805480-55ad-11eb-9dc7-3a013f1703ed.png">

**Issue#2**
- Clicking on create shows errors in console and page is stuck in loading.
<img width="1634" alt="Screen Shot 2021-01-13 at 2 39 00 PM" src="https://user-images.githubusercontent.com/26032343/104518904-5d6c1680-55ad-11eb-87a5-c85dc855b1ce.png">

**Expected:**
Cluster owner of the local cluster should have access to this page. Downstream cluster owner has no permissions

**Comment by catherineluse** [comment] 2022-11-05 19:22
I could not reproduce this issue in v2.7-head. As a cluster owner, I was able to successfully go through the same workflow without crashing:

## Continuous Delivery home page for cluster owner (get started button leads to git repo creation page)

<img width="1481" alt="Screenshot 2022-11-05 at 12 17 47 PM" src="https://user-images.githubusercontent.com/20599230/200137303-edd75895-d6ea-4999-b058-45fdf81343fe.png">

## Cluster registration token page
<img width="1477" alt="Screenshot 2022-11-05 at 12 18 23 PM" src="https://user-images.githubusercontent.com/20599230/200137335-6b039b60-202c-49cc-8086-e36f4006e966.png">

## Creating cluster registration token from YAML
<img width="1479" alt="Screenshot 2022-11-05 at 12 18 31 PM" src="https://user-images.githubusercontent.com/20599230/200137365-01a3fe2c-bf0c-464c-ae27-587818be882b.png">



Moving to test to confirm that there is no work to be done

**Comment by nwmac** [comment] 2024-02-01 09:44
This was marked as can not reproduce a while ago - moving milestone to 2.9.0 and correcting labels so that this can be verified by QA.

**Closed** 2024-04-10 09:31 UTC
Labels: kind/bug, [zube]: Done, product/fleet, QA/manual-test
