### ISSUE TITLE
Google Oauth

### ISSUE THREAD

**Issue by deniseschannon** [rancher/dashboard#2116] opened 2020-12-19 04:28 UTC
Most of the setup occurs on Google websites, with steps listed out in Ember UI. Currently, each of these pages is styled slightly differently: 
![Screen Shot 2020-06-29 at 8 58 45 AM](https://user-images.githubusercontent.com/42977925/86028506-ceb7f380-b9e6-11ea-9235-f11b3e45587b.png)

Use Github auth as example of how to step to external website for Oauth

**Comment by sowmyav27** [comment] 2021-02-14 01:27
@mantis-toboggan-md Do we have a PR for this issue ?

**Comment by sowmyav27** [comment] 2021-02-16 16:40
<img width="439" alt="Screen Shot 2021-02-16 at 8 38 18 AM" src="https://user-images.githubusercontent.com/26032343/108093408-89f2d280-7032-11eb-93b4-b3a72a846c01.png">
**On 2.5-head - commit id: `3e96d7f `**

**Issue#1**

- Enable google auth 
- Error seen `[Google OAuth] configureTest: Failed to form redirect URL with error: unexpected end of JSON input`

**Issue#2**
Can we have the text in input fields OAuth and Service Account creds like how we have in Ember UI ? Hidden until the cursor is in the input field
Ember UI:
<img width="653" alt="Screen Shot 2021-02-16 at 8 38 12 AM" src="https://user-images.githubusercontent.com/26032343/108093391-865f4b80-7032-11eb-88d0-0b12d504b347.png">

Dashboard:

**Comment by sowmyav27** [comment] 2021-02-25 03:20
**On 2.5-head commit id: `30e53bd`**

- Issues seen:
**Issue#1**
- Not able to select `Read from File` OAuth and Service Account creds. The fields remain blank.

**Issue#2**
- On copy pasting the credentials and clicking on enable gives this error
<img width="488" alt="Screen Shot 2021-02-24 at 7 17 40 PM" src="https://user-images.githubusercontent.com/26032343/109097999-4d2f7700-76d5-11eb-9f0c-4829d186a28b.png">

**Note:**
With the same credentials, Ember UI enabled Google Auth
Reopening the issue

**Comment by sowmyav27** [comment] 2021-04-06 03:48
**On 2..5-head commit id: `2f2cfe6`**

- Enable Google auth through dashboard
- Enter creds
- Error seen on the redirected page - 

<img width="574" alt="Screen Shot 2021-04-05 at 8 47 40 PM" src="https://user-images.githubusercontent.com/26032343/113656244-50ad0b00-9650-11eb-91d5-d7e9f3379bc1.png">

**Comment by sowmyav27** [comment] 2021-04-10 05:03
**On 2.5-head commit id: `9b0058c `**

Same error when these steps are taken is seen 
https://github.com/rancher/dashboard/issues/2116#issuecomment-813801142

**Comment by gaktive** [comment] 2021-04-13 16:37
Duplicate of https://github.com/rancher/dashboard/issues/2628 talks about the consistency of the style guide from Github.

**Comment by gaktive** [comment] 2021-04-13 16:38
These likely don't have to be hyperlinks either.

**Comment by sowmyav27** [comment] 2021-04-15 04:44
**On 2.5.8-rc4**

[This issue](https://github.com/rancher/dashboard/issues/2116#issuecomment-813801142)  is still seen. Reopening it.

**Comment by mantis-toboggan-md** [comment] 2021-04-15 15:25
This should be fixed in 2.5-head, but it isn't in dashboard's 2.5.8-rc4

**Comment by sowmyav27** [comment] 2021-04-15 18:31
**On 2.5-head commit id: `41f173a`**

Able to enable and edit and save google Auth.

**Closed by sowmyav27** 2021-04-15 18:31 UTC
Labels: QA/S, [zube]: To Test, area/authentication
