### ISSUE TITLE
Custom Longhorn deployment page

### ISSUE THREAD

**Issue by yasker** [rancher/dashboard#1006] opened 2020-08-11 22:40 UTC
Possible enhancements over the previous questions.yaml:
1. Ensure the system can only be deployed in `longhorn-system` namespace
2. Ensure there should be only one deployment of Longhorn in the cluster.
3. Support multi-cluster deployment with the same `longhorn-system` namespace.

Other than those, Longhorn is fine with the previous `questions.yml` implementation. The latest `questions.yml` (for pre v1.0.2 release), which contains all the customizable fields, is linked [here](https://github.com/longhorn/longhorn/blob/v1.0.2/chart/questions.yml).

**Comment by maggieliu** [comment] 2020-12-17 21:14
#1 is done already. For this ticket only need to work on #2.

**Comment by maggieliu** [comment] 2020-12-17 21:18
Seems like when installing longhorn again it does fail gracefully. So both 1 and 2 are resolved. 3 will just be taken cared of by Fleet.

**Comment by meldafrawi** [comment] 2020-12-17 21:43
Attempt to install Longhorn using cluster explorer then trying to install it again with cluster manager will not fail gracefully and might cause confusion to the user.

Steps to reproduce:
1. In Rancher v2.5 Cluster Explorer dashboard, add a new chart using
`https://github.com/shuo-wu/charts` branch `dev-v2.5`
2. Change the following images tags to Use latest v1.1.0-RC3 images, and deploy Longhorn
![image](https://user-images.githubusercontent.com/18232258/102546599-90abaa80-40c0-11eb-9eae-c57789485ec5.png)
3. Switch to Cluster Manager Dashboard.
4. Add a new Catalog using the following repo  `https://github.com/shuo-wu/charts` branch `master`
5. Move Longhorn Namespace to System project.
6. Try to install Longhorn v1.1.0-RC2. Don't change the images tags to RC3

Result:
- In Cluster Manager: Longhorn App Seems to be in Active State
![image](https://user-images.githubusercontent.com/18232258/102547295-ac638080-40c1-11eb-99dc-d80817cd7a12.png)


- In Cluster Explorer: In installed apps, a new `longhorn-system` app appear alongside with already existing `longhorn` and `longhorn-crd` apps.

![image](https://user-images.githubusercontent.com/18232258/102547249-99e94700-40c1-11eb-9e92-4239044b9d23.png)

**Comment by yasker** [comment] 2020-12-17 22:08
@meldafrawi Can you try if we can install it in Cluster Manager first then Cluster Explorer?

**Comment by nwmac** [comment] 2022-07-13 11:59
Won't fix

**Closed by nwmac** 2022-07-13 11:59 UTC
Labels: [zube]: Backlog, product/longhorn, kind/enhancement
