### ISSUE TITLE
Menu button overflow on hover

### ISSUE THREAD

**Issue by torchiaf** [rancher/dashboard#7510] opened 2022-11-21 11:24 UTC
**Setup**
- Rancher version: 2.7.0
- Browser type & version: Chromium Version 103.0.5060.134 (openSUSE Build) stable (64-bit)

**Describe the bug**

When the mouse pointer goes hover the menu button, the button image overflows the bottom border.

**To Reproduce**

Move the mouse pointer hover the menu button, on top-left corner of the dashboard.

**Expected Result**

No overflows.

**Screenshots**

![image](https://user-images.githubusercontent.com/26394656/203028009-07e9d2c7-90d2-450d-819b-1a7c3622bafb.png)

**Comment by richard-cox** [comment] 2022-11-21 14:03
This affects the whole row on multiple pages
![image](https://user-images.githubusercontent.com/18697775/203074077-7a8494fd-7576-4c92-92f2-52642f01e76c.png)

![image](https://user-images.githubusercontent.com/18697775/203074212-aa51b3a8-bead-4a0d-a0ec-bd4e6817e9c2.png)

**Comment by richard-cox** [comment] 2022-11-21 14:09
Duplicate of #7491

**Closed by richard-cox** 2022-11-21 14:09 UTC
Labels: kind/bug, good-first-issue
