### ISSUE TITLE
Dashboard v2 import cluster has 0 machines displayed on the UI after the nodes are active

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#2963] opened 2021-05-11 18:04 UTC
master-6030ab58d56bbc10ca4764c8c3438fcbfb041206-head

1. Create a kubernetes cluster using rke 
2. Import the cluster into the rancher server with master-head commit 6030ab by running the kubectl in the nodes
3. Once the cluster is active --> verify from the cluster management --> imported cluster shows 0 machines 
4. The nodes can be seen active from the explore cluster --> imported cluster --> cluster --> nodes
5. Enhancement to show the number of nodes registered under machines and the nodes to be accessible from cluster management for the imported cluster is needed

<img width="1650" alt="Screen Shot 2021-05-11 at 10 54 54 AM" src="https://user-images.githubusercontent.com/38144301/117863361-8abd8e00-b248-11eb-96eb-05b21509fa45.png">

**Comment by vincent99** [comment] 2021-05-11 18:26
I think we should probably do something to clarify this, but this isn't really a bug.. "Provisioning" clusters and nodes/machines are separate from the "Management" cluster and the k8s Node type. 

When you're in the cluster, you're looking at the k8s node resources, which exist no matter how the cluster was deployed.

When you're in cluster management, you're looking at the resources we actually provisioned and manage.  There are no nodes shown here because we didn't provision any nodes.  If you delete the cluster, no 'physical' infrastructure will be deleted.  If you make an RKE2+EC2 cluster in there, there will be nodes because we deployed them to EC2, and will clean them up when you delete the cluster.

This is also why they're (sometimes, inconsistently) called "Machines" versus "Nodes".

**Comment by izaac** [comment] 2021-05-18 19:31
Rancher version `2.6 master-head` _55f0bb2_

I am unable to see the `Machines` we provisioned with RKE1 from `Cluster Explorer -> Cluster Management`
I understand the imported clusters issue but shouldn't we display these `Machines/Nodes` here for RKE1?

The cluster information shows the Nodes total of the RKE1 cluster I provisioned


![Screen Shot 2021-05-18 at 12 28 16 PM](https://user-images.githubusercontent.com/27659/118711769-d0dc9980-b7d4-11eb-95f8-c9b509907583.png)




![Screen Shot 2021-05-18 at 12 28 34 PM](https://user-images.githubusercontent.com/27659/118711806-d9cd6b00-b7d4-11eb-8781-9de564e3e2b5.png)

**Comment by izaac** [comment] 2021-05-18 19:37
I've opened an issue for RKE1 specifically, this is for imported clusters.

**Comment by nwmac** [comment] 2022-07-13 13:12
As far as I can tell, this is working correctly - moving to test for QA to validate

**Comment by jameson-mcghee** [comment] 2022-09-08 16:01
I attempted to reproduce this issue on both v2.6.7 and v2.6-head (Commit ID: 400e559), and I was unable to reproduce this issue on either version. Based on that fact, @nwmac's previous comment, and confirmation from both @anupama2501 and @Josh-Diamond, the decision was made to close this ticket as it is unreproducible.

Repro Steps:
(Followed exact steps laid out in the ticket's Description)

v2.6.7
![image.png](https://zube.io/files/rancher/17ba26533c82d4e91fbb22b32132748f-image.png)

**Closed** 2022-09-08 16:01 UTC
Labels: kind/bug, QA/XS, [zube]: QA Working, team/area2
