### ISSUE TITLE
TLS Certificate secrets show Root CA details instead of actual certificate details

### ISSUE THREAD

**Issue by mikeh89** [rancher/dashboard#7898] opened 2022-04-12 10:12 UTC
**Rancher Server Setup**
- Rancher version: 2.6.4 (also present on 2.6.3)
- Installation option (Docker install/Helm Chart): Helm
   - EKS  v1.21.5
   - k3s  v1.21.7

**Information about the Cluster**
- Kubernetes version:
- Cluster Type (Local/Downstream):
   - If downstream, what type of cluster? Imported

**User Information**
- What is the role of the user logged in? Admin
   
**Describe the bug**
In Rancher versions 2.6.3/2.6.4, TLS Certificate secrets containing the full chain (used for Nginx Ingresses) display the expiry date and subject for the root certificate, instead of the expiry for the actual/subscriber certificate. 

**To Reproduce**
Request certificate via Let's Encrypt. 
Create secret using the fullchain.pem (certificate + CA chain).

**Result**
Rancher displays details of Let's Encrypt's root CA: 

"Domain Name ISRG Root X1
Expires: Mon, Sep 30 2024  8:14:03 pm"

**Expected Result**
Should display details of subscriber certificate. e.g: 

Domain Name www.example.com
Expires: Tues, Jul 12 2022  8:14:03 pm 

**Screenshots**

<img width="386" alt="Screenshot 2022-04-12 at 12 11 48" src="https://user-images.githubusercontent.com/31032084/162937756-273b41e8-71ba-4a6f-9e6e-355db9293bd6.png">

**Additional context**
Certificates were displayed correctly in Rancher 2.5
EDIT: It appears this is only present in the new Cluster Explorer view. Legacy/Cluster Manager view displays certificate expiry correctly.

**Comment by gaktive** [comment] 2023-01-10 23:39
Internal reference: SURE-5713

**Comment by gaktive** [comment] 2023-01-10 23:40
Reports from internal folks:
> The certificates were displayed correctly in Rancher 2.5 and this does appear in the cluster explorer view. Although with Rancher 2.6 we only use the cluster explorer view.

**Comment by nwmac** [comment] 2023-01-12 18:36
@gaktive I think this is a duplicate of https://github.com/rancher/dashboard/issues/7081. A fix for that has been merged and is with QA.

**Comment by gaktive** [comment] 2023-01-12 19:30
@nwmac thanks! Looks the same to me so I'll close this as a duplicate and update info elsewhere.

**Closed** 2023-01-12 19:32 UTC
Labels: kind/bug, [zube]: To Triage, JIRA
