### ISSUE TITLE
[RFE] New Dashboard - External IPs not displayed in Nodes page for baremetal clusters

### ISSUE THREAD

**Issue by chrisreed87** [rancher/dashboard#795] opened 2020-05-28 18:13 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug/enhancement

**Steps to reproduce (least amount of steps as possible):**
- Rancher 2.4.x cluster, New Dashboard enabled
- Bare-metal downstream cluster added, with nodes having external and internal ips
- Navigate to Dashboard --> Nodes page

**Result:**
"Internal-IP" field is populated, "External-IP" field is empty

**Other details that may be helpful:**
If you Edit the node in the Dashboard to view annotations, the annotation `rke.cattle.io/external-ip` has a value

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): v2.4.3
- Installation option (single install/HA): HA

**Cluster information**
- Cluster type (Hosted/Infrastructure Provider/Custom/Imported): Imported
- Machine type (cloud/VM/metal) and specifications (CPU/memory): Metal
- Kubernetes version (use `kubectl version`):

```
Kubernetes 1.17.4
```

- Docker version (use `docker version`):

```
Docker 18.9.9
```

gz#10160

**Comment by codyrancher** [comment] 2020-12-21 14:55
I was able to verify that when the `rke.cattle.io/external-ip` annotation is present the external ip is displayed. The external ip is a local ip because I manually set the annotation. 

![image](https://user-images.githubusercontent.com/55104481/102789523-7fcd9400-4361-11eb-9af3-cb1c2ef1b547.png)

**Comment by Ellenqs** [comment] 2020-12-29 00:56
My test: on rancher v2.4.3, using both rke and k3s. The issue can not be reproduced. Both internal/external IP show up. See the screenshots below:
<img width="1295" alt="Screen Shot 2020-12-28 at 4 43 41 PM" src="https://user-images.githubusercontent.com/75277058/103251423-76c65f00-492d-11eb-8d34-150558e32d54.png">
<img width="1270" alt="Screen Shot 2020-12-28 at 4 43 10 PM" src="https://user-images.githubusercontent.com/75277058/103251426-78902280-492d-11eb-9d9d-7383c85198a1.png">

**Comment by sowmyav27** [comment] 2021-01-12 06:04
Have not been able to reproduce this issue on 2.4 or 2.5.5 (released version of 2.5)

**On 2.5-head - commit id: `65a15b94`**

**Steps:**

- Create a single node docker install. The rancher will have a local cluster, with only an internal IP.
- Edit the node, add `rke.cattle.io/external-ip` annotation, value=test on this node.
- The Amber UI now shows 
<img width="446" alt="Screen Shot 2021-01-11 at 10 01 52 PM" src="https://user-images.githubusercontent.com/26032343/104275981-c4c48200-5458-11eb-81ee-9ee38fd97460.png">

- The Dashboard does NOT show this. External ip is still None.
<img width="981" alt="Screen Shot 2021-01-11 at 10 01 43 PM" src="https://user-images.githubusercontent.com/26032343/104275977-c2fabe80-5458-11eb-9509-6c2091b19fe5.png">

Question:

Is ^^^ expected to change based on `rke.cattle.io/external-ip` annotation ? 

Reopening the issue

**Comment by Ellenqs** [comment] 2021-01-12 21:54
Tested on v2.5.3.

steps :
1. Bring up rke cluster on aws ec2, 
2. Import it to rancher

Results:

<img width="1060" alt="Screen Shot 2021-01-12 at 9 53 22 AM" src="https://user-images.githubusercontent.com/75277058/104378800-6988a300-54dd-11eb-8f9d-fc971b50a4e1.png">

<img width="652" alt="Screen Shot 2021-01-12 at 9 53 29 AM" src="https://user-images.githubusercontent.com/75277058/104378819-6f7e8400-54dd-11eb-89f0-70678f21e616.png">

Both internal and external ip are there.

**Comment by gaktive** [comment] 2021-02-02 22:56
This looks like it's working across various versions now. Can we mark this as done?

**Comment by sowmyav27** [comment] 2021-02-03 17:18
We were not able to reproduce the issue on 2.4.x or 2.5.5 (released version of 2.5). We are not quite sure what was fixed as we see it working always.

**Comment by nwmac** [comment] 2021-02-20 16:00
If the External and Internal IP addresses are the same, we only show one value, otherwise we do correctly show both.

Feels like we should always show both, even if they are the same.

**Comment by nwmac** [comment] 2021-02-21 22:21
Okay - I think you’re saying the current behaviour is as expected and the original issue was in fact the external up showing as none. I’ll close this or and update the issue to say this is fixed.

**Comment by nwmac** [comment] 2021-02-21 22:22
This is fixed - note if both the external and internal IPs are the same we will only show one.

**Comment by jiaqiluo** [comment] 2021-02-24 19:27
The bug cannot be reproduced on v2.5-head 87006de

Also, a related issue about showing `none` when the external IP exists has been fixed a long time ago according to [this comment](https://github.com/rancher/dashboard/pull/2367#issuecomment-782932107)

This issue is closed for now.

**Closed by jiaqiluo** 2021-02-24 19:27 UTC
Labels: [zube]: To Test, area/node, internal, kind/bug
