### ISSUE TITLE
Date and time format is displayed wrong in the preferences after editing.

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6193] opened 2022-06-16 18:40 UTC
Internal reference: SURE-4831
Reported in 2.6.5

Issue description:
Date and time format is changed after editing in the preferences 

Before editing: 
*Date Format*
`Wed, Jun 15 2022`

After Editing:
*Date Format*
`map[label:Wed, Jun 15 2022 value:ddd, MMM D YYYY]`

Same with the time format too. Rancher is creating events and throwing the error messages, generating a lot of logs.

Repro steps:

- Open preferences
- Edit the date and time format 
- Click on the dark or light theme or any other button on that page, and the format changes

Workaround: none

Actual behavior:
The format is changing to a different format which is not there in the drop-down.

Expected behavior:
The format should change as per the format in the drop-down and should not throw errors in the rancher logs.

Files, logs, traces: Rancher logs

```2022/06/15 05:57:07 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "date-format": the object has been modified; please apply your changes to the latest version and try again
2022/06/15 05:57:51 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "time-format": the object has been modified; please apply your changes to the latest version and try again
2022/06/15 05:57:57 [ERROR] Unknown error: Operation cannot be fulfilled on preferences.management.cattle.io "date-format": the object has been modified; please apply your changes to the latest version and try again```

Additional notes:
Attached are the screenshots a user's setup.

![Preferences-Formatting.png](https://zube.io/files/rancher/bc19bfeb6bfc171941049095176dc199-preferences-formatting.png)

![Screenshot 2022-06-15 at 11.36.25 AM.png](https://zube.io/files/rancher/8000be4677aef9cad5db5be9bb17b03e-screenshot-2022-06-15-at-11-36-25-am.png)

![console 2022-06-15 11.28.10.png](https://zube.io/files/rancher/50efeed6ce09214a914074006fc4808c-console-2022-06-15-11-28-10.png)

**Comment by richard-cox** [comment] 2022-06-17 08:58
Closing as duplicate of https://github.com/rancher/dashboard/issues/5979 (fixed in 2.6.6).

**Closed by richard-cox** 2022-06-17 08:58 UTC
Labels: kind/bug, [zube]: Done, priority/0, JIRA
