### ISSUE TITLE
When creating cluster with Rancher deployed on Azure instance, the user is brought back to cluster management page

### ISSUE THREAD

**Issue by thaneunsoo** [rancher/dashboard#7654] opened 2022-12-08 16:31 UTC
**Setup**
- Rancher version: v2.7-head
- Browser type & version: Chrome build 107

**Describe the bug**

After deploying Rancher on an azure instance suse 15.4, I clicked create cluster but then after selecting either node driver or custom, I was brought back to the cluster management page. You can see that the URL is in create
![image](https://user-images.githubusercontent.com/108360907/206507061-227a1308-0fa4-4132-af60-6d930ba3af98.png)

**To Reproduce**

1. Deploy v2.7-head Rancher on SUSE 15.4 on azure
2. Click create cluster
3. Click any of the options, I chose custom in the image above
4. See that you are brought back to the cluster page and not to the config edit page

**Result**
User is not brought to the config edit page, but is brought back to the cluster management page

**Expected Result**

User should be brought to the edit config page where user can define the values to create a cluster.

**Comment by richard-cox** [comment] 2022-12-08 18:23
Closing as duplicate of https://github.com/rancher/dashboard/issues/7636 (issue applies to all non-rke2 clusters)

**Closed by richard-cox** 2022-12-08 18:23 UTC
Labels: kind/bug, team/area2
