### ISSUE TITLE
Vue3: Explorer Header: Describe Resource fails to open description slide in 

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#11800] opened 2024-09-03 15:07 UTC
**Setup**
- Rancher version: dev of 2.10.0

**Describe the bug**
- full page dev error
- no slide in

**To Reproduce**
cluster explorer --> nav to pods --> click on `Describe Resource`

**Result**
![image](https://github.com/user-attachments/assets/1974adc8-c557-4acf-89a9-6d888cbfc45a)

**Expected Result**
![image](https://github.com/user-attachments/assets/980dcf45-1e16-437f-b8a3-220796cf9bff)

**Comment by rak-phillip** [comment] 2024-09-03 15:48
Closing as a duplicate of #11699. I explicitly linked this issue as a means to gather more information for whomever picks it up.

**Closed by rak-phillip** 2024-09-03 15:48 UTC
Labels: kind/bug, QA/dev-automation, area/vue3
