### ISSUE TITLE
Apps/Market view not viewable with custom role

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6161] opened 2022-06-13 19:27 UTC
Internal reference: SURE-4055
Reported in 2.6.3

With a custom role, 'Installed Apps' does not show in the side nav.

**Comment by richard-cox** [comment] 2022-06-21 15:48
See JIRA for role template

**Comment by nwmac** [comment] 2022-07-12 11:03
This is due to a difference between the resource types used in the old and new UI.

To give a user access to apps and allow them to see the 'Installed Apps' nav item, addf the following to your custom role template:

```
- apiGroups:
  - catalog.cattle.io
  nonResourceURLs: []
  resourceNames: []
  resources:
  - '*'
  verbs:
  - '*'
```

**Comment by nwmac** [comment] 2022-07-12 11:06
To test this:

- Create a new standard user
- Verify that the user can not see "Installed Apps' in the side nav under the 'Apps' section.
- Create a new Cluster Role and add the verb '*', resource '*' and api group 'catalog.cattle.io'
- Assign this role to the standard user
- Verify that the user can now see the 'Install Apps' nav item

**Comment by brudnak** [comment] 2022-07-29 13:54
# :white_check_mark: PASSED

## Reproduction Environment

#### Not required.

<hr>
  
## Validation Environment

| Component                 | Version / Type                                |
| ------------------------- | --------------------------------------------- |
| Rancher version           | 2.6.6                                         |
| Installation option       | helm                                          |
| RKE binary version used   | 1.3.11                                        |
| If Helm Chart k8s cluster | v1.23.6                                       |
| Cert Details              | let's encrypt                                 |
| Helm version              | v2.16.8-rancher1                              |
| Downstream cluster type   | RKE1 Linode                                   |
| Downstream K8s version    | v1.23.7-rancher1-1                            |
| Logged in user role       | administrator for setup / standard for checks |
| Browser type              | Opera GX                                      |
| Browser version           | LVL4 (core: 89.0.4447.64) (x86_64)            |

**ADDITIONAL SETUP**

- Helm commands for Rancher installation:

```shell
helm install rancher rancher-latest/rancher \
  --namespace cattle-system \
  --set hostname=$URL_VAR \
  --set bootstrapPassword=$PW_VAR \
  --set ingress.tls.source=letsEncrypt \
  --set letsEncrypt.email=$EMAIL_VAR \
  --set letsEncrypt.ingress.class=nginx
```

## Validation steps

1. As administrator, create a RKE1 Linode downstream cluster
2. Create a standard user
3. Create a new Cluster Role named `app-test`:
   - Verb: `*`
   - Resource: `*`
   - API Groups: `catalog.cattle.io`
4. In the downstream RKE1 Linode cluster add a cluster member with the following:
   - Cluster Role: `app-test`
   - User: `the standard user created in step #2`
5. Login as the standard user
6. Verify the ability to see `Installed Apps`
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
standard user can see `Installed Apps` with this custom cluster role

#### :white_check_mark:Actual
standard user can see `Installed Apps` with this custom cluster role

**Closed by brudnak** 2022-07-29 13:54 UTC
Labels: kind/bug, priority/0, [zube]: QA Working, team/area1, size/2, JIRA
