### ISSUE TITLE
User is able to create a deployment when there is an error in the spec

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1286] opened 2020-09-17 21:17 UTC
**On master-head - commit id: `33f755f18`**

- Dashboard --> Deployment --> Create --> Enter name and image
- In the `Pod Scheduling` tab give in the details like this and do NOT specify `topologyKey`

<img width="871" alt="Screen Shot 2020-09-17 at 2 11 45 PM" src="https://user-images.githubusercontent.com/26032343/93529116-3e57c380-f8f0-11ea-95f5-77d624a9b367.png">
- Click on `Create` deployment
- The request goes through and the deployment is NOT created
- Response: `{"type":"error","links":{},"code":"Invalid","message":"Deployment.apps \"test-2\" is invalid: [spec.template.spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Required value: can not be empty, spec.template.spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: \"\": name part must be non-empty, spec.template.spec.affinity.podAffinity.requiredDuringSchedulingIgnoredDuringExecution[0].topologyKey: Invalid value: \"\": name part must consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyName',  or 'my.name',  or '123-abc', regex used for validation is '([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9]')]","status":422,"type":"error"}`

**Expected:**
User is thrown an error in the Dashboard UI as `topologyKey` is a mandatory field

**Comment by sadiapoddar** [comment] 2020-10-30 03:20
reproduced with v2.5.1 r

**Comment by sadiapoddar** [comment] 2020-10-30 18:22
Tested with the following commit
https://github.com/rancher/rancher/commit/cc777ebfabe4dba48216525bb1cd56c01231dd40
and encountered the same issue, not seeing the fix

The steps followed,
Dashboard --> Deployment --> Create --> Enter name and image
In the Pod Scheduling tab didn't provide the value of the required field "topologyKey"

<img width="1235" alt="Screen Shot 2020-10-30 at 11 14 57 AM" src="https://user-images.githubusercontent.com/72409237/97742662-d1644b80-1aa1-11eb-96d4-81eda6c2508d.png">

Expected a warning about the required field instead of the error stack on the UI.

**Comment by sowmyav27** [comment] 2020-10-30 18:40
Reopening the issue based on [this](https://github.com/rancher/dashboard/issues/1286#issuecomment-719721123)

**Comment by sadiapoddar** [comment] 2020-11-05 00:31
Verified the fix with 2.5-head: v2.5-100198aff107b9a0feccdcc3e6fb5b57e83f1fd7-head

Couldn't reproduce the issue by following the same steps.
Dashboard --> Deployment --> Create --> Enter name and image
The Pod Scheduling tab didn't provide the value of the required field "topologyKey"

<img width="1451" alt="Screen Shot 2020-11-04 at 4 17 08 PM" src="https://user-images.githubusercontent.com/72409237/98182495-c2730400-1eba-11eb-9abe-746c8c8842b8.png">

Now seeing the expected error message about missing the "Topology Key" field.

The fix is working as expected, closing the bug.

**Closed by sadiapoddar** 2020-11-05 00:31 UTC
Labels: [zube]: To Test, area/workloads, kind/bug, priority/0
