### ISSUE TITLE
GKEv2 - Cluster details do not load in Cluster Management page when a cluster is in provisioning state

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3715] opened 2021-08-08 01:03 UTC
**On 2.6-head commit id: `0ab00d7`**

- Deploy a GKEv2 hosted cluster.
- The cluster is in provisioning state
- Click on CLuster --> Details --> Config page
- The page is sometimes stuck in loading
```
Uncaught TypeError: Cannot read property 'lastNode' of null
    at me.lastNode (runtime.js:1190)
    at fe.lastNode (runtime.js:1190)
    at Wt.lastNode (runtime.js:5108)
    at ge.lastNode (runtime.js:1303)
    at Yt.evaluate (runtime.js:5200)
    at Ht._execute (runtime.js:5052)
    at Ht.execute (runtime.js:5033)
    at Jt.rerender (runtime.js:5402)
    at ln.render (index.js:8295)
    at index.js:8587
```

- In some instances the The UI is seen in this state with error in console:
```
service.js:110 Uncaught TypeError: Cannot read property 'googleAuthURLPrefix' of undefined
    at service.js:110
    at Array.map (<anonymous>)
    at getValueFromOauthScopes (service.js:109)
    at e.unmapOauthScopes (service.js:173)
    at e.init (component.js:47)
    at e.n [as init] (index.js:442)
    at g (core_object.js:88)
    at Function.create (core_object.js:604)
    at g.create (index.js:527)
    at Ge.create (index.js:4393)
```
<img width="843" alt="Screen Shot 2021-08-07 at 5 58 13 PM" src="https://user-images.githubusercontent.com/26032343/128617446-687b29ec-2d31-469a-af75-b4ad3448e1ba.png">

**Comment by nwmac** [comment] 2021-08-11 13:19
@vincent99 Can you take a look

**Comment by gaktive** [comment] 2021-08-24 16:36
@vincent99 couldn't repro the issue though he has some other fixes in this area that will address other UI matters. Those should be merged soon.

**Comment by codyrancher** [comment] 2021-08-24 20:13
I also haven't been able to reproduce this. @sowmyav27 do you have any more details on reproducing? Do you have a rancher instance up that still reproduces this?

**Comment by prabalsharma** [comment] 2021-08-24 23:00
Tried on latest 2.6-head (v2.6-2e55e8436f77ce6f6142f0e322fc8f7c04b1a41b-head)
I was not able to reproduce this.

**Comment by sowmyav27** [comment] 2021-08-24 23:28
Closing this issue, as we were not able to reproduce

**Closed** 2021-08-24 23:28 UTC
Labels: kind/bug, [zube]: Done
