### ISSUE TITLE
In Create: Service we should say what type of service they are creating

### ISSUE THREAD

**Issue by tfiduccia** [rancher/dashboard#1544] opened 2020-09-30 21:55 UTC
Steps:
1.  Go to Services list page
2.  Click on Create
3.  Select Cluster IP

Results:  Top Title only says Service: Create, wold be nice if it said the type as well.  So include "Cluster IP" at top.
![image](https://user-images.githubusercontent.com/11514927/94743872-ee83ee00-032c-11eb-81a7-6f7ace6373d4.png)

**Comment by deniseschannon** [comment] 2020-10-06 23:37
@tfiduccia you've created this issue in the past :) https://github.com/rancher/dashboard/issues/1302

It's still a duplicate of: https://github.com/rancher/dashboard/issues/1073

**Closed by deniseschannon** 2020-10-06 23:37 UTC
Labels: area/service, kind/design
