### ISSUE TITLE
Cannot edit imported cluster from dashboard with same fields as Ember UI

### ISSUE THREAD

**Issue by aaronRancher** [rancher/dashboard#3005] opened 2021-05-14 23:51 UTC
**What kind of request is this (question/bug/enhancement/feature request):**
Bug

**Steps to reproduce (least amount of steps as possible):**
On Rancher `master-head` `version be0b016`
From dashboard cluster management view, import an RKE2 cluster.
After cluster becomes available, edit the cluster from Dashboard.

**Result:**
User cannot edit the RKE2 cluster with the same fields as Ember UI. RKE2 options are missing.
![Screen Shot 2021-05-14 at 3 45 21 PM](https://user-images.githubusercontent.com/57409052/118341413-e2bbf500-b4d3-11eb-86c3-fcae5beb321d.png)

**Other details that may be helpful:**
Expected edit from Ember UI:
![Screen Shot 2021-05-14 at 3 41 49 PM](https://user-images.githubusercontent.com/57409052/118341418-e8b1d600-b4d3-11eb-8ce5-9730bdd5c787.png)

**Environment information**
- Rancher version (`rancher/rancher`/`rancher/server` image tag or shown bottom left in the UI): `master-head` `version be0b016`
- Installation option (single install/HA): single install

**Comment by kravciak** [comment] 2021-05-17 11:00
Cluster edit options are available for cluster imported in emberUI.
They are not visible on cluster imported from dashboard.

Tested on master-head (5d2b7ac)

**Comment by gaktive** [comment] 2021-05-17 15:44
Duplicate of a recent case. Vince to check with Darren about what to do and then possibly iFrame.

**Closed by gaktive** 2021-05-17 15:44 UTC
Labels: [zube]: Done, kind/bug
