### ISSUE TITLE
CIS Benchmark: Console error on the scan list view

### ISSUE THREAD

**Issue by rak-phillip** [rancher/dashboard#11915] opened 2024-09-12 22:29 UTC
## Steps to reproduce

- Install CIS Benchmark cluster tool helm chart
- Cluster --> Tools --> install CIS Benchmark --> refresh
- Navigate to resource menu CIS Benchmark --> Scans

## Actual behavior

Errors are printed to the browser console

![Screenshot 2024-09-11 at 2 00 52 PM](https://github.com/user-attachments/assets/1409cc38-b295-4149-bc93-ecadaf6dd08f)

## Expected behavior

No errors printed to the console

**Comment by izaac** [comment] 2024-09-20 17:20
From Epic:

> I've added QA backlog task to explore the chart install automation effort as I didn't find a CIS covered in the current code
https://github.com/rancher/qa-tasks/issues/1547

**Comment by richard-cox** [comment] 2024-09-23 07:50
IS this solved by https://github.com/rancher/dashboard/pull/11916?

**Comment by aalves08** [comment] 2024-09-23 09:31
I couldn't reproduce it @richard-cox

**Comment by rak-phillip** [comment] 2024-09-23 15:21
> IS this solved by #11916?

I don't believe that #11916 would have addressed the issue described above. It's more likely that this issue was resolved by something different, I can try to identify what that was.

**Comment by rancher-max** [comment] 2024-11-11 22:55
I'm closing this as we are no longer able to reproduce. If it turns up again, we can reopen or open a new issue accordingly with more details.

**Closed by rancher-max** 2024-11-11 22:55 UTC
Labels: kind/bug, QA/dev-automation, area/vue3
