### ISSUE TITLE
UI does not shows up the Project Default Limit settings in the Namespaces during create or edit

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#4953] opened 2022-01-20 16:23 UTC
Internal reference: SURE-3912
Reported in 2.6.2

*Issue description:*
Create/Edit Namespaces:
- Able to see only the options of CPU and Memory, but with clean values. Not able to see/set ConfigMap, Pods, etc.
- Using the old UI is possible to see ConfigMap and Pods correctly, but CPU and Memory got converted/changed values. CPU values added by 000 (3 zeros), Memory values converted to weird values like 0.0003662109375

*Business impact:*
 N/A

*Troubleshooting steps:*
 Environment behavior reproduced in Lab

*Repro steps:*
 * Created a new and fresh RKE 1.3.1, v1.20.11, Rancher 2.6.2
 * Defined Project Resource Quotas / Namespace Default Limit for CPU, Memory, ConfigMaps and Pods
 * Created new Namespaces

*Workaround:*
 Is workaround available and implemented? 
- YES and NO
 What is the workaround: 
- Access the old UI (URL/g), but it doesn't work for CPU and Memory 'cause Memory and CPU values are converted/changed.

*Actual behavior:*
- UI only show up CPU and Memory empty filed values during Namespace create;

- UI doesn't show up the option to add other resource limits;

- UI doesn't show ConfigMap, Pods Namespaces - Project pre-configured Default Limit (Namespace looks like is not inheriting Project values)

*Expected behavior:*
 - See inherited values from Project definitions during Namespace create and/or Edit

- Be able to add more resource limits during Namespace create and/or edit, instead of being able to set only CPU and Memory

**Comment by neillsom** [comment] 2022-04-28 06:02
1. Not able to reproduce malformed data values as of 2.6.5
2. Both Ember UI and dashboard appear to match in regards to creation options:
  * New Project: add new Resource Quotas, configure Resource Limits
  * New Namespace: configure Resource Limits

**Comment by ronhorton** [comment] 2022-06-08 18:43
per @brandonsuse since dev unable to reproduce,  and no code changes, moving to done

**Closed** 2022-06-08 18:43 UTC
Labels: kind/bug, [zube]: To Test, internal, team/area3, area/project-quota, JIRA
