### ISSUE TITLE
Creating a new receiver in Monitoring dashboard fails

### ISSUE THREAD

**Issue by janbaer** [rancher/dashboard#1845] opened 2020-11-14 17:28 UTC
When I'm trying to add a new Slack receiver from the UI I just get a red error: Cannot read property 'data' of undefined

If I want to try the alternative with creating it from Yaml, I get no error, but the receiver will also not be created. I also see in the network requests of the browser no POST requests, only a get.

I use a fresh installed version 2.5.2 of Rancher in a Docker container.

**Comment by codyrancher** [comment] 2020-12-04 22:32
@jiaqiluo what are you doing to reproduce this? 

1. I'm using `docker run -d --restart=unless-stopped -p 8080:80 -p 8443:443 --privileged rancher/rancher:v2.5-head`.
2. I install monitoring
3. After monitoring is done installing I create a new slacker receiver without a problem

![receivers](https://user-images.githubusercontent.com/55104481/101221843-c32bc100-3645-11eb-91c2-a0dcddcc3050.gif)

**Comment by jiaqiluo** [comment] 2020-12-04 23:15
I cannot reproduce the bug on 
- `v2.5-head` 6e1e33c with monitoring v2 `9.4.202`
- `v2.5.3` with monitoring v2 `9.4.201` 

@janbaer  Do you still see the issue happen? Could you please try a newer version of Rancher or Monitoring v2.

**Comment by janbaer** [comment] 2020-12-06 08:23
I just updated the image and now I have version 2.5.2 running, but unfortunately, the error is still the same

**Comment by janbaer** [comment] 2020-12-06 09:07
![rancher-exception](https://user-images.githubusercontent.com/528331/101276068-b4125380-37aa-11eb-952e-a436974e2016.png)
This is where it's crashing when I click on "create"

**Comment by jiaqiluo** [comment] 2020-12-07 18:15
Hi @janbaer  Thank you for the feedback. 

I eventually got the bug reproduced last Friday, and the fix was merged and available on rancher:`v2.5-head` and rancher:`master-head`.

**Comment by jiaqiluo** [comment] 2020-12-07 18:17
The fix is validated on rancher:`v2.5-head` 395b4fe

Adding new receivers or deleting the existing receivers (even the default one) does not trigger the error anymore.

**Closed by jiaqiluo** 2020-12-07 18:17 UTC
Labels: [zube]: To Test, bug
