### ISSUE TITLE
Permissions Granted -  a  user with restricted user-base role can create / import existing cluster 

### ISSUE THREAD

**Issue by seb-835** [rancher/dashboard#5001] opened 2022-01-25 14:01 UTC
**Rancher Server Setup**
- Rancher version: 2.6.3
- Installation option :  Helm Charts -

**Information about the Cluster**
- Kubernetes version:Kubernetes v1.21.4 ( set with kubespray)
- Cluster Type : Local

**User Information**
What is the role of the user logged in? 
-  Local USER + Global-Permission set to  User Base   + Project Member Role 

**Describe the bug**
This user have the ability to : 
   - in Home : create  Custone cluster  
   -  in Home  import existing Generic cluster 
   - in Virtualization Management  :  ​create Harvester cluster
​
**To Reproduce**
Create an user with User-Base role , log with this user and go checking in Home 
to see that buttons :  create and import existing are there.

**Expected Result**
User-Base role should not permit that

**Comment by richard-cox** [comment] 2022-01-28 15:57
Both buttons just need to be gated on something like...

```
 const schema = this.$store.getters['management/schemaFor'](CAPI.RANCHER_CLUSTER);

 return !!schema?.collectionMethods.find(x => x.toLowerCase() === 'post');
```

**Comment by nwmac** [comment] 2022-03-15 14:27
@Sean-McQ Is this in review? I don't see a PR?

**Comment by gaktive** [comment] 2022-03-16 23:04
@nwmac looks like https://github.com/rancher/dashboard/pull/5328 is the PR but it's merged, so this may have been accidentally closed without QA based on the link, though I'm not sure what actually did happen here.

Putting in To Test so QA can validate, or then tell UI if something else went sideways here with our workflow.

**Comment by brudnak** [comment] 2022-03-17 23:57
# :white_check_mark: PASSED

## Reproduction Environment

| Component                          | Version / Type                                      |
| ---------------------------------- | --------------------------------------------------- |
| Rancher version                    | 2.6.3                                               |
| Installation option                | Helm high availability                              |
| If Helm Chart k8s cluster          | RKE v1.22.6                                         |
| Cert Details                       | ingress.tls.source=secret (certificates from files) |
| Docker version                     | 20.10.7, build f0df350                              |
| Helm version                       | v2.16.8-rancher1                                    |
| Downstream cluster type            | not applicable                                      |
| Downstream K8s version             | not applicable                                      |
| Logged in  role for test setup     | Local Administrator                                 |
| Logged in  role for test execution | Local User-Base                                     |
| Browser type                       | Google Chrome                                       |
| Browser version                    | 99.0.4844.51 (Official Build) (x86_64)              |

## Reproduction steps

1. Log into Rancher as a local administrator user
2. Navigate to `hamburger menu` -> `Users & Authentication` -> `Users` -> `Create`
3. Create a user with only `User-Base` permissions
4. Log out as administrator and login as the user-base user
5. Signed into the default of `/dashboard/home`
6. Observe the around `Clusters` in the UI
  
## Additional Info

## RESULTS

#### :white_check_mark: Expected
For no import or cluster creation buttons to be visible

#### :x: Actual
There are two buttons that shouldn't be there
1. `Import Existing`
2. `Create`

<hr>
  
## Validation Environment

| Component                          | Version / Type                                      |
| ---------------------------------- | --------------------------------------------------- |
| Rancher version                    | 2.6.4-rc9                                           |
| Installation option                | Helm high availability                              |
| If Helm Chart k8s cluster          | RKE v1.22.6                                         |
| Cert Details                       | ingress.tls.source=secret (certificates from files) |
| Docker version                     | 20.10.7, build f0df350                              |
| Helm version                       | v2.16.8-rancher1                                    |
| Downstream cluster type            | not applicable                                      |
| Downstream K8s version             | not applicable                                      |
| Logged in  role for test setup     | Local Administrator                                 |
| Logged in  role for test execution | Local User-Base                                     |
| Browser type                       | Google Chrome                                       |
| Browser version                    | 99.0.4844.51 (Official Build) (x86_64)              |

## Validation steps

1. Log into Rancher as a local administrator user
2. Navigate to `hamburger menu` -> `Users & Authentication` -> `Users` -> `Create`
3. Create a user with only `User-Base` permissions
4. Log out as administrator and login as the user-base user
5. Signed into the default of `/dashboard/home`
6. Observe the around `Clusters` in the UI

## Additional Info

## RESULTS

#### :white_check_mark: Expected
For no import or cluster creation buttons to be visible

#### :white_check_mark:Actual
No import or cluster creation buttons is visible

<img width="3265" alt="2022-03-17_16-52-27" src="https://user-images.githubusercontent.com/40877149/158912454-7ef450c2-51df-4b83-9199-2deb02f0abe8.png">

**Closed by brudnak** 2022-03-17 23:57 UTC
Labels: priority/0, [zube]: QA Working, team/area1
