### ISSUE TITLE
aksv2 - for imported clusters, when performing Edits, UI thinks k8s version has been updated

### ISSUE THREAD

**Issue by prabalsharma** [rancher/dashboard#3872] opened 2021-08-16 19:44 UTC
For imported clusters, when performing Edits from Rancher, UI thinks k8s version has been updated even when thats not the case. 

1. Import AKS cluster
2. Once Active, click Edit
3. Go to NPs. You will see the following even when k8s version has not been changed

<img width="767" alt="Screen Shot 2021-08-13 at 2 25 40 PM" src="https://user-images.githubusercontent.com/3749546/129419947-d900f5fd-2240-40d4-a9c2-8d8802672563.png">

This goes away once k8s version of CP is actually upgraded from Rancher.

(This was a Docker install of v2.6-e22c6bb23ee7e65f04e953afb7a449532cb44db0-head)

Feel free to change the milestone to 2.6.x

**Comment by claudioser** [comment] 2021-08-31 10:37
similar findings when "mistakenly" upgrading from Kubernetes v1.19.11 to 1.21.11. Receive msg that upgrade is not allowed. See screenshot. 
![image](https://user-images.githubusercontent.com/53047113/131488033-25ad096a-17ff-44b9-8fd1-111e913d64c2.png)

When trying to edit cluster again and rectifying it to a upgradable version, unable to do so as it thinks it is already upgraded.. 

![image](https://user-images.githubusercontent.com/53047113/131488227-6bd74cb5-37ab-4f20-b308-b6e30bf1f420.png)

**Comment by gaktive** [comment] 2021-10-01 16:37
As noted by @vincent99, this is adopted behaviour from kubectl, so the UI is given the same info as you'd see outside of Rancher. Working as designed unless you can show a discrepancy from kubectl.

**Comment by vincent99** [comment] 2021-10-01 21:26
@gaktive I don't think your comment is on the right issue?  I don't know what the cause of this one is but it has nothing to do with kubectl.

**Comment by gaktive** [comment] 2021-10-01 21:30
@vincent99 I'll put this back in our pile to look at then. I need to then find out which comment that was meant for...

**Comment by yonasberhe23** [comment] 2024-06-28 21:31
seems like there are no e2e/unit tests attached to the fix (I'm guessing it's because we don't have a way to create clusters in a cloud provider - please advise @mantis-toboggan-md) so we'll need to manually test this. moving to To Test

**Comment by yonasberhe23** [comment] 2024-07-11 18:11
Tested in: 
- v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
- master 84975df

No longer seeing the message when k8s version has not been changed on an imported cluster - only appears when version changed

https://github.com/rancher/dashboard/assets/127343932/b5df16da-1cad-44fd-af25-63f33a52f196

**Closed by yonasberhe23** 2024-07-11 18:11 UTC
Labels: kind/bug-qa, QA/dev-automation

**Comment by gaktive** [comment] 2024-07-24 20:44
Fixing milestone since this was still in the `.x` backlog.
