### ISSUE TITLE
 [Bug] Namespace resource quota configuration is missing in Cluster Explorer

### ISSUE THREAD

**Issue by janeczku** [rancher/dashboard#4412] opened 2021-10-19 10:20 UTC
Rancher 2.6.1

1. Create a project with the following resource quota assigned:
```
CPU limit: 2000 (Namespace default: 1200)
CPU reservation: 1000 (Namespace default: 600)
```
2. Configure container default resource limit of:
```
CPU reservation/limit 100/200
Memory reservation/limit 64MB/128MB
```
3. Create two namespaces in the project
4. Create a pod in each namespace

**Actual Result:**

- While creating a namespace in a project that has resource quota enabled, there is no UI element to configure pro-rata quota allocated to each namespace (as opposed to Rancher 2.5 Ember UI behaviour).
- The workload deployed in the second namespace fails to be scheduled because that namespace gets configured with a resource quota of `0` (although the project quota is not exhausted). 
    
<img width="1423" alt="Screenshot 2021-10-19 at 11 39 04" src="https://user-images.githubusercontent.com/3813921/137891084-f09d987e-dd1c-4318-bbd5-bbeae9cafdd7.png">

- There is no way of assigning the remaining project quota (2000-1200, 1000-600) to the second namespace

**Expected Result:**

When creating a namespace in a project that has a resource quota allocated, the UI must allow the user to configure the pro-rata resource quota that should be allocated to the namespace.

**Rancher 2.6 Available configuration options for creating namespace in a project with resource quota enabled**

<img width="1444" alt="2 6-add-project-namespace" src="https://user-images.githubusercontent.com/3813921/137890781-9bc7d9fe-db2a-48e7-9015-0c41fdad02bb.png">

**Rancher 2.5 Available configuration options for creating namespace in a project with resource quota enabled**

<img width="1328" alt="2 5-add-project-namespace" src="https://user-images.githubusercontent.com/3813921/137890987-457952d9-1d03-4e0a-8366-d02d8327bba9.png">

**Comment by brudnak** [comment] 2021-12-06 06:49
# ❌  My checks FAILED

## Reproduction Environment

#### Not required. Already completed above / previously.

<hr>
  
## Validation Environment

| Component               | Version / Type                          |
| ----------------------- | --------------------------------------- |
| Rancher version         | v2.6.3-rc3                              |
| Rancher cluster type    | Docker                                  |
| Docker version          | 20.10.7, build 20.10.7-0ubuntu5~20.04.2 |
| Helm version            | v2.16.8-rancher1                        |
| Downstream cluster type | RKE1 Linode                             |
| Downstream K8s version  | v1.21.6-rancher1-1                      |
| Browser type            | Google Chrome                           |
| Browser version         | 96.0.4664.55 (Official Build) (x86_64)  |

## Validation steps

<hr>

#### ✅  PASS | Scenario 1 | Project with two namespaces with enough resources to function as expected

1. Starting from the Rancher homepage `/dashboard/home` -> Click `hamburger menu` -> `Cluster Management` -> `Explore` (next to the cluster described in the reproduction environment) -> `Projects/Namespace` -> `Create Project`
2. Create a project like the following
    - Name: `test-project-1`
    - Click `Resource Quotas` -> `Add Resource`
    - Click `Add Resource` again for a total of 2 resource quotas
        - Resource Type: `CPU Limit` -> Project Limit: `2000` -> Namespace Default Limit: `1200`
        - Resource Type: `CPU Reservation` -> Project Limit: `1000` -> Namespace Default Limit: `600`
    - Click `Create` -> to create the project -> redirected back to `Projects/Namespaces`
3. Create two namespaces in the newly created project
    1. `test-namespace-one`
    2. `test-namespace-two`
    3. Leave the default alloted resource limits for both
4. Click `Workload` -> `Deployments` -> `Create`
    - Namespace: `test-namespace-two`
    - Name: `test-deploy-one`
    - Container Image: `brudnak/hello-rancher-golang`
    - Click `Resources`
        - CPU Reservation: `100`
        - CPU Limit: `200`
        - Memory Reservation: `64`
        - Memory Limit: `128`
    - Click `General`
        - Click `Add Port`
          -  Service Type: `Node Port`
          -  Private Container Port: `3000`
          -  Listening Port: `30441`
          -  Protocol: `TCP`
    - Click `Create` -> to create the cluster -> redirected back to the deployments page

**RESULT**

Deployment is successfully created!

<hr>

#### ❌  FAILED | Scenario 2 | Editing resource quota after creating namespace

>Editing the resource quota does not save when creating a namespace.

1. Starting from the Rancher homepage `/dashboard/home` -> Click `hamburger menu` -> `Cluster Management` -> `Explore` (next to the cluster described in the reproduction environment) -> `Projects/Namespace` -> `Create Project`
2. Create a project like the following
    - Name: `test-project-1`
    - Click `Resource Quotas` -> `Add Resource`
    - Click `Add Resource` again for a total of 2 resource quotas
        - Resource Type: `CPU Limit` -> Project Limit: `2000` -> Namespace Default Limit: `1200`
        - Resource Type: `CPU Reservation` -> Project Limit: `1000` -> Namespace Default Limit: `600`
    - Click `Create` -> to create the project -> redirected back to `Projects/Namespaces`
3. Create 1st namespace in the newly created project
    1. `test-namespace-one`
    2. Leave the default CPU Limit `1200`
    3. Leave the default CPU Reservation `600`
4. Create 2nd namespace in the newly created project
    1. `test-namespace-two`
    2. Leave the default CPU Limit `800`
    3. Leave the default CPU Reservation `400`
5. From the `Projects/Namespaces` page click the `ellipsis (three dots)` next to `test-namespace-two` -> click `Edit Config` 
6. Edit the `Resource Quotas`
    - Change CPU Limit from `800` to `200`
    - Change CPU Reservation from `400` to `64`
    - Click `Save` -> Redirected back to `Projects/Namespaces`
    - Click the `ellipsis` next to `test-namespace-two` again -> click `Edit Config`
7. Observe that the resource quotas have not been saved / changed. Even though there was no error message displayed and the form appeared to save successfully from the UI.
8. Observe screenshot labeled `A1` below. Even though the UI is not showing the updated values, they are being displayed in the Vue dev tools.

![Screen Shot 2021-12-05 at 11 41 28 PM](https://user-images.githubusercontent.com/40877149/144800377-b93f93e2-3e7f-4808-a3ef-a0477ccf8a8e.png)


**RESULT**

Unable to edit the alloted resource quota limits on a namespace. No error or warning message provided even though the change did not save successfully.

**EXPECTED**

For the save to be successful. Or for there to be an error message if this was an invalid operation.

**Comment by deniseschannon** [comment] 2021-12-09 19:23
Whoever picks this up for dev-validate, can you please follow the 2 steps that @brudnak had completed as part of his validation to confirm there is no regression.

**Comment by n313893254** [comment] 2021-12-14 12:20
Verify on the latest UI: v2.6-5b56b17e2515302ad07b9e14e73024455157c546-head

✅  PASS | Scenario 1 | Project with two namespaces with enough resources to function as expected

![image](https://user-images.githubusercontent.com/18737885/145997218-1b468836-cc32-46b0-9263-e9ba1369aad9.png)


✅  PASS | Scenario 2 | Editing resource quota after creating the namespace

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/0e251d1f-420c-44ce-9eb6-c75f36a814db)

**Comment by n313893254** [comment] 2021-12-15 15:01
Reopen due to verify fail.

Verify on the latest UI: v2.6-5b56b17e2515302ad07b9e14e73024455157c546-head

#### ❌  FAILED | Scenario 1 | Create namespace with default memory resource quota

1. Starting from the Rancher homepage `/dashboard/home` -> Click `hamburger menu` -> `Cluster Management` -> `Explore` (next to the cluster described in the reproduction environment) -> `Projects/Namespace` -> `Create Project`
2. Create a project like the following
    - Name: `resource-quota`
    - Click `Resource Quotas` -> `Add Resource`
    - Click `Add Resource` again for a total of 2 resource quotas
        - Resource Type: `Memory Limit` -> Project Limit: `9216` -> Namespace Default Limit: `256`
        - Resource Type: `Memory Reservation` -> Project Limit: `4096` -> Namespace Default Limit: `128`
    - Click `Create` -> to create the project -> redirected back to `Projects/Namespaces`
 3. Create a namespace in the newly created project
 
**RESULT**

![image](https://user-images.githubusercontent.com/18737885/146207031-16c39ab1-09bd-418e-9f96-4f6dce50115c.png)

**EXPECTED**

Compared with the Rancher old UI(Manager UI), The Default value of Resource Quotas should be the same as **Namespace Default Limit**. The default namespace resource quota should be `256` and `128`

![image](https://user-images.githubusercontent.com/18737885/146207138-7191aa35-4145-4d42-b4d9-d9abc4432d39.png)

#### ❌  FAILED | Scenario 2 | Edit namespace memory resource quota
1. Starting from the Rancher homepage `/dashboard/home` -> Click `hamburger menu` -> `Cluster Management` -> `Explore` (next to the cluster described in the reproduction environment) -> `Projects/Namespace` -> `Create Project`
2. Create a project like the following
    - Name: `resource-quota`
    - Click `Resource Quotas` -> `Add Resource`
    - Click `Add Resource` again for a total of 2 resource quotas
        - Resource Type: `Memory Limit` -> Project Limit: `9216` -> Namespace Default Limit: `256`
        - Resource Type: `Memory Reservation` -> Project Limit: `4096` -> Namespace Default Limit: `128`
    - Click `Create` -> to create the project -> redirected back to `Projects/Namespaces`
 3. Create a namespace in the newly created project
 4. Edit resource quota
        - Resource Type: `Memory Limit` -> `256`
        - Resource Type: `Memory Reservation` -> `128`
 
 **RESULT**
 Any input will be rewirte
![image](https://user-images.githubusercontent.com/18737885/146208983-daae4d6e-38ea-4f68-bc71-a09fd7884e5c.png)

**EXPECTED**

The namespace resource quota should be `256` and `128`

**Comment by guangbochen** [comment] 2021-12-16 12:20
verified on https://github.com/harvester/harvester/issues/1450#issuecomment-995759640, feel free to close it.

**Comment by gaktive** [comment] 2021-12-16 17:45
@sowmyav27 by the sounds of it, this is tested. I'll leave this for you to close if that's ok.

**Closed** 2021-12-16 18:01 UTC
Labels: kind/bug, area/namespace, [zube]: To Test, internal, status/dev-validate, area/harvester, status/release-blocker
