### ISSUE TITLE
Trim index URL when creating new Chart Repositories

### ISSUE THREAD

**Issue by PennyScissors** [rancher/dashboard#3794] opened 2021-08-11 17:10 UTC
Problem:
When you create a new Chart Repository and copy/paste an index URL, sometimes the URL may have leading and/or trailing spaces. You can then go on and create the Chart Repository, but it will fail due to the spaces which are hard to see in the text box and the error message.

Solution:
Trim leading and trailing spaces from the URL, or add validation for the URL before allowing creating the Chart Repository.

Chart Repository with a index URL containing leading and trailing spaces
![image](https://user-images.githubusercontent.com/8951271/129071592-11c12830-8c77-406e-b54e-46f9d1d51f36.png)

Error with leading spaces only:
![image](https://user-images.githubusercontent.com/8951271/129071869-3d483434-ab63-490f-a5da-1182eb6bbccd.png)

Error with trailing spaces only:
![image](https://user-images.githubusercontent.com/8951271/129072145-f241c82d-303e-492d-a1b3-a1925bec4eda.png)

After manually removing spaces to fix it:
![image](https://user-images.githubusercontent.com/8951271/129073321-ea34d9a8-6854-4916-8385-af85cafe2756.png)

**Comment by thehejik** [comment] 2021-08-30 10:08
Tested on `rancher/rancher:v2.6-head 940ebaf`

It works correctly for `http` (leading/ending tabulators and spaces are trimmed out) URL but doens't work for git repo url. 

Once I enter something like`   https://charts.rancher.io    ` or `\t\t charts.rancher.io \t` as git repo url the spaces are not trimmed and rancher is still  reporting errors:
![git-repo-spaces-failure](https://user-images.githubusercontent.com/12828077/131323281-4e2f5510-b93e-4a98-9144-90d5c179a0d7.png)

Reopening.

**Comment by davidnuzik** [comment] 2021-09-07 19:58
Hmm something still isn't quite right. This doesn't appear to be working.
 
**My checks Failed**
 
**Reproduction Steps:**

Not required. I understand the issue clearly and how to reproduce.
 
**Validation Environment:**

Rancher version: v2.6-head `1718f1455` pulled at 9/7/21 12:04 pm Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Explore the local cluster in the vue ui. Go To Apps & Marketplace -> Chart Repositories. Click edit for the git.rancher.io/charts entry that already exists.
2. Edit this entry add some spaces after the URL (these should get trimmed upon submission). In my case I added five spaces after the Git Repo URL. Click Save to update and send the PUT request.
![image](https://user-images.githubusercontent.com/45179589/132402729-0edaf468-3c76-4edc-8d6a-507b4bf72fbf.png)
Inspect the PUT request payload. The spec looks normal (no trailing spaces)
![image](https://user-images.githubusercontent.com/45179589/132402808-fb656d96-9038-401c-b240-2891feecbf9c.png)
HOWEVER it looks like my FireFox browser dev tool here is "lying" to us - inspect the raw json payload -- we still see the trailing spaces submitted in the PUT request:
![image](https://user-images.githubusercontent.com/45179589/132402966-e7f3ad96-bb9d-460b-b7f2-119bcb8c1180.png)
Additionally we see the server response payload also includes the trailing spaces (it looks exactly the same as the request).
3. Tested with other scenarios like spaces before the URL, and with http instead of https - same situation regardless.

 
**Additional Info:**
spaces before URL:
![image](https://user-images.githubusercontent.com/45179589/132403351-77b8497d-7bb5-4efe-8618-14ff460d2c27.png)
spaces after URL:
![image](https://user-images.githubusercontent.com/45179589/132403402-ee1f9f14-184f-4879-a16e-ee959ad3d613.png)

We can also observe the issue in the Rancher Server logs:
![image](https://user-images.githubusercontent.com/45179589/132403444-5fd6253a-ef5e-44fe-9f0a-c27bd4efb1fc.png)

**Comment by davidnuzik** [comment] 2021-09-08 16:29
There was a problem where v2.6-head rancher was not using latest dashboard UI. Fixed in https://github.com/rancher/rancher/pull/34675. I am going to test again -- this time rancher should be pulling in the latest UI.

**Comment by davidnuzik** [comment] 2021-09-09 17:46
**My checks Passed**
 
**Reproduction Steps:**

Not required. I understand the issue clearly and how to reproduce.
 
**Validation Environment:**

Rancher version: v2.6-head `a6e7905` pulled 9/9/21 10:37am Pacific
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Explore the local cluster in the vue ui. Go To Apps & Marketplace -> Chart Repositories. Click edit for the git.rancher.io/charts entry that already exists.
2. Edit this entry add some spaces after the URL (these should get trimmed upon submission). In my case I added five spaces after the Git Repo URL. Click Save to update and send the PUT request.
3. Inspect the PUT request payload and response - view in RAW JSON because firefox will truncate extra spaces in the default view (in it's browser dev tool).
CONFIRMED that any postfix spaces in the URL are now trimmed.
4. Do the same, but this time add spaces before the Git Repo URL
CONFIRMED that any prefix spaces in the URL are now trimmed.

Adding spaces before or after always result in a successful PUT request (200 OK) and inspecting the request/response payloads shows that the spaces were trimmed:
```
    "spec": {
        "clientSecret": null,
        "gitBranch": "dev-v2.6",
        "gitRepo": "https://git.rancher.io/charts"
    },
```

**Closed by davidnuzik** 2021-09-09 17:46 UTC
Labels: [zube]: QA Working
