### ISSUE TITLE
RKE2 Custom Cluster details page taking long time to show after creating a cluster and No Registration command displayed on creation

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#3677] opened 2021-08-05 15:46 UTC
**On 2.6.0-rc1**

- Deploy rancher server
- Deploy a custom RKE2 cluster - enter a name and hit Create (Happens on the very first custom cluster in the rancher setup)
- It takes almost like 15 seconds to load the next page. It is stuck in loading
- And there is no registration command seen
<img width="1679" alt="Screen Shot 2021-08-05 at 8 43 03 AM" src="https://user-images.githubusercontent.com/26032343/128380253-62619e56-cfa7-4e01-95e1-be7dfb6eb68b.png">

**Note:**
- But when the user goes back to Cluster Management page and returns to detail page of ^^ custom cluster, registration command is available
- Any further custom rke2 clusters _have_ the registration command right after creation

**Comment by richard-cox** [comment] 2021-08-05 16:27
Highly likely related to #3396, specifically incoming fix mentioned in https://github.com/rancher/dashboard/issues/3396#issuecomment-893470097

**Comment by richard-cox** [comment] 2021-08-07 08:58
The second part will be fixed via #3711. The first part is most probably an issue when making the request to saving the provisioning cluster but requires confirmation, specifically having monitoring the request in dev tools network tab. Will mark as fixed to validate fix for second part and confirm network request for first.

**Comment by igomez06** [comment] 2021-08-09 23:06
Verified on v2.6-head - c47122a

**Steps taken to see the issue is fixed:**
* Fresh rancher setup, created the first custom cluster.
* After creation, user is taken to the detail page, and the cluster registration command is immediately available. NO delay.

**Closed by igomez06** 2021-08-09 23:07 UTC
Labels: kind/bug, [zube]: QA Next up, status/release-blocker
