### ISSUE TITLE
Error message not displayed while creating Gitrepo with invalid characters

### ISSUE THREAD

**Issue by mmartin24** [rancher/dashboard#12444] opened 2024-10-31 14:25 UTC
**Setup**
- Rancher version: `2.10.0-alpha5`
- Rancher UI Extensions:
- Browser type & version:Brave 1.70

**Describe the bug**

User is correctly prevented from creating a gitrepo with invalid characters but Error message is not dispayed in UI

**To Reproduce**

- Deploy Rancher 2.10.0-alpha5
- Attempt to create gitrepo named `Test.1-repo-local-cluster` in local cluster

**Result**
Error is triggered but no message is shown
![image](https://github.com/user-attachments/assets/6e9de0b0-5894-4793-9ea6-82c8344c8a27)

**Expected Result**
Message should be shown as it was in 2.9
![image](https://github.com/user-attachments/assets/eb411dc4-471c-4a52-a20a-3bef43471d11)

**Screenshots**

**Additional context**

**Comment by eva-vashkevich** [comment] 2024-10-31 18:19
Could be a duplicate of #12391

**Closed** 2024-10-31 18:26 UTC
Labels: kind/bug, QA/dev-automation
