### ISSUE TITLE
After login there is an error - Cannot read properties of null (reading 'startsWith') Home

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#5004] opened 2022-01-28 17:51 UTC
Internal reference: SURE-3978

Issue description:
After upgrading to 2.6.3 I get an error on login, 
`Cannot read properties of null (reading 'startsWith') Home`

Business impact:
the UI is unusable in the 2.6.3 release in this case.

Troubleshooting steps:
User was notified that this can mean that one cluster you were working with is unavailable or offline at the moment ... because 2.6.x can remember your home screen as different pages/places hit the Home button there and make sure the UI comes up.

https://github.com/rancher/dashboard/issues/4967 is similar but slightly different. Google suggests this is problem with the underlying node system and not an API hiccup.

Repro steps:
Upgrade to Rancher 2.6.3 seems to be the only thing that triggers this

Workaround:
They discovered the old UI is still valid at the `/g/` suffix and they're using that at the moment (and happy to do so, love the old UI). There are some hiccups like an overlay that loads on page nav (guessing that RMC is pulling info for a new namespace) doesn't disappear and they need to manually remove it.

**Comment by richard-cox** [comment] 2022-03-09 17:39
I've tried to reproduce this but don't get the exact error shown, only one that's slightly workable
1. I've installed 2.6.2 HA/Helm 
2. imported a local (k3d) cluster
3. set that cluster as my home page
4. upgraded to 2.6.3
5. visited `<rancher url>/` and everything is fine
6. stopped the local cluster (not available)
7. visited `<rancher url>/` and get the `fail-whale` error page with a somewhat cryptic `{"data":"lost connection to cluster: failed to find Session for client stv-cluster-c-m-fw99x5xj"}` error, but the burger menu is still accesible and the `home` button works ok.

![image](https://user-images.githubusercontent.com/18697775/157498823-ea05f595-86a0-4170-a2d4-44ce576ccaee.png)

I've also messed around in 2.6-head and get something similar. Here's some questions

- What is the exact error text? 
- Where is it shown?
  - On screen - Can you provide any errors shown in the browser's Dev Tools console or network tab?
  - In the browser's Dev tools console - Can you provide a screenshot of what's shown on screen?
- If the error is shown on screen what is the url, does it end in `fail-whale`? If so can the user still use the burger menu top left to get back to the working dashboard?
- What type of user (admin, non-admin)?
- What did they set their 'home' page to be, is a specific cluster? What is the state of that cluster?

**Comment by mantis-toboggan-md** [comment] 2022-03-09 18:21
I've just been directed to /fail-whale and seen `Cannot read properties of null (reading 'startsWith')` after timing out/being booted to the login and re-logging-in. No upgrade involved but it might be worth investigating @richard-cox ? The console error:
![Screen Shot 2022-03-09 at 10 35 16 AM](https://user-images.githubusercontent.com/42977925/157505873-301b4a1f-38ec-4dfc-8320-d625e8439111.png)

**Comment by richard-cox** [comment] 2022-03-10 12:03
Given @mantis-toboggan-md 's finding I think this is an issue with the generic 404 page. The process was broken which meant we always showed the fail-whale page with cryptic `Cannot read properties of null (reading 'startsWith')` error. I can't confirm if this fixes the original issue due to the lack of info, but the error message they're seeing matches that which is resolved by the associated PR (I've also added better debugging for these kind of errors). For those reasons I think this should be resolved

**Comment by nwmac** [comment] 2022-03-10 13:26
@richard-cox So can we move this to test?

**Comment by richard-cox** [comment] 2022-03-10 13:32
@nwmac PR's in review - https://github.com/rancher/dashboard/pull/5332, requested of Nancy this (uk) morning, happy to do with you if you wish?

**Comment by anupama2501** [comment] 2022-03-18 22:06
On 2.6.3, after the initial login,
<img width="500" alt="UInull" src="https://user-images.githubusercontent.com/38144301/159090113-90f1fc76-dbb4-454f-9d89-f4e2432e7cd3.png">

- Created a cluster and set the login page to that cluster
- Upgraded rancher to v2.6-head `15b8f2c ` and do not see the error anymore

**Closed by anupama2501** 2022-03-18 22:06 UTC
Labels: kind/bug, internal, [zube]: QA Next up, priority/1, team/area1, status/waiting-response

**Comment by gaktive** [comment] 2022-03-28 17:13
There's a request through @snasovich to backport this to 2.6.3 as patch 3. A new ticket to be filed and linked here.

@rak-phillip to look at what was done for branching with patch 1 to replicate for this.

**Comment by rak-phillip** [comment] 2022-03-28 22:52
Last time around, we branched `release/v2.6.3-patch1` from the commit that was used for release `v2.6.3`. After that, we cherry-picked any commits that needed to be backported into `release/v2.6.3` and used that as the target branch for the release.
