### ISSUE TITLE
Labels and Annotations section different in Services vs Configmaps

### ISSUE THREAD

**Issue by sowmyav27** [rancher/dashboard#1118] opened 2020-08-27 17:03 UTC
**On master-head - commit id: `5e1b21b93`**

<img width="1686" alt="Screen Shot 2020-08-27 at 10 01 38 AM" src="https://user-images.githubusercontent.com/26032343/91472544-77020100-e84c-11ea-8a53-1bf8a15c0744.png">

<img width="1686" alt="Screen Shot 2020-08-27 at 10 01 50 AM" src="https://user-images.githubusercontent.com/26032343/91472571-808b6900-e84c-11ea-8cab-ceeac744e1f3.png">

**Expected:**

Services Labels and Annotations section should match Configmaps and Namespaces

**Comment by deniseschannon** [comment] 2020-08-31 17:39
Duplicate of https://github.com/rancher/dashboard/issues/1067

When ^^ is fixed, this will be fixed.

**Closed by deniseschannon** 2020-08-31 17:39 UTC
Labels: kind/bug
