### ISSUE TITLE
Delete Pod Dialog - can't delete lots of pods at once

### ISSUE THREAD

**Issue by agxs** [rancher/dashboard#731] opened 2020-06-05 10:45 UTC
If you try and delete lots of pods at once the dialog doesn't scroll and the delete button is off the bottom of the page. See the example screenshot:

![image](https://user-images.githubusercontent.com/804915/83867856-fd151c80-a721-11ea-9e39-b736de281f35.png)

A workaround is to use the Chrome developer tools, then find the Delete button in the markup in the Elements tab and select 'Scroll Into View'

**Comment by izaac** [comment] 2020-06-29 22:35
Reproduced in Rancher `v2.4.5`
![pods_button_not_shown](https://user-images.githubusercontent.com/27659/86062637-0a21e480-ba1e-11ea-95b6-8095d0ec2f31.png)

**Comment by izaac** [comment] 2020-06-29 23:55
Validated in Rancher `master-head` commit _1a5e5622b_

![Screen Shot 2020-06-29 at 4 49 08 PM](https://user-images.githubusercontent.com/27659/86066990-8cafa180-ba28-11ea-9def-b79326349eb1.png)

I still don't see the the UI refreshing the pods table automatically after clicking `Delete` not sure if that's feature ready @mantis-toboggan-md or where it's being tracked.

Also I can't get the key combination mentioned in the tip to work `protip: Hold the Command key while clicking delete to bypass this confirmation`.

If I try it I get:

``` javascript
TypeError: Cannot set property 'alt' of null
    at f.applyTableAction (selection.js:354)
    at click (index.vue?8f5c:1)
    at Qt (vue.runtime.esm.js:1854)
    at HTMLButtonElement.n (vue.runtime.esm.js:2179)
    at HTMLButtonElement.c._wrapper (vue.runtime.esm.js:6917)
te @ 215e04da83c9d8e51c70.js:2
Zt @ 215e04da83c9d8e51c70.js:2
Jt @ 215e04da83c9d8e51c70.js:2
Qt @ 215e04da83c9d8e51c70.js:2
n @ 215e04da83c9d8e51c70.js:2
c._wrapper @ 215e04da83c9d8e51c70.js:2
```

**Comment by mantis-toboggan-md** [comment] 2020-07-17 18:12
A fix for the alt action is merged now. The issue of resource lists needing a refresh to reflect deletion was being addressed by @vincent99 in rancher/dashboard#644

**Comment by vincent99** [comment] 2020-07-17 18:30
Delete is currently not reflecting in the list again in some cases, but because the backend isn't sending a `resource.remove` event...

**Comment by izaac** [comment] 2020-07-21 00:16
Rancher version `master-head (07/20/2020)` commit _c289ff7de_
dashboard-index -> `latest`
Cluster Owner is a `Standard User`
Upstream Cluster -> RKE (DO)

I'm assuming the Command key in Mac OS X / Chrome is => ⌘

But holding that key and then clicking Delete while selecting the pods to delete is throwing this error now:

```js
vue.runtime.esm.js:1888 TypeError: Invalid attempt to spread non-iterable instance.
In order to be iterable, non-array objects must have a [Symbol.iterator]() method.
    at nonIterableSpread.js:2
    at c (toConsumableArray.js:6)
    at E (selectionStore.js:256)
    at y.executeTable (selectionStore.js:190)
    at Array.<anonymous> (vuex.esm.js:847)
    at y.dispatch (vuex.esm.js:512)
    at y.dispatch (vuex.esm.js:402)
    at f.applyTableAction (selection.js:359)
    at click (index.vue?8f5c:1)
    at Qt (vue.runtime.esm.js:1854)
te @ app.3f215696971a0f4251fe.js:2
Zt @ app.3f215696971a0f4251fe.js:2
Jt @ app.3f215696971a0f4251fe.js:2
Qt @ app.3f215696971a0f4251fe.js:2
n @ app.3f215696971a0f4251fe.js:2
c._wrapper @ app.3f215696971a0f4251fe.js:2
```

**Comment by izaac** [comment] 2020-08-03 21:01
Validated in Racher `master-head (08/03/2020)` _30e77d238_
dashboard-index -> `latest`

The Delete card-container is now showing a summary of the pods to delete.
Using the pro-tip holding the ⌘ key and clicking delete, directly deletes the pods without the card-container dialog.

Validated in both dark and light themes.

**Closed by izaac** 2020-08-03 21:01 UTC
Labels: [zube]: To Test
