### ISSUE TITLE
[UI] Unable to see logs in UI

### ISSUE THREAD

**Issue by Torkolis** [rancher/dashboard#6453] opened 2022-06-24 10:45 UTC
**Rancher Server Setup**
- Rancher version: 2.6.5
- Installation option (Docker install/Helm Chart): Helm
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc): RKE2
- Proxy/Cert Details: Trusted certificate in Ingress

**Information about the Cluster**
- Kubernetes version: v1.23.7+rke2r2
- 
- Cluster Type (Local/Downstream): Local

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom): Admin

   
**Describe the bug**
When clicking "show logs" for any pod, the window pops up but stays empty all the time. Console logs say that there is some TypeError.

**To Reproduce**
1. Change preference in the logs window to show e.g. last 1,000 lines.
2. log out from Rancher
3. close and reopen browser
4. try to show logs again.

**Screenshots**
![image](https://user-images.githubusercontent.com/98939160/175519489-2841f521-28bf-4195-8887-d35bc63da282.png)

**Additional context**
Errors in browser console:
```
vue.runtime.esm.js:1888 TypeError: r.replace is not a function
    at C (opsgenie.vue?578b:153:1)
    at f.rangeOptions (opsgenie.vue?578b:116:9)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.rangeOptions (vue.runtime.esm.js:4836:17)
    at fn (rke2.svg:1:2097)
    at Object.r [as title] (vue.runtime.esm.js:2590:62)
    at f.r (rke.svg:1:159)
    at t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
te @ vue.runtime.esm.js:1888
Zt @ vue.runtime.esm.js:1879
Jt @ vue.runtime.esm.js:1839
t._render @ vue.runtime.esm.js:3550
r @ vue.runtime.esm.js:4066
_n.get @ vue.runtime.esm.js:4479
_n @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
$n.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
v @ vue.runtime.esm.js:5925
(anonymous) @ vue.runtime.esm.js:6477
t._update @ vue.runtime.esm.js:3945
r @ vue.runtime.esm.js:4066
_n.get @ vue.runtime.esm.js:4479
_n @ vue.runtime.esm.js:4468
t @ vue.runtime.esm.js:4073
$n.$mount @ vue.runtime.esm.js:8415
init @ vue.runtime.esm.js:3118
(anonymous) @ vue.runtime.esm.js:5978
v @ vue.runtime.esm.js:5925
_ @ vue.runtime.esm.js:6053
v @ vue.runtime.esm.js:5954
S @ vue.runtime.esm.js:6106
(anonymous) @ vue.runtime.esm.js:6233
j @ vue.runtime.esm.js:6319
(anonymous) @ vue.runtime.esm.js:6482
t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
_n.get @ vue.runtime.esm.js:4479
_n.run @ vue.runtime.esm.js:4554
gn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ie @ vue.runtime.esm.js:1906
Promise.then (async)
ee @ vue.runtime.esm.js:1933
se @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
_n.update @ vue.runtime.esm.js:4544
_t.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
n.addObject @ array.ts:65
addTab @ app.19d73dab09087954b96b.js:2
(anonymous) @ vuex.esm.js:840
(anonymous) @ vuex.esm.js:462
(anonymous) @ vuex.esm.js:461
y._withCommit @ vuex.esm.js:620
y.commit @ vuex.esm.js:460
commit @ vuex.esm.js:405
r.commit @ vuex.esm.js:792
open @ app.19d73dab09087954b96b.js:2
(anonymous) @ vuex.esm.js:847
y.dispatch @ vuex.esm.js:512
dispatch @ vuex.esm.js:402
r.dispatch @ vuex.esm.js:775
value @ RoleDetailEdit.vue?9983:83
(anonymous) @ app.19d73dab09087954b96b.js:2
execute @ app.19d73dab09087954b96b.js:2
(anonymous) @ vuex.esm.js:847
y.dispatch @ vuex.esm.js:512
dispatch @ vuex.esm.js:402
execute @ PromptRemove.vue?ff5e:207
click @ browserMd5.js:3
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
c._wrapper @ vue.runtime.esm.js:6917
Show 5 more frames
socket.js:81 Socket connecting (id=32, url=wss://#####/api/v1/namespaces/#####/pods/#####/log...)
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at opsgenie.vue?578b:222:1
    at d (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at O.forEach.t.<computed> [as next] (runtime.js:97:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
te @ vue.runtime.esm.js:1888
Zt @ vue.runtime.esm.js:1879
Jt @ vue.runtime.esm.js:1839
(anonymous) @ vue.runtime.esm.js:1856
Promise.catch (async)
Qt @ vue.runtime.esm.js:1856
cn @ vue.runtime.esm.js:4219
insert @ vue.runtime.esm.js:3139
$ @ vue.runtime.esm.js:6346
(anonymous) @ vue.runtime.esm.js:6565
t._update @ vue.runtime.esm.js:3948
r @ vue.runtime.esm.js:4066
_n.get @ vue.runtime.esm.js:4479
_n.run @ vue.runtime.esm.js:4554
gn @ vue.runtime.esm.js:4310
(anonymous) @ vue.runtime.esm.js:1980
ie @ vue.runtime.esm.js:1906
Promise.then (async)
ee @ vue.runtime.esm.js:1933
se @ vue.runtime.esm.js:1990
(anonymous) @ vue.runtime.esm.js:4402
_n.update @ vue.runtime.esm.js:4544
_t.notify @ vue.runtime.esm.js:730
(anonymous) @ vue.runtime.esm.js:882
n.addObject @ array.ts:65
addTab @ app.19d73dab09087954b96b.js:2
(anonymous) @ vuex.esm.js:840
(anonymous) @ vuex.esm.js:462
(anonymous) @ vuex.esm.js:461
y._withCommit @ vuex.esm.js:620
y.commit @ vuex.esm.js:460
commit @ vuex.esm.js:405
r.commit @ vuex.esm.js:792
open @ app.19d73dab09087954b96b.js:2
(anonymous) @ vuex.esm.js:847
y.dispatch @ vuex.esm.js:512
dispatch @ vuex.esm.js:402
r.dispatch @ vuex.esm.js:775
value @ RoleDetailEdit.vue?9983:83
(anonymous) @ app.19d73dab09087954b96b.js:2
execute @ app.19d73dab09087954b96b.js:2
(anonymous) @ vuex.esm.js:847
y.dispatch @ vuex.esm.js:512
dispatch @ vuex.esm.js:402
execute @ PromptRemove.vue?ff5e:207
click @ browserMd5.js:3
Qt @ vue.runtime.esm.js:1854
n @ vue.runtime.esm.js:2179
c._wrapper @ vue.runtime.esm.js:6917
socket.js:313 Socket opened (state=connecting, id=32)
Taints.vue?e932:408 Ping [management] from dev
```

**Comment by richard-cox** [comment] 2022-07-22 09:13
Thanks for raising this issue, however as mentioned above it's a duplicate of https://github.com/rancher/dashboard/issues/5984 and will be resolved in 2.6.7. There's some info about workarounds in https://github.com/rancher/dashboard/issues/5984#issuecomment-1180191702

**Closed** 2022-07-22 09:16 UTC
