### ISSUE TITLE
Unable to view logs in Rancher UI after setting 'Show the last' option

### ISSUE THREAD

**Issue by gaktive** [rancher/dashboard#6441] opened 2022-07-21 16:26 UTC
Internal reference: SURE-4885
Reported in 2.6.5

Issue description:
After viewing Pod logs via the Rancher UI, clicking the cog icon, and setting a "Show the last" option for the logs, logs are no longer visible via the UI.

Issue by external people already in https://github.com/rancher/rancher/issues/38082 (with additional comments and a workaround as described later)

Business impact:
Pods logs not viewable via the UI

Repro steps:

- Provision a Rancher v2.6.5 instance (I used github.com/superseb/tf-do-rancher2)
- Log and successfully view the Pod logs of a Pod in the local cluster
- Click the cog icon, and set a value in "Show the last", e.g. 1000 lines
- Observe you can still successfully view the logs of a Pod
- Refresh the browser window or logout and login
- Observe that attempting to view Pod logs now fails, and the browser console shows errors of the following format:

```
vue.runtime.esm.js:1888 TypeError: r.replace is not a function
    at C (opsgenie.vue?578b:153:1)
    at f.rangeOptions (opsgenie.vue?578b:116:9)
    at _n.get (vue.runtime.esm.js:4479:25)
    at _n.evaluate (vue.runtime.esm.js:4584:21)
    at f.rangeOptions (vue.runtime.esm.js:4836:17)
    at fn (rke2.svg:1:2097)
    at Object.r [as title] (vue.runtime.esm.js:2590:62)
    at f.r (rke.svg:1:159)
    at t._render (vue.runtime.esm.js:3548:22)
    at f.r (vue.runtime.esm.js:4066:21)
Socket connecting (id=15, url=wss://188.166.60.208/k8s/clusters/c-xbqjf/api/v1/namespaces/cattle-system/pods/cattle-node-agent-smjd9/log...)
vue.runtime.esm.js:1888 TypeError: Cannot read properties of undefined (reading 'addEventListener')
    at opsgenie.vue?578b:222:1
    at d (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at O.forEach.t.<computed> [as next] (runtime.js:97:21)
    at r (asyncToGenerator.js:3:20)
    at l (asyncToGenerator.js:25:9)
```

- Execute `kubectl -n <user-id> delete preferences logs-range` in the Rancher local cluster
- Refresh the browser window or logout and login
- Observe it is not possible to successfully view Pod logs via the UI

Workaround:
Is workaround available and implemented? 
Execute `kubectl -n <user-id> delete preferences logs-range` in the Rancher local cluster

Actual behavior:
Logs not viewable via UI after setting "Show the last" option for logs

Expected behavior:
Logs viewable via UI after setting "Show the last" option for logs

**Comment by mantis-toboggan-md** [comment] 2022-07-21 17:23
This is a duplicate of https://github.com/rancher/dashboard/issues/5984 (and is fixed in 2.6.7)

**Closed** 2022-07-21 17:23 UTC
Labels: kind/bug, [zube]: To Triage, area/logging, priority/1, JIRA
