### ISSUE TITLE
(SURE-5538) Persistent Volume is not having CSI driver as vol plugin which is current default for latest versions of AKS

### ISSUE THREAD

**Issue by kkaempf** [rancher/dashboard#8791] opened 2023-02-03 14:12 UTC
### Issue description:
Persistent Volume is not having CSI driver as vol plugin which is current default for latest version of AKS

### Business impact:
Unable to use storage PV for operations purposes

### Troubleshooting steps:
Recreate AKS environment and import into rancher

### Repro steps:

step 1: Establish a PV in Rancher
step 2: Attempt to connect PV to cluster

### Workaround:
Is workararound available and implemented? no
What is the workaround: n/a

### Actual behavior:
Unable to establish proper storage volumes in rancher

### Expected behavior:
PV's attach as expected to clusters

**Comment by kwwii** [comment] 2023-06-14 15:49
1) Setup env
2) Understand how the list is populated
  a) why isn't it shown?
  b) should it be shown?

**Comment by cnotv** [comment] 2023-06-23 17:03
> > 1. Setup env
> > 2. Understand how the list is populated
> >    a) why isn't it shown?
> >    b) should it be shown?
> 
> PV components needs to be added for Azure Disk CSI and Azure Filesystem CSI. Fields TBD based on similar criteria and defined templates.

Looks like the list of PV is 23 as mentioned, while we hide the unsupported one. From the UI it's not clear how to display them, nor is defined in the documentation.

This is what can be returned by enforcing the support.

![Screenshot 2023-06-23 at 18 59 05](https://github.com/rancher/dashboard/assets/5009481/0c20a453-9d0b-426b-91e4-0e16b4ef38d8)

![Screenshot 2023-06-23 at 19 02 37](https://github.com/rancher/dashboard/assets/5009481/4a197c65-7804-46eb-9f24-772962a76df5)

 
@mjura could you confirm this is now supported?
As we had already a CSI in our UI, do you know why we do not have a further specificity in the term as in the 2 cases reported from you?

**Comment by cnotv** [comment] 2023-06-26 09:34
@mjura @kkaempf I'm proceeding to add these 2 new PVs to the list and related forms.
Since it's not mentioned if as Rancher we support them, could you please give a clear statement about this?

**Comment by kkaempf** [comment] 2023-06-26 12:23
If engineering is ok with the solution, we can declare it supported.

**Comment by cnotv** [comment] 2023-06-26 14:43
I have been able to create resource for both the cases after enabling the support flag, by just using what we have.
Since it's not clear the requirement, I assign you back to test and define what is the impediment.

<img width="1665" alt="Screenshot 2023-06-26 at 16 41 18" src="https://github.com/rancher/dashboard/assets/5009481/4de73445-e569-4459-b1b4-175c06a8cd2a">

<img width="1691" alt="Screenshot 2023-06-26 at 16 41 30" src="https://github.com/rancher/dashboard/assets/5009481/3fec103a-9ae7-48fa-8449-40f836edd951">

**Comment by kkaempf** [comment] 2023-06-26 15:41
@davidstauffer 👆🏻

**Comment by kwwii** [comment] 2023-07-19 09:34
@davidstauffer @kkaempf The driver is not being shown because a feature flag needs to be set to enable it. Can someone decide whether this behaviour needs to be changed as it currently works as intended.

**Comment by gaktive** [comment] 2023-07-19 18:58
This may slip to Q4 based on the open question here.

**Comment by davidstauffer** [comment] 2023-07-20 10:20
We had a conversation at standup about it, @mjura pointed out that the CSI driver is enabled by default from a BE side for every AKS cluster, so that means the default behaviour in the GUI should reflect that. Meaning that it should be enabled by default.

**Comment by gaktive** [comment] 2023-07-20 15:46
The CSI driver needs to be added to the list of the supported plugins for AKS.

**Comment by cnotv** [comment] 2023-07-20 15:53
CSI Driver is already added, we just need to flag it as supported in the configuration.

**Comment by mjura** [comment] 2023-07-21 05:44
I confirm that AKS CSI drivers are present in the UI

![akcs-csi](https://github.com/rancher/dashboard/assets/4455471/be55853c-e2a2-4c21-b01c-53b9f0a12f51)

@kkaempf @davidstauffer @cnotv We have to decide only if it is supported or not ? I have no idea who can make this decission, please help.

**Comment by cnotv** [comment] 2023-07-21 07:25
It was already present in the list and we just turned on as supported. 
What do you mean that we have to decide?

**Comment by cnotv** [comment] 2023-07-21 07:28
Is that screenshot not another resource, the PersistentVolume**Claim**, so not PV as mentioned?

**Comment by davidstauffer** [comment] 2023-07-21 08:26
@mjura the CSI driver is under the umbrella of our general AKS support. Therefore we support it.

**Comment by mjura** [comment] 2023-07-21 08:28
> Is that screenshot not another resource, the PersistentVolume**Claim**, so not PV as mentioned?

for AKS PV are provisioned using Dynamic Provisiong by specifying PVC with StorageClassName. PV will be created automatically by CSI driver which is in place in AKS and Rancher.

For us there is nothing to do.

We can close it.

**Closed by mjura** 2023-07-21 08:28 UTC
Labels: [zube]: To Test, area/storage, kind/enhancement, size/2, JIRA, QA/dev-automation, team/highlander
