### ISSUE TITLE
[project monitoring v2] 409 error on post request when creating a project monitor

### ISSUE THREAD

**Issue by ronhorton** [rancher/dashboard#6089] opened 2022-06-02 18:21 UTC
**Setup**
- Rancher version: `2.6.5`
- Browser type & version: `Chrome latest`

**Describe the bug**
On a downstream ec2 rke1 cluster, installed project monitoring v2. when creating a project monitor on a newly created project, there's a 409 error when clicking `create`

**To Reproduce**
1. create new project
2. create new namespace
3. create project monitor for new project

**Result**
`VM14:1          POST https://ront.qa.rancher.space/v3/projects/c-h6r6z:p-ggl56?action=setpodsecuritypolicytemplate 409`
`vuex.esm.js:538 Uncaught (in promise) {baseType: 'error', code: 'Conflict', message: 'error updating PSPT ID', status: 409, type: 'error', …}`
The monitor is created and deployed with no apparent error in the UI. 

**Expected Result**
new project monitor created with no errors. 

**Screenshots**

![Screen Shot 2022-06-02 at 2 19 47 PM](https://user-images.githubusercontent.com/89212856/171699404-fb19f0b9-db3c-4930-98c2-020eaae7ecf5.png)

**Comment by gaktive** [comment] 2022-06-13 15:49
@richard-cox can help out with the way that we handle resource conflicts in this situation.

**Comment by richard-cox** [comment] 2022-06-13 16:02
The `CreateEditView` mixin `save` function has a way to handle 409 errors. It tries to determine if the changes server side conflict with the changes client side, and if not update the server copy with client side changes before trying to save one more time.

I'm not sure how that resource saves, but if it goes through the standard flow it's worth debugging the `conflict` function.

**Comment by catherineluse** [comment] 2022-07-12 06:50
I couldn't reproduce the error in v2.6-head. The error message is also odd to me because it mentions PodSecurityPolicies and to my knowledge, project monitoring doesn't interact with those.

@ronhorton Do you remember if your environment had PodSecurityPolicies or if someone could have been editing them when you were testing?

**Comment by Sean-McQ** [comment] 2022-07-12 07:24
It looks like [this](https://github.com/rancher/rancher/issues/22834) might be very similar to this issue from a few years ago. If the issue is the same it sounds like timing is a factor in reproducing it and the culprit is mostly resource versions getting out of whack somewhere along the line. @aiyengar2 could probably understand the intricacies a bit better than I could though.

**Comment by catherineluse** [comment] 2022-07-12 21:33
After trying again, I did reproduce it. I saw it immediately after creating a project in an RKE1 cluster:

<img width="1220" alt="Screen Shot 2022-07-12 at 2 21 48 PM" src="https://user-images.githubusercontent.com/20599230/178598848-bfa57f59-3a85-4256-a8ec-6d2deba47304.png">

I agree with Sean - I don't think there's anything to fix. Is it ok to close the issue? @ronhorton

**Comment by catherineluse** [comment] 2022-07-12 21:43
Confirmed with Ron that we can close as expected behavior.

**Closed by catherineluse** 2022-07-12 21:43 UTC
Labels: [zube]: Working, area/monitoring, kind/bug-qa, team/area3, size/2
