### ISSUE TITLE
Support `application/jsonl` content type from api when listing resources

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#4512] opened 2021-11-04 18:14 UTC
https://github.com/rancher/rancher/issues/34721

Steve now supports listing resources as json lines instead of a single json object.  The dashboard should use this new content type and process objects as they stream in rather than downloading all objects as a single json object.

**Comment by vincent99** [comment] 2021-11-05 17:29
QA: I've tested the performance and am satisfied that it's an improvement, so I don't think you necessarily need to prove that.. There is a _lot_ of variance in the server response times and you need both the old and new UI running to compare so it's not easy to setup and prove.

For testing the main thing to be concerned with is that it still works in general:
  - The right list of resources is coming back
  -  It isn't missing any entries like being off-by-one and missing the last resource (compare to say `kubectl get`)
  -  The list is still updated when changes occur (e.g. from a change made in another window or with kubectl).
  - Creates and deletes show up as expected
  - If you switch clusters or log out/in you see the right data and not old stuff from previous requests
  - ...

**Comment by sgapanovich** [comment] 2021-11-12 19:24
Reason for re-opening: performance issue with Chrome 

#### Test Environment: ####
Rancher version: v2.6-638b29a687f3818e7de676a573ec9b9156f193a9-head
Rancher cluster type: HA
Docker version: 20.10

Downstream cluster type: ec2 8 node cluster (3 etcd, 3 cp, 3 worker -> all t3.xlarge)
Downstream K8s version: v1.21.6

----------

#### Steps to reproduce: ####
Use Chrome for this testing since it's only being reproduced on Chrome (Firefox didn't have issues)

1. Deploy 500 large config maps and 500 secrets 
2. Navigate to the cluster
3. Storage -> Config Maps
  when navigated for the first time you will notice response times improvements 
  from ~50 sec to 25 sec (compared to 2.6.1)
4. Storage -> Secrets 
  when navigated for the first time you not notice response times improvements
  ~9 sec average time to load all results 

After navigating though the cluster and refreshing pages for about 10 minutes (different laptops with different OS were used)
- come back to Config Maps: 
  - time to load all 500 config maps increased to ~ 3min
- go to Secrets:
  - time to load all 500 secrets increased to ~1 min

if `application/jsonl` is disabled the times go back to what they were in 2.6.1 (see screenshot: it's the same setup and screenshots are taking within 1 min with `/jsonl` enabled/disabled)

The times come back to normal if you use a new incognito window
![jsonl](https://user-images.githubusercontent.com/40282141/141523347-66e4b0cc-e569-4c1c-ae23-eaeaf06c808e.jpg)

**Comment by vincent99** [comment] 2021-11-15 22:21
I haven't been able to reproduce this still so disabling the streaming for 2.6.3 and we'll look at it again later.

**Comment by sgapanovich** [comment] 2021-11-16 00:38
Confirmed that streaming is disabled by default in 2.6-head
Navigated through multiple pages to validate that
UI requests `json` and gets `json` back (no longer `jsonl`)
![disabled .jpg](https://zube.io/files/rancher/034916f2140b6933b5c13a6771b81789-disabled.jpg)

Moving issue back to re-opened and assigning 2.6.4 milestone

**Comment by gaktive** [comment] 2022-01-06 22:32
Internal reference: SURE-3010

**Comment by gaktive** [comment] 2022-02-22 17:54
Based on discussion, it's uncertain that this fix will address the performance complaints we're getting though as a feature, it seems fine. For now, we'll hold on this until we determine if there's another backend or API fix needed, which should spawn a new ticket that is actually performance related.

**Comment by catherineluse** [comment] 2022-11-05 06:09
Closing due to the reasoning in Gary's comment above. We are focusing on other backend performance enhancements which are tracked here: https://github.com/rancher/dashboard/issues/5243

**Closed by catherineluse** 2022-11-05 06:09 UTC
Labels: [zube]: Backlog, internal, QA/M, kind/enhancement, priority/1, team/area2, JIRA
