### ISSUE TITLE
Cannot add or edit cluster labels via the UI

### ISSUE THREAD

**Issue by digiserg** [rancher/dashboard#3086] opened 2021-05-25 17:44 UTC
Version: v2.5.8
Installer: helm chart
Cluster: standalone lab with k3s

When I edit the cluster labels via the Web UI the changes are not applied back to the cluster. If I use the YAML editor however it does work as expected.

![image](https://user-images.githubusercontent.com/58211930/119543582-b54f3100-bd88-11eb-961e-19677d83f2ed.png)

**Comment by 89luca89** [comment] 2021-05-25 19:03
I would add also that patching the resource via kubectl, works as expected, and the `edit yaml` view is correctly updated.
Just the UI seems disjoined from the internal representation

**Comment by nwmac** [comment] 2022-02-16 10:07
@aalves08 see if you can validate- 2.5 UI shown - but the code is the same in 2.6

**Comment by aalves08** [comment] 2022-02-16 11:48
@nwmac works as expected in 2.6-head. No issues here with labels on Clusters in Fleet. Shall we close this?

**Comment by nwmac** [comment] 2022-02-16 11:54
@aalves08 Move it to 'To Test' -> remove the `[zube]: Working` label and add `[zube]: To Test` - we almost always do that and don't close issues - QA will validate again and close the issue.

**Comment by davidnuzik** [comment] 2022-02-23 23:29
**I cannot reproduce this in v2.6.3 actually - this was likely fixed somewhere in the Rancher v2.6 history. I'm changing the milestone to 2.6.3 since no work was done (this is essentially not a "2.6.4 issue").**
 
**Reproduction Environment:**

Rancher version: v2.6.3
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: RKE2
Downstream K8s version: v1.21.9+rke2r1
 
**Reproduction steps:**

1. Create a downstream cluster.
2. Once the cluster is fully ready, navigate to the Continuous Delivery page from the left nav pane.
3. Click on Clusters. Then, to the right of the downstream cluster name, click on the vertical "..." and chose the Edit Config option.
4. Notice the Labels section - I can successfully add or edit cluster labels here. The screenshot shows me adding a label. I confirmed it took. When I re-edit I still see it there. I also changed the label to a different value upon the second time editing and this change took. I can edit a 3rd time and see my change is still there.

![image](https://user-images.githubusercontent.com/45179589/155426829-d6857c88-bfa2-420e-839d-27846298d871.png)

 
**Additional Info:**
Fixed in v2.6.3 or possibly sooner.

**Closed by davidnuzik** 2022-02-23 23:29 UTC
Labels: kind/bug, [zube]: To Test, area/fleet, team/area3
