### ISSUE TITLE
Cluster Dashboard resource gauges show incorrect max values

### ISSUE THREAD

**Issue by kerossin** [rancher/dashboard#2892] opened 2021-05-04 12:29 UTC
The resource gauges (at least for CPU and Memory, don't know about Pod) in Cluster Dashboard seem to show incorrect max values.

![image](https://user-images.githubusercontent.com/79387326/117002338-1b95e600-acec-11eb-805c-327d9e4fd45d.png)

For example, the Memory Used gauge shows 30 of 31 GiB, now the actual usage of 30 GiB seems correct but the max of 31 GiB doesn't because the cluster has a lot more resources. This particular gauge sometimes shows 103% usage so it's obviously wrong.

The CPU gauges seem wrong too since the cluster has more than 10 cores.

Cluster info:
Kubernetes 1.20.5
Rancher 2.5.7
7x CentOS 7 control plane nodes (1 is currently down) 2vCPU 8GB each
2x CentOS 7 worker nodes 2vCPU 8GB each
2x Windows Server 2019 worker nodes 2vCPU 4GB each

**Comment by gaktive** [comment] 2021-05-07 16:34
These gauges will change for 2.6 but we should check if we will run into this problem anew. There is also a possibility that we could exceed 100% but again, we'd need to test.

**Comment by ansilh** [comment] 2022-02-04 06:44
@gaktive , The concern is with the calculation of total memory and not the usage. 
In my case, the total memory of nodes are more than 1TB, but UI shows 503GB which is not correct.
![InkedRancher_Memory_LI](https://user-images.githubusercontent.com/11064902/152484227-792c070c-8246-4899-b6f4-caeb1e435e0d.jpg)

**Comment by gaktive** [comment] 2022-02-07 17:23
Internal reference: SURE-4027
We're getting feedback that alerts are being sent out falsely based on these high numbers, whereby 112% usage is wrong

**Comment by aalves08** [comment] 2022-02-11 14:47
@gaktive been taking a look at this. We don't have the charts anyone (afaik) and the resources count doesn't point to any issues, although I might not have a proper edge-case, so I can't really reproduce it.

The only strange thing that I have found is that the resources count on the side menu is affected by the namespace filter on the header. If you check the screenshots, the "cluster page" shows a total of 60 pods being used, but when you look at the side-menu workload > pods count, it shows 40... That's because the namespace filter on the top is set to "only user namespaces".

If we set no namespace filtering the numbers match.

Otherwise, from a first glance, nothing odd here. Maybe we need to monitor this to see if any issue pops up.

How shall I proceed? 

Thanks

![Screenshot 2022-02-11 at 14.34.24.png](https://zube.io/files/rancher/74da7c0dd26d7ca2fccf730f903b736c-screenshot-2022-02-11-at-14-34-24.png)
![Screenshot 2022-02-11 at 14.34.29.png](https://zube.io/files/rancher/bd7dd00127f01756b8053231e1bdc78e-screenshot-2022-02-11-at-14-34-29.png)

**Comment by aalves08** [comment] 2022-02-24 11:10
@gaktive @nwmac 
Will move forward this issue to testing. Thank you

**Comment by davidnuzik** [comment] 2022-03-01 18:39
@deniseschannon @gaktive what is the goal for my testing then closing out this issue here?
We could not reproduce but identified this is working as expected? Is due to namespace filtering?

What does QA need to do? I see no PRs attached.

**Comment by gaktive** [comment] 2022-03-03 00:36
Possible other internal reference: SURE-4148 -- I'll check if namespace filters are being applied there.

@aalves08 I may have missed some notes here after Alex's diagnosis, but we should be clear here if this is actually expected or not based on our current inability to repro this.

**Comment by gaktive** [comment] 2022-03-03 00:38
Also SURE-4090 so we're getting more feedback about this discrepancy.

**Comment by nwmac** [comment] 2022-03-11 10:59
@aalves08 Where are we with this ticket?

**Comment by aalves08** [comment] 2022-03-17 14:57
Neil & several inconsistencies in the counts between the home page and the cluster dashboard for RKE1 and RK2 clusters, but in the case of displaying incorrect max values for clusters in 2.6.3, we can confirm that those values are correct.
We will open another related issue related to the discrepancies we found and link it to the SURE issues you mentioned as well.

Our recommendation is to move this to test and QA to make sure that the max values for CPU and MEM are correct in 2.6.3.
@gaktive

**Comment by bmdepesa** [comment] 2022-03-22 07:01
rancher/rancher:v2.6.4-rc10

* Deployed several clusters
* Deployed several fleet bundles and feature charts to use some cluster resources
* The CPU / memory stats appear to be correct as far as the total use of available cores and memory for the total number of nodes in the cluster
* Percentages are appearing and seem to be calculated correctly

**Closed by bmdepesa** 2022-03-22 07:01 UTC
Labels: [zube]: Done, internal, priority/0, team/area3
