### ISSUE TITLE
performance is noticeably slow in dropdown lists from external queries (i.e. ec2 instance type list) that are exceptionally long (i.e. more than 20 in list)

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#9900] opened 2023-10-11 20:49 UTC
**Setup**
- Rancher version: v2.7.8
- Rancher UI Extensions: n/a
- Browser type & version: tested on firefix, chrome

**Describe the bug**

when user clicks a dropdown with exceptionally long list, the performance seems laggy / slow when selecting one of the options

**To Reproduce**

* go to create an rke2 cluster using aws node driver
* once credentials are added, change the `instance type` for one of the pools

**Result**
notice that the blue selected item lags behind where the users mouse is

**Expected Result**

performance of selected item / drop down shouldn't be noticeably dependent on the length of the list in the dropdown. 

**Screenshots**

**Additional context**

an example of the expected performance would be from say the `region` on the same page, with less than 20 items in the list. 

this happens on any list that I've tested that is longer than about 25/30, regardless of setup or browser.

**Comment by mantis-toboggan-md** [comment] 2023-10-11 23:33
Closing as duplicate of https://github.com/rancher/dashboard/issues/9668

**Closed by mantis-toboggan-md** 2023-10-11 23:33 UTC
Labels: [zube]: To Triage, kind/bug-qa, area/performance
