### ISSUE TITLE
Adding project members as not project creator is not working 

### ISSUE THREAD

**Issue by umberto10** [rancher/dashboard#5411] opened 2022-03-16 11:01 UTC
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Firefox

**Describe the bug**

I cannot add new project member even if I have Manage Project Members role assigned to the user.
I map my users from keycloak oidc, but it doesn't work with local users too.

This doesn't work in the rancher cli tool neither.

**To Reproduce**

1. Create project with namespace
2. add another user (test2) as member
3. add custom role Manage Project Members for this user (test2)

**Result**
After logging in as test2 you have access to the project but you cannot add any other members to it.
I guess the Add button should appear or something

**Expected Result**

User1 should be able to add members to project if he has Manage Project Members role assigned

**Screenshots**

Project configuration from creator point of view:
![image](https://user-images.githubusercontent.com/43953088/158575145-57cbeba8-f49d-48db-b048-b7d82e3b52a2.png)
Project configuration from member with Manage Project Members role point of view:
![image](https://user-images.githubusercontent.com/43953088/158575653-c8d5cfcd-3b1e-4ff1-afd2-d0aa34548f14.png)
 the problem here.—>

**Comment by richard-cox** [comment] 2022-10-27 14:44
Couldn't reproduce in 2.7-head (around 2.7.1), possible resolved by https://github.com/rancher/dashboard/pull/5664 / https://github.com/rancher/dashboard/issues/5417 from 2.6.5. Will mark as resolved in the next release for QA to validate

**Comment by dasarinaidu** [comment] 2022-11-04 21:23
v2.7-9f1e0435bb45e104ba897c5c329e1f23735843d9-head

Provision rancher with version : v2.7-head

**Reproducible Steps:**
1. Login as Admin
2. Create Cluster, project with namespace
3. Add another user (su-all) as member
4. Add custom role Manage Project Members for this user (su-all)

Now, Logged in as the user ‘su-all’
1. Open namespace and project
2. Check for the ‘Members’ and Add button to add users

**Actual:**

- The user is NOT seeing the Add button to add other users as a Member
- The Add button is displaying/enabled once the user is click on ‘Edit Config’ button

This is working as expected and I m closing the card.

**Validated below Test cases:**
1. Validated with different users
2. Validated on different browsers
3. Validated on different modes (Dark and Auto)


[AddUserbutton.webm](https://user-images.githubusercontent.com/22034884/200076956-9e15d903-c8ab-4926-8c70-c46b5bb4189a.webm)

**Closed by dasarinaidu** 2022-11-04 21:23 UTC
Labels: kind/bug, area/rbac, [zube]: QA Working
