### ISSUE TITLE
`Home Links` settings page is inconsistent with other settings with override available, degraded user experience

### ISSUE THREAD

**Issue by slickwarren** [rancher/dashboard#7335] opened 2022-11-04 16:29 UTC
**Is your feature request related to a problem? Please describe.**

* entering a custom link that matches an existing display text  -> currently, there is differing behavior:
  * if the display text matches an existing **custom** link, **there will be a duplicate entry on the home page links**
  * if the display link matches an existing **default** link, the link **will be overridden** with the custom link
lastly, you can override the `support` default link as well. Given that we disabled the show/hide button for `support` link, this sounds like we wanted users to always have a link to support if they are not paying for it currently. However with the current implementation, there is essentially no effect of hiding the show/hide button as the user can override it anyways. 

**Describe the solution you'd like**

I would like the behavior on the `home links` page to at least be consistent with itself. i.e. if I can override a default link with a custom link, I should be able to override a custom link with a custom link.  
Ideally, this page would not be different than any of our other settings that have an override available, as this UX is a downgrade from what we already have. 

**Describe alternatives you've considered**

this feature was already discussed as `implemented as intended`, however still presents a poor user experience. 

**Additional context**

more discussion in this ticket: https://github.com/rancher/dashboard/issues/6493#issuecomment-1295326711

**Comment by gaktive** [comment] 2023-08-03 13:04
Closing for now since along with the current design working as intended, we've heard no complaints from external folks about this and the current ticket volume is very high. If more complaints arise, we can re-evaluate.

**Closed by gaktive** 2023-08-03 13:04 UTC
Labels: [zube]: Done, status/wontfix, QA/XS, kind/enhancement, team/area2
