### ISSUE TITLE
Create cluster page display incorrect cluster type

### ISSUE THREAD

**Issue by DaiYuzeng** [rancher/dashboard#5499] opened 2022-03-24 10:39 UTC
**Setup**
- Rancher version:
- Browser type & version:

**Describe the bug**

Create clusters always display `custom` subtype.

**To Reproduce**

1. Go to Cluster Create Page.
2. Select Harvester(or other type).
3. Masthead display `Create Custom`, should display `Create harvester`.

**Result**

**Expected Result**

Display correct cluster type and can create Harvester clusters

**Screenshots**

![截屏2022-03-24 下午6 30 13](https://user-images.githubusercontent.com/15041915/159898337-ab029a42-8435-41a0-9037-7caa1b3f0c9b.png)

**Additional context**

**Detailed Description**

**Context**

**Comment by WuJun2016** [comment] 2022-03-24 10:52
Hi， @richard-cox ， I'm trying to fix this, but I'm confused about this line of code https://github.com/rancher/dashboard/blob/e5315ee0184283c273fd223faf01b3b9acd2c9f1/edit/provisioning.cattle.io.cluster/index.vue#L158, so I need the rancher team to take a look at this issue。 thanks.

**Comment by richard-cox** [comment] 2022-03-24 10:55
There were some changes to how this works brought in by https://github.com/rancher/dashboard/pull/5487 and https://github.com/rancher/dashboard/pull/5471, i think that may have caused the regression

**Comment by catherineluse** [comment] 2022-03-24 15:34
What is the rancher ui index? My latest PR to the v2.6.4 release branch was intended to fix this bug

**Comment by richard-cox** [comment] 2022-03-24 16:27
I've tested on the latest `release-2.6.4` (`2.6.4`)  and `master` (`2.6.5`) branches and this works ok. @DaiYuzeng Can you retry? If it still fails could you provide details on how you're running rancher and the UI, the version of Rancher (this should be printed at the bottom of the side menu) and the value of Side Menu / Advanced Settings / `ui-dashboard-index` ?

`master`
![image](https://user-images.githubusercontent.com/18697775/159962496-d608bae7-1a25-4073-ab22-f1ebbda85eef.png)

`release-2.6.4`
![image](https://user-images.githubusercontent.com/18697775/159963665-29f34b8a-0fb2-4ad2-a40d-33c8dc96e356.png)

**Comment by WuJun2016** [comment] 2022-03-25 02:41
@richard-cox  @catherineluse ,I see that it has been fixed in this [pr](https://github.com/rancher/dashboard/commit/aaf303a9a8eb4272b2ef94cfb5650acabe3a9ae8#diff-57eee22cde55fcc07b9a14c4f7f9d24680e0968aae812a5d7c7f611e403fb475L158)。

cc @DaiYuzeng

**Comment by DaiYuzeng** [comment] 2022-03-28 01:22
Verified on latest UI, thanks!

**Comment by brudnak** [comment] 2022-03-28 15:47
# :white_check_mark: PASSED

<hr>
  
## Validation Environment

| Component               | Version / Type                                     |
| ----------------------- | -------------------------------------------------- |
| Rancher version         | v2.6-9ef92c2168bd91ce6b05734731d9c2c21c42a5f4-head |
| Installation option     | Docker                                             |
| Docker version          | 20.10.7, build f0df350                             |
| Helm version            | v2.16.8-rancher1                                   |
| Downstream cluster type | not applicable                                     |
| Downstream K8s version  | not applicable                                     |
| Logged in user role     | Administrator                                      |
| Browser type            | Google Chrome                                      |
| Browser version         | 99.0.4844.83 (Official Build) (x86_64)             |

## Validation steps

1. Starting from the **Default** Rancher homepage
2. Click `hamburger menu` -> `Cluster Management` -> `Create` -> `RKE1` & `RKE2` `Harvester`

## Additional Info

## RESULTS

#### :white_check_mark: Expected
When trying to create RKE1 or RKE2 Harvester it does display `Harvester` and not `Custom`

#### :white_check_mark: Actual
When trying to create RKE1 or RKE2 Harvester it does display `Harvester` and not `Custom`

**Closed by brudnak** 2022-03-28 15:47 UTC
Labels: [zube]: QA Working, status/waiting-harvester
