### ISSUE TITLE
Can't add user in Cluser Explorer 

### ISSUE THREAD

**Issue by olheimer** [rancher/dashboard#5117] opened 2022-02-14 12:18 UTC
**Setup**
- Rancher version: 2.5.12 (same in 2.5.11)
- Browser type & version: any

**Describe the bug**
Can't add user in Cluser Explorer via "Global Applications / User&Authentication".
Logged in as default admin user. 

**To Reproduce**
Click  in Cluser Explorer via "Global Applications / User&Authentication". There is no button "create" anymore. Also an existing user can't be cloned

**Result**

**Expected Result**
Create user

**Comment by catherineluse** [comment] 2022-02-23 02:22
Under under Cluster Management > Users & Authentication, the button to create a user is in the upper right:

![Screen Shot 2022-02-22 at 7.20.14 PM.png](https://zube.io/files/rancher/cfd36cf803bfa1f31e3f8a426b118673-screen-shot-2022-02-22-at-7-20-14-pm.png)

To add a user to a cluster, it's also in Cluster Management. You go to the list of clusters, go to the cluster where you want to add a member and click Edit Config:

![Screen Shot 2022-02-22 at 7.18.29 PM.png](https://zube.io/files/rancher/d2f51107119714b4ad34c7cc13a44c5c-screen-shot-2022-02-22-at-7-18-29-pm.png)

From there you can add cluster members:

![Screen Shot 2022-02-22 at 7.19.35 PM.png](https://zube.io/files/rancher/ade271afb22c76b45e16b0033559ec02-screen-shot-2022-02-22-at-7-19-35-pm.png)

**Comment by catherineluse** [comment] 2022-11-05 05:20
I'm closing this issue because I believe it is a duplicate of this bug https://github.com/rancher/rancher/issues/37531. When Rancher is first installed, it takes some time before all the form elements can work properly. The workaround is to refresh the page.

**Closed by catherineluse** 2022-11-05 05:20 UTC
Labels: kind/bug
