### ISSUE TITLE
Add/remove an authorized IP range for downstream AKS cluster does not work

### ISSUE THREAD

**Issue by a-blender** [rancher/dashboard#6879] opened 2022-06-15 13:41 UTC
**Rancher Server Setup**
- Rancher version: 2.6-head
- Installation option (Docker install/Helm Chart):
   - If Helm Chart, Kubernetes Cluster and version (RKE1, RKE2, k3s, EKS, etc):
- Proxy/Cert Details:

**Information about the Cluster**
- Kubernetes version: 1.23.5
- Cluster Type (Local/Downstream): AKS downstream cluster, provisioned via rancher UI
   - If downstream, what type of cluster? (Custom/Imported or specify provider for Hosted/Infrastructure Provider):

**User Information**
- What is the role of the user logged in? (Admin/Cluster Owner/Cluster Member/Project Owner/Project Member/Custom) admin
  - If custom, define the set of permissions:

**Describe the bug**

2. After provisioning a cluster via the rancher UI,
a. You cannot add an auth IP range in the rancher UI. You can click the both but the +Add Range button is greyed out
b. Removing an existing IP range in the rancher UI doesn't trigger a change/fails

**To Reproduce**
 

* Provision a 1 node AKS cluster via the rancher UI
* Edit the AKS cluster and try to add an auth IP range (ex: 0.0.0.0/0, 10.0.0.4/32). The +Add Range button will be greyed out

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/12955547/173844489-8661609f-e592-40f4-a34f-cbefe1a4f3e1.png">

* Add an auth IP range to the cluster via Azure portal -> Networking
* Edit the AKS cluster in rancher and try to remove the auth IP range. That will also fail. If you Edit the cluster again, you will see it hasn't been removed.

Note: on the backend, neither rancher nor `aks-operator` detects a change in the AKSClusterConfig when you remove an auth IP range, and it should.

<img width="1546" alt="image" src="https://user-images.githubusercontent.com/12955547/173841008-9723e9f5-d80e-41e8-91c3-614c61d37a58.png">

**Comment by gaktive** [comment] 2023-06-08 14:19
We should look at this after we port this page from Ember to Vue.

**Comment by mantis-toboggan-md** [comment] 2023-10-09 23:01
This will be included in https://github.com/rancher/dashboard/pull/9669/files

**Comment by valaparthvi** [comment] 2024-07-11 08:05
**Tested on:**
Rancher: v2.9-3c4ccdc5bc9fde3510089153b5ad58fdbe604880-head
Dashboard: master 00e9eb2

It is **partially** fixed.

Adding a new IP range works as expected, but removing an IP range does not work, from UI, all the buttons are active and even the operator logs indicate that an update is in progress, but when the update finishes, there appears to be no change.

Steps to reproduce:
1. Create an AKS cluster with two authorized IP ranges.
2. Once the cluster is active, update it to remove one of the ranges.
3. Monitor `deploy/aks-config-operator` logs to ensure the update is in progress.
4. Once the update finishes, change the config.

But since this is an operator bug rather than a UI one, I will close this and open another one on rancher/aks-operator.

**Closed by valaparthvi** 2024-07-11 08:05 UTC
Labels: kind/bug, team/area2, ember, area/aks, team/highlander, QA/manual-test
