### ISSUE TITLE
Delete button not active when trying to delete users

### ISSUE THREAD

**Issue by kourosh7** [rancher/dashboard#7484] opened 2022-11-17 17:04 UTC
**Setup**
- Rancher version: 2.6.9
- Browser type & version: 
Firefox 106.0.5
Chrome Version 107.0.5304.87 (Official Build) (64-bit)

**Describe the bug**
At times, when a global admin user selects an existing user in the "Users & Authentication" page, the "Delete" button is not active. 

**To Reproduce**
This is sporadic.
1. Login to Rancher as a global admin user
2. Navigate to Config > Users & Authentication
3. Select a user and observe the state of the "Delete" button

**Result**
The "Delete" button is not always active

**Expected Result**
The "Delete" button should be active

**Screenshots**
In the below screenshot, my global admin account has selected a user and, the "Delete" button is not active:
![image](https://user-images.githubusercontent.com/39573922/202511426-0e1d34bb-779b-45aa-9139-15df1aba88ef.png)
Also, notice that the "Edit Config" option is unavailable from the 3-dot menu options. Instead, it shows "View Config"

In the following screenshot, my global admin account has selected the same user, and the "Delete" button is active:
![image](https://user-images.githubusercontent.com/39573922/202511487-7c895b4f-5fe9-42ee-86fa-0bb92dfa4673.png)

**Additional context**
Interestingly, when the "Delete" button is not active, you can click on the user and then see the "Delete" option from the 3-dot menu drop-down. This is fine for deleting a single user, but the problem is when you want to mass select and delete multiple users and you cannot.

**Comment by gaktive** [comment] 2022-11-19 00:53
Internal reference: SURE-5572

**Comment by nwmac** [comment] 2022-11-21 12:23
@richard-cox Would this be fixed by your PR around bulk actions?

**Comment by nwmac** [comment] 2022-12-01 09:05
@torchiaf Can you see if you can reproduce?

**Comment by torchiaf** [comment] 2022-12-01 11:21
In my case, sometimes the Delete button is not visible:

![image](https://user-images.githubusercontent.com/26394656/205040075-90c07cc7-87c3-4161-b2be-32131970e3a5.png)

**Comment by torchiaf** [comment] 2022-12-01 14:56
@nwmac @richard-cox  I am able to reproduce the bug in both version `2.6.9` and `latest`.

**To Reproduce**

1. Navigate to Config > Users & Authentication
2. Select a user and observe the state of the "Delete" button (It should works as expected)
3. Click on another Tab in the Browser.
4. Return to the Tab where Rancher Dashboard is open.
5. Select a user and observe the state of the "Delete" button. It is always disabled.

The same bug is reproducible in the latest version, but here the button literally disappear:

![image](https://user-images.githubusercontent.com/26394656/205084630-2daab437-4427-4f30-be4f-dde2ee7cacf3.png)

**Comment by nwmac** [comment] 2022-12-01 15:23
@torchiaf Can you take a look and see if you can fix?!

**Comment by torchiaf** [comment] 2022-12-02 09:57
> @torchiaf Can you take a look and see if you can fix?!

Sure, I am working on it.

**Comment by torchiaf** [comment] 2022-12-07 12:19
@richard-cox helped me to investigate on this issue. 
We found that switching Browser tabs triggers a security check in the dashboard :
```
async visibilityChange() {
  if (!document.hidden) {
    await this.$store.dispatch('rancher/findAll', {
      type: NORMAN.USER,
      opt:  {
        url:    '/v3/users',
        filter: { me: true },
        force:  true
      }
    });
  }
},
```


The `findAll` subscribes again the `user` resource, which causes the user to be removed from the cache for some reason. 

![image](https://user-images.githubusercontent.com/26394656/206177670-52a15cb4-a3b8-453c-ab6b-dcc2a053df65.png)


The available actions (like the Delete button) are not properly calculated because it is made based on a sub-set of user objects.

**Comment by dasarinaidu** [comment] 2023-01-04 06:55
I have validated this issue on v2.7 and it got fixed. I did not see any new issues and closing this defect.

**Validation details as below:**
**Rancher Version :** v2.7-7d16a0d3b67cacd5dff58b055d81d7cd9172ec83-head
**Browsers :** Chrome and Firefox
**Users :** Admin and Standard Users
**Modes :** Auto and Dark

**Test Cases:**
1. Add different types of users and Delete users (by selecting a user and Click Delete)
2. Login with Standard user who has manage user permissions and Delete Users

Make sure the `Delete` button is enabled after selecting the user before delete.

**Note:** Delete button is disabled for the same user try to delete

**Closed by dasarinaidu** 2023-01-04 06:55 UTC
Labels: kind/bug, [zube]: To Test, team/area1, JIRA
