### ISSUE TITLE
Launch kubectl

### ISSUE THREAD

**Issue by maggieliu** [rancher/dashboard#896] opened 2020-07-25 18:00 UTC

**Comment by aaronRancher** [comment] 2020-07-27 23:06
The feature is validated in `rancher\rancher:master-head` `version e20f472d4`.

**Comment by vincent99** [comment] 2020-07-29 11:02
Waiting for backend..

**Comment by deniseschannon** [comment] 2020-08-18 21:03
Duplicate of https://github.com/rancher/dashboard/issues/833

**Closed** 2020-08-18 21:07 UTC
Labels: [zube]: Reopened, status/waiting-backend
