### ISSUE TITLE
User without permission to view resource page returns Cannot read properties of null

### ISSUE THREAD

**Issue by rootwuj** [rancher/dashboard#9445] opened 2023-07-28 02:08 UTC
**Setup**
- Rancher version: v2.7.5
- Browser type & version: Chrome

**Describe the bug**

When the project member user accesses the host information on the pod list page，the explorer page wont load and returns `Cannot read properties of null (reading 'parentNameOverride')`

**To Reproduce**

Cluster in local or downstream cluster:
1. Create user user1 and set it as project member role.
2. Log in to user1 and create deployment, waiting for deployment Active.
3. navigate to the pod list, and click node name.

**Result**

The page wont load and returns a blank page with `Cannot read properties of null (reading 'parentNameOverride')`

**Expected Result**

Expected the page to load without errors

**Screenshots**

<img width="1792" alt="image" src="https://github.com/rancher/dashboard/assets/42061003/057a1431-357f-4e0d-b4f5-a24a855301d8">

<img width="1791" alt="image" src="https://github.com/rancher/dashboard/assets/42061003/8645d5c0-131e-4687-8416-f02b4ad433ff">

**Additional context**

Console Errors:

**Comment by dasarinaidu** [comment] 2023-10-11 21:58
@rootwuj @ly5156 @richard-cox I am trying to reproduce this issue on v2.7.5 with steps provided in the ticket but I m unable to reproduce. 

Based on the steps -- I am not getting the workloads option itself. Please some one update the steps? Thanks

**Comment by rootwuj** [comment] 2023-10-12 00:37
@dasarinaidu More detailed steps to reproduce:
1. docker run v2.7.5
2. Log in as admin user
3. Create standard user `user1`
4. Add `user1` to the `Default` project of the local cluster
5. Create deployment `test` under `Default`
6. Navigate to the `pod list` and check the `node name`. You can see it normally.
7. Log out
8. Log in to `user1` and navigate to the `pod list` under the local cluster Default
9. Click the `node name` to reproduce the problem

![nodename-test](https://github.com/rancher/dashboard/assets/42061003/4f6634d9-703d-4c04-9231-6ded1a2f094c)

**Comment by dasarinaidu** [comment] 2023-10-12 03:51
I reproduced it on v2.7.5 and validated the same on `v2.8-6376016a309a166c50fe6203b2e97dae0b90c89c-head` the issue is fixed and I did not see any error/link to local_node.

Closing this issue.
![image](https://github.com/rancher/dashboard/assets/22034884/479c7e4b-3833-4883-a099-43935e0a8008)

**Closed by dasarinaidu** 2023-10-12 03:51 UTC
Labels: kind/bug, [zube]: QA Working, team/area1
