### ISSUE TITLE
CSS for log window should have the `white-space: pre` style

### ISSUE THREAD

**Issue by MAOUXSAKI** [rancher/dashboard#4950] opened 2022-01-20 06:19 UTC
**Setup**
- Rancher version: 2.6.3
- Browser type & version: Chrome 97.0.4692.71

**Describe the bug**
Pod Log Not Have white space

**Screenshots**
![image](https://user-images.githubusercontent.com/54871762/150284102-a212c8a0-aea8-48d7-a380-c159dfca8cad.png)

if I Change white-space value to pre in console , it becomes correct.
![image](https://user-images.githubusercontent.com/54871762/150284234-17ae1a9f-5f97-4286-bd5f-9883688c71b5.png)

![image](https://user-images.githubusercontent.com/54871762/150284159-a9e8e5a4-6510-4ded-a59e-e1ec646b3032.png)

**Comment by catherineluse** [comment] 2022-11-08 02:24
# QA Template

## What was fixed, or what changes have occurred
I made a very small CSS fix
 
## Areas or cases that should be tested

This is what I did:

1. I created a Deployment named `test` of a sample application that has the same Spring Boot logs as the original issue. I used this container image that I found by googling: `springio/gs-spring-boot-docker:latest`
2. Go to the Deployment detail page for `test`
3. On the Pods tab, go to a pod and click the *⋮ > View Logs*
4. Confirm that the "Spring Boot" is formatted properly
 
## What areas could experience regressions?
Log styling for container logs

**Comment by nickwsuse** [comment] 2022-12-08 19:19
@catherineluse I'm noticing that with the new side-pinning ability introduced in https://github.com/rancher/dashboard/issues/4733, if the shell window is smaller and the `Wrap Logs` option is checked in the shell settings, the "Spring" ascii is broken up a bit. Is this something worth fixing? If you uncheck the `Wrap Logs` option then it looks fine, but the logs are y'know, unwrapped and hard to see on the side.

**Wrapped Lines:**
![image](https://user-images.githubusercontent.com/107147272/206547446-1dc075c8-7607-4597-9939-4aeafa4cd0b5.png)

**Unwrapped Lines:**
![image](https://user-images.githubusercontent.com/107147272/206547571-de002818-605e-4c1f-b268-95c6ad4d63f4.png)

**Comment by catherineluse** [comment] 2022-12-08 21:29
Well, I'm inclined to say we shouldn't fix it because I'd expect any sort of ASCII art or table-formatted output to be messed up if the lines are wrapped. I think there will always be some kind ASCII graphics or tables that don't fit in one line and that's ok.

**Comment by nickwsuse** [comment] 2022-12-08 21:56
Ok, that makes sense to me. Just figured I'd ask to be on the safe side.

In that case, verified on `v2.7-head Commit ID: c35f112`

When using the bottom pinned shell everything is formatted correctly whether or not the `Wrap Lines` option is selected. When pinned on either side of the screen, the formatting can potentially break a bit as noted above, but otherwise it looks good.

**Closed by nickwsuse** 2022-12-08 21:56 UTC
Labels: kind/bug, [zube]: QA Working, good-first-issue, team/area3
