### ISSUE TITLE
Add locale selector to log in page

### ISSUE THREAD

**Issue by richard-cox** [rancher/dashboard#3336] opened 2021-06-25 08:21 UTC
The goal of this ticket is to add the Locale Selector to the login page of dashboard.

Currently it is only available in the slide-in menu once you are logged in (bottom-right of the slide-in).

I suggest adding it to the bottom-left of the login page - you should be able to leverage the control straight from the slide-in menu - see: `TopLevelMenue.vue` around line 362. You will need to extract that into a new component that can be used both in the TopLevelMenu and the login screen (`shell/pages/auth/login.vue`).

On the login screen, we don't know who the user is, so we can't retrieve their locale preference from the backend.

I suggest that we cache the locale in browser local storage  

On the login screen:

- If there is no cached locale, we default to English, otherwise we use the locale that has been cached
- When the user changes the locale on the login screen, we update the cache and store in the app that the locale was changed
- Once the user logs in, we will have their locale preference from the backend
-  if the locale was changed on the login screen, we update the user preference with the new locale - this will then be stored by the backend
- If the locale was not changed, we update the cached locale in the browser with the value from the user preference if this is different to what is currently cached

**Comment by bisht-richa** [comment] 2022-09-05 09:28
Use case: Testing Local in two browser 
**Browser 1** Status already logged in, currently on the index page( current local Eng)

**Browser 2**  Login page changed language to **Chines** => Logged in current local **Chines**

**Browser 1** Refresh home page still load local **Eng** ( but pref is changed to**Chines** in browser 2 ) it should load local from the backend.

**Comment by slickwarren** [comment] 2022-09-09 18:38
tested on v2.6-head (68215bc):
* language selection is available on the login page - pass
* with multiple windows/tabs open, if the language is changed in one session, it is updated for all sessions -- pass
* with multiple browsers/incognito sessions open, changes in one session do not update other sessions --TBD
@richard-cox or @bisht-richa could I get confirmation that this is intended behavior? I assume it is, but based on this line from the original ticket, I was a little confused
```
if the locale was changed on the login screen, we update the user preference with the new locale - this will then be stored by the backend

```

**Comment by slickwarren** [comment] 2022-09-20 05:20
reopening for clarification on the above comment

**Comment by nwmac** [comment] 2022-09-20 09:56
@slickwarren Regarding: with multiple browsers/incognito sessions open, changes in one session do not update other sessions 

No - you have to refresh the browser.

**Comment by slickwarren** [comment] 2022-09-20 16:27
closing based on the above conversation and testing

**Closed by slickwarren** 2022-09-20 16:27 UTC
Labels: [zube]: To Test, QA/XS, kind/enhancement, team/area2, size/3, area/localisation
