### ISSUE TITLE
Not able to create git repos in continuous delivery as a restricted admin

### ISSUE THREAD

**Issue by anupama2501** [rancher/dashboard#4909] opened 2022-01-12 20:27 UTC
Setup

Rancher version: `2.5.9`
Browser type & version: Chrome

**Describe the bug**
As a restricted admin, I'm not able to create any git repo from the continuous delivery in the explorer. The screen is stuck in loading.

**To Reproduce**
1. Create a restricted admin - r1
2. Login as r1 and from global tools on the ember UI --> continuous delivery --> git repos --> create

**Result**
Page is stuck in loading and the following console logs were seen:
```
vue.runtime.esm.js:1888 TypeError: Cannot read properties of null (reading 'filter')
    at f.options (SelectOrCreateAuthSecret.vue:134)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.evaluate (vue.runtime.esm.js:4584)
    at f.options (vue.runtime.esm.js:4836)
    at f.r (SelectOrCreateAuthSecret.vue?8efb:3)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.run (vue.runtime.esm.js:4554)
    at gn (vue.runtime.esm.js:4310)
```

**Expected Result**
Expected the create button to work and the user's able to create a git repo from the UI.

**Comment by cbron** [comment] 2022-01-13 18:31
This still exists on 2.5.12.

**Comment by cbron** [comment] 2022-01-13 18:32
@gaktive this should be release noted for 2.5.12 if it won't be fixed.

**Comment by gaktive** [comment] 2022-01-13 18:59
@cbron noted. I'll put this as 2.5.12 though as a "won't fix" for QA.

**Comment by cbron** [comment] 2022-01-13 19:57
To clarify I meant _if_ it won't be fixed in time. It still needs to be fixed, and we are fairly confident its not a backend issue as it exists in 2.6 as well.

**Comment by anupama2501** [comment] 2022-01-14 01:45
https://github.com/rancherlabs/rancher-security/issues/825 -- Original issue logged in 2.6


**Workaround**:
If the restricted admin creates a cluster in the cluster manager, the issue [cannot create git repo] is not seen or the git repos can be created via kubectl

**Comment by davidnuzik** [comment] 2022-01-31 18:13
**My checks PASSED**
**Given that I no longer observe this issue in 2.6.3 and v2.6-head my understanding is I can close out this issue. I will do so.**
 
**Reproduction Environment:**

Rancher version: v2.5.12 and v2.6.3 (I could NOT repro in 2.6.3)
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Reproduction steps:**

0. Create a restricted admin user. Login as the restricted admin.
1. As the restricted admin user, open Continuous Delivery (in 2.5.12 do this by going to tools -> Continuous Delivery, in 2.6.3 go to Continuous Delivery on the left nav pane).
2. Now, try to create a gitRepo - You will see a TypeError in the browser dev console and the page does not finish loading due to this.

 
**Additional Info:**
In 2.5.12 I see a similar TypeError to the one originally reported:
```
TypeError: this.allSecrets is null
    options SelectOrCreateAuthSecret.vue:133
    VueJS 3
    r SelectOrCreateAuthSecret.vue:3
    VueJS 13
    e NuxtJS
    d runtime.js:45
    _invoke runtime.js:274
    e runtime.js:97
    Babel 8
    NuxtJS 3
    VueJS 22
```

In 2.6.3 I do NOT encounter this issue.

-----
 
**Validation Environment:**

Rancher version: v2.6.3 and v2.6-head
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: n/a
Downstream K8s version: n/a
 
**Validation steps:**

1. Execute the same steps as those outlined above in the repro section. No TypeError is seen and the Create GitRepo form loads without any issues.

**Additional Info:**
I tested with v2.6.3 only because the issue mentioned this was a problem in 2.6 so I tried our last release and it didn't have the problem for me. Perhaps an older release like 2.6.0 or 2.6.1 or 2.6.2 did.

**Closed by davidnuzik** 2022-01-31 18:13 UTC
Labels: [zube]: QA Working, kind/bug-qa, release-note, team/area1
