### ISSUE TITLE
[Logging V2] Chart Install Page

### ISSUE THREAD

**Issue by paynejacob** [rancher/dashboard#1109] opened 2020-08-26 16:37 UTC
Overview:
The overview tab will cover the concepts of a logger, flow, and output. There should also be a link to the banzi cloud logging docs and explanation of what their operator does. @paynejacob will write this text and add it to this issue.

Additional Loggers:
This tab will have configuration options for the helm chart that enable log collection for specific cluster providers.  Users should only be able to select a single provider. Providers may have additional options, see table below.  There should also be a flag to optionally force the log aggregators to be deployed to control plane nodes.  If this is set The tolerations should be passed to the helm chart.

Cluster Flow:
This tab will optionally create a cluster flow and cluster output for the user to get them started.  The flow should automatically be configured to point to the created output and users should see the same output form from the custom CRD page.

Tolerations:
`
- key: node-role.kubernetes.io/controlplane
     value: true
     effect: NoSchedule
- key: node-role.kubernetes.io/etcd
     value: true
     effect: NoExecute
`

**Comment by paynejacob** [comment] 2020-08-26 18:47
https://github.com/rancher/rancher/issues/20565

**Comment by codyrancher** [comment] 2020-08-27 22:35
@paynejacob **Additional Loggers** sounds alot like what we currently have. Wasn't this supposed to be moved to a CRD?

**Comment by paynejacob** [comment] 2020-08-27 22:38
The old chart was configuring outputs.  The additional loggers configures loggings that will feed the outputs.  They have much simpler configuration, most will just be a flag.

**Comment by codyrancher** [comment] 2020-08-27 22:46
Alright, that works for me. Thanks for the info.

**Comment by paynejacob** [comment] 2020-08-28 21:04
Overview Text: for this we can use the readme.

**Comment by paynejacob** [comment] 2020-08-28 21:04
For the additional logger section: "Select a service to enable more detailed log collection for your given provider."

**Comment by deniseschannon** [comment] 2020-09-01 20:40
@paynejacob There are no details of the fields that you are trying to create a UI page from.

**Comment by paynejacob** [comment] 2020-09-01 21:47
Fields:

Additional loggers content::
| Display | Key | type | default |
| ---------- | ----- | ---------  | --- |
| RKE 1   | additionalLoggingSources.rke1.enabled | bool | false |
| RKE 2   | additionalLoggingSources.rke2.enabled | bool | false |
| K3S       | additionalLoggingSources.k3s.enabled  | bool | false |
| K3S Container Engine   | additionalLoggingSources.k3s.container_engine | str<systemd\|openrc> | systemd |
| EKS  | additionalLoggingSources.eks.enabled | bool | false |

**Comment by izaac** [comment] 2020-09-10 16:35
Rancher version: `master-head (09/10/2020)` _198ec5bdf52d3ed2b4865cfcf6ac1d61150bf55f_

The `Deploy to control plane nodes` checkbox  I don't see it making any change in the chart deployment if I check it and then click install.

**Comment by codyrancher** [comment] 2020-09-10 20:27
@izaac the checkbox controls tolerations. It's put at the root of the value not under additionalLoggingSources. @paynejacob this is the intended behavior isn't it?

![image](https://user-images.githubusercontent.com/55104481/92800284-65028100-f369-11ea-8e6b-a00a85ad7636.png)

**Comment by paynejacob** [comment] 2020-09-10 20:30
Yes it should set the root tolerations

**Comment by codyrancher** [comment] 2020-09-10 20:34
I just noticed the second half. We're passing the cluster provider which is rke.

Per https://github.com/rancher/dashboard/pull/1182#issuecomment-689050092 this appears to be correct. @paynejacob is it supposed to be rke1? If so, do we have a mapping of cluster provider to chart cluster provider I can use?

**Comment by paynejacob** [comment] 2020-09-10 20:36
It should be rke1 that was a mistake on my part.

RKE -> rke1
RKE Federal -> rke2
K3s -> k3s
EKS -> eks

**Comment by codyrancher** [comment] 2020-09-10 20:49
I had a discussion offline with @paynejacob and it looks like he's going to update the chart to accept the provider constants listed here https://github.com/rancher/kubernetes-provider-detector/tree/master/providers.

This means that we should expect rke instead of rke1 once the chart is updated.

**Comment by izaac** [comment] 2020-09-10 23:17
Opened https://github.com/rancher/rancher/issues/28847 to follow the chart changes.

**Comment by deniseschannon** [comment] 2020-09-17 21:07
@izaac Can I close this in favor of the other chart changes issue?

**Comment by izaac** [comment] 2020-09-17 21:08
@deniseschannon sounds good

**Comment by izaac** [comment] 2020-09-19 19:34
Rancher version `master-head (09/19/2020)` _bd88c23_ HA k8s

Installed with and without the Control Plane nodes option checked in UI in all the cluster types. 

- RKE
- RKE2 (RKE Federal)
- EKS
- k3s (openrc and systemd)

Opened #1316 as a separate issue.

**Closed by izaac** 2020-09-19 19:34 UTC
Labels: [zube]: To Test, area/logging
