### ISSUE TITLE
Logging: Error trying to Create ClusterFlow or Flow

### ISSUE THREAD

**Issue by nwmac** [rancher/dashboard#2326] opened 2021-02-15 12:02 UTC
Installed Logging into a cluster and go to the Logging product.

Click on either ClusterFlows or Flows. Click the Create button - you get an error 'filtersYaml.substring(...).replaceAll is not a function'.

In 2.5.5 you got this message: "This resource contains a match configuration that the form editor does not support. Please use YAML edit." - which is slightly confusing, as there is no way to edit the YAML.

Click 'Create' here:
![Logging_Error_Create](https://user-images.githubusercontent.com/1955897/107944736-83a71c80-6f86-11eb-97f9-f4086d6f0d5d.png)

Error seen:
![Logging_Error](https://user-images.githubusercontent.com/1955897/107944137-9c630280-6f85-11eb-912c-689bc185691e.png)

**Comment by codyrancher** [comment] 2021-02-16 19:34
@nwmac are you still able to reproduce this? It seems to be working for me in the latest.

![Kapture 2021-02-16 at 12 33 16](https://user-images.githubusercontent.com/55104481/108112427-4ceb0800-7053-11eb-85f1-c939091bf26d.gif)

**Comment by nwmac** [comment] 2021-02-17 12:01
Thanks @codyrancher - turns out my Chrome on my linux box is version 81 (April 2020).

The code uses String.replaceAll, which was not available in Chrome until version 85 (Aug 2020)  - https://caniuse.com/mdn-javascript_builtins_string_replaceall

I've added a fix for this in this PR: #2336

**Comment by ryansann** [comment] 2021-02-25 22:16
Tested on Rancher `v2.5.6-rc5` and Chrome 88, Brave 1.18.78, Safari 13.1.3

Steps:
- Provision cluster
- Navigate to Cluster Explorer
- Deploy Logging App
- Navigate to Logging > ClusterFlows, Click Create (observe no issue)
- Navigate to Logging > Flow, Click Create (observe no issue)

This looks good from my tests

@nwmac can you confirm this works in your earlier version of Chrome?

**Comment by deniseschannon** [comment] 2021-02-26 00:57
@nwmac Seems like this can only be tested if you have an older version of Chrome. Do you still have that older version? Otherwise, we should close this.

**Comment by nwmac** [comment] 2021-02-26 09:32
@denise @ryansann I have verified that this is fixed for older Chrome (80).

**Closed** 2021-02-26 14:34 UTC
Labels: [zube]: To Test, kind/bug
