### ISSUE TITLE
Commit ID redirects to release notes

### ISSUE THREAD

**Issue by kravciak** [rancher/dashboard#2939] opened 2021-05-10 12:06 UTC
Open Top-Left corner menu and click commit id link (8c014ef).

Current result: it redirects to /dashboard/docs/release-notes page
Expected result: it should show version information

Tested on master-head (8c014ef)

**Comment by nwmac** [comment] 2021-05-11 15:21
This will be addressed by PR rancher/dashboard#2919

**Comment by richard-cox** [comment] 2021-05-12 19:08
Dupe of #2903

**Closed by richard-cox** 2021-05-12 19:08 UTC
Labels: [zube]: Review, kind/bug
