### ISSUE TITLE
NVIDIA GPU Reservation needs to be added to workload form

### ISSUE THREAD

**Issue by catherineluse** [rancher/dashboard#5005] opened 2022-01-28 20:59 UTC
Someone in the Rancher users slack asked why the GPU reservation form is not in v2.6.x but used to be in v2.5.

It looks like the field was intended to be added to v2.6.x as it is mentioned in this comment about the design of the form: https://github.com/rancher/dashboard/issues/267#issuecomment-582671809

The field would be added to the resources tab:
![Screen Shot 2022-01-28 at 11 55 20 AM](https://user-images.githubusercontent.com/20599230/151620597-3637ea3a-a237-4748-bf73-6531f30fcfbc.png)

Ember UI for reference:
![image](https://user-images.githubusercontent.com/20599230/151620705-17b3a7ee-9696-4aad-9059-f6b2f0cd417b.png)

**Comment by nwmac** [comment] 2022-01-31 14:11
The task here is:

- Add a new field under the 'CPU Limit' similar to CPU - the units is just 'GPUs' - label 'NVIDIA GPU Limit/Reservation"
- This field in a numeric input

If the value is not a number is 0, the resource limit/request for gpus should be removed. Otherwise it should be set to the value in the input box.

The code for cpu/memory limits/reservations is in the `ContainerResourceLimit` component. This is used in `edit/workload/index.vue`.

For this GPU setting, the key to use is `nvidia.com/gpu` - see  'nvidia.com/gpu'.

Unlike for the CPU and Memory, we only have 1 input box and we use the value in this for both the limits and requests. 

You can test this feature by ensuring that the yaml created for a container contains the correct gpu limits/requests settings.

**Comment by MbolotSuse** [comment] 2022-03-09 18:20
No validation template was filled out for this, but I can try and go off @nwmac 's comment here: https://github.com/rancher/dashboard/issues/5005#issuecomment-1025778356 for what to look for.

# Validation Failed

While the resource limit was properly set as expected and is present in the UI, the request value was not set. Based on the earlier comment, I expected these to have the same value. Let me know if I am wrong there.

## Reproduction steps
- Rancher Version: 2.6.3 (Docker single node - `docker pull rancher/rancher:v2.6.3` and `docker run -d --restart=unless-stopped -p 8080:80 -p 8081:443 --name rancher --privileged rancher/rancher:v2.6.3`)

1. Start rancher:v2.6.3.
2. Log in as an admin user.
3. In the local cluster, attempt to create a job. 
4. In the job creation screen, select resources.
5. Confirm that there is no ability to set an NVIDIA GPU Reservation.

![Before](https://user-images.githubusercontent.com/95644600/157500206-39e8fd3e-bd36-4f00-9a7d-ce3d3a42063b.png)


## Validation steps
- Rancher Version: 2.6-head (Docker single node - `docker pull rancher/rancher:v2.6-head` and `docker run -d --restart=unless-stopped -p 8080:80 -p 8081:443 --name rancher --privileged rancher/rancher:v2.6-head`)
- 2.6-head digest: `sha256:3f7cad0584b73619958c4b02cf1203b1c906c4ea0d609b58858cd013d980521e`
- Latest commit (from rancher): `572ab58344b409b452ee3a3144e21066a5d89245`

1. Start rancher:v2.6-head.
2. Log in as an admin user.
3. In the local cluster, attempt to create a job.
4. Set the name to `test-job`.
5. Set the container image to `debian:stable-slim`.
6. In the job creation screen, select resources.
7. Confirm that you can set a limit for NVIDIA GPU reservation.
8. Create the job. Confirm that a limit was set for `nvidia.com/gpu` to the requested value. Confirm that a request was set for `nvidia.com/gpu` to the requested value.

This was also validated for other non-Pod workload types (CronJobs, DaemonSets, Deployments, StatefulSets). Screenshots from those resources are not included for brevity's sake. StatefulSets seem to have a separate issue that required me to use the yaml to set the servicename, but that appears to be unrelated to this change.

![After_1](https://user-images.githubusercontent.com/95644600/157500244-80befdcf-1074-4d3b-8807-e309a17a5400.png)

![After_2](https://user-images.githubusercontent.com/95644600/157500264-722d0292-0b01-4866-9537-7a18e4a19041.png)

![After_3](https://user-images.githubusercontent.com/95644600/157500285-e0230d6c-3492-4bef-8f52-af9e5dbbc4bd.png)

**Comment by nwmac** [comment] 2022-03-11 15:13
@neillsom The value is being set as a string, where it should be an number - see YAML:

```
        resources:
          limits:
            nvidia.com/gpu: "1"
```

(Should not be quoted)

Also, the ask here is to use the same value for requests, so we should duplicate the value, so you'd get:

```
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
```

This isn't strictly necessary, but mirrors the Ember UI - this was what was referred to originally on this ticket by:

*Unlike for the CPU and Memory, we only have 1 input box and we use the value in this for both the limits and requests.*

**Comment by neillsom** [comment] 2022-03-11 21:22
@nwmac This string issue appears to be coming from the backend. We are sending a number but receiving a string. I'll create another PR for the limits/requests issue.

![Screen Shot 2022-03-11 at 2.11.59 PM.png](https://zube.io/files/rancher/6c0e7966d1c100c74a5d44b4c27fa3e3-screen-shot-2022-03-11-at-2-11-59-pm.png)

![Screen Shot 2022-03-11 at 2.12.25 PM.png](https://zube.io/files/rancher/fb9c4e95d3d373e78b8fcfe74e037489-screen-shot-2022-03-11-at-2-12-25-pm.png)

**Comment by jtravee** [comment] 2022-03-16 22:30
Confirmed with @catherineluse and @gaktive to add `release note` label.

**Comment by gaktive** [comment] 2022-03-21 15:04
PR https://github.com/rancher/dashboard/pull/5424 addresses this and it was merged.

**Comment by MbolotSuse** [comment] 2022-03-22 15:34
Validation Passed 
## Reproduction steps
- Rancher Version: 2.6.3 (Docker single node - `docker pull rancher/rancher:v2.6.3` and `docker run -d --restart=unless-stopped -p 8080:80 -p 8081:443 --name rancher --privileged rancher/rancher:v2.6.3`)

1. Start rancher:v2.6.3.
2. Log in as an admin user.
3. In the local cluster, attempt to create a job. 
4. In the job creation screen, select resources.
5. Confirm that there is no ability to set an NVIDIA GPU Reservation.

![Before](https://user-images.githubusercontent.com/95644600/159517280-c90ee3bf-a64b-4094-bfcf-98d70e2c851e.png)

## Validation steps
- Rancher Version: 2.6-head (Docker single node - `docker pull rancher/rancher:v2.6-head` and `docker run -d --restart=unless-stopped -p 8080:80 -p 8081:443 --name rancher --privileged rancher/rancher:v2.6-head`)
- 2.6-head digest: `sha256:6b212fa904effc44676e8eb7315377f088ee3fa37cb6bc1f0132a57470eeeacd`
- Latest commit (from rancher): `0b4457317840d80c17990b5e04ba326eb411fb8f`

1. Start rancher:v2.6-head.
2. Log in as an admin user.
3. In the local cluster, attempt to create a job.
4. Set the name to `test-job`.
5. Set the container image to `debian:stable-slim`.
6. In the job creation screen, select resources.
7. Confirm that you can set a limit for NVIDIA GPU reservation.
8. Create the job. Confirm that a limit was set for `nvidia.com/gpu` to the requested value. Confirm that a request was reset for the requested value.

This was also validated for other non-Pod workload types (CronJobs, DaemonSets, Deployments, StatefulSets). Screenshots from those resources are not included for brevity's sake.

### Notes on other workload types
- Cronjobs appeared to suffer from another UI issue. When hitting `Create` or `Edit as Yaml` an error appeared (on the UI in the first case, in the console on the second case) indicating that `template.spec.containers` is undefined. This appears to be a separate UI issue unrelated to this change.
- StatefulSets seem to have a separate issue that required me to use the yaml to set the servicename, but that appears to be unrelated to this change. I used the UI to set the gpu limits, which worked as expected (despite the fact that the end create was done through the yaml).

![After_1](https://user-images.githubusercontent.com/95644600/159518542-807366f6-187c-4b8f-b5f3-3ded6ea13772.png)

![After_2](https://user-images.githubusercontent.com/95644600/159518568-a09b467f-c1a7-4e87-9eb3-e4e7bab497ad.png)

![After_3](https://user-images.githubusercontent.com/95644600/159518601-01ddd334-6e89-42f3-8712-299112e3920f.png)



## Notes
- The values set in the yaml were strings as noted by @nwmac. This did not appear to affect functionality (resources refused to schedule due to `0/1 nodes are available: 1 Insufficient nvidia.com/gpu.` on my local cluster).
- While I did validate that the yaml was properly set, I did not verify that this works end to end (i.e. that you get what you requested and that you can properly use GPU in a container). I think that this would be a good test for QA to run to make sure that this works all the way through - @sowmyav27 let me know what you think on this.

**Comment by anupama2501** [comment] 2022-03-24 18:48
Verified on v2.6-head c2d8e32
- Created an EKS cluster with 3 p3.large nodes with GPU option enabled.
- Once the cluster is active run `kubectl create -f https://raw.githubusercontent.com/NVIDIA/k8s-device-plugin/v1.10/nvidia-device-plugin.yml`
- Verify GPU on each node by running the command `kubectl get nodes \
- "-o=custom-columns=NAME:.metadata.name,GPU:.status.allocatable.nvidia\.com/gpu"`
- Create a job by adding value 1 in the resources section for GPU
- Verified the values are updated for limits and requests under `nvidia.com/gpu` in the yaml file of the job 
```      
  resources:
          limits:
            nvidia.com/gpu: "1"
          requests:
            nvidia.com/gpu: "1"
```
- Job/deployment comes up active.

**Closed by anupama2501** 2022-03-24 18:48 UTC
Labels: status/dev-validate, [zube]: QA Working, kind/enhancement, release-note, team/area1, size/1
