### ISSUE TITLE
Add back Drain/Cordon button to nodes

### ISSUE THREAD

**Issue by 0SkillAllLuck** [rancher/dashboard#4092] opened 2021-08-31 09:48 UTC
**Is your feature request related to a problem? Please describe.**
In the old cluster manager there was an option to drain/cordon nodes.

**Describe the solution you'd like**
It would be very nice to have those buttons back in the new cluster explorer under nodes.

**Describe alternatives you've considered**
Manually doing it works via the kubectl shell but overall is a less than optimal experience.

**Comment by 0SkillAllLuck** [comment] 2021-09-02 14:25
@superseb I can't see the buttons, or am I on the wrong page?
<img width="1671" alt="image" src="https://user-images.githubusercontent.com/43417046/131861538-5358e067-fbb2-482f-a1fa-e8425cda43d2.png">

**Comment by 0SkillAllLuck** [comment] 2021-09-02 14:29
Rancher is latest v2.6.0 and cluster type as you can see is rke2 with v1.21.4

**Comment by UberKuber** [comment] 2021-09-03 07:12
> @superseb I can't see the buttons, or am I on the wrong page?
> <img alt="image" width="1671" src="https://user-images.githubusercontent.com/43417046/131863225-51432c9c-7297-4477-af48-76190bca69e8.png">

@0SkillAllLuck you are on the local cluster there which is an imported cluster. If you view the nodes on a created downstream cluster the cordon and drain buttons are there. In v2.5.9 there is only an option to drain the nodes on the local cluster.

**Comment by 0SkillAllLuck** [comment] 2021-09-03 07:43
I thought it was possible to drain and cordon nodes for all clusters in the old Cluster Manager before. Maybe I am wrong.

**Comment by richard-cox** [comment] 2021-09-03 10:22
Under the hood, the dashboard uses the same Norman node mechanism to show & execute cordon/drain (if you excuse the pun, #4088 fixed a drain... plumbing... issue).

If the cordon/drain action is showing successfully for non-local clusters, the question here is in what conditions if any should cordon/drain show for the local cluster? If none, then this is working as expected, if only in a multi-node environment then there's a backend bug.

**Comment by richard-cox** [comment] 2021-09-06 09:20
@kinarashah How's it looking, is this working as expected or something you'll need to change your side?

**Comment by rak-phillip** [comment] 2021-12-03 17:37
@richard-cox @kinarashah @gaktive do we have an update on this one? I've seen people asking for this feature on slack

**Comment by richard-cox** [comment] 2021-12-06 12:06
@rak-phillip I've confirmed in 2.6.3 drain/cordon is visible and working for multi-node environments (rke1 & rke2) and not visible in single-node environments (rancher docker image 'local' cluster & imported k3s cluster).

**Comment by davidnuzik** [comment] 2021-12-08 19:24
@richard-cox what is needed for me to test here? (what changed?) Is there a PR that needs to be linked to?
cc: @sowmyav27

**Comment by davidnuzik** [comment] 2021-12-08 19:25
Is it just this change? https://github.com/rancher/dashboard/issues/4092#ref-commit-03c667b

**Comment by davidnuzik** [comment] 2021-12-08 21:34
**My checks Failed**
It looks like this was fixed even before v2.6.0 release? Due to commit on Aug 24th before 2.6.0 release. I think the milestone is wrong. Because this issue shouldn't exist in any 2.6 release I used an old v2.6-head build before v2.6.0 release to reproduce.

**_If this doesn't sound right -- someone please correct me._** All I see on this issue is a commit on August 24th as far as code changes (days before v2.6.0 release).
 
**Reproduction Environment:**

Rancher version: [v2.6-863351dc2c3a4ad4e49281cecd62e9adc5c3de5c-head](https://hub.docker.com/layers/rancher/rancher/v2.6-863351dc2c3a4ad4e49281cecd62e9adc5c3de5c-head/images/sha256-803e138c81305b1d2a0d210c6af2efa16b57895d877b09e406ea1a05957d111c?context=explore) 8/20/2021 (few days before commit)
Rancher cluster type: single-node docker install
Docker version: 20.10
 
Downstream cluster type: rke1
Downstream K8s version: v1.20
 
**Reproduction steps:**

1. Create an RKE1 cluster. In my case I created one pool with 3 nodes each with every role. I also created an RKE2 cluster with same configuration.
2. Explore the cluster and navigate to the Nodes page.
3. I did see the drain/cordon buttons, and they also seem to work - so I wasn't able to successfully reproduce here.

**Comment by davidnuzik** [comment] 2021-12-08 21:59
Since I didn't observe any issues I've been instructed to close this out.

**Closed by davidnuzik** 2021-12-08 21:59 UTC
Labels: [zube]: Reopened

**Comment by richard-cox** [comment] 2021-12-09 13:32
@davidnuzik Sorry, time zone fun. This was originally implemented a while ago, then broken, then fixed again. The general feature of drain/cordon just needed a re-test in the latest code base, which you've done and it looks like all is good. Thanks!
