### ISSUE TITLE
Private Registries Template override value not getting passed through

### ISSUE THREAD

**Issue by brendarearden** [rancher/dashboard#3940] opened 2021-08-19 21:21 UTC
**Description of Issue**
Some user override values are not being passed through.

When creating a cluster with a cluster template that allows user override values for Private Registries, the value entered into the form is not passed through, but the default cluster template value is. 

**Steps to Recreate**
Rancher setup: HA Rancher v2.6.0-rc3, rke v1.2.11 to create 3 node cluster (2 workers, 1 all), `helm install`

1. In your rancher instance, navigate to cluster management
2. Go to RKE1 Configuration >> RKE Templates and Add Template with the following values:  

- Template Name: example-template
![Screen Shot 2021-08-19 at 2 01 13 PM](https://user-images.githubusercontent.com/19455540/130143353-02b5d934-d701-433b-83a9-fab4ee3ee82e.png)
- Kuernetes Options
     Kubernetes Version: Toggle Allow User Override 
![Screen Shot 2021-08-19 at 2 01 31 PM](https://user-images.githubusercontent.com/19455540/130143387-ceb1b6a9-70c6-4746-99fc-ce7fb6b007e5.png)
     Cloud Provider: Azure(In-Tree)
          Fill in required fields (*) and toggle allow 
               For the aadClientSecret, I used `examplepassword`
![Screen Shot 2021-08-19 at 2 02 25 PM](https://user-images.githubusercontent.com/19455540/130143500-c4f48dc5-42df-490d-827b-6074ffc2e936.png)
- Private Registry 
     Private Registry
          Select enabled and fill out required fields, toggle Allow User Override for password
          For the Password, I used `exampleregistrypassword`
![Screen Shot 2021-08-19 at 2 06 01 PM](https://user-images.githubusercontent.com/19455540/130143855-dfab798b-5a48-4947-95f3-7e8db04e4133.png)
3. Then click create to create the template and go to create a RKE1 cluster. I selected Digital Ocean because we do not need the cluster to provision to validate the PUT call. 
4. Under cluster options, check the `Use an existing RKE Template and revision` and select `example-template` from the drop down.
5. Finish filing out the required fields.
6. Override the `aadClientSecret` field with `override1234`
7. Add a password for the Private Registry of `override5678`
8. Create the cluster

**Result**
If you are using the developer network tool, and you look at the Request Payload answers and values you see 
```
answers: {values: {rancherKubernetesEngineConfig.kubernetesVersion: "v1.21.4-rancher1-1",…}}
values: {rancherKubernetesEngineConfig.kubernetesVersion: "v1.21.4-rancher1-1",…}
rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientId: "example123"
rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.aadClientSecret: "override1234"
rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.subscriptionId: "example456"
rancherKubernetesEngineConfig.cloudProvider.azureCloudProvider.tenantId: "example789"
rancherKubernetesEngineConfig.kubernetesVersion: "v1.21.4-rancher1-1"
rancherKubernetesEngineConfig.privateRegistries[0].password: "exampleregistrypassword"
```
Which shows that the user override value worked for the `aadClientSecret` field, but was not passed through for the `rancherKubernetesEngineConfig.privateRegistries[0].password` field. 

**Expected**
Any field that allows for a user override should pass the override value through when performing the PUT

**Additional Info**
I did not test all potential override values so this could be an issue with other ones - I have seen the kubernetes config and cloud provider values be overridden as expected.

**Comment by gaktive** [comment] 2021-08-19 22:45
I've been advised that this exists on the Ember side with the v1 work. This appears to be an edge case for a scenario that may now have worked in earlier versions.

@codyrancher once you've worked through the other 2.6 blockers, can you check whether this worked before? This may be a 2.6.x thing if it's consistent.

**Comment by gaktive** [comment] 2021-08-19 22:46
Similar issue: https://github.com/rancher/dashboard/issues/3715

**Comment by codyrancher** [comment] 2021-09-08 21:57
This is a duplicate of https://github.com/rancher/rancher/issues/27166. I'm closing in favor of that one.

**Comment by deniseschannon** [comment] 2021-12-01 20:31
Re-opening this issue as it's a front end and back end fix. This is to track the front end fix even though it's in Ember.

**Comment by jiaqiluo** [comment] 2022-01-19 00:50
The fix in the backend is merged. 
cc @codyrancher

**Comment by gaktive** [comment] 2022-01-20 23:44
Whoever tests this, can you confirm whether project-scoped registry secrets work? We've received reports that those can't be created in the 2.6 UI, only namespace-scoped secrets. This apparently worked in the old Ember (Cluster Manager) interface but we've had a lot of tickets tied to this area.

If that's the case, ping me and I'll create a new ticket for that and we can leave this ticket based on what's already here.

**Comment by slickwarren** [comment] 2022-02-10 00:03
tested using rancher v2.6.4-rc2 as a standard user:
* Override for password, user, and registry values -- pass
* set override of each, but leave to default values -- pass
* disabling override in future versions of a template -- pass

Other tests performed:
* create a cluster, and give a user `project-owner` permissions in the default project
* create a registry secret (secrets -> registry)
* create a workload using the registry secret as an environment variable -- fail -> will file an issue for this.

**Closed by slickwarren** 2022-02-10 00:03 UTC
Labels: kind/bug, [zube]: To Test, team/area2
